### PR TITLE
support bitwise or/'|' operation

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

part of https://github.com/apache/arrow-datafusion/issues/1619

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by houqp — APPROVED** [review]
LGTM. Do we need to support unsigned integer types as well?

**Comment by liukun4515** [comment]
> LGTM. Do we need to support unsigned integer types as well?

Yes, the unsigned integer will be supported but not now.
From the reference of some database, such as PG and spark, there is no cases for bitwise operation of unsigned integer.
I can't get some use cases to infer the rule of coercion when we meet  `i32 | u32` and other cases.
@houqp

**Comment by alamb** [comment]
@liukun4515  this PR has some conflicts now -- any chance you have a few moments to resolve them so we can get it merged? If not, I will attempt to do so later in the week.

**Comment by liukun4515** [comment]
> this PR has some conflicts now -- any chance you have a few moments to resolve them so we can get it merged? If not, I will attempt to do so later in the week.

I will resolve the conflicts tomorrow.

**Comment by liukun4515** [comment]
It's ready to be merged.

**Comment by alamb** [comment]
Thanks @liukun4515

**Pull request merged**
