### PR TITLE
git-ignore `datafusion/proto/src/generated/datafusion.rs`

### PR DESCRIPTION
**Pull request by crepererum**
# Which issue does this PR close?
\-

# Rationale for this change
I was close to accidentally adding this file to my PRs so many times by now, let's just git-ignore it.

# What changes are included in this PR?
New git-ignore rule.

# Are these changes tested?
\-

# Are there any user-facing changes?
\-

### CODE REVIEW

**Comment by tustvold** [comment]
This is intentionally checked in https://github.com/apache/arrow-datafusion/blob/master/datafusion/proto/proto/datafusion.proto as part of the story around not needing users to have protoc installed? It is gross, but see #3950 for more context

If you're seeing a diff this would imply something is off with the version pins somewhere?

**Comment by crepererum** [comment]
I'm not talking about the `proto` file but the generated `.rs` file. The latter one is NOT checked in at the moment (although I can change this PR to do so).

**Comment by tustvold** [comment]
Oh... I'm curious what is generating that, is it some artifact from before #3950 perhaps? I can't seem to generate such a file locally...

**Review by jackwener — APPROVED** [review]
I also meet this😂 
Make sense to me

**Comment by crepererum** [comment]
I cannot reproduce this on current `master` anymore. Maybe it's a left-over.

**Pull request closed without merging**
