### PR TITLE
refactor: relax the signature of register_* in SessionContext

### PR DESCRIPTION
**Pull request by waynexia**
Signed-off-by: Ruihang Xia <waynestxia@gmail.com>

# Which issue does this PR close?

NAN

# Rationale for this change

Change the API for `register_*` (like `register_udf`) in `SessionContext`. Relax the share requirement from `&mut self` to `&self`. Because the actual state is wrapped in a `RwLock` (`state: Arc<RwLock<SessionState>>`), it's unnecessary to require `&mut self` for `SessionContext` itself.

# What changes are included in this PR?

Relax the share requirement from `&mut self` to `&self`.

# Are these changes tested?
 
No need I suppose. 

# Are there any user-facing changes?

Yes, this is API change.

### CODE REVIEW

**Comment by tustvold** [comment]
I wonder if perhaps this is a sign that we don't really need these locks :thinking: will have a play around

**Review by alamb — APPROVED** [review]
Looks good to me 👍

**Comment by alamb** [comment]
BTW I think @tustvold  has some larger ideas of how to simplify the configuration system -- see https://github.com/apache/arrow-datafusion/issues/4617 and related tickets

I think it is fine to merge this PR , even though there is likely going to be some churn in this API anyways

**Comment by waynexia** [comment]
Thanks for that info!

**Pull request merged**
