### PR TITLE
fix `cargo clippy` warning

### LINKED ISSUE #4653: Fix the clippy errors
**Describe the bug**
Rust has updated to 1.66. We need to fix the clippy error.

**To Reproduce**
1. run `rustup update`.
2. run `cargo clippy --all-targets --workspace --features avro,jit,pyarrow,scheduler -- -D warnings`

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #4653 #4654 .

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by HaoYang670** [comment]
This will close #4653

**Review by HaoYang670 — APPROVED** [review]
LGTM!

**Comment by mingmwang** [comment]
👍

**Comment by mingmwang** [comment]
Waiting for this PR to get merged.

**Comment by alamb** [comment]
Thank you @jackwener

**Pull request merged**
