### PR TITLE
Create writer with `arrow::ipc::IPCWriteOptions`

### LINKED ISSUE #4708: Support compression in `IPCWriter`
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently `IPCWriter` writes the arrow data in the default way (without compression).
We should  support writing it with compression.

**Describe the solution you'd like**
Introduce a method `try_new_with_options` with a new `IpcWriteOptions` parameter. This can be forwarded to the underlying `FileWriter`.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by askoa**
# Which issue does this PR close?
Closes #4708

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you @askoa 

I wonder if it might be worth adding some test to ensure this API is not accidentally broken

**Comment by askoa** [comment]
> I wonder if it might be worth adding some test to ensure this API is not accidentally broken / removed as part of some future refactoring

The API dos not add new functionality. It provides a bridge to access the compression function in `arrow-rs`. I don't think 'someone might remove it' is a good reason to add test. The person removing the code might also remove the test. If anyone ends up accidentally removing it, then the integration with `arrow-ballista` will fail.  I don't see a need to add new test for this.

**Comment by Dandandan** [comment]
> > I wonder if it might be worth adding some test to ensure this API is not accidentally broken / removed as part of some future refactoring
> 
> The API dos not add new functionality. It provides a bridge to access the compression function in `arrow-rs`. I don't think 'someone might remove it' is a good reason to add test. The person removing the code might also remove the test. If anyone ends up accidentally removing it, then the integration with `arrow-ballista` will fail. I don't see a need to add new test for this.

Thank you very mucht for adding this feature, no worries for the test!

In some cases, features might be lost by someone moving / refactoring the code as part of another change - this happened quite a few times before in arrow-rs / arrow-datafusion! Tests covering those code paths help avoiding issues like that. In ballista this might be only discovered once the version is updated (which may be only after a new version is released).

**Comment by askoa** [comment]
> In some cases, features might be lost by someone moving / refactoring the code as part of another change - this happened quite a few times before in arrow-rs / arrow-datafusion! Tests covering those code paths help avoiding issues like that. In ballista this might be only discovered once the version is updated (which may be only after a new version is released).

I don't know the scenarios you are referring to. But during those refactoring the person might remove the test along with the code. So, in my opinion,  catching when `arrow-ballista` consumes the changes is the best way to catch such issues rather than adding tests.

**Comment by alamb** [comment]
> But during those refactoring the person might remove the test along with the code

This is definitely true. Tests such as @Dandandan  and I are referring to do not guarantee code isn't broken. 

However, I for one, when reviewing PRs look quite carefully at the tests that are changed / modified so having them act as a "second check"

I think it is fine for this PR to not have added tests, but I do think they serve an important purpose which is why I am belaboring this point

**Pull request merged**
