### PR TITLE
Minor: Refine doc comments for BuiltinScalarFunction::return_dimension

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?
Related to https://github.com/apache/arrow-datafusion/pull/7008

# Rationale for this change
I only just now realized what "dimension" meant in the context of ListArray / Arrays so I tried to document it

# What changes are included in this PR?
Doc comments

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
@izveigor or @jayzhan211 I wonder if you have some time to review this PR?

**Comment by alamb** [comment]
Thanks @izveigor  -- I'll keep chipping away at keeping the codebase readable and documented :)

**Comment by jayzhan211** [comment]
I thought that ListArray is 1D...
But, this definition looks good to me too.

**Comment by alamb** [comment]
> I have different thoughts on this, List() is 1D, List(List()) is 2D, Int64 is 0D, dimension is only meaningful to List, not non-List type,

@jayzhan211  That is what I was trying to say. 

> But, If we want a new definition of dimensions, it is also fine.

My intention was **not** to change the definition but to capture what this function does. I am pretty sure that given the input `int64` this function would return `1`

**Comment by jayzhan211** [comment]
@alamb In your opinion, which one do you prefer? I think both are fine but need to be consistent everywhere

**Comment by alamb** [comment]
> @alamb In your opinion, which one do you prefer?

* Int64 is 0D,
* List() is 1D
* List(List()) is 2D,

Makes the most sense to me given my understanding of multi-dimensional array terminology. 

I don't know the code well enough to understand how large a code change updating to that definition would be

**Comment by jayzhan211** [comment]
I don't think there are many to change so changing the code might not be a problem. We just need to have a consensus on the definition of list dimensions, also add them to code comment and documentation

These are some code I know that is related to List dimensions
https://github.com/apache/arrow-datafusion/blob/11b7b5c215012231e5768fc5be3445c0254d0169/datafusion/expr/src/built_in_function.rs#L439-L460

https://github.com/apache/arrow-datafusion/blob/11b7b5c215012231e5768fc5be3445c0254d0169/datafusion/physical-expr/src/array_expressions.rs#L128-L162

https://github.com/apache/arrow-datafusion/blob/11b7b5c215012231e5768fc5be3445c0254d0169/datafusion/expr/src/built_in_function.rs#L494-L517

@izveigor Do you know any code that considers the list dimensions?

**Pull request merged**
