### PR TITLE
Add example on how to query multiple parquet files

### LINKED ISSUE #1484: Is it possible to query multiple parquet files ?
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
- i would like to query multiple parquet files. 
- can we have an example on how to achieve this ?

Thanks

### PR DESCRIPTION
**Pull request by nitisht**
# Which issue does this PR close?

Closes #1484 

 # Rationale for this change

This is a simple change to add an example on how to query multiple Parquet files using Datafusion

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks @nitisht

**Comment by alamb** [comment]
The build failure looks the same as https://github.com/apache/arrow-datafusion/issues/1498

**Comment by nitisht** [comment]
Thanks @alamb . Anything I can do to get this merged ?

**Comment by alamb** [comment]
@nitisht  I will get this merged -- I'll merge in the workaround for the time being while we sort out the quote / arrow stuff upstream

**Comment by alamb** [comment]
I merged `master` to your branch to pick up the changes. Hoping for a clean CI run now

**Comment by alamb** [comment]
@nitisht  it looks like there are some clippy and compilation errors. Can you please fix them?

**Comment by nitisht** [comment]
Just pushed some fixes.

**Comment by alamb** [comment]
🤔  the tests still seem not to be passing

**Comment by nitisht** [comment]
> 🤔 the tests still seem not to be passing

My apologies, I had not fixed everything. Just fixed the build/clippy issues. Runs fine locally, hopefully the CI should be happy now.

**Comment by alamb** [comment]
Thanks again @nitisht ! Great first contribution

**Comment by AdheipSingh** [comment]
awesome !!
thanks @nitisht @alamb

**Pull request merged**
