### PR TITLE
Minor: fix wrong function call

### PR DESCRIPTION
**Pull request by Weijun-H**
## Which issue does this PR close?

Closes #.

## Rationale for this change

This issue is called #8744 , but I am curious why it passed the ci 🤔

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
This seems like it is an oversight in our CI -- is it possible to write a test that would fail without this code change 🤔 

Nice catch

**Comment by Weijun-H** [comment]
> This seems like it is an oversight in our CI -- is it possible to write a test that would fail without this code change 🤔
> 
> Nice catch

The problem may not related to ci, because I tested it on cli, and it also worked. @alamb 
```
❯ select array_resize([1,2],5);
+------------------------------------------------------+
| array_resize(make_array(Int64(1),Int64(2)),Int64(5)) |
+------------------------------------------------------+
| [1, 2, , , ]                                         |
+------------------------------------------------------+
1 row in set. Query took 0.009 seconds.
```

**Review by comphead — APPROVED** [review]
lgtm thanks @Weijun-H

**Comment by alamb** [comment]
> The problem may not related to ci, because I tested it on cli, and it also worked. @alamb

Right, sorry, what I was saying is that given there is a bug you found in the code (by manual inspection) but 
1. it wasn't found by tests
2. you didn't have to update any tests when you changed the code

I conclude there is a gap in our test coverage. Thus I was suggesting we find a way to write a test that would fail prior to this code change, but will pass with the change

**Comment by Weijun-H** [comment]
The additional tests is in #8868 @alamb

**Comment by alamb** [comment]
Thanks again @Weijun-H

**Pull request merged**
