### PR TITLE
`datafusion.optimizer.repartition_file_scans` enabled by default

### LINKED ISSUE #5125: Enable parquet parallel scans by default
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
@korowa  added a feature to automatically repartition individual files in https://github.com/apache/arrow-datafusion/pull/5057 however it is behind a feature flag that defaults to false

**Describe the solution you'd like**
Turn on file level repartitioning that was added in https://github.com/apache/arrow-datafusion/pull/5057 by default so that all users of DataFusion can benefit

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by korowa**
# Which issue does this PR close?

Closes #5125.

# Rationale for this change

I guess, it's fine to enable repartitioning by default in 19.0.0 (or, more likely, first release candidate for 19.0.0)

# What changes are included in this PR?

Default value of `datafusion.optimizer.repartition_file_scans` is `true` now.

# Are these changes tested?

Covered by existing tests

# Are there any user-facing changes?

Repartitioning of file scans will be enabled by default

### CODE REVIEW

**Review by alamb — APPROVED** [review]
I think it is a good idea. Thank you @korowa

**Comment by alamb** [comment]
What do you think @tustvold @Dandandan  @andygrove  -- any concerns about turning on automatic repartitioned file scans (which allows scanning a single large parquet file in parallel)

**Comment by ozankabak** [comment]
This should help with mitigating the "low-performance" impression -- many people will not dig deep to configuration options and simply try things out with OOTB defaults.

**Comment by alamb** [comment]
I will plan to merge this sometime over the weekend unless anyone else would like time to comment or offer more thoughts

**Review by jackwener — APPROVED** [review]

**Comment by jackwener** [comment]
> This should help with mitigating the "low-performance" impression -- many people will not dig deep to configuration options and simply try things out with OOTB defaults.

Look great to me.

**Pull request merged**
