### PR TITLE
Remove `Transformed` enum

### PR DESCRIPTION
**Pull request by peter-toth**
## Which issue does this PR close?

Closes #.

## Rationale for this change

It seems there is no need for the `Transformed` enum so let's try getting rid of it.

### CODE REVIEW

**Comment by peter-toth** [comment]
@alamb, I don't see any reason why we wrap the nodes into `Transformed` in `TreeNode::transform...()` methods. Do you think it make sense to remove it?

**Comment by alamb** [comment]
> @alamb, I don't see any reason why we wrap the nodes into `Transformed` in `TreeNode::transform...()` methods. Do you think it make sense to remove it?

If it is not actually used I agree it makes sense to remove it

I thought it was used at some point to avoid unecessary tree traversals somehow, though if you didn't find any evidence of that maybe it has been removed 🤔 

Maybe @yahoNanJing  or @liukun4515  can remember

**Comment by andygrove** [comment]
The `Transformed` enum was introduced in https://github.com/apache/arrow-datafusion/pull/5630

There is a comment `Introduce enum Transformed to avoid clone in the TreeNode` but I am not sure that this is still relevant. This PR does not seem to be adding any additional clones.

It does seem useful to know if a rule transformed the plan or not without having to perform an expensive plan comparison. This functionality does not seem to be used within DataFusion though. I wonder if downstream projects are making use of this public API?

I'd also like to see if we can an opinion from  @yahoNanJing or @liukun4515

**Comment by alamb** [comment]
Basically if @yahoNanJing  and/or @liukun4515  agree, I think we should merge this PR to make the API simpler. It will be a breaking change for anyone who has tree node transforms (e.g our custom optimizer passes in IOx) but the changes will be mechanical

**Comment by berkaysynnada** [comment]
Thanks @peter-toth. I haven't come across any use cases yet, so it's a simplification. However, I wonder if PR https://github.com/apache/arrow-datafusion/pull/8817 can be merged beforehand? I plan to reopen it today.

**Comment by peter-toth** [comment]
> #8817

IMO the current form of https://github.com/apache/arrow-datafusion/pull/8817 has very fundamental issues: https://github.com/apache/arrow-datafusion/pull/8817#discussion_r1447628922.
Also, the change in this PR might be conflicting to https://github.com/apache/arrow-datafusion/pull/8817 but the fix is very straightforward to apply so I'm not sure the 2 PRs needs to land in any specific order.

**Comment by andygrove** [comment]
fwiw, in the logical optimizer, rules return a `Result<Option<LogicalPlan>>` and return `None` if the rule does not rewrite the plan.

**Comment by yahoNanJing** [comment]
Thanks @peter-toth. 

> Probably we all agree that currently Transformed has no point. IMO we should either remove it or make use of it / fix it.

Yes, I agree it's not used currently.

> I can think of 2 uses of this enum:

Yes, it seems the `OptimizerRule` does not leverage the `TreeNode` very much. For the long time goal, it would be better to use `TreeNode` to simplify the logic of `OptimizerRule`. 

And you are correct and the current interface may not be correct. How about changing the interface like this:
```
    fn transform_up<F>(self, op: &F) -> Result<Transformed<Self>>
    where
        F: Fn(Self) -> Result<Self>
```

Then we can leverage the `Transformed` to avoid use `with_new_children_if_necessary` in some cases.

**Comment by peter-toth** [comment]
> And you are correct and the current interface may not be correct. How about changing the interface like this:
> 
> ```
>     fn transform_up<F>(self, op: &F) -> Result<Transformed<Self>>
>     where
>         F: Fn(Self) -> Result<Transformed<Self>>
> ```
> 
> Then we can leverage the `Transformed` to avoid use `with_new_children_if_necessary` in some cases.

Yes, that's one of the options if we want to keep `Transformed`. But because `Transformed` is kind of a boolean flag and both `::Yes` and `::No` wraps a `TreeNode` we could just use `Result<(Self, bool)>`. In this case `transform_up()` would look like this:
```rust
    fn transform_up<F>(self, f: &F) -> Result<(Self, bool)>
    where
        F: Fn(Self) -> Result<(Self, bool)>,
    {
        self.map_children(|node| node.transform_up(f)).map(
            |node_with_new_children, children_transformed| {
                f(node_with_new_children).map(
                    |(new_node_with_new_children, transformed)| {
                        (
                            new_node_with_new_children,
                            children_transformed || transformed,
                        )
                    },
                )?
            },
        )
    }
```

**Comment by peter-toth** [comment]
If we want to keep the `Transformed` enum and fix it to serve its purpose then I think we should wait for https://github.com/apache/arrow-datafusion/pull/8891, https://github.com/apache/arrow-datafusion/pull/8817 and https://github.com/apache/arrow-datafusion/pull/8664 as those PRs eliminate many trees and rewrite many closures.

**Comment by yahoNanJing** [comment]
> We could also type alias (Self, bool) or create a struct

Thanks @peter-toth. I'm OK to change the Enum to your proposals. And we can wait for other PRs to do this change.

**Comment by peter-toth** [comment]
FYI https://github.com/apache/arrow-datafusion/pull/8891 contains the fix to the `Transformed` enum, see the PR description for the details.

**Pull request closed without merging**
