### PR TITLE
ScalarFunctionExpr Maintaining Order

### PR DESCRIPTION
**Pull request by berkaysynnada**
## Which issue does this PR close?

Closes #.

## Rationale for this change

After `ProjectionExec` is able to propagate the orders of non-column expressions, it is also possible to preserve the order of some `ScalarFunctionExpr`'s. This PR implements that feature. 

This PR is the 3rd step of https://github.com/apache/arrow-datafusion/pull/7296 and https://github.com/apache/arrow-datafusion/pull/7364 PR's. Now, we have the support of propagating the sort order over different kinds of `PhysicalExpr`'s at the projection stage.

## What changes are included in this PR?

While creating `ScalarFunctionExpr`, we check its order preservation info from `BuiltinScalarFunction`.  `math_expressions` and `datetime_expressions` are labeled according to their functional monotonicity. `ScalarFunctionExpr` now has a field `monotonicity: Option<FuncMonotonicity>`. `FuncMonotonicity` keeps monotonicity information of the function. It is one to one mapped to `args` of the function, and it specifies the effect of an increase or decrease in the corresponding `arg` to the function value.

## Are these changes tested?

Yes, by .slt tests with some of the functions.

### CODE REVIEW

**Comment by alamb** [comment]
I believe CI will pass after merging up from `main` to get the change in  https://github.com/apache/arrow-datafusion/pull/7416

**Comment by berkaysynnada** [comment]
@alamb I have synced the branch. If no objection, the PR is ready to merge.

**Review by ozankabak — APPROVED** [review]
LGTM, any feedback @alamb?

**Comment by ozankabak** [comment]
There doesn't seem to be any concerns about this, so I will go ahead with merging. Should there be any issues, we will address via quick follow-on PRs.

**Comment by alamb** [comment]
> LGTM, any feedback @alamb?

Sorry I was on vacation -- thanks for merging it and moving things along!

**Review by alamb — COMMENTED** [review]
Looks good to me -- thanks @berkaysynnada

**Pull request merged**
