### PR TITLE
[TEST]Update Rust version to 1.53.0 for integration test

### LINKED ISSUE #596: Integration test build failure due to arrow-rs using unstable feature
**Describe the bug**
While running the integration test in dev/, the docker build failed due to using of unstable feature:
```
#29 293.2 error[E0658]: use of unstable library feature 'partition_point': new API
#29 293.2   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/arrow-4.3.0/src/compute/kernels/partition.rs:88:14
#29 293.2    |
#29 293.2 88 |             .partition_point(|idx| {
#29 293.2    |              ^^^^^^^^^^^^^^^
#29 293.2    |
#29 293.2    = note: see issue #73831 <https://github.com/rust-lang/rust/issues/73831> for more information
````

**To Reproduce**
run ./dev/integration-tests.sh on master branch

**Expected behavior**
Integration test run as expected

### PR DESCRIPTION
**Pull request by yjshen**
# Which issue does this PR close?

Closes #596.

 # Rationale for this change
[partition_point](https://doc.rust-lang.org/std/primitive.slice.html#method.partition_point) is stabilized in 1.52.0, we should update the rust docker image used in the integration test to fix the broken test.

# What changes are included in this PR?
Update rust docker image version

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by houqp** [comment]
arrow shouldn't require nightly to build though, have you tried bumping rust version to the latest stable release?

**Comment by yjshen** [comment]
@houqp Thanks for the guidance, I've updated the docker image version used in the integration test, PTAL.

**Review by Jimexist — APPROVED** [review]
using `stable` label is better

**Review by houqp — APPROVED** [review]

**Comment by alamb** [comment]
FYI @andygrove and @edrevo

**Pull request merged**
