### PR TITLE
Add serde support for Arrow FileTypeWriterOptions

### LINKED ISSUE #8599: Add serde support for Arrow FileTypeWriterOptions
### Is your feature request related to a problem or challenge?

DataFusion supports many FileTypeWriterOptions:

```rust
pub enum FileTypeWriterOptions {
    #[cfg(feature = "parquet")]
    Parquet(ParquetWriterOptions),
    CSV(CsvWriterOptions),
    JSON(JsonWriterOptions),
    Avro(AvroWriterOptions),
    Arrow(ArrowWriterOptions),
}
```

The serde support in the `datafusion-proto` crate currently only supports JSON:

```protobuf
message FileTypeWriterOptions {
  oneof FileType {
    JsonWriterOptions json_options = 1;
  }
}
```

### Describe the solution you'd like

Add serde support for Arrow FileTypeWriterOptions

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tushushu**
## Which issue does this PR close?

Closes #8599.

By reading https://github.com/apache/arrow-datafusion/pull/8627 and https://github.com/apache/arrow-datafusion/pull/8641, I speculated that maybe the code should be written like this, but I'm not entirely sure if the code I wrote is correct. Maybe I should read more documentation about arrow-rs in the future.

### CODE REVIEW

**Comment by tushushu** [comment]
By reading [#8627](https://github.com/apache/arrow-datafusion/pull/8627) and [#8641](https://github.com/apache/arrow-datafusion/pull/8641), I speculated that maybe the code should be written like this, but I'm not entirely sure if the code I wrote is correct. Maybe I should read more documentation about arrow-rs in the future.

**Review by alamb — APPROVED** [review]
Thank you @tushushu  -- this PR makes sense to me. I realize it is somewhat strange that there are no fields yet but once they are added I think this PR has all the plumbing in place to add them to seriailzation easily.

Thank you

**Comment by alamb** [comment]
I took the liberty of merging this branch up from main and once the CI passes I intend to merge it in

**Comment by alamb** [comment]
Thanks again @tushushu

**Comment by tushushu** [comment]
@alamb Thanks Andrew for reviewing the PR~

**Pull request merged**
