### PR TITLE
MINOR: beautify code with neat idents

### PR DESCRIPTION
**Pull request by WinkerDu**
# Which issue does this PR close?

Closes #.

 # Rationale for this change

Careless idents exist in Some macro code of `scalar.rs`

# What changes are included in this PR?

Beautify this code with neat idents.

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by yjshen** [comment]
Is it possible to replicate your effort at https://github.com/apache/arrow-datafusion/pull/2033 here, to fix existing problems and prevent further violations?

**Comment by WinkerDu** [comment]
@yjshen 
I tried to set following configuration to `rustfmt.toml` (see [format_macro_matchers](https://rust-lang.github.io/rustfmt/?version=master&search=#format_macro_matchers) [format_macro_bodies](https://rust-lang.github.io/rustfmt/?version=master&search=#format_macro_bodies) )
```
format_macro_matchers = true
format_macro_bodies = true
```
then run `cargo fmt --all -- --check`, some warning messages raise
```
Warning: can't set `format_macro_matchers = true`, unstable features are only available in nightly channel.
Warning: can't set `format_macro_bodies = true`, unstable features are only available in nightly channel.
```
Hope to get some suggestions, thank you

**Comment by yjshen** [comment]
We do have MIRI checks that rely on nightly here: https://github.com/apache/arrow-datafusion/blob/master/.github/workflows/rust.yml#L356-L388.

What do you think if we have a macro check with rust nightly in CI as well?

**Comment by WinkerDu** [comment]
> We do have MIRI checks that rely on nightly here: https://github.com/apache/arrow-datafusion/blob/master/.github/workflows/rust.yml#L356-L388.
> 
> What do you think if we have a macro check with rust nightly in CI as well?

Sounds reasonable, I will try it later

**Comment by alamb** [comment]
Thank you for this contribution @WinkerDu

**Comment by WinkerDu** [comment]
@yjshen 
I run `cargo +nightly fmt -- --config format_macro_bodies=true --config format_macro_matchers=true --check`
Checking result is disappointing:
- No idents violation detect, such as https://github.com/apache/arrow-datafusion/blob/41b4e491663029f653e491b110d0b5e74d08a0b6/datafusion/common/src/scalar.rs#L771-L795
- Some metavariables format result is as unexpected, such as
```
Diff in /Users/duripeng/code/arrow-datafusion/arrow-datafusion/datafusion/physical-expr/src/tdigest/mod.rs at line 681:
     // A macro to assert the specified `quantile` estimated by `t` is within the
     // allowable relative error bound.
     macro_rules! assert_error_bounds {
-        ($t:ident, quantile = $quantile:literal, want = $want:literal) => {
+        ($t:ident,quantile = $quantile:literal,want = $want:literal) => {
             assert_error_bounds!(
                 $t,
                 quantile = $quantile,
Diff in /Users/duripeng/code/arrow-datafusion/arrow-datafusion/datafusion/physical-expr/src/tdigest/mod.rs at line 689:
                 allowable_error = 0.01
             )
         };
-        ($t:ident, quantile = $quantile:literal, want = $want:literal, allowable_error = $re:literal) => {
+        (
+            $t:ident,quantile =
+            $quantile:literal,want =
+            $want:literal,allowable_error =
+            $re:literal
+        ) => {
             let ans = $t.estimate_quantile($quantile);
             let expected: f64 = $want;
             let percentage: f64 = (expected - ans).abs() / expected;
```

IMO, it's better not to import macro format check for now, and just merge this pr for easily reading code?
How do you think about it?

**Review by alamb — APPROVED** [review]
Looks like a nice cleanup to me (even if we can't apply this automatically via CI)-- thank you @WinkerDu  

Using whitespace blind diff made it easier for me to double check the differences
https://github.com/apache/arrow-datafusion/pull/2295/files?w=1

**Comment by alamb** [comment]
Thanks for looking into the CI

**Comment by WinkerDu** [comment]
Thank you all ❤️

**Pull request merged**
