### PR TITLE
chore: fix catalog's usage docs error and add docs about `CatalogList` trait

### PR DESCRIPTION
**Pull request by tanruixiang**
## Which issue does this PR close?

Closes #.

## Rationale for this change
The documentation misuses `MemoryCatalogList` and missings the introduction of `CatalogList`. There are also some markdown structure issues.

## What changes are included in this PR?
Fix docs's errors and add the `CatalogList` trait content.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you @tanruixiang 

cc @tshauck  (someone is reading the documentation)

**Comment by tshauck** [comment]
nice -- thanks from me as well @tanruixiang

**Comment by tanruixiang** [comment]
Thanks to @alamb and @tshauck. I'm gathering information to introduce developers who will be using datafusion but new to datafusion to how to use datafusion. I'm happy and look forward to continuing to help the community improve the documentation.

**Comment by alamb** [comment]
> I'm happy and look forward to continuing to help the community improve the documentation.

that would be most appreciated and valuable @tanruixiang  -- it is an area that really could use more improvement and will help future users a lot. THANK YOU 🙏

**Pull request merged**
