### PR TITLE
Port tests in timestamp.rs to sqllogictest. Part 1

### PR DESCRIPTION
**Pull request by caicancai**
## Which issue does this PR close?

part of https://github.com/apache/arrow-datafusion/issues/8216

### CODE REVIEW

**Comment by caicancai** [comment]
Dont't merge

**Comment by caicancai** [comment]
2024-01-10 22-25-35屏幕截图
I found that there is a test about the now function in timestamp.slt. I don’t know if I should add it.

**Comment by caicancai** [comment]
Dot't merge

**Comment by alamb** [comment]
> @alamb Hello,excuse me
> I found that there is a test about the now function in timestamp.slt. I don’t know if I should add it.
> And if I add the select now test, the result may be fixed, but the result of now is changing all the time, which may have an impact on the project itself.

Hi @caicancai  -- if there are tests that can't be ported to sqllogictest (for example, that now() doesn't change across session statements) can you please put a comment on them saying something like "can't write this in sqllogictest, so use a rust test" and just leave them in timestamp.rs?

Thank you 🙏

**Review by comphead — COMMENTED** [review]
I think `now` can still be ported, its not stable value, but we can do it quasi stable like

```
select now() = current_time
```
or 
```
select now() > to_date('2023-01-01')
```

**Comment by caicancai** [comment]
> I think `now` can still be ported, its not stable value, but we can do it quasi stable like
> 
> ```
> select now() = current_time
> ```
> 
> or
> 
> ```
> select now() > to_date('2023-01-01')
> ```

Thank you for your reply. I noticed that the original timestamp.slt already has some tests belonging to now. I am not sure whether to continue adding them.

**Review by comphead — COMMENTED** [review]
Thanks for double checking `now()` is in `timestamp.slt`, I also verified that and looks like test in slt for now is enough, and now I'm wondering if we still need `timestamp.rs`?

**Review by alamb — APPROVED** [review]
Thank you @caicancai  -- this looks like a good improvement to me. Perhaps we can investigate @comphead 's question about needing timestamp.rs at all as part of a follow on PR

**Comment by caicancai** [comment]
> Thanks for double checking `now()` is in `timestamp.slt`, I also verified that and looks like test in slt for now is enough, and now I'm wondering if we still need `timestamp.rs`?

From a personal point of view, I agree

**Review by comphead — APPROVED** [review]
lgtm @caicancai thanks.
I think it will be good to create a followup ticket to move remaining tests. I went trhough them real quick they looks migratable imho

**Pull request merged**
