### PR TITLE
Remove date code no longer needed since arrow-rs PR 2031 merge

### PR DESCRIPTION
**Pull request by avantgardnerio**
# Which issue does this PR close?

Closes this comment https://github.com/apache/arrow-datafusion/pull/3110#discussion_r945973316

 # Rationale for this change

We added code that is no longer needed, thanks to upstream merges in `arrow-rs` & `chrono`

# What changes are included in this PR?

Removal of temporary code.

# Are there any user-facing changes?

The requirement to have a newer chrono.

### CODE REVIEW

**Comment by avantgardnerio** [comment]
@alamb heads up!

**Comment by alamb** [comment]
Looks great -- the CI hasn't yet run on this PR, but when it does I am feeling good about it 👍

**Comment by alamb** [comment]
Screen Shot 2022-08-15 at 2 50 31 PM

🤔  github claims it has conflicts -- maybe it needs a rebase against master?

**Comment by avantgardnerio** [comment]
> thinking github claims it has conflicts -- maybe it needs a rebase against master?

Unfortunately due to the implementation of this:

[xxx](https://github.com/apache/arrow-datafusion/blob/15a9a4becc4bb41262b10f1d5395fc1d026de753/datafusion/physical-expr/src/expressions/datetime.rs#L295)

I think we have to wait for this:

https://github.com/chronotope/chrono/pull/778

So that we can do this:

```
fn do_date_math<D>(prior: D, scalar: &ScalarValue, sign: i32) -> Result<D>
where
    D: Datelike + Add<Duration, Output = D> + Add<Months, Output = D>,
```

**Pull request closed without merging**
