### PR TITLE
support cross_join in `limit_push_down`

### LINKED ISSUE #4256: Current `limit_push_down` can't support cross_join
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #4256.

# Rationale for this change

# What changes are included in this PR?

- support limit-push-down with cross_join
- add UT

# Are these changes tested?

- cross-join meet limit
- cross-join meet limit-with-skip

# Are there any user-facing changes?

### CODE REVIEW

**Review by waynexia — APPROVED** [review]
Looks good to me, it's well tested 👍

**Comment by jackwener** [comment]
cc @liukun4515 @andygrove @alamb

**Review by liukun4515 — APPROVED** [review]
Thanks @jackwener

**Comment by liukun4515** [comment]
I think we can also optimize `limit - FULL Join` pattern. @jackwener

**Comment by liukun4515** [comment]
> I think we can also optimize `limit - FULL Join` pattern. @jackwener

This thought has bug, will close this issue.

**Comment by alamb** [comment]
👌

**Pull request merged**
