### PR TITLE
fix and update window function sql tests

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

fix and update window function sql tests, because for window functions without `order by` the nth value calls do not make sense

Closes #.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Dandandan** [comment]
Changes are looking good to make the tests deterministic. I think it might be worthwhile to add now or later some tests for the now missing cases (first/last/nth) for non-ordered windows in empty over or only having `partition by`.

**Review by alamb — APPROVED** [review]
Thank you @Jimexist !

> do not make sense

Another way to put it is that the answers are not well defined :)

Practically speaking this will help with the upgrade to `arrow` 6.0 as well (https://github.com/apache/arrow-datafusion/pull/984) where sorting has become non-stable and thus can vary more

The python failure looks unrelated:
https://github.com/apache/arrow-datafusion/pull/1059/checks?check_run_id=3718965175

**Comment by alamb** [comment]
I restarted the python test and we'll see what happens

**Comment by alamb** [comment]
Also, it should be said, this also helps along the `arrow2` work: https://github.com/apache/arrow-datafusion/pull/68

**Comment by alamb** [comment]
Thanks @Jimexist

**Pull request merged**
