### PR TITLE
array[] / make_array() will error if the types can not be coerced to a common type

### LINKED ISSUE #3170: `array[]` / `make_array()` will error if the types can not be coerced to a common type
**Describe the bug**
`make_array()` will error if the types can not be coerced to a common type, as in postgres and spark

**To Reproduce**

Run this query (see `query_array_scalar_coerce` test added in https://github.com/apache/arrow-datafusion/pull/3122)

```sql
SELECT [1, 2, '3']
```

This results in an error:

```
"Error during planning: Coercion from [Int64, Int64, Utf8] to the signature VariadicEqual failed.",);
```

**Expected behavior**
I expect this to return like postgres where it has coerced all the arguments to int (tried to coerce all arguments to the same type as the first, which in this case is `1` and thus `int`

```shell
alamb=# select array[1, 2, '3'];
  array  
---------
 {1,2,3}
(1 row)
```

**Additional context**
Found in https://github.com/apache/arrow-datafusion/pull/3122

### PR DESCRIPTION
**Pull request by comphead**
# Which issue does this PR close?

Closes #3170 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by comphead** [comment]
@alamb please provide your input here.
Since there are 2 diff codebases, the error messages are also different
`Coercion from [Int64, Utf8] to the signature Variadic([Int64]) failed` vs `Cannot cast string 'a' to value of Int64 type`

`make_array` is scalar function, I was thinking to make `array` or `[]` as aliases to use the same code, but I cant find where `array/[]` comes from, tbh.

Your input highly appreciated

**Comment by comphead** [comment]
@alamb if you dont mind to address this

**Comment by alamb** [comment]
Sorry I don't have time to address this problem / potential solution :( Maybe someone else can chime in with some thoughts

**Comment by alamb** [comment]
Closing as this PR is over a year old. Please feel free to reopen it / rebase it if you plan to keep working on it

**Pull request closed without merging**
