### PR TITLE
enhance the checking of type errors in the test `window_frame_creation`

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>

# Which issue does this PR close?

None.
Related to #4685.

# Rationale for this change

We should test the type errors in a query could be detected from either the logical plan (skip_failed_rules = false) or the physical plan (skip_failed_rules = true).

# What changes are included in this PR?
Only update the test.

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by HaoYang670** [comment]
@jackwener  @alamb could you please help to review? Thank you!

**Review by jackwener — APPROVED** [review]
Look great to me. Thank you @HaoYang670.
This PR is same with #5224.
I prepare polish them like this PR.

**Review by alamb — APPROVED** [review]
Thanks @HaoYang670  and @jackwener 

I think @mustafasrepo  and @metesynnada  may be interested in these changes (to improve error checking / move the type checks out of physical plan creation and into logical plan creation)

**Comment by mustafasrepo** [comment]
LGTM!. This enables us to add tests for skipped errors. Thank you @HaoYang670.

**Pull request merged**
