### PR TITLE
Add Decimal256 sqllogictests for SUM, MEDIAN and COUNT aggregate expressions

### LINKED ISSUE #7888: Add Decimal256 sqllogictests for SUM, MEDIAN and COUNT aggregate expressions
### Is your feature request related to a problem or challenge?

Except for newly added Decimal256 support of AVG, MIN/MAX, SUM and MEDIAN already have Decimal256 support but lack of sqllogictests tests.

### Describe the solution you'd like

Add Decimal256 sqllogictests for SUM, MEDIAN and COUNT aggregate expressions

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #7888.

### CODE REVIEW

**Review by comphead — APPROVED** [review]
lgtm
Thanks @viirya 

One question `Except for newly added Decimal256 support of AVG, MIN/MAX, SUM and MEDIAN already have Decimal256 support but lack of sqllogictests tests.`

should we also add tests for AVG, MIN/MAX, COUNT?

**Comment by viirya** [comment]
> should we also add tests for AVG, MIN/MAX, COUNT?

Yea, they are already added.

**Comment by viirya** [comment]
Oh, `count` isn't. I just added it.

**Review by alamb — APPROVED** [review]

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
Thanks @viirya

**Comment by viirya** [comment]
Thank you @Dandandan @alamb @comphead

**Pull request merged**
