### PR TITLE
Improve error handling for array downcasting

### PR DESCRIPTION
**Pull request by retikulum**
# Which issue does this PR close?

Discussed in #3152 .

# Rationale for this change

This is the new PR in series to improve error handling for downcasting.
# What changes are included in this PR?

- Add `as_xxx_array` functions for following types to downcast:
  - `MapArray`
  - `NullArray`
  - `UnionArray`
  - `TimestampNanosecondArray`
  - `TimestampMillisecondArray`
  - `TimestampMicrosecondArray`
  - `TimestampSecondArray`
  - `BinaryArray`

### CODE REVIEW

**Comment by retikulum** [comment]
Is there any problem about `cargo test pyarrow` check? Other newly opened PRs are also failed on this test. It seems that problem is in the installation part.

image

**Comment by alamb** [comment]
> Is there any problem about cargo test pyarrow check? Other newly opened PRs are also failed on this test. It seems that problem is in the installation part.

I agree there is some problem (maybe @isidentical  has some idea). I haven't had a chance to look at the check recently and I am nearing my end of day here. If no one has figured it out tomorrow I'll look into it

**Comment by alamb** [comment]
Check got fixed in https://github.com/apache/arrow-datafusion/pull/4450

**Review by alamb — APPROVED** [review]
Looks great to me -- thank you @retikulum

**Pull request merged**
