### PR TITLE
[MINOR] Change `downcast_value!` macro so it does not need to use `use std::any::type_name;`

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?
N/A

 # Rationale for this change
@iajoiner  added `downcast_value!` in #3347 which is awesome 👏 . @andygrove suggested I use `downcast_value!` in https://github.com/apache/arrow-datafusion/pull/3454#discussion_r970072753 which was also a great idea. 

I noticed I had to add a `use` statement however:

```rust
use std::any::type_name;
```

I figured it would clean up the code and future uses of `downcast_value!` if users didn't have to manually add a `use` as well

# What changes are included in this PR?
1. add `use std::any::type_name;` to the macro definition
2. remove now redundant `use std::any::type_name;` around the codebase 

# Are there any user-facing changes?
No

### CODE REVIEW

**Comment by iajoiner** [comment]
@alamb Thanks! There is also a bug that can be fixed either now or in my next PR. The T in the macro need to be $T.

**Comment by alamb** [comment]
> @alamb Thanks! There is also a bug that can be fixed either now or in my next PR. 

I'll make a PR for it

**Comment by alamb** [comment]
PR for bug fix: https://github.com/apache/arrow-datafusion/pull/3486

**Review by waynexia — APPROVED** [review]
Nice improvement 👍 Only the PR title should be `downcast_value` rather than `downcast_any` 😃

**Pull request merged**
