### PR TITLE
add tpch sqllogicaltest and remove some duplicated test

### LINKED ISSUE #4801: add sqllogicaltest for tpch and remove some duplicated test.
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #4801.

# Rationale for this change

I just want to remove tpch in Unit-Test, because it's duplicated with independent test for TPCH.
But these UT contains some data-test, so I add sqllogicaltest for it.

# What changes are included in this PR?

- add tpch sqllogicaltest
- remove some duplicated test. 

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by jackwener** [comment]
Some query result is strange, but run successfully.🤔

**Comment by andygrove** [comment]
These tests are really to check that subqueries get rewritten as joins rather than being about tpch. The change in the test here just checks for correct results and does not check the details of how the plans are rewritten, so I feel like we are losing some value with this change. However, we also check for expected plans in tpch so maybe this is fine. Would be good to check with @avantgardnerio who originally implemented these tests, or @iajoiner.

**Comment by jackwener** [comment]
> These tests are really to check that subqueries get rewritten as joins rather than being about tpch. The change in the test here just checks for correct results and does not check the details of how the plans are rewritten, so I feel like we are losing some value with this change. However, we also check for expected plans in tpch so maybe this is fine. Would be good to check with @avantgardnerio who originally implemented these tests, or @iajoiner.

But these test already exist, they are same with tpch-test.

like 
- https://github.com/apache/arrow-datafusion/blob/master/benchmarks/expected-plans/q2.txt
- https://github.com/apache/arrow-datafusion/blob/master/benchmarks/expected-plans/q4.txt
- https://github.com/apache/arrow-datafusion/blob/master/benchmarks/expected-plans/q17.txt
- https://github.com/apache/arrow-datafusion/blob/master/benchmarks/expected-plans/q20.txt

**Comment by jackwener** [comment]
> These tests are really to check that subqueries get rewritten as joins rather than being about tpch. The change in the test here just checks for correct results and does not check the details of how the plans are rewritten, so I feel like we are losing some value with this change. However, we also check for expected plans in tpch so maybe this is fine. Would be good to check with @avantgardnerio who originally implemented these tests, or @iajoiner.

My mistake🥲, after a careful comparison, I find that they are not exactly the same .

**Review by alamb — APPROVED** [review]
Thank you @jackwener 

Unless I hear otherwise from anyone I plan to merge this PR in the next day or two

I think it is a significant testing improvement -- given we now have the proper tpch test in https://github.com/apache/arrow-datafusion/blob/169b5228800f991be913b10ffdfd161e2cbc7baf/.github/workflows/rust.yml#L126-L165 I am not even sure the new slt test is adding much value 🤔

**Pull request merged**
