### PR TITLE
cleanup(tests): Move tests from `push_down_projections.rs` to `optimize_projections.rs`

### LINKED ISSUE #9978: Consolidate push_down_projection tests under optimize_projections
### Is your feature request related to a problem or challenge?

#8340 removed push_down_projection rules in favour of optimize_projections

### Describe the solution you'd like

Move tests in [push_down_projection.rs](https://github.com/apache/arrow-datafusion/blob/d201ec742b08fa2a0549fc27f0b39622d67391ab/datafusion/optimizer/src/push_down_projection.rs) to [optimize_projections.rs](https://github.com/apache/arrow-datafusion/blob/d201ec742b08fa2a0549fc27f0b39622d67391ab/datafusion/optimizer/src/optimize_projections.rs) and remove the `push_down_projection.rs` file

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kavirajk**
## Which issue does this PR close?

Closes #9978

## Rationale for this change
The PR #8340 removed `push_down_projections.rs` in favour of `optimize_projections.rs`. This PR moves the tests as well.

## What changes are included in this PR?
Moving tests. No other changes.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @kavirajk  🙏 !

**Review by alamb — APPROVED** [review]
Thank you @kavirajk  -- this is a very nice first contribution. 🧹 ✅ 

FYI @mustafasrepo and @jackwener

**Review by mustafasrepo — APPROVED** [review]
Thanks for this PR.

**Comment by alamb** [comment]
Thanks again @kavirajk

**Pull request merged**
