### PR TITLE
generate new projection plan in inline_table_scan instead of discarding

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #.

# Rationale for this change

In origin rule, we will discard all `projection` in `table_scan`.
This isn't a best choice. we can remain it.

# What changes are included in this PR?

generate new `projection` plan accord by original `projection` in `table_scan`.

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Dandandan** [comment]
👍  can we add a test as well?

**Comment by jackwener** [comment]
> 👍 can we add a test as well?

Added it

**Review by alamb — APPROVED** [review]
I think this code looks fine, but I don't understand the rationale for the change (e.g none of the overall plans changed) Maybe it is part of a larger project?

**Comment by jackwener** [comment]
> I think this code looks fine, but I don't understand the rationale for the change (e.g none of the overall plans changed) Maybe it is part of a larger project?

Yes! It's related with this #5366.

When I try to eliminate unnecessary projection. This will cause a bug.

**Comment by jackwener** [comment]
Thanks @Dandandan and @alamb

**Pull request merged**
