### PR TITLE
Minor: consolidate map sqllogictest tests

### PR DESCRIPTION
**Pull request by alamb**
## Which issue does this PR close?

Minor follow on to https://github.com/apache/arrow-datafusion/pull/8501 from @razeghi71 

## Rationale 

I think the test added in https://github.com/apache/arrow-datafusion/pull/8501 would be easier to find if they were in the existing `map.slt` file

## What changes are included in this PR?
1. Move test with map array to `map.slt`

## Are these changes tested?
only tests

### CODE REVIEW

**Review by comphead — APPROVED** [review]
lgtm thanks @alamb 
btw what do you think about adding a mandatory description on the test query and eventually output it?

**Comment by alamb** [comment]
> lgtm thanks @alamb btw what do you think about adding a mandatory description on the test query and eventually output it?

Thanks @comphead  -- I am not quite sure what you mean

Do you mean require a comment on each query that explains what is expected? It sounds reasonable to me, though if we aren't careful we'll end up with comments like `# ensure correct output` which probably don't add much value

**Comment by comphead** [comment]
> > lgtm thanks @alamb btw what do you think about adding a mandatory description on the test query and eventually output it?
> 
> Thanks @comphead -- I am not quite sure what you mean
> 
> Do you mean require a comment on each query that explains what is expected? It sounds reasonable to me, though if we aren't careful we'll end up with comments like `# ensure correct output` which probably don't add much value

composing a correct description can be part of review.

**Comment by alamb** [comment]
> composing a correct description can be part of review.

I agree this would be great. I am just wondering how to make it happen -- if the review requires human intervention anyways, I am not sure automation will help 🤔

**Pull request merged**
