### PR TITLE
Fix wrong projection 'optimization'

### LINKED ISSUE #264: Wrong result from projection
**Describe the bug**
Projection is removed when it contains the same fields.
This 

**To Reproduce**

```sql

> select (1+1) as a from (select 1 as a);
+---+
| a |
+---+
| 1 |
+---+
1 rows in set. Query took 0 seconds.;
```

**Expected behavior**
Should return 2 instead of reusing the expression from the field.

**Additional context**
The bug seems to originate from the `project` function https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/sql/planner.rs#L652 .
I think when we remove the "optimization" to get rid of the projection, the query will return the correct result.
Removal of any redundant projections should move to a properly tested optimization pass rather than in the sql -> logical plan planner.

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #264

 # Rationale for this change
SQL planning to logical plan had a wrong rule: whenever the schema fields names were equal, it applies an "optimization" to remove the projection. 
I found this while working on the `SELECT DISTINCT`.
If we want to have an optimization pass like this, it should look at whether the expressions are equal instead and I think it would be better to include as a real optimization rule instead of while building the logical plan from the query.

# What changes are included in this PR?

Skip the "optimization".

# Are there any user-facing changes?

No.

### CODE REVIEW

**Review by returnString — COMMENTED** [review]
Nice catch! Though looks like removing the optimisation breaks a crapload of logical plan text assertions in the tests that now contain an extra top-level projection node :(

Could we retain the optimisation but only apply it when `expr` consists entirely of simple column refs? Not sure if that'd patch up all the tests or not.

**Comment by Dandandan** [comment]
> Nice catch! Though looks like removing the optimisation breaks a crapload of logical plan text assertions in the tests that now contain an extra top-level projection node :(
> 
> Could we retain the optimisation but only apply it when `expr` consists entirely of simple column refs? Not sure if that'd patch up all the tests or not.
> 
> Edit: or we could just modify the test assertions, I suppose, if we want to keep the initial planning process simple and do this kind of optimisation later?

Thanks @returnString !
I will have a look later. I think it would be best to update the tests instead for now.

I think the optimization also doesn't improve performance that much, as the projection with just the fields should be almost "free" in DF. I will add an issue to add the optimization as a rule.

**Comment by houqp** [comment]
+1 for moving this to a separate optimization rule instead of doing it within the SQL planner.

**Review by returnString — APPROVED** [review]

**Comment by Dandandan** [comment]
Merging this - seems a uncontroversial change / correctness improvement. Adding an issue for bringing back an optimization to get rid of unnecessary projections.

**Comment by alamb** [comment]
Thank you for this @Dandandan  👍

**Pull request merged**
