### PR TITLE
Address typo in ExprVisitable trait documentation

### PR DESCRIPTION
**Pull request by jdye64**
# Which issue does this PR close?

N/A very small change and CONTRIBUTING.md lead me to believe it was not needed. If indeed an issue is required I'm happen to open one.

 # Rationale for this change
Simple typo in documentation that presents itself in the docs

# What changes are included in this PR?
single line change of docs

# Are there any user-facing changes?
No

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
LGTM. No need for an issue for a small change like this.

**Comment by yjshen** [comment]
```rust
struct Print{}

impl ExpressionVisitor for Print {
    fn pre_visit(self, expr: &Expr) -> datafusion_common::Result<Recursion<Self>> where Self: ExpressionVisitor {
        println!("pre {}", expr);
        Ok(Recursion::Continue(self))
    }

    fn post_visit(self, expr: &Expr) -> datafusion_common::Result<Self> {
        println!("post {}", expr);
        Ok(self)
    }
}

#[test]
fn a() {
    let a = BinaryExpr {
        left: Box::new(Expr::Column(Column::from_name("foo"))),
        op: Operator::Gt,
        right: Box::new(Expr::Column(Column::from_name("bar")))
    };
    a.accept(Print{}).unwrap();
}
```
and I get
```
pre #foo > #bar
pre #foo
post #foo
pre #bar
post #bar
post #foo > #bar
```

**Comment by yjshen** [comment]
```rust
struct Print{}

impl ExpressionVisitor for Print {
    fn pre_visit(self, expr: &Expr) -> datafusion_common::Result<Recursion<Self>> where Self: ExpressionVisitor {
        println!("pre {}", expr);
        Ok(Recursion::Continue(self))
    }

    fn post_visit(self, expr: &Expr) -> datafusion_common::Result<Self> {
        println!("post {}", expr);
        Ok(self)
    }
}

#[test]
fn a() {
    let a = BinaryExpr {
        left: Box::new(Expr::Column(Column::from_name("foo"))),
        op: Operator::Gt,
        right: Box::new(Expr::Column(Column::from_name("bar")))
    };
    a.accept(Print{}).unwrap();
}
```
and I get
```
pre #foo > #bar
pre #foo
post #foo
pre #bar
post #bar
post #foo > #bar
```

**Comment by houqp** [comment]
@jdye64 I think the order that @yjshen printed should the be right order instead?

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/pull/1996

**Comment by jdye64** [comment]
I agree. I had simply noticed the multiple instances of "bar" and just naively assumed it should have been changed to "foo". Would you like another PR since this one is merged now or just another commit to this branch?

**Comment by jdye64** [comment]
Nevermind. Noticed @alamb PR #1996 after sending my previous message.

**Comment by alamb** [comment]
> I agree. I had simply noticed the multiple instances of "bar" and just naively assumed it should have been changed to "foo". Would you like another PR since this one is merged now or just another commit to this branch?

@jdye64  thank you -- this PR definitely made the comment *more* correct than it was lol

**Pull request merged**
