### PR TITLE
Left join could use bitmap for left join instead of Vec<bool>

### LINKED ISSUE #240: Left join could use bitmap for left join instead of `Vec<bool>`
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
To save some memory usage, and potentially also is faster, the data in`visited_left_side` in the `HashJoinStream` could be stored in a bitmap instead of a `Vec<bool>`. This would save ~7/8 byte per left row.
If we store _only_ 32 bit integers on the left, the savings would be ~4-5% assuming we use 4 bytes for the items and roughly 16 bytes per left side row for the hasmap. Not too big, but a nice win in some cases. This could be bigger when we use a more memory-efficient data-structure for the hashmap.

Additionally, in case every row is not matches or no row is unmatched, it could include a fast path for those cases.

**Describe the solution you'd like**
Use a bitmap instead of `Vec<bool>`. The bitmap could be from arrow or maybe the `bitvec` crate.

**Describe alternatives you've considered**
Keep using a `Vec<bool>`

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by boazberman**
# Which issue does this PR close?

Depends on: https://github.com/apache/arrow-rs/pull/693
Closes #240 .
This is a new version (arrow native) of: https://github.com/apache/arrow-datafusion/pull/342 (which is also me, from the company account)

 # Rationale for this change

Described in the issue.

# What changes are included in this PR?

Described in the issue.

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by boazberman** [comment]
The build will fail due to the fact it relies on an new api to `BooleanBufferBuilder` which is under this PR: https://github.com/apache/arrow-rs/pull/693

Please let me know what If you need anything else on my side to make this happen. Thanks! (cc @alamb that corresponded with me on the previous PR)

**Review by Dandandan — APPROVED** [review]
Looks good to me (if it's integrated to arrow)👍 thanks @boazberman , nice addition!

**Comment by alamb** [comment]
FYI assuming we merge + backport https://github.com/apache/arrow-rs/pull/693 (which seems likely) it would be available in arrow-rs 5.3.0 (target release date in about 2 weeks time). Thank you very much for sticking with this @boazberman

**Review by alamb — APPROVED** [review]
Looks very nice ❤️  -- thank you @boazberman

**Comment by houqp** [comment]
Nice work @boazberman ! I wish there is automated benchmark report against master so we get to see the sweet performance gain number :) I vaguely remember ursalabs built a tool for this particular use-case for the main arrow repo.

**Comment by alamb** [comment]
Closing a seemingly stale PR -- please reopen if that was a mistake.

**Pull request closed without merging**
