### PR TITLE
delete tail space, fix `error: unused import: DataFusionError`

### PR DESCRIPTION
**Pull request by Tangruilin**
## Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/9387

## What changes are included in this PR?

delete some tail space

Also fixes a CI failure: https://github.com/apache/arrow-datafusion/actions/runs/8083720466/job/22087560300

### CODE REVIEW

**Comment by Tangruilin** [comment]
@alamb  Maybe you can look at this, I delete some tail space

**Review by alamb — APPROVED** [review]
Looks good to me. Thank you @Tangruilin

**Comment by alamb** [comment]
This also fixes a failure on main: https://github.com/apache/arrow-datafusion/actions/runs/8083720466/job/22087560300

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/9387 for the CI failure and linked it to this PR

**Comment by alamb** [comment]
I plan to merge this PR when it passes CI

**Comment by alamb** [comment]
Thanks again @Tangruilin

**Pull request merged**
