### PR TITLE
Fix optimizer regressions

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/3690

 # Rationale for this change

PR https://github.com/apache/arrow-datafusion/pull/3662 introduced regressions that were not detected due to a lack of test cases and also due to the fact that we default to `skip_failing_rules = true`.

# What changes are included in this PR?

- Adds tests for the regressions
- Reverts https://github.com/apache/arrow-datafusion/pull/3662

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by andygrove** [comment]
@alamb @liukun4515 This PR is one solution for fixing the recent regressions introduced into the optimizer - by reverting the PR that introduced them - but maybe @liukun4515 can fix these issues in a separate PR, then we won't need to merge this one.

**Comment by liukun4515** [comment]
> @alamb @liukun4515 This PR is one solution for fixing the recent regressions introduced into the optimizer - by reverting the PR that introduced them - but maybe @liukun4515 can fix these issues in a separate PR, then we won't need to merge this one.

I have done the enhancement to fix the bug in https://github.com/apache/arrow-datafusion/pull/3699

**Comment by alamb** [comment]
@andygrove  can you verify your dask tests work now?

The two tests described above are included now in the optimizer integration test by @liukun4515 : https://github.com/apache/arrow-datafusion/blob/57312284c082c914dd5e1edaa5c1fe3dbe4f222d/datafusion/optimizer/tests/integration-test.rs#L33-L57

**Comment by andygrove** [comment]
Closed in favor of https://github.com/apache/arrow-datafusion/pull/3699

https://github.com/apache/arrow-datafusion/pull/3699 fixes some of the regressions :+1:  but there are are more. I will file a new issue shortly once I have a good repro case.

**Pull request closed without merging**
