### PR TITLE
change result type of count/count_distinct from uint64 to int64

### LINKED ISSUE #2635: The result type of count/count_distinct
**Describe the bug**
Now, the result type of count is `UINT64` in the current version.

From the pg document, https://www.postgresql.org/docs/current/functions-aggregate.html

We get that 

```
count ( * ) → bigint

Computes the number of input rows.
```

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

Closes #2635
From the #2635, the result type of count is `uint64` and this is not compatible with PG and other db system.

This pr just convert the result type from `uint64` to `int64`

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

# Does this PR break compatibility with Ballista?

### CODE REVIEW

**Comment by liukun4515** [comment]
@alamb @andygrove PTAL

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @liukun4515

**Review by alamb — APPROVED** [review]
Looks like `COUNT` has been `u64` a long time in DataFusion ( I remembered vaguely that this got changed recently, but I can't find evidence of that)

FWIW I think postgres returns `i64` because it has no distinction between `u64` and `i64`; https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-INT

**Comment by alamb** [comment]
Thanks @liukun4515  and @andygrove !

**Pull request merged**
