### PR TITLE
Optimize MergeJoin by storing joined indices instead of creating small record batches for each match

### LINKED ISSUE #2491: Sort-merge join optimization by avoiding too many small batches
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

currently, sort-merge join creates one temporary record batch for each joined key, which results in many small batches and bad performance.

**Describe the solution you'd like**

to achieve better performance, we can only store indices of joined pairs and generate a bigger record batch when the number of stored indices reaches the target batch size.

**Describe alternatives you've considered**

row format with JIT is hopefully a better solution in the joining scenario.

**Additional context**

fuzzy testing with inner joining 1,000,000 integers:
the original implementation:
```
real	0m32.045s
user	0m30.868s
sys	0m1.136s
```

improved implementation:
```
real	0m3.367s
user	0m2.242s
sys	0m1.048s
```

### PR DESCRIPTION
**Pull request by richox**
# Which issue does this PR close?

Closes #2491 .

 # Rationale for this change

# What changes are included in this PR?

store joined indices instead of creating small record batches, achieving better performance.

fuzzy testing with inner joining 1,000,000 integers:
the original implementation:
```
real	0m32.045s
user	0m30.868s
sys	0m1.136s
```
improved implementation:
```
real	0m3.367s
user	0m2.242s
sys	0m1.048s
```
# Are there any user-facing changes?

### CODE REVIEW

**Review by yjshen — APPROVED** [review]
Looks great to me, thanks @richox!

**Comment by alamb** [comment]
cc @Dandandan

**Comment by Dandandan** [comment]
This looks really cool @richox impressive benchmark result 🎉

**Comment by Dandandan** [comment]
I do not have time to look into detail coming days, feel free to merge when it's ready

**Comment by yjshen** [comment]
Thanks @richox @Dandandan @alamb, I'm merging this and we could always iterate from here.

**Pull request merged**
