### PR TITLE
make page filter public

### PR DESCRIPTION
**Pull request by jiacai2050**
# Which issue does this PR close?

Closes #.

# Rationale for this change

We at CeresDB are using a customized parquet reader based on parquet-rs for some historical reason, in order to reuse those page prune functions from datafusion, those interface should be public.

# What changes are included in this PR?
- Public page_filter related API.

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
This is a fine change in my mind -- @jiacai2050  can you comment about why you would like to have this API public ? I didn't see any rationale or a linked ticket?

Also if you want to use this API long term I suggest we implement an end to end test (maybe in datafusion/core/tests/parquet somewhere) for it so that it isn't broken accidentally in some future refactor

**Comment by jiacai2050** [comment]
@alamb Thanks, I'm still testing this changeset in CeresDB, I will add more context once I'm done.

> Also if you want to use this API long term I suggest we implement an end to end test (maybe in datafusion/core/tests/parquet somewhere) for it so that it isn't broken accidentally in some future refactor

Agreed!

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
This PR still says "WIP" in the title so I am not sure if you think it is ready to merge @jiacai2050  -- or if you plan to work on an end to end test before doing so?

**Comment by alamb** [comment]
I believe if you merge up to latest main branch the clippy failure has been resolved.

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
It appears that `cargo doc` wants documentation for public structures, so the structures that are now `pub` need documentation to pass CI

**Comment by alamb** [comment]
THanks @jiacai2050

**Pull request merged**
