### PR TITLE
Fix inconsistent array type for binary numerical operators result between array and scalar

### LINKED ISSUE #6243: Aggregation with group by cannot work for Dictionary array
### Describe the bug

We fixed some Dictionary input issue for aggregate functions like `sum` and `avg` in #6197. But we also found another issue of Dictionary input. Aggregation with group by cannot work for Dictionary array.

### To Reproduce

I've added test cases in `datafusion/core/tests/sqllogictests/test_files/aggregate.slt`.

```
DataFusion error: External error: Arrow error: Invalid argument error: RowConverter column schema mismatch, expected Int64 got Dictionary\(Int64, Int64\)
select sum(x_dict) from value_dict group by x_dict % 2;
```

### Expected behavior

Aggregation with group by should work with Dictionary array.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #6243.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Given that that queries that used to fail pass with this change I think it is a step forward in the right direction. 

As I understand it this code will force the output of an expression back to non dictionary at query time. 

Now that some of the kernels actually support dictionary encoded arrays natively, I wonder if it would be possible to maintain the dictionary encoding as part of the coercion rules (rather than coercing the output to a primitive type)?

https://github.com/apache/arrow-datafusion/blob/2e9beeba01b85afb6d4f6557201e673008ea9edd/datafusion/expr/src/type_coercion/binary.rs#L475-L483

**Comment by alamb** [comment]
Thank you @viirya

**Comment by viirya** [comment]
> Now that some of the kernels actually support dictionary encoded arrays natively, I wonder if it would be possible to maintain the dictionary encoding as part of the coercion rules (rather than coercing the output to a primitive type)?

For mathematics numerical kernels, the returned type of two dictionary input arrays is primitive array. So for `mathematics_numerical_coercion`, this looks still correct.

**Comment by alamb** [comment]
> For mathematics numerical kernels, the returned type of two dictionary input arrays is primitive array. So for mathematics_numerical_coercion, this looks still correct.

Yeah, I guess I was thinking it would nice to avoid the unpacking of the dictionary result into a primitive array (when possible)

**Comment by viirya** [comment]
> Yeah, I guess I was thinking it would nice to avoid the unpacking of the dictionary result into a primitive array (when possible)

I meant, for mathematics numerical kernels (e.g. add, minus etc.), the result of operation between two dictionary arrays is primitive array. We don't unpack dictionary array into primitive array. This is why the coercion rule specifies the result type of such op as primitive type instead of dictionary of it.

But for such op between dictionary and a scalar, the result is dictionary array as for such op it can simply apply on dictionary values which is not the same for above case (dictionary and dictionary). So the inconsistency (primitive for dictionary/dictionary and dictionary for dictionary/scalar) leads to the bug we saw.

We can either changing primitive result of op on dictionary/dictionary to dictionary, or changing dictionary result of op on dictionary/scalar to primitive. This takes the later one as a fix. One reason is that this is simply to apply to fix the issue now. Another reason is that I'm not sure packing op result of dictionary/dictionary as dictionary making sense. It is doable but considering dictionary encoding during mathematics numerical op, it might be introducing performance penalty. I'll find some time trying that.

**Comment by viirya** [comment]
Thanks @alamb. I will find some time looking at the possibility to packing primitive result of math kernels on dictionary/dictionary as dictionary.

**Pull request merged**
