### PR TITLE
support large-utf8 in groupby

### PR DESCRIPTION
**Pull request by ritchie46**
This PR adds support for `LargeUtf8` in groupby operations. 

~Administrative question, Do I need to create an addtional issue?~

Closes https://github.com/apache/arrow-datafusion/issues/38

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Looks good @ritchie46 -- thank you!

I think all that is missing is some sort of test that exercises this codepath (to ensure that we don't accidentally break / regress in this functionality in the future)

Perhaps you might following the model of `group_by_dictionary`: https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/execution/context.rs#L1650

**Comment by alamb** [comment]
> Administrative question, Do I need to create an addtional issue?

Yes, please do -- we are hoping to use issues to create the changelog for each release

**Review by returnString — APPROVED** [review]

**Comment by ritchie46** [comment]
> Looks good @ritchie46 -- thank you!
> 
> I think all that is missing is some sort of test that exercises this codepath (to ensure that we don't accidentally break / regress in this functionality in the future)
> 
> Perhaps you might following the model of `group_by_dictionary`: https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/execution/context.rs#L1650

Thanks, for pointing me in the direction. I still need to get a bit more familiar with this code base.

**Review by alamb — APPROVED** [review]
Looks good - thanks @ritchie46

**Pull request merged**
