### PR TITLE
change SQL numeric literals from float to decimal

### LINKED ISSUE #3394: change SQL non-integer numeric literal type from Float64 to Decimal128
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

Per discussion on #166 , capturing for example `1.1` in the SQL literal as a Decimal results in accurate numbers, especially during expression simplification, where a Float can result in wrong data. Postgres also captures these literals as decimals.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by kmitchener**
# Which issue does this PR close?

Closes #3394.

 # Rationale for this change

This introduces Decimal type in place of Float for numeric SQL literals.

# What changes are included in this PR?

This PR:
* makes the change to Decimal128 from Float64
* consolidates the logic for converting the number string we get from the parser to Int64 or Decima128 types
* it also comments out tests that fail due to related bugs in the epic #3480

# Are there any user-facing changes?

### CODE REVIEW

**Comment by kmitchener** [comment]
I want to highlight that I've entered issues (tracked in #3480) and commented out tests for some things that broke when using Decimal128. It does feel a bit like Decimal128 has some maturing to do to match the quality of the other numeric datatypes. But I wanted to submit this PR anyway -- if we're committed to making the change to decimal type in this way, then getting it in master is a good way to get additional eyes (and bigger brains than mine) on it.

**Comment by Jimexist** [comment]
i think this change to UX is a bit too big. can we actually allow some of these functions to auto-convert from decimal to double or vice versa? i don't think asking existing queries to annotate `::double` is helpful for adoption in the long term

**Comment by alamb** [comment]
> I want to highlight that I've entered issues (tracked in https://github.com/apache/arrow-datafusion/issues/3480) and commented out tests for some things that broke when using Decimal128. It does feel a bit like Decimal128 has some maturing to do to match the quality of the other numeric datatypes. But I wanted to submit this PR anyway

THanks @kmitchener 

I wonder if we can perhaps mark this PR as a draft as we work through whatever other maturing Decimal needs so that we don't require `::double`. I agree with @Jimexist  that that seems like a step backwards in functionality

**Comment by kmitchener** [comment]
Sure, I will switch it to draft and add another issue for changing the mathematical functions to accept and return decimal types in addition to float, where appropriate. That should reduce the amount of casting needed.

**Comment by alamb** [comment]
Thanks @kmitchener

**Comment by alamb** [comment]
Closing as this PR is over a year old. Please feel free to reopen it / rebase it if you plan to keep working on it

**Pull request closed without merging**
