### PR TITLE
Fix compilation for ballista in stand-alone mode

### LINKED ISSUE #1000: Ballista client fails to build with --features=standalone
**Describe the bug**
```cargo check --features=standalone``` fails

**To Reproduce**
see above

**Expected behavior**
It builds

**Additional context**
Came across this while doing my default ```cargo check --all-features```

### PR DESCRIPTION
**Pull request by Igosuki**
# Which issue does this PR close?

Closes #1000 

 # Rationale for this change
API changes broke compilation and execution of the standalone ballista client.

# What changes are included in this PR?
Compilation fixes, and another fix is required for tests to pass

# Are there any user-facing changes?
None

### CODE REVIEW

**Comment by Igosuki** [comment]
Problem here https://github.com/apache/arrow-datafusion/blob/master/ballista/rust/executor/src/standalone.rs#L55 
By the time df collects test results the tonic server is unreachable, I tried to make it run ad-vitam but then the tests never end.

**Comment by alamb** [comment]
I verified that the `cargo check --features=standalone` compiles on this branch, but does not on master

When we fix the ballista test, I recommend we start running the standalone client tests as part of CI so they aren't broken again

**Comment by alamb** [comment]
This seems like an improvement to me, so merging it in. We can always improve things more in the future

**Comment by alamb** [comment]
Thanks again @Igosuki

**Comment by Igosuki** [comment]
So how do we fix the ballista test though ? I don't understand why the tonic server is unreachable since even if the thread gets detached because the tokio JoinHandle gets dropped it should still be running right ?

**Comment by alamb** [comment]
> I wonder which part of the not is not parsing.

Sorry @Igosuki  I am not super familiar with the ballista codebase yet. What test are you referring to (aka what command are you running locally that is failing)? 

With that information I can file a ticket for the problem and probably find someone in the community who can help fix it

**Comment by Igosuki** [comment]
@alamb This one https://github.com/apache/arrow-datafusion/blob/master/ballista/rust/client/src/context.rs#L300

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/1020 to track test failing

**Pull request merged**
