### PR TITLE
Replace lazy_static with OnceLock

### LINKED ISSUE #7408: Replace lazy_static with OnceLock
### Is your feature request related to a problem or challenge?

As of Rust 1.70, we can use `OnceLock` as a standard Rust library.
I think we can use it to replace `lazy_static`, and we can reduce dependency.

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sarutak**
## Which issue does this PR close?
Closes #7408 

## Rationale for this change
As of Rust 1.70, we can use `OnceLock` as a standard Rust library.
So, this PR proposes to replace  `lazy_static` with `OnceLock` to reduce third-party dependency.

## Are these changes tested?
Done by existing tests.

## Are there any user-facing changes?
No

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]
Cool, nice cleanup

**Review by viirya — APPROVED** [review]

**Comment by alamb** [comment]
I believe CI will pass after merging up from `main` to get the change in  https://github.com/apache/arrow-datafusion/pull/7416

**Comment by alamb** [comment]
I took the liberty of merging up from main to fix the CI tests. I'll plan to merge this PR once they pass

**Comment by Dandandan** [comment]
Thanks @sarutak

**Comment by sarutak** [comment]
Thanks all.

**Pull request merged**
