### PR TITLE
move some contents from readme into user guide

### LINKED ISSUE #1400: Duplicated content in Readme and User Guide -- should we consolidate
**Describe the bug**
There appears to be duplicated content / overlap between 

https://github.com/apache/arrow-datafusion/blob/master/docs/source/user-guide/ (which is eventually published to https://arrow.apache.org/datafusion/ ) 

and https://github.com/apache/arrow-datafusion/blob/master/README.md 

I worry that the content is diverging (e.g. with the list of supported SQL)

**Expected behavior**
I wonder if it would ok to move all content from and https://github.com/apache/arrow-datafusion/blob/master/README.md into the users guide and change README.md to have a link to the user guide?

### PR DESCRIPTION
**Pull request by xudong963**
# Which issue does this PR close?

Closes #1400

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by houqp — APPROVED** [review]
The rest looks good to me, I think the example usage section still provides value in giving readers a quick overview on what datafusion is. I suggest we either keep that section or insert a link to the usage section in our user guide.

**Comment by xudong963** [comment]
cc @alamb

**Review by alamb — APPROVED** [review]
Thanks @xudong963 -- I'll go try and make a PR to publish this content on arrow.apache.org/datafusion

**Comment by alamb** [comment]
(Sorry for the delay in review / merge -- I took the day off yesterday lol)

**Review by alamb — COMMENTED** [review]
🤔  I can't figure out how https://arrow.apache.org/datafusion/ is updated anymore -- I'll look into it later perhaps

**Comment by xudong963** [comment]
> (Sorry for the delay in review / merge -- I took the day off yesterday lol)

No worries!

**Comment by alamb** [comment]
> 🤔 I can't figure out how https://arrow.apache.org/datafusion/ is updated anymore -- I'll look into it later perhaps

I found it! I was on the wrong branch (`master` rather than `asf-site`) .  I simply read the README from @houqp  too quickly 🤦

**Comment by alamb** [comment]
https://github.com/apache/arrow-site/pull/191

**Pull request merged**
