### PR TITLE
chore(doc) remove ballista from datafusion-cli readme

### PR DESCRIPTION
**Pull request by ming535**
# Which issue does this PR close?
NONE

 # Rationale for this change
improve documentation

# What changes are included in this PR?
- remove ballista from datafusion-cli readme
- build datafusion-cli and update Cargo.lock

# Are there any user-facing changes?
no
# Does this PR break compatibility with Ballista?
NA

### CODE REVIEW

**Comment by waynexia** [comment]
Thanks for this improvement. Could you please remove this paragraph https://github.com/apache/arrow-datafusion/blob/master/datafusion-cli/README.md#ballista as well. And I suppose the help text should also be update.

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @ming535

**Comment by waynexia** [comment]
https://github.com/apache/arrow-datafusion/pull/2604/files#diff-f8e712e7c585d2987696b343e70f216cb9695cf4c119c6a4035a030dff00eabbR40-R41
```
        --host <host>                Ballista scheduler host
        --port <port>                Ballista scheduler port
```

These are also outdated

**Review by waynexia — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @ming535  and @waynexia

**Pull request merged**
