### PR TITLE
cleanup function return type fn

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #.

 # Rationale for this change

# What changes are included in this PR?

function return type fn is too clumsy and we can use macros to clean it up.

# Are there any user-facing changes?

this is purely code refactoring, no user facing changes.

### CODE REVIEW

**Review by jorgecarleitao — APPROVED** [review]
Beautiful! ❤️

**Review by alamb — APPROVED** [review]
I agree -- this looks really nice @Jimexist . Thank you

**Comment by alamb** [comment]
This PR appears to need a rebase

**Comment by alamb** [comment]
So ✨ clean 👍

**Pull request merged**
