### PR TITLE
7.x: fix clippy

### PR DESCRIPTION
**Pull request by jychen7**
# Which issue does this PR close?

fix clippy

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by jackwener** [comment]
It was forgotten.
```
   --> datafusion/tests/merge_fuzz.rs:106:20
    |
106 |               .iter()
    |  ____________________^
107 | |             .map(|p| p.iter())
108 | |             .flatten()
    | |______________________^ help: try using `flat_map` instead: `.flat_map(|p| p.iter())`
```

**Review by jackwener — APPROVED** [review]

**Review by alamb — APPROVED** [review]
Looking good. Thank you @jychen7. I'll make a PR to get the last one

**Comment by jychen7** [comment]
> It was forgotten

hi, my macOS have problem running with `cargo clippy` (similar to https://github.com/rust-lang/rust-clippy/issues/8470), so I just relies on CI for the checking (And CI didn't show all errors at once)

I will mark this PR as "Ready for review" once `clippy` pass

**Comment by yjshen** [comment]
Thanks @jychen7!

**Pull request merged**
