### PR TITLE
port position test to scalar

### PR DESCRIPTION
**Pull request by Lordworms**
## Which issue does this PR close?

Closes #.

## Rationale for this change
modify for #8922

### CODE REVIEW

**Review by Weijun-H — APPROVED** [review]
LGTM! Thanks @Lordworms . Could you delete `position.slt`?

**Comment by Lordworms** [comment]
sure

**Review by comphead — DISMISSED** [review]
nice, thanks @Lordworms 
Since touching that, may I ask you to add tests with nulls and bad scenarios

```
select position(null in null)

select position('' in '')

select position(1 in 1)

```

and different other combinations in this direction

**Comment by Lordworms** [comment]
sure

**Review by alamb — APPROVED** [review]
Thank you very much @Lordworms  and @Weijun-H !

**Pull request merged**
