### PR TITLE
[WIP] Documentation updates for 11.0.0 release

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

N/A

 # Rationale for this change

Making some small improvements before we release

# What changes are included in this PR?

- Combine the two CLI pages into a single page and improve formatting
- Move expressions out of DataFrame page and into a new page
- Remove Ballista content
- Fix link to sqlparser source
- Rename "Community" section to  "Developer Resources" and moved link to docs.rs there
- Fix broken link to communication page
- Renamed one of the roadmap pages so we don't have two "roadmap" links

This is how the index looks now:

docs-index

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by andygrove** [comment]
@kmitchener I'm planning on cutting the 11.0.0 release candidate in the next few days, so went ahead and made some small docs improvements here. Apologies if this overlaps a bit with some of your efforts.

**Comment by andygrove** [comment]
Converted to draft because this is in conflict with https://github.com/apache/arrow-datafusion/pull/3128

**Comment by andygrove** [comment]
I am going to break this down into smaller PRs.

**Comment by kmitchener** [comment]
> @kmitchener I'm planning on cutting the 11.0.0 release candidate in the next few days, so went ahead and made some small docs improvements here. Apologies if this overlaps a bit with some of your efforts.

ok, I'll hold off on anything more until this latest flurry of changes gets committed. it's looking good!

**Pull request closed without merging**
