### PR TITLE
Add assertion for invariant in `create_physical_expression` and fix ViewTable projection

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/3240

 # Rationale for this change

`create_physical_expression` accepts an Arrow schema and a DataFusion schema. They should have the same number of fields but there was no check.

# What changes are included in this PR?

- Add an assertion that both schemas have the same length
- Fix regressions caused by this change
- ViewTable no longer ignores projections
- Remove some unwraps from simplify_expressions

# Are there any user-facing changes?

Not  sure

### CODE REVIEW

**Comment by andygrove** [comment]
@matthewmturner @DaltonModlin @kmitchener Since this affects views, could you please review if you have time?

**Comment by kmitchener** [comment]
> @matthewmturner @DaltonModlin @kmitchener Since this affects views, could you please review if you have time?

LGTM. If you want to reproduce, this triggered the error prior to the fix:
```sql
create view v as select 1 as a, 2 as b, 3 as c;
select * from (select b from v); -- returned column a prior to fix
```

**Comment by kmitchener** [comment]
Given the above sql, it results in this plan. Isn't this 1 too many projections?

```
create view v as select 1 as a, 2 as b, 3 as c;
explain analyze select * from (select b from v);
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type         | plan                                                                                                                                                                         |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Plan with Metrics | CoalescePartitionsExec, metrics=[output_rows=1, elapsed_compute=72.1µs, spill_count=0, spilled_bytes=0, mem_used=0]                                                          |
|                   |   ProjectionExec: expr=[b@0 as b], metrics=[output_rows=1, elapsed_compute=3.311µs, spill_count=0, spilled_bytes=0, mem_used=0]                                              |
|                   |     ProjectionExec: expr=[b@0 as b], metrics=[output_rows=1, elapsed_compute=5.511µs, spill_count=0, spilled_bytes=0, mem_used=0]                                            |
|                   |       ProjectionExec: expr=[2 as b], metrics=[output_rows=1, elapsed_compute=53.011µs, spill_count=0, spilled_bytes=0, mem_used=0]                                           |
|                   |         RepartitionExec: partitioning=RoundRobinBatch(12), metrics=[repart_time{inputPartition=0}=1ns, fetch_time{inputPartition=0}=27µs, send_time{inputPartition=0}=7.6µs] |
|                   |           EmptyExec: produce_one_row=true, metrics=[]                                                                                                                        |
|                   |                                                                                                                                                                              |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

**Comment by andygrove** [comment]
> Given the above sql, it results in this plan. Isn't this 1 too many projections?
> 
> ```
> create view v as select 1 as a, 2 as b, 3 as c;
> explain analyze select * from (select b from v);
> +-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | plan_type         | plan                                                                                                                                                                         |
> +-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | Plan with Metrics | CoalescePartitionsExec, metrics=[output_rows=1, elapsed_compute=72.1µs, spill_count=0, spilled_bytes=0, mem_used=0]                                                          |
> |                   |   ProjectionExec: expr=[b@0 as b], metrics=[output_rows=1, elapsed_compute=3.311µs, spill_count=0, spilled_bytes=0, mem_used=0]                                              |
> |                   |     ProjectionExec: expr=[b@0 as b], metrics=[output_rows=1, elapsed_compute=5.511µs, spill_count=0, spilled_bytes=0, mem_used=0]                                            |
> |                   |       ProjectionExec: expr=[2 as b], metrics=[output_rows=1, elapsed_compute=53.011µs, spill_count=0, spilled_bytes=0, mem_used=0]                                           |
> |                   |         RepartitionExec: partitioning=RoundRobinBatch(12), metrics=[repart_time{inputPartition=0}=1ns, fetch_time{inputPartition=0}=27µs, send_time{inputPartition=0}=7.6µs] |
> |                   |           EmptyExec: produce_one_row=true, metrics=[]                                                                                                                        |
> |                   |                                                                                                                                                                              |
> +-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> ```

These could easily be optimized out if we could run the optimizer here, but we can't. This also means we lose projection push-down when selecting from a view. This does at least fix the correctness issue, even if this is not efficient so it might be best to file a specific issue for this. I'll take another look at this tomorrow.

**Comment by andygrove** [comment]
> These could easily be optimized out if we could run the optimizer here, but we can't. This also means we lose projection push-down when selecting from a view. This does at least fix the correctness issue, even if this is not efficient so it might be best to file a specific issue for this. I'll take another look at this tomorrow.

I was wrong about this. We are optimizing. I will add a check to avoid adding a redundant projection.

**Comment by liukun4515** [comment]
I will review it tomorrow, it's too later for me today. @andygrove

**Comment by andygrove** [comment]
I filed https://github.com/apache/arrow-datafusion/issues/3248 for removing the redundant projection. The physical plan being returned from `ViewTable::scan` does not have it, so I think this is a bug that is unrelated to this PR.

ViewScan::scan returns this:

```
ProjectionExec: expr=[b@0 as b]
  ProjectionExec: expr=[2 as b]
    EmptyExec: produce_one_row=true
```

`EXPLAIN ANALYZE` shows this:

```
+---------------+---------------------------------------+
| plan_type     | plan                                  |
+---------------+---------------------------------------+
| logical_plan  | Projection: #v.b                      |
|               |   TableScan: v projection=[b]         |
| physical_plan | ProjectionExec: expr=[b@0 as b]       |
|               |   ProjectionExec: expr=[b@0 as b]     |
|               |     ProjectionExec: expr=[2 as b]     |
|               |       EmptyExec: produce_one_row=true |
|               |                                       |
+---------------+---------------------------------------+
```

**Review by jdye64 — APPROVED** [review]
Changes look good. Like the idea of using the Arrow schema for determining the expression data types.

**Review by yjshen — APPROVED** [review]
LGTM.

**Comment by matthewmturner** [comment]
@andygrove sorry i didnt get to this sooner, looks good.

**Pull request merged**
