### PR TITLE
move array function unit_tests to sqllogictest

### LINKED ISSUE #8324: Port tests in `array_expression.rs` to `sqllogictest`
The goal is that there is no rust test in this file anymore.

Part of https://github.com/apache/arrow-datafusion/issues/6195

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/8313#discussion_r1405386301_

File an issue to list the pending test to avoid duplicate work
- [ ] make_array
- [ ] array_element
- [ ] array_pop_back
- [ ] array_slice
- [ ] array_append
- [ ] array_prepend
- [ ] array_concat
- [ ] array_position
- [ ] array_to_string
- [ ] cardinality
- [ ] array_length
- [ ] array_dims
- [ ] Port other function to common::utils  or just remove it

### PR DESCRIPTION
**Pull request by Veeupup**
## Which issue does this PR close?

Closes #8324 .

I have checked the unit tests in `array_expressions.rs` and found that almost all test cases are covered by `sqllogictest`.

So this PR is almost about removing the duplicate unit tests

### CODE REVIEW

**Comment by Veeupup** [comment]
cc @jayzhan211  @alamb  PTAL

**Review by alamb — APPROVED** [review]
Thank you very much @Veeupup

**Comment by alamb** [comment]
Let me know if this looks good to you @jayzhan211

**Review by jayzhan211 — APPROVED** [review]
LGTM!

@Veeupup Before closing #8324, how about function like `test_align_array_dimensions`?
We should either remove it or move it to dfcommon::utils if it is possible to be used elsewhere.

**Comment by Veeupup** [comment]
> LGTM!
> 
> @Veeupup Before closing #8324, how about function like `test_align_array_dimensions`? We should either remove it or move it to dfcommon::utils if it is possible to be used elsewhere.

Sure! But I found that `align_array_dimensions` is only used in `array_expressions.rs` and its signature is not `pub`. So it would be fine to just keep in `array_expressions.rs`

**Comment by alamb** [comment]
> Sure! But I found that align_array_dimensions is only used in array_expressions.rs and its signature is not pub. So it would be fine to just keep in array_expressions.rs

I agree this is a good plan (to keep `align_array_dimensions` test in `array_expressions.rs`

**Comment by jayzhan211** [comment]
OK, we can keep it. I am just afraid that people will create test in array_expression.rs if there is still rust test  (any kind of test) inside it.

**Comment by Weijun-H** [comment]
> OK, we can keep it. I am just afraid that people will create test in array_expression.rs if there is still rust test (any kind of test) inside it.

Maybe we should leave some comments for it 🤔

**Comment by jayzhan211** [comment]
> > OK, we can keep it. I am just afraid that people will create test in array_expression.rs if there is still rust test (any kind of test) inside it.
> 
> Maybe we should leave some comments for it 🤔

I think comments help.

**Review by alamb — APPROVED** [review]
Thank you @Veeupup  @jayzhan211 and @Weijun-H

**Pull request merged**
