### PR TITLE
Move `radians`, `signum`, `sin`, `sinh` and `sqrt` functions to `datafusion-functions` crate

### LINKED ISSUE #9860: move Radians, Signum, Sin, Sinh, Sqrt functions to datafusion-functions
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/arrow-datafusion/issues/9285 move the Radians, Signum, Sin, Sinh, Sqrt functions to the new datafusion-functions/math crate in the new structure.

### Describe the solution you'd like

Functions are migrated to the new crate and use the new patterns as described in https://github.com/apache/arrow-datafusion/issues/9286 & https://github.com/apache/arrow-datafusion/pull/9216

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by erenavsarogullari**
## Which issue does this PR close?
Closes #9860.

## What changes are included in this PR?
`radians`, `signum`, `sin`, `sinh` and `sqrt` functions are moved to `datafusion-functions` crate.

## Are these changes tested?
Yes, all `scalar.slt` based `radians`, `signum`, `sin`, `sinh` and `sqrt` functions' tests are passed.

## Are there any user-facing changes?
No

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Looks great to me -- thank you @erenavsarogullari  🙏 
 
I took the liberty of merging up from main to get the CI passing on this PR

**Comment by alamb** [comment]
🤔  there seems to be one more CI failure related to this PR

**Comment by erenavsarogullari** [comment]
Thanks for the review. CI failure has been addressed.

**Comment by alamb** [comment]
🚀  -- thanks @Weijun-H  and @erenavsarogullari ❤️

**Pull request merged**
