### PR TITLE
use requirements.txt to formalize python deps

### LINKED ISSUE #504: normalize the python dev environment requirements
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

we should normalize the python dev environment for testing so that it's predictable across different setup

**Describe the solution you'd like**

use `pip-tools` to compile `requirements.txt` with hashes

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #504.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by jorgecarleitao — APPROVED** [review]
Looks great. Great to see pip-tools being used :)

What do you think about adding to the README how to update test dependencies? Something like

> To change test dependencies, change the `requirements.in` and run
> ```
> # change requirements.in
> pip install pip-tools
> pip-compile --generate-hashes
> ```
>
> To update dependencies, run
> ```
> pip-compile update
> ```
> More details [here](https://github.com/jazzband/pip-tools)

**Comment by Jimexist** [comment]
> Looks great. Great to see pip-tools being used :)
> 
> 
> 
> What do you think about adding to the README how to update test dependencies? Something like
> 
> 
> 
> > To change test dependencies, change the `requirements.in` and run
> 
> > ```
> 
> > # change requirements.in
> 
> > pip install pip-tools
> 
> > pip-compile --generate-hashes
> 
> > ```
> 
> >
> 
> > To update dependencies, run
> 
> > ```
> 
> > pip-compile update
> 
> > ```
> 
> > More details [here](https://github.com/jazzband/pip-tools)
> 
> 

Personally I lean towards using poetry but that demands changes to publishing procedures as well - what do you think of that?

**Comment by jorgecarleitao** [comment]
I do not quite follow: AFAIK both pip-tools and poetry are tools for Python applications, not Python libraries. For libraries, we only need to provide a `setup.py / project.toml`, which madurin does for us. I.e. the `install_requires` is [here](https://github.com/apache/arrow-datafusion/blob/master/python/Cargo.toml#L41).

AFAI understand this PR is only concerned with the dependencies used for testing.

**Comment by Jimexist** [comment]
> I do not quite follow: AFAIK both pip-tools and poetry are tools for Python applications, not Python libraries. For libraries, we only need to provide a `setup.py / project.toml`, which madurin does for us. I.e. the `install_requires` is [here](https://github.com/apache/arrow-datafusion/blob/master/python/Cargo.toml#L41).
> 
> AFAI understand this PR is only concerned with the dependencies used for testing.

i meant the format for defining the project (the poetry way), but you are right this is probably non-related to this PR.

**Comment by Jimexist** [comment]
> I do not quite follow: AFAIK both pip-tools and poetry are tools for Python applications, not Python libraries. For libraries, we only need to provide a `setup.py / project.toml`, which madurin does for us. I.e. the `install_requires` is [here](https://github.com/apache/arrow-datafusion/blob/master/python/Cargo.toml#L41).
> 
> AFAI understand this PR is only concerned with the dependencies used for testing.

`README.md` updated, PTAL

**Pull request merged**
