### PR TITLE
Extract logical plans in LogicalPlan as independent struct: TableScan

### LINKED ISSUE #1228: Extract logical plans in  LogicalPlan as independent struct
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
During I try to implement `Select (subquery)` , I add ` Select(Box<LogicalPlan>)` in `Expr`. Because `Expr` derives `PartialEq, PartialOrd`, but `LogicalPlan` not, I try to derive `PartialEq, PartialOrd` for `LogicalPlan`. Unfortunately, I got an error, because some logical plan contains traits, such as `TableScan`, which contains the `TableProvider` trait. 

more thoughts: https://github.com/apache/arrow-datafusion/issues/1228#issuecomment-969443381

**Describe the solution you'd like**
In order to achieve better scalability, I think we can extract logical plans in LogicalPlan as independent structs. For example
```rust
pub enum LogicalPlan {
   ...
    TableScan {
        /// The name of the table
        table_name: String,
        /// The source of the table
        source: Arc<dyn TableProvider>,
        /// Optional column indices to use as a projection
        projection: Option<Vec<usize>>,
        /// The schema description of the output
        projected_schema: DFSchemaRef,
        /// Optional expressions to be used as filters by the table provider
        filters: Vec<Expr>,
        /// Optional limit to skip reading
        limit: Option<usize>,
    },
   ...
}
```
```rust
pub struct TableScanPlan {
    /// The name of the table
    table_name: String,
    /// The source of the table
    source: Arc<dyn TableProvider>,
    /// Optional column indices to use as a projection
    projection: Option<Vec<usize>>,
    /// The schema description of the output
    projected_schema: DFSchemaRef,
    /// Optional expressions to be used as filters by the table provider
    filters: Vec<Expr>,
    /// Optional limit to skip reading
    limit: Option<usize>,
}

pub enum LogicalPlan {
  ...
  TableScan(TableScanPlan),
  ...
}

```
**Describe alternatives you've considered**

**What changes are planned in further issues/PRs?**
- #1302 
- #1303 
- #1304 
- #1305 
- #1306 
- #1307

### PR DESCRIPTION
**Pull request by xudong963**
# Which issue does this PR close?

Related to #1228 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by xudong963** [comment]
I extracted `TableScan` as an example, PTAL.

I have two questions:
1. How about extracting every plan to a single file.
2. Extract All plans at once as one ticket or divide them into multiple tickets. I think dividing into multiple tickets will be good to review.

**Comment by liukun4515** [comment]
@xudong963,  If you split them to multiple task, you can list every subtask, may be i can help you to do someone.

**Review by alamb — APPROVED** [review]
Thank you for the contribution @xudong963  - this PR looks exactly like what is discussed on https://github.com/apache/arrow-datafusion/issues/1228 👍 

I think this looks like an improvement to me. It will be a fairly large, but mechanical change to the codebase but I do think it will help over time

What do you think about this change @Jimexist @houqp @rdettai and @Dandandan

**Comment by xudong963** [comment]
> Thank you for the contribution @xudong963 - this PR looks exactly like what is discussed on #1228 👍
> 
> I think this looks like an improvement to me. It will be a fairly large, but mechanical change to the codebase but I do think it will help over time

My pleasure! I believe after finishing this, it'll bring help for subqueries implementation.

**Review by houqp — APPROVED** [review]

**Comment by alamb** [comment]
> The ticket can be merged? Then we can push related tickets🎯

Any concerns @Dandandan  / @andygrove / @Jimexist  / @rdettai ?

**Review by rdettai — COMMENTED** [review]
Thanks for your work @xudong963. I am not sure I fully understand the big picture of the change though. It seems from #1228 that this is part of adding subqueries, but I would find it clearer if there was an umbrella issue with bullet points that list to steps/issues.

**Comment by alamb** [comment]
There is some good discussion on https://github.com/apache/arrow-datafusion/issues/1228#issuecomment-969443381 -- to be clear, in my mind, the purpose of this refactoring is to make `LogicalPlan` nodes easier to work with longer term. 

Thanks @xudong963  for leading the charge

**Pull request merged**
