### PR TITLE
Minor: Add TPCH scale factor 10 to bench.sh, use 10 iteration

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Related to https://github.com/apache/arrow-datafusion/issues/4973

# Rationale for this change

The new grouping code is so fast that the measurement noise is becoming significant 😆  so I need larger data

# What changes are included in this PR?

add `tpch10` as well as `tpch` to bench.sh

So you can run `bench.sh run tpch10` now

# Are these changes tested?
I tested them manually

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Dandandan** [comment]
What about increasing the number of iterations as well? This also reduces the variance in the results.

**Review by Dandandan — APPROVED** [review]

**Comment by alamb** [comment]
>  What about increasing the number of iterations as well? This also reduces the variance in the results.

That is a good idea 🤔 It turns out that DataFusion blew up my machine's memory when trying to run TPCH on SF10 as well. Maybe I also need to limit the memory (so the queries error rather than swap the OS to death)

**Comment by alamb** [comment]
>  What about increasing the number of iterations as well? This also reduces the variance in the results.



Changed to 10 in  [bd6812d](https://github.com/apache/arrow-datafusion/pull/6893/commits/bd6812d3d6708a27f33c6a813397b96c23e62519)

**Comment by Dandandan** [comment]
Thanks @alamb

**Pull request merged**
