### PR TITLE
Add example to ci

### LINKED ISSUE #8018: Run `datafusion-examples`  when start CI
### Is your feature request related to a problem or challenge?

Currently, we have not verified the accuracy of the test classes in the datafusion-example directory, so we should test it while running ci. Reduce the probability of coding errors

### Describe the solution you'd like

The current idea may be relatively simple. I will create two directories, one named external_storage and one named flight_sql. External_storage will contain test cases that require external storage, and flight_sql will contain flight-related test cases. When I run my tests I skip these two directories.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by smallzhongfeng**
## Which issue does this PR close?

Closes  #8018.

## Rationale for this change

Allow all tests under the example directory to run, and there is no need to add a new test to rust.yml every time.

## What changes are included in this PR?

Add a new script named 'rust_example.sh' to run example in ci

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by smallzhongfeng** [comment]
PTAL @alamb

**Review by waynexia — APPROVED** [review]
This is great!! Thanks 👍

**Review by alamb — COMMENTED** [review]
Thank you @smallzhongfeng  -- this is great

Can you also please update the example README document with the new paths: https://github.com/apache/arrow-datafusion/blob/main/datafusion-examples/README.md#single-process

🙏

**Comment by smallzhongfeng** [comment]
> Thank you @smallzhongfeng -- this is great
> 
> Can you also please update the example README document with the new paths: https://github.com/apache/arrow-datafusion/blob/main/datafusion-examples/README.md#single-process
> 
> 🙏

No problem, it has been updated.

**Pull request merged**
