### PR TITLE
chore: use taplo to format Cargo.toml manifests

### PR DESCRIPTION
**Pull request by waynexia**
## Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/9262.

## Rationale for this change

See https://github.com/apache/arrow-datafusion/issues/9262 for details.

## What changes are included in this PR?

Changes:
- Add taplo to CI
- Format existing `Cargo.toml` files
- Add a configuration file
- Update related docs

To install `taplo`, run `cargo install taplo-cli`. Or by other ways in [document](https://taplo.tamasfe.dev/cli/installation/binary.html).

To format toml files, use `taplo format`. It would read config file `taplo.toml` from this PR.

## Are these changes tested?

no need

## Are there any user-facing changes?

For developers, yes.

### CODE REVIEW

**Review by Jefffrey — COMMENTED** [review]
Won't lie, it bugs me a little that `name` is no longer the first key in this new format :sweat_smile: 

I guess it is better to have some defined order for keys, but can this be configured?

Unless others are fine with the default alphabetical :+1:

**Comment by waynexia** [comment]
Thanks for reviewing this @Jefffrey 

I added a rule to skip reordering `package` table, it should look better now. Please check it out 😆

**Review by Jefffrey — APPROVED** [review]
Nice :rocket:

**Comment by Omega359** [comment]
This broke /dev/rust-lint.sh because 

/ci/scripts/rust_toml_fmt.sh isn't valid bash:

set -ex
taplo format
done <-- this should be removed.

**Comment by waynexia** [comment]
Ahhh my bad 😵‍💫 Are you willing to submit a fix?

**Pull request merged**
