### PR TITLE
Updated Rust version to 1.59 in all the files

### LINKED ISSUE #1902: Update `rust-version` to 1.59
**Describe the solution you'd like**
update `rust-version` from 1.58 to 1.59.

**Additional context**
https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html

### PR DESCRIPTION
**Pull request by NaincyKumariKnoldus**
Hey @HaoYang670 I have updated rust version in all the files. Please review this and if any changes needed do inform me.
Thanks!

#1902 
closes #1902

### CODE REVIEW

**Comment by HaoYang670** [comment]
@alamb Please trigger the workflows. Thank you!

**Comment by xudong963** [comment]
After I update the rust version to 1.59 in my local, running `cargo clippy` got the following error.
```
➜  arrow-datafusion git:(pr1903) rustup -V
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.59.0 (9d1b2106e 2022-02-23)`
➜  arrow-datafusion git:(pr1903) cargo -V
cargo 1.59.0 (49d8809dc 2022-02-10)
➜  arrow-datafusion git:(pr1903)
```
```
error: could not compile `datafusion-physical-expr`

Caused by:
  process didn't exit successfully: ...(signal: 6, SIGABRT: process abort signal)
```

**Comment by HaoYang670** [comment]
> After I update the rust version to 1.59 in my local, running `cargo clippy` got the following error.
> 
> ```
> ➜  arrow-datafusion git:(pr1903) rustup -V
> rustup 1.24.3 (ce5817a94 2021-05-31)
> info: This is the version for the rustup toolchain manager, not the rustc compiler.
> info: The currently active `rustc` version is `rustc 1.59.0 (9d1b2106e 2022-02-23)`
> ➜  arrow-datafusion git:(pr1903) cargo -V
> cargo 1.59.0 (49d8809dc 2022-02-10)
> ➜  arrow-datafusion git:(pr1903)
> ```
> 
> ```
> error: could not compile `datafusion-physical-expr`
> 
> Caused by:
>   process didn't exit successfully: ...(signal: 6, SIGABRT: process abort signal)
> ```

This is a little weird. I test on my desktop, and everything works fine.
```bash
(base) remziy@remzi-desktop:~/Datafusion$ git checkout pr_1903 
Switched to branch 'pr_1903'
(base) remziy@remzi-desktop:~/Datafusion$ rustup -V
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.59.0 (9d1b2106e 2022-02-23)`
(base) remziy@remzi-desktop:~/Datafusion$ cargo -V
cargo 1.59.0 (49d8809dc 2022-02-10)
(base) remziy@remzi-desktop:~/Datafusion$ rustc -V
rustc 1.59.0 (9d1b2106e 2022-02-23)
(base) remziy@remzi-desktop:~/Datafusion$ cargo clippy
    Checking datafusion v7.0.0 (/home/Datafusion/datafusion)
    Checking ballista-core v0.6.0 (/home/Datafusion/ballista/rust/core)
    Checking datafusion-cli v7.0.0 (/home/Datafusion/datafusion-cli)
    Checking ballista v0.6.0 (/home/Datafusion/ballista/rust/client)
    Checking ballista-executor v0.6.0 (/home/Datafusion/ballista/rust/executor)
    Checking ballista-scheduler v0.6.0 (/home/Datafusion/ballista/rust/scheduler)
    Checking arrow-benchmarks v5.0.0 (/home/Datafusion/benchmarks)
    Checking ballista-examples v0.6.0 (/home/Datafusion/ballista-examples)
    Finished dev [unoptimized + debuginfo] target(s) in 9.78s
```

**Comment by NaincyKumariKnoldus** [comment]
Thank you @alamb

**Pull request merged**
