### PR TITLE
simplify python function definitions

### LINKED ISSUE #479: reduce boilerplate in defining and exposing functions in Python
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

so far there is a lot of boilerplate code in defining and exposing functions in Python.

**Describe the solution you'd like**

leverage macros to reduce duplicates

**Describe alternatives you've considered**

**Additional context**

we'll like to have them documented as well

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #479
Depends on #483

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Thanks a lot, @Jimexist . This makes sense, however, I have a question, though:

pyo3 uses rusts' docs (`///`) to populate Python's documentation. Maybe there is a way to do it via a macro, but atm this increases the barrier to add doc strings to the functions, no? I.e. how do we add a docstring to say `ascii` in this new code base?

**Comment by Jimexist** [comment]
> Thanks a lot, @Jimexist . This makes sense, however, I have a question, though:
> 
> pyo3 uses rusts' docs (`///`) to populate Python's documentation. Maybe there is a way to do it via a macro, but atm this increases the barrier to add doc strings to the functions, no? I.e. how do we add a docstring to say `ascii` in this new code base?

maybe [this][1] will work?

[1]: https://github.com/apache/arrow-datafusion/pull/477/files#diff-8874a0c4021b6e824c35bd9f57ac5c1d7f7186603136c3bc6451cce05e2c9175R77

**Comment by Jimexist** [comment]
```
In [3]: from datafusion import functions as f

In [4]: dir(f)
Out[4]:
['__all__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'array',
 'ascii',
 'avg',
 'bit_length',
 'btrim',
 'character_length',
 'chr',
 'col',
 'concat_ws',
 'count',
 'in_list',
 'initcap',
 'left',
 'lit',
 'lower',
 'lpad',
 'ltrim',
 'max',
 'md5',
 'min',
 'now',
 'octet_length',
 'random',
 'regexp_replace',
 'repeat',
 'replace',
 'reverse',
 'right',
 'rpad',
 'rtrim',
 'sha224',
 'sha256',
 'sha384',
 'sha512',
 'split_part',
 'starts_with',
 'strpos',
 'substr',
 'sum',
 'to_hex',
 'translate',
 'trim',
 'udaf',
 'udf',
 'upper']

In [5]: f.ascii??
Docstring: Returns the numeric code of the first character of the argument. In UTF8 encoding, returns the Unicode code point of the character. In other multibyte encodings, the argument must be an ASCII character.
Type:      builtin_function_or_method
```

**Comment by Jimexist** [comment]
error is likely not relevant, merge after fix in #468

**Pull request merged**
