### PR TITLE
Upgrade to arrow 13

### PR DESCRIPTION
**Pull request by alamb**
Related to https://github.com/apache/arrow-rs/issues/1623

This PR is a WIP while I work on releasing arrow 13.0.0 -- and making sure datafusion works with arrow 13.0.0 is part of my pre-release testing 👍 

Will turn this into a proper PR once arrow 13.0.0 is released (sometime next week)

### CODE REVIEW

**Comment by alamb** [comment]
arrow 13 has been released to crates.io and I have updated this PR's code, so it is now ready for review

cc @WinkerDu

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
There is a minor clippy failure

**Review by WinkerDu — APPROVED** [review]

**Comment by WinkerDu** [comment]
Thanks @alamb 
It's cool to go after fixing the minor clippy failure

**Comment by alamb** [comment]
> It's cool to go after fixing the minor clippy failure

🤦  sorry about that -- fixed and will merge when green

**Pull request merged**
