### PR TITLE
fix calculate in many_to_many_hash_partition test.

### PR DESCRIPTION
**Pull request by Ted-Jiang**
# Which issue does this PR close?
#1462 

Closes #.

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
@Ted-Jiang great find/fix! there is one clippy error:

```rust
   --> datafusion/src/physical_plan/repartition.rs:581:24
    |
581 |             .map(|x| x.into_iter().map(|x| x.num_rows()).sum::<usize>())
    |                        ^^^^^^^^^ help: call directly: `iter`
    |
    = note: `-D clippy::into-iter-on-ref` implied by `-D warnings`
```

**Comment by Ted-Jiang** [comment]
> 
Thanks, how do i check this before commit ?   i can not find in `Developer's guide` 😂

**Comment by Ted-Jiang** [comment]
> @Ted-Jiang great find/fix! there is one clippy error:
> 
> ```rust
>    --> datafusion/src/physical_plan/repartition.rs:581:24
>     |
> 581 |             .map(|x| x.into_iter().map(|x| x.num_rows()).sum::<usize>())
>     |                        ^^^^^^^^^ help: call directly: `iter`
>     |
>     = note: `-D clippy::into-iter-on-ref` implied by `-D warnings`
> ```

Thanks, how do i check this before commit ?   i can not find in `Developer's guide` 😂

**Review by Jimexist — APPROVED** [review]

**Comment by Dandandan** [comment]
> > @Ted-Jiang great find/fix! there is one clippy error:
> > ```rust
> >    --> datafusion/src/physical_plan/repartition.rs:581:24
> >     |
> > 581 |             .map(|x| x.into_iter().map(|x| x.num_rows()).sum::<usize>())
> >     |                        ^^^^^^^^^ help: call directly: `iter`
> >     |
> >     = note: `-D clippy::into-iter-on-ref` implied by `-D warnings`
> > ```
> 
> Thanks, how do i check this before commit ? i can not find in `Developer's guide` 😂

You can run `cargo clippy` 

> > @Ted-Jiang great find/fix! there is one clippy error:
> > ```rust
> >    --> datafusion/src/physical_plan/repartition.rs:581:24
> >     |
> > 581 |             .map(|x| x.into_iter().map(|x| x.num_rows()).sum::<usize>())
> >     |                        ^^^^^^^^^ help: call directly: `iter`
> >     |
> >     = note: `-D clippy::into-iter-on-ref` implied by `-D warnings`
> > ```
> 
> Thanks, how do i check this before commit ? i can not find in `Developer's guide` 😂

You can run `cargo clippy` and you get the warnings 👍

**Comment by Dandandan** [comment]
Thank you @Ted-Jiang

**Pull request merged**
