### PR TITLE
Fix SQL planner to support multibyte column names

### LINKED ISSUE #356: SQL Planner panics when multibyte characters are used in column names
**Describe the bug**

As mentioned in the issue title, `ctx.sql()` panics when using multibyte characters for column names.

**To Reproduce**

First, save the csv bellow as `person.csv`:

```csv
id,名前
1,NameA
2,NameB
```

And then, run the code bellow:

```rust
use datafusion::{
    execution::context::ExecutionContext,
    prelude::CsvReadOptions,
};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut ctx = ExecutionContext::new();
    ctx.register_csv("person", "person.csv", CsvReadOptions::new())?;
    ctx.sql(r#"SELECT "名前" FROM person;"#)?;
    Ok(())
}
```

I got the following panic message:

```
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside '名' (bytes 0..3) of `名前`', /home/agatan/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-4.0.0/src/sql/planner.rs:860:21
```

**Expected behavior**

Exit successfully.

**Additional context**

- `rustc -V` : rustc 1.52.1 (9bc8c42bb 2021-05-09)
- crates:
  - arrow = "4.0.0"
  - datafusion = "4.0.0"
  - tokio = "1.6.0"

### PR DESCRIPTION
**Pull request by agatan**
# Which issue does this PR close?

Closes #356 

 # Rationale for this change

Please refer #356 for more detail.

# What changes are included in this PR?

Slicing string will cause panic if the boundary is not correct as UTF-8.
To check if the first character is '@' or not, we should use `s.chars().nth(0)` instead of `&s[0..1]`.

# Are there any user-facing changes?

No.

### CODE REVIEW

**Review by jorgecarleitao — APPROVED** [review]
LGTM! 👍

**Review by Dandandan — APPROVED** [review]
😀 emoji support! 💯

**Comment by agatan** [comment]
Oh, sorry, I made a mistake in modifying the test case.
I'll fix it now.

**Comment by alamb** [comment]
Looks great @agatan  - thank you! I just started CI on this PR and  once we get a clean run I think this one is ready to merge

**Comment by alamb** [comment]
@agatan  can you please fix the clippy error: https://github.com/apache/arrow-datafusion/pull/357/checks?check_run_id=2620378740

```

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: called `.nth(0)` on a `std::iter::Iterator`, when `.next()` is equivalent
   --> datafusion/src/sql/planner.rs:860:20
    |
860 |                 if id.value.chars().nth(0) == Some('@') {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^ help: try calling `.next()` instead of `.nth(0)`: `id.value.chars().next()`
    |
    = note: `-D clippy::iter-nth-zero` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#iter_nth_zero
```

**Comment by agatan** [comment]
Thank you! I just fixed it now.

**Review by andygrove — APPROVED** [review]

**Pull request merged**
