### PR TITLE
NEW Logo

### PR DESCRIPTION
**Pull request by pinarbayata**
## Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/8788.

## Rationale for this change

The existing logo, which solely contained `DataFusion`, lacked the Apache branding. Following extensive discussions and community input across three rounds of suggestions, we have settled on a new logo.

## What changes are included in this PR?

Update of all instances of the old `DataFusion` logo across website, documentation, and marketing materials to the new `Apache DataFusion` logo.

Also I have added a brand guideline following [Apache Foundation Style](https://www.apache.org/foundation/press/kit/ApacheFoundation_StyleGuide.pdf) style. It can be found in `./docs/logo/Datafusion_Branding_Guideline.pdf`.

## Are these changes tested?

- Engaged with the DataFusion community to gather feedback on the updated branding, ensuring it resonates well and maintains the project's identity.
- Reviewed all updated materials for adherence to both the new branding guidelines and ASF branding standards.

## Are there any user-facing changes?
N/A

## Follow Up
I will add various sticker designs in subsequent PRs.

### CODE REVIEW

**Review by comphead — APPROVED** [review]
looks gorgeous thanks @pinarbayata 
I was concerned  if TM is relevant for the project? But in Apache Spark they have it in their logo

**Comment by metesynnada** [comment]
Looks perfect! Thanks for the effort @pinarbayata

**Review by alamb — APPROVED** [review]
I built the documentation and it is looking great. Thank you @pinarbayata both for making the images, doing this PR and running a wonderfully collaborative process 

Screenshot 2024-02-28 at 11 13 37 AM

**Comment by alamb** [comment]
> looks gorgeous thanks @pinarbayata I was concerned if TM is relevant for the project? But in Apache Spark they have it in their logo

I think having the TM on the logo follows the ASF guidelines (here https://www.apache.org/foundation/marks/#principles)

**Comment by alamb** [comment]
Let's plan to merge this tomorrow unless there are any other comments

**Review by andygrove — APPROVED** [review]
Thanks @pinarbayata. The new logos look really great.

**Comment by alamb** [comment]
👏

**Pull request merged**
