### PR TITLE
fix sqllogicaltest result

### PR DESCRIPTION
**Pull request by jackwener**
## Which issue does this PR close?

Closes #.

## Rationale for this change

CI failed in #9442 #9439 

## What changes are included in this PR?

Current CI related with`sqllogicaltest` is failed

### CODE REVIEW

**Comment by jackwener** [comment]
cc @SteveLauC

**Comment by jackwener** [comment]
PTAL @alamb @Dandandan

**Review by jayzhan211 — APPROVED** [review]
LGTM

**Comment by jayzhan211** [comment]
merge to fix ci

**Comment by alamb** [comment]
Thank you @jackwener  and @jayzhan211

**Pull request merged**
