### PR TITLE
Rule ReplaceDistinctWithAggregate

### LINKED ISSUE #5348: Add a rule to replace distinct with aggregate
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by mingmwang**
# Which issue does this PR close?

Closes #5348.

# Rationale for this change

Add a rule to replace the logical `Distinct` with the logical `Aggregate`, so that other logical rules do not need to handle `Distinct` additionally besides  the `Aggregate`. This will simply the other logical rules, sometime they might handle the `Aggregate` but forget to handle `Distinct`.

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by mingmwang** [comment]
retest please

**Comment by jackwener** [comment]
> retest please

I have rerun failed test. look like GHA occurred some problem😂

**Review by jackwener — APPROVED** [review]
Look great to me. Thanks @mingmwang

**Review by jackwener — COMMENTED** [review]
If there is no new review comments, I prepare to merge this PR in a day.

**Review by yjshen — APPROVED** [review]

**Pull request merged**
