### PR TITLE
Update to arrow-7.0.0

### PR DESCRIPTION
**Pull request by alamb**
~Draft until arrow-7.0.0 is actually released.~
This includes code from https://github.com/apache/arrow-datafusion/pull/1283

~Once arrow 7 is released (hopefully next week) I'll update this PR to use it and mark as ready to review. Until that time feel free to rebase any branches off this one if you need new features.~

This PR is now ready for review / merge

 # Rationale for this change
Update to get new code in arrow

# What changes are included in this PR?
1. Update arrow
2. Update `prost` dependency 0.8 -->  0.9 and `tonic` from 0.5 --> 0.6
2. Change DataFusion code for interface changes
3. Change Ballista code for interface changes

# Are there any user-facing changes?
requires new arrow

### CODE REVIEW

**Comment by liukun4515** [comment]
wait for this pr to be merged.

**Comment by alamb** [comment]
This PR is now ready for review / merge

**Comment by liukun4515** [comment]
thanks, @alamb  I can go on works depending on arrow-rs 7.0.0.

**Comment by alamb** [comment]
> thanks, @alamb I can go on works depending on arrow-rs 7.0.0.

Sorry it took so long @liukun4515  -- I hope this delay will be reduced by the proposal in https://github.com/apache/arrow-rs/issues/1120 

Thank you for all your contributions and your support

**Pull request merged**
