### PR TITLE
feat: column support for `array_dims`, `array_ndims`, `cardinality` and `array_length`

### PR DESCRIPTION
**Pull request by izveigor**
# Which issue does this PR close?

Part of https://github.com/apache/arrow-datafusion/issues/6804

# Rationale for this change
This is the second PR for solving the column issue.

# What changes are included in this PR?
Four array functions now start to support column data:
`array_dims`,
`array_ndims`,
`cardinality`,
`array_length`

# Are these changes tested?
Yes

# Are there any user-facing changes?
Yes

### CODE REVIEW

**Comment by alamb** [comment]
Thanks @izveigor  -- I plan to review this over the weekend  (also I found https://github.com/apache/arrow-datafusion/issues/6887 which is related perhaps). I can't keep up with all the structured array goodness you and @jayzhan211  are throwing our way!

**Comment by alamb** [comment]
🤔  maybe you and @jayzhan211 could potentially review each other's PRs initially?

**Review by jayzhan211 — APPROVED** [review]
LGTM!

**Review by alamb — APPROVED** [review]
Thanks @izveigor  -- I took a look through this PR and while I don't understand the entire thing I think it is a step forward and we should merge it in. 

I think this PR has a conflict but once that is resolved I'll plan to merge

**Comment by alamb** [comment]
Thank you @jayzhan211  for the review

**Pull request merged**
