### PR TITLE
[Minor] add debug info in optimizer.rs

### PR DESCRIPTION
**Pull request by Ted-Jiang**
# Which issue does this PR close?
it's better output which rule is running in debug log.
I got confused when debugging optimizer.
Closes #.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks @Ted-Jiang 

You probably know it, but you can also use `EXPLAIN VERBOSE` to see the output of the plans after each pass

For example:
```sql
EXPLAIN VERBOSE SELECT * from foo where x > 5
```

**Comment by waynexia** [comment]
These logs are useful to me. They are exactly what I add when debugging #2712 🤣 (some panicking rules cannot benefit from `EXPLAIN`)

**Comment by Ted-Jiang** [comment]
> Thanks @Ted-Jiang
> 
> You probably know it, but you can also use `EXPLAIN VERBOSE` to see the output of the plans after each pass
> 
> For example:
> 
> ```sql
> EXPLAIN VERBOSE SELECT * from foo where x > 5
> ```

@alamb Thanks a lot for your kindly advice! Like @waynexia  said, our team send logical plan to datafusion, it's easy to debug in this way.(Not want change our code 😂)

**Comment by alamb** [comment]
Makes sense -- I just wanted to point out the EXPLAIN VERBOSE thing too

**Pull request merged**
