### PR TITLE
Remove ObjectStore from FileStream (#4533)

### LINKED ISSUE #4533: FileStream requires fake ObjectStore when ParquetFileReaderFactory is used
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I am using `ParquetExec` in combination with `ParquetFileReaderFactory` to bypass `ObjectStore`. In order to create `FileScanConfig`, I need to fill a fake parameter for `object_store_url`, later `FileStream` creation fails because It tries to fetch `ObjectStore` that doesn't exist. Right now I work around that problem by creating fake `ObjectStore` that is never used.

**Describe the solution you'd like**
One solution that comes to my mind is making `FileOpener` self contained by combining each Opener with `ObjectStore` and `FileMeta`. There are some challenges with that solution, e.g. `ParquetFileReaderFactory` wants to own `FileMeta` when creating a reader, that would require to either clone `FileMeta` or take self in `FileOpener` to move `FileMeta` out of self. Alternatively we could have `FileMeta` behind shared pointer, but then we cannot move `ObjectMeta` out of it. 

One thing that **might** be a positive outcome, is that in future files with different openers could be processed within single FileStream. 

Please share your thoughts, I really wouldn't mind if there is a simpler way to improve that situation.

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4533

# Rationale for this change

Reduces the coupling between ParquetExec and ObjectStore

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Seems reasonable to me -- is the rationale that any opener that needs a `object_store` reference should obtain one as part of construction (rather than requiring it on the trait)?

**Comment by tustvold** [comment]
> the rationale that any opener that needs a object_store reference should obtain one as part of construction (rather than requiring it on the trait)?

The rationale is that some users are not using ObjectStore at all, and are using ParquetFileReaderFactory to provide a custom AsyncFileReader to the parquet crate's async reader. The FileStream plumbing, however, still required an ObjectStore necessitating a dummy object to be propagated through only to be ignored.

**Comment by Cheappie** [comment]
LGTM

**Comment by tustvold** [comment]
I plan to merge this this afternoon, unless I hear any objections

**Pull request merged**
