### PR TITLE
Remove call_ip in the SchedulerServer

### LINKED ISSUE #1558: Remove call_ip in the SchedulerServer
**Describe the bug**

Currently there's a field in the SchedulerServer for recording caller ip which sends requests to the scheduler. However, for one scheduler, there will be multiple clients. Concurrency issue may occur. It's not a good way for record the requester info in a global field. Therefore, it's better to remove it from the SchedulerServer.

We can get the requester ip from the hyper info and set it to the tonic info. Then in each tonic-based grpc interface, we can get the  the requester ip from the **Request**.

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #1558.

 # Rationale for this change

# What changes are included in this PR?

The field of _call_ip_ is removed from the _SchedulerServer_.
# Are there any user-facing changes?

### CODE REVIEW

**Review by houqp — APPROVED** [review]
nice clean up

**Comment by alamb** [comment]
Thanks @yahoNanJing  -- CI seems to be failing on this PR. Can you please resolve the issues?

**Comment by alamb** [comment]
I took the liberty of `git merge apache/master` on this branch to hopefully get a clean CI run and then will merge. Sorry for the delay @yahoNanJing

**Comment by msathis** [comment]
Some tests also has to be corrected it seems.

**Comment by yahoNanJing** [comment]
It's been merge with another PR. Will close this.

**Pull request closed without merging**
