### PR TITLE
Prepare for 23.0.0 release

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

N/A

# Rationale for this change

Regular release schedule

# What changes are included in this PR?

- Bump version
- [Changelog](https://github.com/andygrove/arrow-datafusion/blob/prep-23/dev/changelog/23.0.0.md)

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by andygrove** [comment]
Test failure:

```
 ---- datasource::file_format::csv::tests::query_compress_csv stdout ----
Error: IoError(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })
```

I see the same locally. I do not have the file references in the test, even after running `git submodule update --init`.

```rust
let df = ctx
            .read_csv(
                &format!("{}/csv/aggregate_test_100.csv.gz", arrow_test_data()),
                csv_options,
            )
            .await?;
```

**Comment by andygrove** [comment]
@Ted-Jiang @alamb any idea why I am running into this?

**Comment by andygrove** [comment]
nm, looks like I updated the git submodule in this PR somehow

**Review by alamb — APPROVED** [review]
Looks like it is going to be a good release. Thank you @andygrove

**Pull request merged**
