### PR TITLE
Support date datatypes in max/min

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #.

 # Rationale for this change

Currently only datafusion only supports string, numeric and timestamp types for min max aggregation. This is to add date types to make it more complete.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by viirya** [comment]
cc @houqp

**Review by houqp — APPROVED** [review]
LGTM, thank you @viirya !

**Review by Dandandan — APPROVED** [review]
👍

**Comment by viirya** [comment]
Thank you @houqp @Dandandan !

**Pull request merged**
