### PR TITLE
add notice file for python binding

### PR DESCRIPTION
**Pull request by houqp**
# Which issue does this PR close?

From https://github.com/apache/arrow-datafusion/pull/875#discussion_r688900939.

Relates to https://github.com/apache/arrow-datafusion/issues/887.

# Rationale for this change

Since our python binding release artifacts will be binaries, we need to include all licenses used by our dependencies.

# What changes are included in this PR?

Add notice file following https://github.com/apache/arrow/blob/master/NOTICE.txt

# Are there any user-facing changes?

no

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Thanks a lot for taking this, QP!

I was imagining that our notice would have to be something like "go to all our (transitive and non-transitive) dependencies, extract their licenses, create a notice based on the list of dependencies and respective licenses".

This offers the guarantees that anyone using the binary shipped from Apache that we verified that it can be used in the same or comparable terms as the Apache license itself (my understanding of why such notice exists in apache/arrow, but I am not very experienced here).

**Comment by houqp** [comment]
@kszucs it would be really helpful you can provide some insights here since I noticed you have made significant change to arrow's NOTICE.txt file. Do you know if arrow's NOTICE.txt file is managed manually or through automation? How deep do we need to get into the dependency graph to fish out all the downstream licenses?

The change in this PR only includes non-transitive dependencies.

**Comment by kszucs** [comment]
We maintain the license and notice files manually. I think it's enough to mention the dependencies where we have vendored source code from. Otherwise we'd need to generate the whole cargo dependency tree since we statically link everything with cargo (if I'm not mistaken). cc @kou

**Comment by kou** [comment]
These documents will help us:

* http://apache.org/legal/src-headers.html#notice
* https://infra.apache.org/licensing-howto.html#binary

**Comment by houqp** [comment]
Thanks @kszucs and @kou for the pointers. I went through the ASF docs, it looks like we do need to account for the full dependency tree for statically linked binary release :(

For source releases, we only need to take care of vendored source code.

Both LICENSE file and NOTICE needs to be updated for each compiled in dependency for the binary release.

**Comment by houqp** [comment]
closing this in favor of #966

**Pull request closed without merging**
