### PR TITLE
Consolidate `OwnedTableReference` with `TableReference`

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Related to https://github.com/apache/arrow-datafusion/pull/5343. I am trying to specifically demonstrate what I was talking about on https://github.com/apache/arrow-datafusion/pull/5343/files#r1123708924

# Rationale for this change

`TableReference` vs `OwnedTableReference` and having to convert back and forth between them is cumbersome to work with. This PR proposes removing the `OwnedTableReference` as `TableReference` can actually hold an owned string (via `Cow<'static>`

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Jefffrey** [comment]
I see what you mean now, it didn't occur to me to use `'static` as the lifetime for `TableReference<'a>` 🤯

Maybe change `OwnedTableReference` to be a type alias for `TableReference<'static>`? 🤔

**Comment by alamb** [comment]
> Maybe change OwnedTableReference to be a type alias for TableReference<'static>? 🤔

That may help people understand how to use it better. I'll give it a try and see what it looks like

**Comment by Jefffrey** [comment]
> That may help people understand how to use it better. I'll give it a try and see what it looks like

FYI I've done that implementation on #5343 already @alamb

**Comment by alamb** [comment]
> FYI I've done that implementation on https://github.com/apache/arrow-datafusion/pull/5343 already @alamb

Awesome -- thanks @Jefffrey  -- I haven't made it back to that PR yet. I'll close this PR then

**Pull request closed without merging**
