### PR TITLE
[minor] add Coverage Status in readme

### PR DESCRIPTION
**Pull request by Ted-Jiang**
# Which issue does this PR close?
Add code Coverage tag 😊
image

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Ted-Jiang** [comment]
@alamb After add code Coverage forget add this tag 😂
Seems higher than `arrow-rs`

**Review by andygrove — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @Ted-Jiang !

> Seems higher than arrow-rs

I think at least one problem is that doctests don't count for coverage and arrow-rs has a bunch of doctests

**Comment by Ted-Jiang** [comment]
> Thanks @Ted-Jiang !
> 
> > Seems higher than arrow-rs
> 
> I think at least one problem is that doctests don't count for coverage and arrow-rs has a bunch of doctests

@alamb Got it! will try to add this doctests to the report!

**Comment by alamb** [comment]
Thanks @Ted-Jiang

**Pull request merged**
