### PR TITLE
Refactor `UnwrapCastInComparison` to implement `OptimizerRule::rewrite()`

### PR DESCRIPTION
**Pull request by peter-toth**
## Which issue does this PR close?

Part of https://github.com/apache/arrow-datafusion/issues/9637.

## Rationale for this change

Eliminates a `LogicalPlan::with_new_exprs()` call and so `Expr` cloning.

## What changes are included in this PR?

This PR refactors `UnwrapCastInComparison::try_optimize()` to `UnwrapCastInComparison::rewrite()`.

## Are these changes tested?

Yes, with existing UTs.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you @peter-toth -- amazing how simple these PRs are now that we have the pattern down.- There are still some `Expr` copies left in the actual implementation I noticed, but this gets a bunch of the structural copying out of the way 

Very nice

**Review by jayzhan211 — APPROVED** [review]
👍

**Comment by jayzhan211** [comment]
Thanks @peter-toth

**Comment by peter-toth** [comment]
> There are still some `Expr` copies left in the actual implementation I noticed, but this gets a bunch of the structural copying out of the way

I will try to eliminate those in a follow-up PR.

Thanks for the review @alamb, @jayzhan211!

**Comment by peter-toth** [comment]
@alamb, @jayzhan211 here is a follow-up PR to remove remaining `Expr` clones: https://github.com/apache/arrow-datafusion/pull/10115

**Pull request merged**
