### PR TITLE
Refactor: Consolidate expression simplification code in `simplify_expression.rs`

### PR DESCRIPTION
**Pull request by alamb**
# NOTE: This PR just moves code around (it doesn't change logic) so please don't be too scared of its size

# Which issue does this PR close?

Re https://github.com/apache/arrow-datafusion/issues/1160 (more sophisticated expression simplification)

 # Rationale for this change
There are at least three places where expressions are simplified, with some overlap: `const_evaluator.rs`, `expression_simplifier.rs`, and `optimizer/util.rs`

This makes it hard both to understand what simplifications are applied, as well as what is redundant (e.g. https://github.com/apache/arrow-datafusion/pull/1164)

# What changes are included in this PR?
1. Move `ConstEvaluator` and `Simplifier` logic and tests into `expression_simplifier.rs`.
2. Rename some tests

# Are there any user-facing changes?
The location of `ConstEvaluator` has changed

### CODE REVIEW

**Comment by alamb** [comment]
FYI @rdettai this is one strategy to hopefully make reviews a bit easier: the first PR is mechanical and hopefully quick to review. The second PR can then have logic changes in it without as many mechanical changes.

**Comment by alamb** [comment]
FYI @houqp  / @jgoday / @liukun4515  -- I plan a bit of consolidation in the expression simplification logic. See this PR and the ones linked to it

**Comment by liukun4515** [comment]
> FYI @houqp / @jgoday / @liukun4515 -- I plan a bit of consolidation in the expression simplification logic. See this PR and the ones linked to it

I will review this later.
But the context is too much, I need more time to understand them.
Maybe takes two or three days.

@alamb

**Comment by alamb** [comment]
> I will review this later.

Thank you @liukun4515  -- this PR in particular looks massive but in reality is pretty simple -- I literally cut/pasted code from one module to another

**Comment by alamb** [comment]
I don't actually think this change requires much review (as it just moves stuff around) so unless anyone has any objections, I'll plan to merge it sometime tomorrow

**Review by houqp — APPROVED** [review]

**Review by liukun4515 — APPROVED** [review]
LGTM

**Comment by alamb** [comment]
Thank you @houqp  and @liukun4515

**Pull request merged**
