### PR TITLE
RFC: add error macros

### PR DESCRIPTION
**Pull request by alamb**
Suggested by @comphead  on https://github.com/apache/arrow-datafusion/pull/6721/files#r1235622262

I made some macros and then had trouble using them. Issues I ran into:

1. The macros return `Result<..>` rather than `DataFusionError` so they can't be used in all places (e.g the one @comphead suggested in https://github.com/apache/arrow-datafusion/pull/6721/files#r1235622262)
2. Many errors are created using `format!(...)` which I couldn't figure out how to make into a nice macro invocation

Maybe someone else has some ideas

### CODE REVIEW

**Review by comphead — COMMENTED** [review]
I tried that 

```
            if val.is_null() {
                plan_err!(
                    "Invalid window frame: start bound cannot be UNBOUNDED FOLLOWING"
                )?
            }
        } else if let WindowFrameBound::Preceding(val) = &end_bound {
            if val.is_null() {
                plan_err!(
                    "Invalid window frame: end bound cannot be UNBOUNDED PRECEDING"
                )?
            }
```

Looks more concise. Reg to `format!` checking if that can be done better

**Comment by comphead** [comment]
```
#[macro_export]
macro_rules! plan_err {
    ($($arg:tt)*) => {{
        let res = format!($($arg)*);
        Err(datafusion_common::DataFusionError::Plan(res.into()))
    }}
}
```

```
            if !val.is_null() {
                plan_err!("value is not null {}", val)?
            }
```

**Comment by comphead** [comment]
@alamb let me know what do you think.

**Comment by comphead** [comment]
@alamb I can take all the findings and create a PR replacing all plan errors for now, if you think it is a right direction to go

**Comment by alamb** [comment]
Sorry for the late reply @comphead 

> @alamb let me know what do you think.

I think it looks great to me. 

> @alamb I can take all the findings and create a PR replacing all plan errors for now, if you think it is a right direction to go

I think that would be good. Perhaps we you could make the macros and do a few changes and we can make sure it looks reasonable before spending the time to migrate the whole codebase?

Thanks again @comphead

**Pull request closed without merging**
