### PR TITLE
[CI] Fix RUSTFLAGS

### PR DESCRIPTION
**Pull request by Jefffrey**
## Which issue does this PR close?

Closes #.

## Rationale for this change

https://github.com/apache/arrow-datafusion/commit/428973732b14055971604204bf3dcd605120b3dd sped win ci up, running at 33min:

- https://github.com/apache/arrow-datafusion/actions/runs/7433532490

Following commit https://github.com/apache/arrow-datafusion/commit/dd4263f843e093c807d63edf73a571b1ba2669b5 had runtime of 39min:

- https://github.com/apache/arrow-datafusion/actions/runs/7433765725

Subsequent runs fall around 39-42min range

Until this commit https://github.com/apache/arrow-datafusion/commit/d9a1d4261f78dfd3ead235d6b850c64e0ae9bec6 which causes runtime of 47min:

- https://github.com/apache/arrow-datafusion/actions/runs/7494637547

Subsequent runs (up to latest main) fall around 44-48min range

## What changes are included in this PR?

Fix accidental regression by https://github.com/apache/arrow-datafusion/commit/d9a1d4261f78dfd3ead235d6b850c64e0ae9bec6 which named the env var incorrectly.

### CODE REVIEW

**Comment by Jefffrey** [comment]
Two commit action runs with fix:

- https://github.com/apache/arrow-datafusion/actions/runs/7600594577 - 41min
- https://github.com/apache/arrow-datafusion/actions/runs/7609479932 - 42min

Fixes https://github.com/apache/arrow-datafusion/commit/d9a1d4261f78dfd3ead235d6b850c64e0ae9bec6

For https://github.com/apache/arrow-datafusion/commit/dd4263f843e093c807d63edf73a571b1ba2669b5 I'm not sure if the slowdown was due to setting `RUST_MIN_STACK` or due to the code changes. If it was due to the `RUST_MIN_STACK` then hopefully should be resolved by https://github.com/apache/arrow-datafusion/issues/8837

**Review by comphead — APPROVED** [review]
thanks @Jefffrey for fixing that nasty typo

**Comment by comphead** [comment]
Basically CI times fluctuates, I saw Macos builds being 19 mins, and on the same codebase the next run 28mins.

**Comment by alamb** [comment]
Thanks @Jefffrey  and @comphead

**Pull request merged**
