### PR TITLE
All building execution context from another execution context's state

### LINKED ISSUE #1439: ExecutionContext support init ExecutionContextState with `new(state: Arc<Mutex<ExecutionContextState>>)` method
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Now, we can only create a datafusion execution context with default table information in ballista, we can't just create a new context because we need a context that has tables registered from previous SQL statements that have been executed.
image

**Describe the solution you'd like**
If ExecutionContext support init ExecutionContextState with `new(state: Arc<Mutex<ExecutionContextState>>)` method, then we can manage this information in the ballista scheduler, and send this information to the ballista executor, where every datafusion ExecutionContext created in the ballista executor can be Have the same ExecutionContextState content.

### PR DESCRIPTION
**Pull request by hntd187**
# Which issue does this PR close?

Closes #1439 

# Rationale for this change
See issue, but this allows a way to carry over current state to newly created execution contextes 

# What changes are included in this PR?
Changes to carry over execution conext

# Are there any user-facing changes?
Not really

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
I wonder how different this is to calling `clone()` on the execution context?

In the example from https://github.com/apache/arrow-datafusion/issues/1439 it appears you want to do something like

```rust
let context = ExecutionContext::new();
let new_context = ExecutionContext::with_context(context.get_state());
```

If so, another way to achieve the same thing would be

```rust
let context = ExecutionContext::new();
let new_context = context.clone();
```

I think I may be missing something

**Comment by alamb** [comment]
Thanks @hntd187

**Comment by hntd187** [comment]
It's not and now that I think of it I shouldn't have just done this without asking why. I figured that ExecutionContext did not implement Clone which was why it was necessary. If I just missed the clone impl than this is probably a useless PR we can throw away.

**Comment by alamb** [comment]
I think `ExecutionContext` does implement clone:

```rust
#[derive(Clone)]
pub struct ExecutionContext {
    /// Internal state for the context
    pub state: Arc<Mutex<ExecutionContextState>>,
}
```

**Pull request closed without merging**
