### PR TITLE
Add timezome string to stablize test

### LINKED ISSUE #1262: test `create_external_table_with_timestamps` failed locally
**Describe the bug**
`create_external_table_with_timestamps` failed locally, but CI seems normal.

**To Reproduce**

**Expected behavior**
```
expected:

[
    "+--------+-------------------------+",
    "| name   | ts                      |",
    "+--------+-------------------------+",
    "| Andrew | 2018-11-13 17:11:10.011 |",
    "| Jorge  | 2018-12-13 12:12:10.011 |",
    "+--------+-------------------------+",
]
actual:

[
    "+--------+-------------------------+",
    "| name   | ts                      |",
    "+--------+-------------------------+",
    "| Andrew | 2018-11-13 09:11:10.011 |",
    "| Jorge  | 2018-12-13 04:12:10.011 |",
    "+--------+-------------------------+",
]
```

**Additional context**
It seems a zone question, I'm in east 8th.

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closed #1262.

Fix test failure locally:

```
failures:

---- execution::context::tests::create_external_table_with_timestamps stdout ----
thread 'execution::context::tests::create_external_table_with_timestamps' panicked at 'assertion failed: `(left == right)`
  left: `["+--------+-------------------------+", "| name   | ts                      |", "+--------+-------------------------+", "| Andrew | 2018-11-13 17:11:10.011 |", "| Jorge  | 2018-12-13 12:12:10.011 |", "+--------+-------------------------+"]`,
 right: `["+--------+-------------------------+", "| name   | ts                      |", "+--------+-------------------------+", "| Andrew | 2018-11-14 01:11:10.011 |", "| Jorge  | 2018-12-13 20:12:10.011 |", "+--------+-------------------------+"]`: 

expected:

[
    "+--------+-------------------------+",
    "| name   | ts                      |",
    "+--------+-------------------------+",
    "| Andrew | 2018-11-13 17:11:10.011 |",
    "| Jorge  | 2018-12-13 12:12:10.011 |",
    "+--------+-------------------------+",
]
actual:

[
    "+--------+-------------------------+",
    "| name   | ts                      |",
    "+--------+-------------------------+",
    "| Andrew | 2018-11-14 01:11:10.011 |",
    "| Jorge  | 2018-12-13 20:12:10.011 |",
    "+--------+-------------------------+",
]

', datafusion/src/execution/context.rs:3932:9
```

 # Rationale for this change

To stablize test for developers.

# What changes are included in this PR?

Adding timzome strings to stablize test locally.

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by Jimexist** [comment]
you can just add `Z`

**Review by Jimexist — APPROVED** [review]
thanks for the fix!

**Comment by viirya** [comment]
Thank you @Jimexist !

**Comment by xudong963** [comment]
related issue: https://github.com/apache/arrow-datafusion/issues/1262

**Comment by viirya** [comment]
Thanks @xudong963 . Linked to the issue.

**Comment by viirya** [comment]
Can we merge this? @Jimexist

**Review by alamb — APPROVED** [review]
I think this is related to the arrow 6.1.0 release -- specifically https://github.com/apache/arrow-rs/pull/832 to have the csv reader have the same date/time parsing logic as the rest of the stack.

Thank you @viirya  for fixing this

**Comment by viirya** [comment]
Thank you @alamb!

**Pull request merged**
