### PR TITLE
Be consistent with pg on real datatype

### LINKED ISSUE #1380: real data type is float32 in PG database, but in the datafusion it is as float64
**Describe the bug**
In the PG database, the `real` datatype is as the float32, but it is as float64 in the datafusion.

Do we need to be consistent with PG database in the point?

1. https://github.com/apache/arrow-datafusion/blob/3bf5811b9a275b7ce6792867a5c1fa230a880742/datafusion/src/catalog/information_schema.rs#L416
2. https://github.com/apache/arrow-datafusion/blob/414c826bf06fd22e0bb52edbb497791b5fe558e0/datafusion/src/sql/planner.rs#L377

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by hntd187**
# Which issue does this PR close?

Closes #1380 .

 # Rationale for this change
Be consistent with pg

# What changes are included in this PR?
Change real datatype to map to f32 instead of f64

# Are there any user-facing changes?

### CODE REVIEW

**Comment by liukun4515** [comment]
@hntd187  thanks for your contribution.
We should make consistent with the community first.
If the datafusion just want to support the float64, i think it is not a bug.
@houqp @alamb

**Comment by houqp** [comment]
@hntd187 do you mind writing a quick test to guard against regression?

**Review by houqp — APPROVED** [review]

**Comment by hntd187** [comment]
Of course, let me do that

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @hntd187 

I kicked off CI and once that passes I plan to merge this in

**Review by liukun4515 — APPROVED** [review]
LGTM

**Pull request merged**
