### PR TITLE
Improve readability of table scan projections in query plans (remove `Some` and `None`)

### LINKED ISSUE #2697: Improve readability of table scan projections in query plans
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
From discussion in https://github.com/apache/arrow-datafusion/pull/2690#discussion_r889492584

What about only showing the projection when there is one and ommiting it when there are none.
This could remove the None/Some too:

```
TableScan a projection=[col1,col2]
```

vs

```
TableScan a
```

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by comphead**
# Which issue does this PR close?

Closes #2697 .

 # Rationale for this change

Improve readability for Table scans. Provide column name instead of column index.

`TableScan a projection=[col1,col2]` instead of `TableScan a projection=Some([col1,col2])`
# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by comphead** [comment]
@andygrove my concern however the output like 

```
        "  Projection: #aggregate_test_100.c1",
        "    Filter: #aggregate_test_100.c2 > Int64(10)",
        "      TableScan: aggregate_test_100 projection=[c1, c2], 
```

Afaik Projection here is query projection(selected by user output), and TableScan projection is what needs to be fetched from the table to make query work. Since both of it named as projection won't be that confusing?

**Comment by comphead** [comment]
+ @LiuYuHui

**Comment by comphead** [comment]
@andygrove please check this

**Review by alamb — APPROVED** [review]
Thank you @comphead  -- I think the plans now look much nicer 🧹 👍

**Pull request merged**
