### PR TITLE
Minor: fix warning of 'Unnecessary braces in use statement'

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

N/A

## Rationale for this change
Reported by rust-analyzer diagnostics.

c632bef6-c8cc-4f32-a731-2cf38b4b0288_capture

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

**Review by Jefffrey — APPROVED** [review]
Nice cleanup :+1: 

Interesting that `cargo fmt` didn't catch this :thinking:

**Comment by jonahgao** [comment]
> Nice cleanup 👍
> 
> Interesting that `cargo fmt` didn't catch this 🤔

It seems that cargo-fmt has not covered these files, which might be related to creating modules within macros. I need to investigate it further.

**Review by viirya — APPROVED** [review]

**Comment by comphead** [comment]
> Nice cleanup 👍
> 
> Interesting that `cargo fmt` didn't catch this 🤔

I have the same question.....

**Comment by jonahgao** [comment]
> > Nice cleanup 👍
> > Interesting that `cargo fmt` didn't catch this 🤔
> 
> I have the same question.....

Filled a new issue #9281.

**Pull request merged**
