### PR TITLE
feat: implement exists subquery

### LINKED ISSUE #1209: support more subqueries
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
support more subqueries and pass the TPCH associated with the subquery: https://github.com/apache/arrow-datafusion/issues?q=is%3Aopen+is%3Aissue+milestone%3ATPC-H

**Describe the solution you'd like**

- [ ] `WHERE EXISTS (SELECT ...)`
- [ ] `SELECT (subquery) AS x` or `WHERE (subquery) = x`
- [ ] `[ NOT ] IN (SELECT ...)`  https://github.com/apache/arrow-datafusion/issues/1835
- [ ] `<expr> <op> ANY/SOME (<query>)`
- [ ] `<expr> <op> ALL (<query>)`
- [ ] Single-Row Comparison

**Describe alternatives you've considered**
Correlated subqueries will be implemented by nested loop initially. After the realization of basic functions, we can do some optimization, such as decorrelation and so on.

**Additional context**

### PR DESCRIPTION
**Pull request by xudong963**
# Which issue does this PR close?

Closes #1209

But in this ticket, I only implement the **exists** subquery. I believe this ticket is building a subquery skeleton which will make adding other subqueries convenient.

# What changes are included in this PR?

After generating LogicalPlan, if the logical plan contains subqueries, it'll be rewrite to unnesting in logical level. The core advantage is that subqueries won't influence physical level.

# Are there any user-facing changes?

Yes, API changes have already taken place in draft implementation.
But users can use subquery!

### CODE REVIEW

**Comment by xudong963** [comment]
This ticket is actively developing during my chunks of free time, such as weekends and holidays. When I think it's ok, I'll make it ready for review.

**Comment by yahoNanJing** [comment]
Hi @xudong963, how's the progress? 

In our case, we need to use in subquery. Do you have plan for that? If no, I'll try to implement that.

**Comment by xudong963** [comment]
> Hi @xudong963, how's the progress?
> 
> In our case, we need to use in subquery. Do you have plan for that? If no, I'll try to implement that.

The PR now has finished skeleton, I'll fix the bug and add more tests in the PR on weekend. After the PR is finished, the IN subquery can be easy to add by using the subquery skeleton.

**Comment by mingmwang** [comment]
Hi, @xudong963 

If you do not mind, I can continue working on this PR.

**Comment by xudong963** [comment]
> Hi, @xudong963
> 
> If you do not mind, I can continue working on this PR.

Thanks @mingmwang, I don't mind at all. I recently changed my job and didn't have much time to move forward.

**Pull request closed without merging**
