### PR TITLE
Add write_csv to DataFrame

### LINKED ISSUE #1777: [EPIC] Improve DataFusions ability to work with files
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

I would like to add functionality for writing files from DataFusion.  To start, I've thought of the below.

- [ ] (1) Add write functionality to `ObjectStore`
- [x] (2)Add `write_json` to `ExecutionContext`
- [ ] (3) Add `write_arrow` to `ExecutionContext`
- [x] (4) Add `COPY` / `COPY TO` command for SQL (like postgres https://www.postgresql.org/docs/current/sql-copy.html)
- [ ] (5) Add ability to write partitioned datasets
- [ ] (6) Add support for writing metadata
- [x] (7) Add `write_csv` method to `DataFrame`
- [x] (8) Add `write_parquet` method to `DataFrame`
- [ ] (9) Add `write_arrow` method to `DataFrame`
- [x] (10) Add `write_json` method to `DataFrame`
- [x] (11) Add `read_json` method to `DataFrame`
- [x] (12) Add `read_json` method to `ExecutionContext`
- [x] (13) Add `register_json` method to `ExecutionContext`
- [x] (14) Support `IF NOT EXISTS` for `CREATE EXTERNAL TABLE`
- [ ] (15) Add `read_arrow` to `ExecutionContext`
- [ ] (16) Add `read_arrow` to `DataFrame`

I will use this as a parent / tracker issue for the above points which will each have an issue.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by matthewmturner**
# Which issue does this PR close?

Closes #1777 task 7

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by matthewmturner** [comment]
@alamb would you mind checking this out to see if going in right direction?  I took the logic for writing csvs and put it in new function `plan_to_csv` within `src/physical_plan/file_format/csv` and moved testing there.  Then just used that function in both `ExecutionContext` and `DataFrame`

currently failing because of the signature of `write_csv` having `impl AsRef<str>` which i took from the existing implementation on `ExecutionContext` but doesnt work because trait object cant have method with generic type parameter.  Is there a reason we cant use `&str`?  More details here https://doc.rust-lang.org/error-index.html#E0038  and i dont think any of the proposed workarounds are good for our use case.

**Comment by alamb** [comment]
>  I took the logic for writing csvs and put it in new function plan_to_csv within src/physical_plan/file_format/csv and moved testing there. Then just used that function in both ExecutionContext and DataFrame

Looks good to me 👍 

> currently failing because of the signature of write_csv having impl AsRef<str> which i took from the existing implementation on ExecutionContext but doesnt work because trait object cant have method with generic type parameter. Is there a reason we cant use &str? 

I think taking `&str` is totally fine in the `DataFrame` trait

**Comment by matthewmturner** [comment]
@alamb thanks!

**Comment by Jimexist** [comment]
Hi thanks for the contribution 

I wonder if we can use an extension trait for Csv writing method so that users can choose to use the method if they import the trait - same goes to other potential methods like write json files, etc.

This way we can reduce the minimal dataframe struct size

**Comment by matthewmturner** [comment]
@Jimexist im not opposed, but would the idea be to do this only for methods that are writing? or should this be generalized to all IO methods? Im just wondering where we draw the line between core dataframe methods and extensions.

**Comment by matthewmturner** [comment]
@Jimexist what would you think about merging this as is and then tackling that point as part of convos on #1712 where there is interest in moving DataFrame from trait to struct.

**Review by Jimexist — APPROVED** [review]

**Pull request merged**
