### PR TITLE
fix: fix `GLIBC_2.35' not found error in ci

### PR DESCRIPTION
**Pull request by ZhengLin-Li**
## Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/9209.

## Rationale for this change

Previously, we got the following error:
```
❯ docker run -it -v /tmp:/data datafusion-cli
datafusion-cli: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by datafusion-cli)
datafusion-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by datafusion-cli)
datafusion-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by datafusion-cli)
datafusion-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by datafusion-cli)
```

## What changes are included in this PR?

Update the versions in CI, It ensures that the Rust image is based on a specific release.

## Are these changes tested?

Yes, I tested the change in my local machine. Here is the screenshot:
image

## Are there any user-facing changes?

No

### CODE REVIEW

**Review by comphead — APPROVED** [review]
Thanks @ZhengLin-Li for your contribution.

lgtm, I checked this on my Mac M, it works.
But with prev builder I got the process SIGKILLed

**Comment by ZhengLin-Li** [comment]
Thanks for your review! @comphead

Could you elaborate more on "But with prev builder I got the process SIGKILLed"? If this is an issue, I will try to fix it.

**Comment by comphead** [comment]
> Thanks for your review! @comphead
> 
> Could you elaborate more on "But with prev builder I got the process SIGKILLed"? If this is an issue, I will try to fix it.

The crate `datafusion-physical-expr` could not compile on docker, so it just killed by the kernel with no obvious reason
```
(signal: 9, SIGKILL: kill)
```

With proposed builder I was able to build the DF client properly

**Comment by ZhengLin-Li** [comment]
ok, got it. So it seems that everything goes well now. Could you help with the merge? @comphead

**Pull request merged**
