### PR TITLE
Minor: remove a strange char

### PR DESCRIPTION
**Pull request by haohuaijin**
## Which issue does this PR close?

Closes #.

### CODE REVIEW

**Review by Weijun-H — APPROVED** [review]
LGTM! Thanks @haohuaijin

**Comment by Weijun-H** [comment]
Can we check for redundant white backgrounds using clippy 🤔?

**Comment by Weijun-H** [comment]
> this char is not white backgrounds, but in mac's chrome is look like is white backgrounds. Xnip2023-11-02_22-49-46

I just checked it on GitHub, and now it makes sense.

**Review by alamb — COMMENTED** [review]
Thanks @haohuaijin

**Review by alamb — APPROVED** [review]

**Pull request merged**
