### PR TITLE
cli: add cargo.lock

### LINKED ISSUE #2071: Commiting the Cargo.lock
Hi, could you commit the cargo.lock file please ?

The reason I am asking is that it is usually needed to build the software from source to package for other discributions.
I am currently having a look at packaging for nixos.

Let me know if you need more details.

### PR DESCRIPTION
**Pull request by happysalada**
# Which issue does this PR close?

Add a cargo.lock to enable packaging for different os.

Since cargo will not tolerate a lock that is not at the root of the workspace, I had to add the lock there.
I've added some exclude statements for it not to be included for all the other libraries.

Closes #2071 

# Are there any user-facing changes?

None

### CODE REVIEW

**Comment by houqp** [comment]
@happysalada I think you need to put the lock file inside the datafusion-cli directory instead.

**Comment by houqp** [comment]
Ha, I saw your other comment now, @happysalada you need to exclude datafusion-cli from the root workspace by removing it from https://github.com/apache/arrow-datafusion/blob/b7d3bb1e3f2a884fc0775dc9dc869ae77b226269/Cargo.toml#L26. Then add it to an exclude list, something like this: https://github.com/delta-io/delta-rs/blob/346f51a277c23be09eca373cd6d775b745d59c05/Cargo.toml#L10

**Comment by happysalada** [comment]
I had another go at it doing what you suggested, let me know.

**Comment by happysalada** [comment]
@houqp let me know what you think when you have a moment. (no worries if you are busy).

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
LGTM, thanks @happysalada

**Review by alamb — APPROVED** [review]
LGTM. Thanks @happysalada  and @houqp 

The CI was failing as `datafusion-cli` is not part of the workspace anymore

https://github.com/apache/arrow-datafusion/runs/5797584094?check_suite_focus=true

I pushed a small change in 30341de85 to fix

**Comment by alamb** [comment]
Looks like the integration test also wants to use datafusion-cli and the build script needs to be updated

https://github.com/apache/arrow-datafusion/runs/5799193929?check_suite_focus=true

**Comment by happysalada** [comment]
it looks like 2 more files need to be updated.
I've updated the python integration tests file.
however the workflow file also needs to be modified here https://github.com/apache/arrow-datafusion/commit/30341de85a93c875a4542fc48c960187a4a219e2#diff-73e17259d77e5fbef83b2bdbbe4dc40a912f807472287f7f45b77e0cbf78792dL213
I don't think I can do that though.

**Comment by alamb** [comment]
cc @Jimexist

**Comment by alamb** [comment]
Thanks @happysalada

**Pull request merged**
