### PR TITLE
Refine the statistics estimation for the limit and aggregate operator

### LINKED ISSUE #4715: Refine the statistics estimation for the limit and aggregate operator
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Statistics is very useful for making intelligent decisions, especially for choosing proper join implementation. Therefore, it's better to introduce it into each plan operator as much as possible.

**Describe the solution you'd like**

- For the `limit` operator, the output row count is surely not larger than its limited number;
- For the `aggregate` operator, the output row count is surely not larger than its input row count.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #4715.

# Rationale for this change

With these introduced row count info, for a SQL similar to the following pattern, the `JoinSelection` optimizer rule will successfully be able to choose the `CollectLeft` partition mode rather than the `Partitioned`, which reduces the query duration running on Ballista from 7.5s to 4.5s for a data set of 1.3 billion rows.

```
select column_of_high_cardinality,
       sum(measure_1)
from table_0
where column_of_high_cardinality in
    (select column_of_high_cardinality
     from table_0
     group by column_of_high_cardinality
     order by sum(measure_0) desc
     limit 1000)
group by column_of_high_cardinality
```

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by yahoNanJing** [comment]
Hi @alamb, @Dandandan, @mingmwang, could you help review this PR?

**Comment by alamb** [comment]
I believe this PR actually builds on https://github.com/apache/arrow-datafusion/pull/4714

(the idea of improving the statistics for limits and aggregates is a good one, 👍 )

**Comment by yahoNanJing** [comment]
Hi @alamb, since #4714 has been merged, now this PR is ready for review.

**Review by alamb — COMMENTED** [review]
Code looks reasonable to me 👍 

I think this PR needs some tests to verify the behavior (and make sure we don't break it by accident in a follow on PR)

**Comment by alamb** [comment]
Marking as draft so it is more clear the PR  is awaiting some tests prior to merge

**Comment by yahoNanJing** [comment]
Hi @alamb, is this PR ready for review and merge now?

**Review by alamb — APPROVED** [review]
LGTM -- thank you @yahoNanJing

**Comment by alamb** [comment]
Thank you @yahoNanJing

**Pull request merged**
