### PR TITLE
refactor: split relation of planner into one part.

### LINKED ISSUE #4392: Enhancement: split the SQL `planner` into smaller modules
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The current planner file is too large, we can split it.

Like 
- query.rs
- select.rs
- set_expr.rs
- ....

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #4392.

FOLLOWUP #4783

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by jackwener** [comment]
@alamb @liukun4515 PTAL

**Review by alamb — APPROVED** [review]
Looks great to me @jackwener -- I  verified that just code was moved and that no tests were changed 

Thank you so much

I think this PR is relatively uncontroversial and is likely to accumulate / cause conflicts, but I plan to wait to merge until @andygrove cuts the release https://github.com/apache/arrow-datafusion/issues/4776  hopefully later today to avoid introducing last minute churn.

**Comment by alamb** [comment]
BTW @jackwener another thing I noticed was that the sql planner tests could probably be put into  you plan to move the tests into something like `datafusion/sql/test/planning.rs` or whatnot to make the planner.rs module even smaller

https://github.com/apache/arrow-datafusion/blob/169b5228800f991be913b10ffdfd161e2cbc7baf/datafusion/sql/src/planner.rs#L2021-L2032

**Comment by liukun4515** [comment]
I will take a look later

**Comment by jackwener** [comment]
> BTW @jackwener another thing I noticed was that the sql planner tests could probably be put into you plan to move the tests into something like `datafusion/sql/test/planning.rs` or whatnot to make the planner.rs module even smaller
> 
> https://github.com/apache/arrow-datafusion/blob/169b5228800f991be913b10ffdfd161e2cbc7baf/datafusion/sql/src/planner.rs#L2021-L2032

Thanks @alamb, I have finished it.

**Review by alamb — APPROVED** [review]
Thanks again @jackwener  

I double checked to make sure the tests still run now that they are moved to a different module:

https://github.com/apache/arrow-datafusion/actions/runs/3862329303/jobs/6583883751#step:7:3200


```
...
     Running tests/integration_test.rs (target/debug/deps/integration_test-02f1355111e126c1)

running 231 tests
test aggregate_with_cube ... ok
test aggregate_with_grouping_sets ... ok
test aggregate_with_rollup_with_grouping ... ok
test aggregate_with_rollup ... ok
test approx_median_window ... ok
test boolean_literal_in_condition_expression ... ok
test cast_from_subquery ... ok
test create_external_table_csv ... ok
test cast_to_invalid_decimal_type ... ok
test create_external_table_custom ... ok
test create_external_table_csv_no_schema ... ok
test create_external_table_parquet ... ok
test create_external_table_parquet_no_schema ... ok
test create_external_table_with_compression_type ... ok
test cte_unbalanced_number_of_columns ... ok
test cross_join_not_to_inner_join ... ok
...
```

Since this PR has a large potential for conflicts and I think it is uncontroversial  as it is mechanical (it moves code around and we can always move it back if that is deired) I am going to merge it and I think we can deal with follow up 

Thanks @liukun4515

**Pull request merged**
