### PR TITLE
Fix required partitioning of Single aggregation mode

### LINKED ISSUE #6949: Single aggregation mode doesn't correctly declare `required_input_distribution`
### Describe the bug

When looking at aggregation modes I found that the single aggregation mode requires inputs to be partitioned already, but it doesn't.

As we're only using the `Single` mode in an optimizer rule, it isn't too much of a problem ATM, but would be if we start using the mode more often.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #6949

# Rationale for this change
Fix a small issue in this aggregation mode .
Currently the `Single` mode returns `UnspecifiedDistribution` as required distribution, which is not correct. If we would re-optimize / change the plan, it could cause the plan to return incorrect results. This currently is not the case in DataFusion as we rely on the fact that required distribution is already satisfied and we don't modify that part of the plan.

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Dandandan** [comment]
FYI @mingmwang

**Comment by mustafasrepo** [comment]
According to `CombinePartialFinalAggregate` rule, when planner sees `AggregateMode::Partial` + `AggregateMode::Final` or `AggregateMode::Partial` + `AggregateMode::FinalPartitioned`, it replaces these immediate operators with `AggregateMode::Single`. 
For second case changing distribution requirement to `Distribution::HashPartitioned` makes sense. However, for first case distribution requirement should be `SinglePartition` I guess.  

With the proposed changes, `AggregateMode::Single` will require `vec![Distribution::HashPartitioned(vec![])]` (where group by is empty). when it is constructed from `AggregateMode::Partial` + `AggregateMode::Final` stack. 

Will this requirement add `RepartitionExec(hash)` during planning?

**Comment by mingmwang** [comment]
@mustafasrepo 

I think the purpose of this PR is to extend the use case of `AggregateMode::Single`. I think the change make sense, but it is better to add some comments.

**Review by mingmwang — APPROVED** [review]
LGTM

**Comment by Dandandan** [comment]
> According to `CombinePartialFinalAggregate` rule, when planner sees `AggregateMode::Partial` + `AggregateMode::Final` or `AggregateMode::Partial` + `AggregateMode::FinalPartitioned`, it replaces these immediate operators with `AggregateMode::Single`. For second case changing distribution requirement to `Distribution::HashPartitioned` makes sense. However, for first case distribution requirement should be `SinglePartition` I guess.
> 
> With the proposed changes, `AggregateMode::Single` will require `vec![Distribution::HashPartitioned(vec![])]` (where group by is empty). when it is constructed from `AggregateMode::Partial` + `AggregateMode::Final` stack.
> 
> Will this requirement add `RepartitionExec(hash)` during planning?

Ah I missed that part. 
I missed the part that `Final` + `FinalPartitioned` is also being converted to `Single`. I think the correct way (that avoids planning errors) would be a `Single` that requires `SinglePartition` in that case.

Currently the optimization rule runs after the `RepartitionExec(hash)` and `CoalescePartitions` are added so it *should* already have those requirements, but I think it's better to generate a correct plan, otherwise we could introduce errors later on (e.g. by a rule that removes unnecessary `RepartitionExec` / `CoalescePartitions` or by using the `Single` mode directly before the required partitioning is added).

**Review by mustafasrepo — APPROVED** [review]
Thanks @Dandandan for this PR.

**Pull request merged**
