### PR TITLE
fix 593, reduce cloning by taking ownership in logical planner's `from` fn

### LINKED ISSUE #593: logical plan builder from method should take owned value as input
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

```
pub fn from(plan: &LogicalPlan) -> Self {
    Self { plan: plan.clone() }
```

The from method takes a LogicalPlan reference, then does clone internally.

**Describe the solution you'd like**

It would be better to take an owned value and let the caller handle the clone if needed.

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #593

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Yes, I really like this change (there is far too much cloning in the creation of plans (and `Expr`s generally). It is an API change so I think maybe we should leave it open for a few days to see if anyone else has opinions

**Review by jorgecarleitao — APPROVED** [review]
Solid improvement to me 👍 Tjhanks @Jimexist !

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
If we really want to make this backwards compatible, we could use `impl Into<LogicalPlan>` as the argument type, see https://github.com/apache/arrow-datafusion/pull/615.

**Review by Dandandan — APPROVED** [review]

**Comment by Jimexist** [comment]
> If we really want to make this backwards compatible, we could use `impl Into<LogicalPlan>` as the argument type, see #615.

thanks for the suggestion. unless it's a goal, i'd like to keep this simple for the moment.

**Comment by alamb** [comment]
Thanks again @Jimexist

**Pull request merged**
