### PR TITLE
Error after pre-release arrow upgrade: "out of order projection is not supported" (NOT FOR MERGING)

### PR DESCRIPTION
**Pull request by alamb**
This PR demonstrates a test that fails with the code from https://github.com/apache/arrow-rs/pull/1682 in arrow (not included in arrow 14.0.0). 

This PR pins datafusion to arrow right after https://github.com/apache/arrow-rs/pull/1682 was merged at commit https://github.com/apache/arrow-rs/commit/5b154ea40314dc2f09babbb363bf7f1fe439d4eb

To reproduce:

```shell
cargo test -p datafusion --lib
```

Results in:
```shell
failures:

---- physical_plan::file_format::parquet::tests::evolved_schema_filter stdout ----
thread 'physical_plan::file_format::parquet::tests::evolved_schema_filter' panicked at 'called `Result::unwrap()` on an `Err` value: ArrowError(ExternalError(ParquetError(General("out of order projection is not supported"))))', datafusion/core/src/physical_plan/file_format/parquet.rs:968:14

---- physical_plan::file_format::parquet::tests::evolved_schema_inconsistent_order stdout ----
thread 'physical_plan::file_format::parquet::tests::evolved_schema_inconsistent_order' panicked at 'called `Result::unwrap()` on an `Err` value: ArrowError(ExternalError(ParquetError(General("out of order projection is not supported"))))', datafusion/core/src/physical_plan/file_format/parquet.rs:819:14


failures:
    physical_plan::file_format::parquet::tests::evolved_schema_filter
    physical_plan::file_format::parquet::tests::evolved_schema_inconsistent_order

test result: FAILED. 656 passed; 2 failed; 1 ignored; 0 measured; 0 filtered out; finished in 2.00s

error: test failed, to rerun pass '-p datafusion --lib'
Error: Process completed with exit code 101.
```

### CODE REVIEW

**Comment by tustvold** [comment]
Likely related https://github.com/apache/arrow-datafusion/issues/2453 - the DataFusion logic for handling column projection to parquet is currently silently broken and likely only working because of the schema adapter logic

**Comment by alamb** [comment]
🤔  I suppose we'll have to fix datafusion then...

**Comment by alamb** [comment]
> the DataFusion logic for handling column projection to parquet is currently silently broken and likely only working because of the schema adapter logic

 I don't understand how things can be broken but also be working...

**Comment by tustvold** [comment]
I've not had time to look properly yet, but my suspicion is that the schema adapter logic knows what the expected output schema is and rearranges the columns - masking the fact what was returned by the parquet reader did not respect the projection order.

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/2543 to track

**Pull request closed without merging**
