### PR TITLE
Replace RwLock<HashMap> and Mutex<HashMap> by using DashMap

### LINKED ISSUE #4077: Replace RwLock<HashMap> and Mutex<HashMap> by using DashMap
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In Ballista, we have replaced `RwLock<HashMap>` and `Mutex<HashMap>` by using DashMap in many places. And the performance improved a lot. Therefore, it's time for the datafusion to leverage DashMap, too.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #4077 .

# Rationale for this change

`DashMap` leverages shard-level lock to achieve good performance for high concurrency, like the ConcurrencyHashMap in Java.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by tustvold — COMMENTED** [review]
I'm surprised any of these data structures are contended, and so dashmap is unlikely to yield benefits here? It may even be slower.

Do you have any benchmark results you could share?

**Comment by alamb** [comment]
I agree I think it would be good to have some more evidence that using a new third-party library adds benefits other than that libraries marketing materials

**Comment by alamb** [comment]
Or maybe put another way, if a different locking implementation improved performance significantly in Ballista, I wonder if we should investigate ways to avoid locking all together (copy-on-write, for example) 🤔

**Comment by alamb** [comment]
Looks like maybe dashmap was added in https://github.com/apache/arrow-ballista/pull/319 but there aren't any performance measurements that I could see there

**Comment by metesynnada** [comment]
> I'm surprised any of these data structures are contended, and so dashmap is unlikely to yield benefits here? It may even be slower.
> 
> Do you have any benchmark results you could share?

Actually, it is better in most use cases. You can [check ](https://github.com/xacrimon/conc-map-bench). It is quite similar to Java's [ConcurrentHashMap](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html).

**Comment by tustvold** [comment]
Those benchmarks are all for high throughput workloads, in this case I would be extremely surprised to see these hashmaps showing up in profiles. In the absence of a compelling benchmark it is hard for me to approve this... It is a non-trivial additional dependency, not to mention one that I've run into API issues with in the past, for an unclear benefit

**Comment by yahoNanJing** [comment]
Thanks @alamb and @tustvold, I'll try to add some benchmark testing before this PR be accepted.

**Review by xudong963 — COMMENTED** [review]
I'm not sure if it'll improve performance, but the code looks cleaner!

**Comment by ozankabak** [comment]
My two cents: I think it is more about encapsulating certain low-level operations regarding the data structure within the data structure itself, vs. exposing them in higher-level code. I think this is probably what @xudong963 means by cleaner, and I agree.

I also agree with @tustvold that typical workloads will not result in contention, without which performance improvements will not manifest.

If this change would merge, the benefits would be:
1. Code with better separation of concern (although the benefit is not as much as the Ballista change)
2. Potential performance gain in the unrealistic-looking contention scenarios
3. Being more in-line with Ballista codebase
The main disadvantage that I can see:
1. Introducing a dependency to Datafusion (albeit it is fairly commonly-used one)

I don't think the argument either way is super strong, but it seems to me that pros somewhat outweigh the cons (unless I am missing something).

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Until the fix for https://github.com/apache/arrow-datafusion/issues/4100 is merged, clippy will be failing on this PR as well

**Comment by ozankabak** [comment]
@yahoNanJing, given that #4100 is merged, this can merge if you resolve the conflicts.

**Comment by yahoNanJing** [comment]
Thanks @ozankabak. Just rebased.

**Review by xudong963 — APPROVED** [review]
Thanks @yahoNanJing

**Comment by alamb** [comment]
Let's plan to merge this tomorrow if we don't hear any additional comments 👍

**Comment by alamb** [comment]
Thanks again everyone!

**Pull request merged**
