### PR TITLE
Minor: Fix compilation error

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #.

# Rationale for this change

Current CI reports the error as follow:

```
error[E0061]: this method takes 3 arguments but 2 arguments were supplied
   --> datafusion/optimizer/src/test/mod.rs:131:42
    |
131 |         Analyzer::with_rules(vec![rule]).execute_and_check(plan, &options)?;
    |                                          ^^^^^^^^^^^^^^^^^---------------- an argument is missing
    |
note: associated function defined here
   --> datafusion/optimizer/src/analyzer/mod.rs:83:12
    |
83  |     pub fn execute_and_check<F>(
    |            ^^^^^^^^^^^^^^^^^
84  |         &self,
85  |         plan: &LogicalPlan,
    |         ------------------
86  |         config: &ConfigOptions,
    |         ----------------------
87  |         mut observer: F,
    |         ---------------
help: provide the argument
    |
131 |         Analyzer::with_rules(vec![rule]).execute_and_check(plan, &options, /* observer */)?;
    |                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

https://github.com/apache/arrow-datafusion/actions/runs/4715203170/jobs/8362040848?pr=5980

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by viirya** [comment]
cc @alamb

**Review by scsmithr — APPROVED** [review]
Ran into this too.

**Review by yjshen — APPROVED** [review]

**Comment by viirya** [comment]
Thanks @yjshen

**Comment by viirya** [comment]
Thanks @scsmithr too

**Comment by alamb** [comment]
Thanks @viirya  -- sorry about that. Maybe it is time to enable github merge queue to avoid such problems 🤔

**Pull request merged**
