### PR TITLE
Lazy TempDir creation in DiskManager

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Related https://github.com/apache/arrow-datafusion/issues/1690

First part of https://github.com/apache/arrow-datafusion/issues/1690: only do IO / `TempDir` creation when tempfiles are actually needed in a plan

I plan a second PR to  avoid creating so many `DiskManager` instances in the first place

 # Rationale for this change
Creating temp files is expensive and now DataFusion is doing it frequently during processing (see https://github.com/apache/arrow-datafusion/issues/1690 for more backstory)

# What changes are included in this PR?

Changes;
If the user doesn't specify explicit temp directories, do not create a system assigned tempfile unless it is actually requested

# Are there any user-facing changes?
less tempfiles!

### CODE REVIEW

**Comment by alamb** [comment]
cc @yjshen

**Review by yjshen — APPROVED** [review]
LGTM

**Review by xudong963 — APPROVED** [review]
Make sense to me. @alamb 👍
I am curious about the next step you'll do  -- "I plan a second PR to avoid creating so many DiskManager instances in the first place"

If I read our code correctly. when executing a plan, we need to create `RuntimeEnv` where will create a `DiskManager` instance. So I can't understand if there will be **so many** `DisManager` instances?

**Comment by alamb** [comment]
> If I read our code correctly. when executing a plan, we need to create RuntimeEnv where will create a DiskManager instance. So I can't understand if there will be so many DisManager instances?


@xudong963  I think (non obviously) there are several more surprising places which create a DiskManager instance today -- for example https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_optimizer/pruning.rs#L132

**Comment by yjshen** [comment]
https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/datasource/listing/helpers.rs#L244
https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/optimizer/simplify_expressions.rs#L293

two more.

**Comment by alamb** [comment]
> two more.
> I think the main reasons are the optimizers/planners are detached from the execution context but need functionalities somehow.

💯  @yjshen  -- see https://github.com/apache/arrow-datafusion/pull/1700 :)

**Pull request merged**
