### PR TITLE
Fix sqllogictests link in contributor-guide/index.md

### PR DESCRIPTION
**Pull request by qrilka**
## Which issue does this PR close?

None

## Rationale for this change

The crate was moved so the link needs to be updated

## Are there any user-facing changes?

The new link shouldn't got to the "moved" document anymore.

### CODE REVIEW

**Review by viirya — COMMENTED** [review]
In `How to add a new aggregate function` section, there are two broken links too:

```
In [core/tests/sqllogictests/test_files](../../../datafusion/core/tests/sqllogictests/test_files), add new `sqllogictest` integration tests where the function is called through SQL against well known data and returns the expected result.
  - Documentation for `sqllogictest` [here](../../../datafusion/core/tests/sqllogictests/README.md)
```

Could you fix it together in this PR?

**Comment by qrilka** [comment]
Sure

**Comment by qrilka** [comment]
I have also found an outdated link in sqllogictest/README.md

**Comment by viirya** [comment]
Thank you @qrilka

**Pull request merged**
