### PR TITLE
Count distinct floats

### LINKED ISSUE #199: COUNT DISTINCT does not support for `Float64`
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-12312

If you try to run a `COUNT (DISTINCT ..)` query on a float column you get the following error:

thread 'tokio-runtime-worker' panicked at 'Unexpected DataType for list', datafusion/src/scalar.rs:342:22

Reproducer:
```
 echo "foo,1.23" > /tmp/foo.csv
 ./target/debug/datafusion-cli
```

And then
```
> CREATE EXTERNAL TABLE t (a varchar, b float) STORED AS CSV LOCATION '/tmp/foo.csv';
0 rows in set. Query took 0 seconds.
> select count(distinct a) from t;
+-------------------+
| COUNT(DISTINCT a) |
+-------------------+
| 1                 |
+-------------------+
1 rows in set. Query took 0 seconds.
> select count(distinct b) from t;
thread 'tokio-runtime-worker' panicked at 'Unexpected DataType for list', datafusion/src/scalar.rs:342:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ArrowError(ExternalError(Canceled))
```

### PR DESCRIPTION
**Pull request by pjmore**
# Which issue does this PR close?
Closes #199 .

# What changes are included in this PR?
Modified try_from_array method on ScalarValue and added tests to physical_plan/distinct_expressions.rs

The tests cover all of the floating point weirdness that I could think of, namely NaN, the infinities, and subnormal numbers, but if I missed any I'm happy to add tests for them.

# Are there any user-facing changes?
No

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]
Looks goed, thanks @pjmore !

**Review by returnString — APPROVED** [review]

**Review by alamb — APPROVED** [review]
I tried it out locally and it works great. Thank you @pjmore !

```
alamb@ip-10-0-0-124:~/Software/arrow-datafusion$  echo "foo,1.23" > /tmp/foo.csv
alamb@ip-10-0-0-124:~/Software/arrow-datafusion$ cargo run -p datafusion-cli
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/datafusion-cli`
> CREATE EXTERNAL TABLE t (a varchar, b float) STORED AS CSV LOCATION '/tmp/foo.csv';
0 rows in set. Query took 0 seconds.

> select count(distinct a) from t;
+-------------------+
| COUNT(DISTINCT a) |
+-------------------+
| 1                 |
+-------------------+
1 rows in set. Query took 0 seconds.
> select count(distinct b) from t;
+-------------------+
| COUNT(DISTINCT b) |
+-------------------+
| 1                 |
+-------------------+
1 rows in set. Query took 0 seconds.
```

**Comment by Dandandan** [comment]
Thanks again @pjmore !

**Comment by alamb** [comment]
🎉

**Pull request merged**
