### PR TITLE
Make previous unchecked division kernel available

### LINKED ISSUE #6967: Make unchecked division kernel available
### Is your feature request related to a problem or challenge?

With #6792, now divisions check dividing by zero.
This is an API change and we are (and some other users may be) looking for an old behavior.

### Describe the solution you'd like

we would like to propose to implement `DivideUnchecked` operation that behaves like the old `Division` operator (return null for dividing by zero)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
# Which issue does this PR close?

Closes #6967

# Rationale for this change

With #6792, now divisions check dividing by zero.
That is an API change and we are (and some other users may be) looking for an old behavior.

# What changes are included in this PR?

This PR implements `DivideUnchecked` operation that behaves like the previous Division operator (return null for dividing by zero)

# Are these changes tested?

Yes

# Are there any user-facing changes?

No, but users have a choice explicitly to use the previous division behavior.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Makes sense to me -- thank you for the contribution @kazuyukitanimura 

cc @liukun4515 and @tustvold

**Comment by tustvold** [comment]
This operator has actually been removed upstream...

**Comment by alamb** [comment]
> This operator has actually been removed upstream... Perhaps this could be implemented as a nullif zero prior to division? This would be consistent with postgres.

Confirming you mean something like  https://docs.rs/datafusion/latest/datafusion/logical_expr/fn.nullif.html so like

```rust
let expr = nullif(expr, lit(0.0f64))
``` ?

What do you think @kazuyukitanimura ?

**Comment by ozankabak** [comment]
Let's make this behavior (exception vs. NaN vs. null during division) configurable. There are many use cases where one wants the output of division to be nullable, or NaN for floats. PostgreSQL goes the exception route, but many others (e.g. Spark) proceed with execution. Applications involving numerics often prefer the latter and handle such situations downstream. The entire family of streaming use cases is also another example where exception behavior is problematic.

**Comment by tustvold** [comment]
I would be fine with making this configurable and use the nullif kernel as suggested.

That being said it does seem inconsistent to special case integer division by zero and not all the other sources of errors in DF, from casting to arithmetic overflow. I wonder if there is a higher level issue if not producing errors is important? FWIW in ANSI mode, which I think is what we should be aiming to replicate, Spark will return errors.

**Comment by kazuyukitanimura** [comment]
Thank you all for the reviews. I am currently testing the performance of the `nullif` approach.

**Comment by alamb** [comment]
Marking as a draft so I don't accidentally merge this PR

**Comment by kazuyukitanimura** [comment]
It seems no performance degradation for the `nullif` solution. Closing.
Thanks

**Pull request closed without merging**
