### PR TITLE
mv register_schema() to impl

### PR DESCRIPTION
**Pull request by wqc200**
# Which issue does this PR close?

Closes #.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thanks @wqc200 ! Can you please explain the reason for this proposed API change ?

It seems strange to me, for example, for wanting to extend the built in InformationSchema provider -- though I suspect you have a reason for wanting to do so. It would help to know what the reason was

**Comment by wqc200** [comment]
> 
> 
> Thanks @wqc200 ! Can you please explain the reason for this proposed API change ?
> 
> It seems strange to me, for example, for wanting to extend the built in InformationSchema provider -- though I suspect you have a reason for wanting to do so. It would help to know what the reason was

@alamb thanks

I'm going to call the DataFusion Context from an external program, and I'm going to dynamically add a schema to the catalog in the DataFusion Context, so I need to add an API to the DataFusion Context.
To sum up, I needed the ability to call DataFusion Context from the outside.

**Comment by alamb** [comment]
My concern about with adding a `register_schema` to the *trait* is that that will force all catalog providers to allow new schemas to be added, even for those where it might not make sense.

I think you can dynamically add a schema to the catalog if you install / use a `MemoryCatalogProvider` directly and retain a handle to it. The code would look something like:

```rust
        let catalog = MemoryCatalogProvider::new();
        let catalog = Arc::new(catalog);
        // register catalog with the context, but keep an `Arc` to it for later
        ctx.register_catalog("my_catalog", catalog.clone());
        // ... stuff ...
        // Now, at some time later, add my_schema to the previously registered schema
        catalog.register_schema("my_schema", Arc::new(schema));
```

The key is to maintain a reference to `catalog`. There might be other [examples](https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/execution/context.rs#L2741) in the tests too that could help

**Comment by wqc200** [comment]
@alamb 

`
pub struct Execution {
    datafusion_context: ExecutionContext,
}

impl Execution {
    pub fn new() -> Self {
        let mut datafusion_context = ExecutionContext::with_config(
            ExecutionConfig::new()
        );

        Self {
            datafusion_context,
        }
    }
}

impl Execution {
    /// Create a new execution context for in-memory queries
    pub fn try_init(&mut self) {
        for (catalog_name, schema_map) in catalog_map.iter() {
            let catalog = MemoryCatalogProvider::new();
            let catalog = Arc::new(catalog);
            self.datafusion_context.state.catalog_list.register_catalog(catalog_name.clone(), catalog);

            for (schema_name, _) in schema_map.iter() {
                if schema_name == meta_util::INFORMATION_SCHEMA_NAME {
                    continue;
                }

                /// will output an error, MemoryCatalogProvider has not copy impl
                catalog.register_schema(schema_name.as_str(), schema);
            }
        }
    }

    pub fn register_schema_too(&mut self, catalog_name: String) {
        /// What should I do here
        let schema = Arc::new(MemorySchemaProvider::new());
        let catalog_provider = self.datafusion_context.state.catalog_list.catalog(catalog_name.as_str()).unwrap();
        catalog_provider.register_schema(schema_name.as_str(), schema);
    }
}
`

**Comment by wqc200** [comment]
@alamb 


```
pub struct Execution {
    datafusion_context: ExecutionContext,
}

impl Execution {
    pub fn new() -> Self {
        let mut datafusion_context = ExecutionContext::with_config(
            ExecutionConfig::new()
        );

        Self {
            datafusion_context,
        }
    }
}

impl Execution {
    /// Create a new execution context for in-memory queries
    pub fn try_init(&mut self) {
        for (catalog_name, schema_map) in catalog_map.iter() {
            let catalog = MemoryCatalogProvider::new();
            let catalog = Arc::new(catalog);
            self.datafusion_context.state.catalog_list.register_catalog(catalog_name.clone(), catalog);

            for (schema_name, _) in schema_map.iter() {
                if schema_name == meta_util::INFORMATION_SCHEMA_NAME {
                    continue;
                }

                /// will output an error, MemoryCatalogProvider has not copy impl
                catalog.register_schema(schema_name.as_str(), schema);
            }
        }
    }

    pub fn register_schema_too(&mut self, catalog_name: String) {
        /// What should I do here
        let schema = Arc::new(MemorySchemaProvider::new());
        let catalog_provider = self.datafusion_context.state.catalog_list.catalog(catalog_name.as_str()).unwrap();
        catalog_provider.register_schema(schema_name.as_str(), schema);
    }
}
```

**Comment by alamb** [comment]
@wqc200  I think you need to keep the `Arc` to `catalog`. How about something like this:

```rust
 pub fn register_catalog_and_schema(&mut self) {
        for (catalog_name, schema_map) in catalog_map.iter() {
            let catalog = MemoryCatalogProvider::new();
            let catalog = Arc::new(catalog);

            // -->  make sure you keep a copy of the `catalog`, so pass in a `clone()` (of the ARC)
            self.datafusion_context.state.catalog_list.register_catalog(catalog_name.clone(), catalog.clone());

            for (schema_name, _) in schema_map.iter() {
                /// This should now be ok
                catalog.register_schema(schema_name.as_str(), schema);
            }
        }
    }
```

**Comment by wqc200** [comment]
@alamb  I want to register a schema in the following function. What should I do?

```
    pub fn register_schema_another(&mut self, catalog_name: String) {
        /// **What should I do here**
        let schema = Arc::new(MemorySchemaProvider::new());
        let catalog_provider = self.datafusion_context.state.catalog_list.catalog(catalog_name.as_str()).unwrap();
        catalog_provider.register_schema(schema_name.as_str(), schema);
    }
```

**Comment by alamb** [comment]
@wqc200  how about something like the following (downcast the reference via `as_any`):

```rust
   pub fn register_schema_another(&mut self, catalog_name: String) {
        let schema = Arc::new(MemorySchemaProvider::new());
        let catalog_provider = self.datafusion_context.state.catalog_list.catalog(catalog_name.as_str()).unwrap();
        // ** try to cast catalog provider to MemoryCatalogProvider
        let catalog_provider = catalog_provider.as_any()
                .downcast_ref::<MemoryCatalogProvider>()
                .expect("Catalog provider was a MemoryCatalogProvider");
        catalog_provider.register_schema(schema_name.as_str(), schema);
    }
```

**Comment by wqc200** [comment]
@alamb 

Yes, that can be done.
However, this is a relatively complicated way to write, adding to the cost of learning and presenting difficulties for a Rust novice.

**Comment by alamb** [comment]
> However, this is a relatively complicated way to write, adding to the cost of learning and presenting difficulties for a Rust novice.

Yes I agree -- perhaps we can add some examples / tests to help out new people

> I think software design and development should be simple and easy to use.

Again, I agree -- there are parts of Rust that are definitely not 'obvious' in the way I have found languages like Python to be.

**Comment by alamb** [comment]
@Dandandan  or @returnString  do you have any thoughts on this API change -- I think getting some other perspectives might help

**Comment by returnString** [comment]
Hrm, I think if we're moving this to the interface, we need to codify some notion of "unsupported operation". That's actually why I left it out initially - registering a schema inside e.g. the information_schema catalog doesn't really make sense, because it's a read-only projection of DB internals, and I didn't want to commit to more public API than was necessary.

In my DataFusion-powered projects, I typically treat ExecutionContext instances as immutable which simplifies a lot of the setup. Essentially this entails creating catalogues using concrete types like `MemoryCatalogProvider` and then just attaching those to a new context, so I can work with the type-specific impls, rather than just trait methods. I'm not sure how widely adopted this is as a methodology, but I've found it works well!

For example, if I were building a traditional database, here's how I'd execute queries:
- build the list of catalogs (and internally, schemas/tables) the user has permissions to access (this relies on out-of-band data)
- create an execution context populated with said catalog list
- run the query using the context
- discard the context

Obviously this relies on the context setup being quite cheap, but I don't see any moves toward making that a particularly intensive process 😄

**Comment by returnString** [comment]
Had to remind myself how all the catalog code works, but we _do_ support registering tables into a schema via the trait. However, the trait method has a default impl which fails:


```rust
fn register_table(
	&self,
	name: String,
	table: Arc<dyn TableProvider>,
) -> Result<Option<Arc<dyn TableProvider>>> {
	Err(DataFusionError::Execution(
		"schema provider does not support registering tables".to_owned(),
	))
}
```

So if we wanted to do this for registering schemas into catalogs, we should probably use the same style of fallible operation.

**Comment by alamb** [comment]
> For example, if I were building a traditional database, here's how I'd execute queries:

In IOx we took a very similar approach to what you describe: 🤣  https://github.com/influxdata/influxdb_iox/blob/main/server/src/db/access.rs#L201

**Pull request closed without merging**
