### PR TITLE
Prepare 37.0.0 Release

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Part of https://github.com/apache/arrow-datafusion/issues/9682

## Rationale for this change

Scheduled release

## What changes are included in this PR?

- Update version
- Update changelog ([rendered](https://github.com/andygrove/arrow-datafusion/blob/prep-37/dev/changelog/37.0.0.md))

### CODE REVIEW

**Comment by comphead** [comment]
@andygrove please let me know if it would be possible to include https://github.com/apache/arrow-datafusion/pull/9686 to the 37 release?

**Comment by Dandandan** [comment]
@andygrove @alamb took updated this branch for release

**Comment by alamb** [comment]
I think we need to update the CHANGELOG too, but otherwise looks good to me. Thank you @Dandandan

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
@andygrove  are we ready for the 37.0.0?

**Comment by comphead** [comment]
Thanks folks, any plan to cut the release?

**Comment by alamb** [comment]
@andygrove normally does it -- I think we are ready. If @andygrove  doesn't have time I can try and do it later this weekend

**Comment by andygrove** [comment]
Sorry for the delay .. I was away the past few days. I will update this PR now.

**Pull request merged**
