### PR TITLE
Minor: consolidate parquet `custom_reader` integration test into parquet_exec

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

re #3463 

# Rationale for this change

The easier it is to find existing parquet tests the easier it is to evaluate our coverage

# What changes are included in this PR?

I suggest reviewing this PR commit by commit. The 

1. The first commit moves the file
2. the second cleans up the test code by removing a `#clippy(allow)` and an unnecessary level of indent

# Are these changes tested?

They are all tests 

They are run like:
```shell
cargo test  --test parquet_exec
```
And you can see the output like:
```
...
test parquet::custom_reader::route_data_access_ops_to_parquet_file_reader_factory ... ok
```
# Are there any user-facing changes?

No tests only

### CODE REVIEW

**Comment by alamb** [comment]
cc @crepererum

**Comment by alamb** [comment]
@Ted-Jiang  or @crepererum  I wonder if you would have time to review this PR?

**Review by Ted-Jiang — APPROVED** [review]
LGTM, nice rearrangement.❤️

**Review by crepererum — APPROVED** [review]
thank you

**Pull request merged**
