### PR TITLE
if none columns in window expr are needed, remove the window exprs

### LINKED ISSUE #2542: Unused Window functions experssion is wrongly removed from LogicalPlan during optimalization
**Describe the bug**
Unused window function is wrongly removed from Logical Plan during optimization. It leaves WindowAgg empty, which causes `Impossibly got empty window expression` error.

**To Reproduce**

```sql
RUST_LOG=debug datafusion-cli

WITH _sample_data AS (
  SELECT 1 as a, 'aa' AS b
  UNION ALL
  SELECT 3 as a, 'aa' AS b
  UNION ALL
  SELECT 5 as a, 'bb' AS b
  UNION ALL
  SELECT 7 as a, 'bb' AS b
  
), _data2 AS (
  SELECT
    row_number() OVER (PARTITION BY s.b ORDER BY s.a) AS seq,
    s.a,
    s.b
  FROM _sample_data s
)
SELECT d.b, MAX(d.a) AS max_a
FROM _data2 d
GROUP BY d.b
ORDER BY d.b;

-- Result
-- Error: Impossibly got empty window expression
```

**Expected behavior**

With above SQL i should got:
```sql
-- Result
| b  | max_a |
+----+-------+
| aa | 3     | 
| bb | 7     | 
+----+-------+

```

**Additional context**

Input logical plan:
```
    Sort: #d.b ASC NULLS LAST
      Projection: #d.b, #MAX(d.a) AS max_a
        Aggregate: groupBy=[[#d.b]], aggr=[[MAX(#d.a)]]
          Projection: #_data2.seq, #_data2.a, #_data2.b, alias=d
            Projection: #ROW_NUMBER() PARTITION BY [#s.b] ORDER BY [#s.a ASC NULLS LAST] AS seq, #s.a, #s.b, alias=_data2
              WindowAggr: windowExpr=[[ROW_NUMBER() PARTITION BY [#s.b] ORDER BY [#s.a ASC NULLS LAST]]]
                Projection: #_sample_data.a, #_sample_data.b, alias=s
                  Union
                    Projection: Int64(1) AS a, Utf8("aa") AS b
                      EmptyRelation
                    Projection: Int64(3) AS a, Utf8("aa") AS b
                      EmptyRelation
                    Projection: Int64(5) AS a, Utf8("bb") AS b
                      EmptyRelation
                    Projection: Int64(7) AS a, Utf8("bb") AS b
                      EmptyRelation
```

Optimized logical plan:
```
    Sort: #d.b ASC NULLS LAST
      Projection: #d.b, #MAX(d.a) AS max_a
        Aggregate: groupBy=[[#d.b]], aggr=[[MAX(#d.a)]]
          Projection: #_data2.a, #_data2.b, alias=d
            Projection: #s.a, #s.b, alias=_data2
              WindowAggr: windowExpr=[[]]  <-------- Here is empty expression
                Projection: #_sample_data.a, #_sample_data.b, alias=s
                  Union
                    Projection: Int64(1) AS a, Utf8("aa") AS b
                      EmptyRelation
                    Projection: Int64(3) AS a, Utf8("aa") AS b
                      EmptyRelation
                    Projection: Int64(5) AS a, Utf8("bb") AS b
                      EmptyRelation
                    Projection: Int64(7) AS a, Utf8("bb") AS b
                      EmptyRelation
```

We can see *windowExpr* is empty after optimization. I have tested this case on master ('[a825891](https://github.com/apache/arrow-datafusion/commit/a82589100d7b07cb629476a2df7eac002f48b8a0)').

I don't use `seq` column in last CTE and this causes error. WIth below SQL it's work
```sql
WITH _sample_data AS (
  SELECT 1 as a, 'aa' AS b
  UNION ALL
  SELECT 3 as a, 'aa' AS b
  UNION ALL
  SELECT 5 as a, 'bb' AS b
  UNION ALL
  SELECT 7 as a, 'bb' AS b
  
), _data2 AS (
  SELECT
    row_number() OVER (PARTITION BY s.b ORDER BY s.a) AS seq,
    s.a,
    s.b
  FROM _sample_data s
)
SELECT d.b, MAX(d.a) AS max_a, max(d.seq)
FROM _data2 d
GROUP BY d.b
ORDER BY d.b;

-- Resut:
| b  | max_a | MAX(d.seq) |
+----+-------+------------+
| aa | 3     | 2          |
| bb | 7     | 2          |
+----+-------+------------+
```

### PR DESCRIPTION
**Pull request by AssHero**
# Which issue does this PR close?

Closes #2542 

 # Rationale for this change
if the columns in window exprs are not referenced by operator, we can remove the window exprs.

# What changes are included in this PR?
remove the window exprs in projection_push_down.rs

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you @AssHero  -- can you please add a test case to this PR showing that it fixes the issue reported on https://github.com/apache/arrow-datafusion/issues/2542?

Perhaps you can add the reproducer from @mateuszkj  to https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/tests/sql/window.rs?

**Comment by AssHero** [comment]
> Thank you @AssHero -- can you please add a test case to this PR showing that it fixes the issue reported on #2542?
> 
> Perhaps you can add the reproducer from @mateuszkj to https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/tests/sql/window.rs?

yes, i can add a test case.

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @AssHero

**Comment by AssHero** [comment]
> Looks good to me -- thank you @AssHero

My pleasure

**Pull request merged**
