### PR TITLE
Add unit test for constant folding on values

### LINKED ISSUE #1170: apply constant folding to LogicalPlan::Values
I suspect it is not likely to matter, but constant folding could be applied to the `Expr`s in `values`. As written this code will not apply constant folding to those expressions

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/1165#discussion_r734958657_

### PR DESCRIPTION
**Pull request by viirya**
# Which issue does this PR close?

Closes #1170.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by viirya** [comment]
Hmm? The test passed locally.

**Comment by viirya** [comment]
cc @Jimexist @alamb

**Review by alamb — APPROVED** [review]
Looks great -- thanks @viirya

**Comment by viirya** [comment]
Thank you @alamb

**Pull request merged**
