### PR TITLE
Disable GitHub actions for draft PRs

### LINKED ISSUE #2086: Proposal: Disable Github CI for draft PRs with label
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
It's from #2084

> I found that draft PR also trigger CI

As title.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Closes #2086.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by jackwener** [comment]
It's from [CI of node](https://github.com/nodejs/node/blob/master/.github/workflows/build-tarball.yml)

**Comment by jackwener** [comment]
We can see the result of those change in this PR.

**Comment by yjshen** [comment]
I suppose draft is a way to tag PRs that are not ready for review? Are we experiencing insufficient resources or similar problems currently?

**Comment by jackwener** [comment]
> I suppose draft is a way to tag PRs that are not ready for review? Are we experiencing insufficient resources or similar problems currently?

Yes, I'm write a draft PR #2084. It's just want to ask for help, I don't want to trigger CI. 
So is #2054.

**Comment by matthewmturner** [comment]
In my case I find value in seeing CI run even when in draft state.  I would think it's ok to keep as long as it isn't draining some limited resource (I'm unsure how that works with Apache projects).

**Comment by jackwener** [comment]
> In my case I find value in seeing CI run even when in draft state. I would think it's ok to keep as long as it isn't draining some limited resource (I'm unsure how that works with Apache projects).

This can save CI resource, I think it's valuable. Because run CI for not ready PR  is not meaningful.

**Comment by jychen7** [comment]
> In my case I find value in seeing CI run even when in draft state

I also agree on that. Because running full test case locally is time consuming. In my case, I always run related test cases locally for my change and if it looks good, draft a PR to trigger a full run. If all checks have passed in Draft, then convert to "Ready for review"

**Pull request closed without merging**
