### PR TITLE
WIP: Add output_partitions_size for CoalescePartitionsExec

### PR DESCRIPTION
**Pull request by xudong963**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/112

First of all, I add output partitions config for CoalescePartitionsExec.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Dandandan** [comment]
In Spark, repartition is using `coalesce` by setting parameter `shuffle=true`.
I think it might be cleaner to keep the `Repartition` and `CoalescePartitions separated, otherwise you get two implementations in the same code without too much sharing?

For implementing `CoalescePartitionsExec` we just have to have a scheme that combines partitions within `execute` (e.g. when reducing the number of partitions from 8 to 4 we can return partitions 0,1 for `execute(0)` 2,3 for `execute(1)` etc.
For Ballista, we have to now (explicitly or implicitly) what partitions are living on what node to avoid shuffles.

**Comment by alamb** [comment]
I see -- The distinction between repartition and coalesce (when there can be more than one partition) in context of a distributed system makes sense. 

On a single machine, the difference seems much less important. 

Maybe it is worth some comments in these operators to note they are also designed to support distributed operations

**Comment by alamb** [comment]
Is this PR ready to merge? Or do you plan more work on it @xudong963 ?

**Comment by xudong963** [comment]
> Is this PR ready to merge? Or do you plan more work on it @xudong963 ?

I plan to do more on it in the coming weekend😄

**Comment by alamb** [comment]
I am trying to clean up the list of PRs to review in DataFusion so marking old ones as stale. Please let us know if you plan to work on this soon. Otherwise we will close it down and reopen it when the time is right.

**Comment by xudong963** [comment]
> I am trying to clean up the list of PRs to review in DataFusion so marking old ones as stale. Please let us know if you plan to work on this soon. Otherwise we will close it down and reopen it when the time is right.

Yeah, we can reopen it when the time is right

**Pull request closed without merging**
