### PR TITLE
Append generated column to the schema instead of prepending for WindowAggExec

### PR DESCRIPTION
**Pull request by mustafasrepo**
# Which issue does this PR close?

This is mostly a simplification PR. This PR un-does  the changes in the #4455

# Rationale for this change

Previously `WindowAggExec` was prepending its result to the schema. This required offset addition to columns of the original schema (in the PR  #4455). By appending, instead of prepending, we can remove changes in the PR #4455. This decreases code size and increases readability.

# What changes are included in this PR?

Since column index changes, physical plan of the some queries changed (very minor change hust index). Hence some tests needed to be updated also.

# Are these changes tested?

Existing tests checks this functionality, specifically [this test](https://github.com/apache/arrow-datafusion/blob/fe477e48832adb59e8992d92f9a292128dfb0a97/datafusion/core/tests/sql/window.rs#L1614) checks the desired behavior.

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
The code changes look good to me and I carefully reviewed the plan changes. Nice cleanup 👍 

cc @mingmwang

**Comment by alamb** [comment]
Screenshot 2022-12-28 at 3 03 55 PM

For some reason github thinks there are conflicts with this PR -- can you please resolve them so I can merge this PR in?

**Comment by ozankabak** [comment]
Should be good to good to go, feel free to merge after CI passes. Thank you!

**Comment by mingmwang** [comment]
LGTM

**Comment by alamb** [comment]
Thanks again@

**Pull request merged**
