### PR TITLE
replace once iter chain with array::IntoIter

### PR DESCRIPTION
**Pull request by houqp**
# Rationale for this change

Follow up for #605.

# What changes are included in this PR?

Replace manual once chain iterator with array::IntoIter to make code more readable based on feedback from https://github.com/apache/arrow-datafusion/pull/605#discussion_r664543206.

# Are there any user-facing changes?

no

### CODE REVIEW

**Review by jorgecarleitao — APPROVED** [review]
This is a branch new rust's API, right? that we can now concert arrays to iterators of values.

**Comment by houqp** [comment]
@jorgecarleitao yes, this is a relatively new API that landed in stable rust 1.51.

**Comment by Jimexist** [comment]
can you remove the intoiter wrapping since array has it implemented by default?

**Comment by houqp** [comment]
@Jimexist good call, I was using 1.52 on my dev machine, which was giving me errors.

**Pull request merged**
