### PR TITLE
Prepare `37.1.0` release (on `branch-37`)

### PR DESCRIPTION
**Pull request by alamb**
NOTE this PR targets branch-37. Once it is merged I will create a PR with a cherry-pick to main to bring the changes there

## Which issue does this PR close?

Part of https://github.com/apache/arrow-datafusion/issues/9904

## Rationale for this change

Patch release to fix regressions

## What changes are included in this PR?

- Update version to `37.1.0`
- Update changelog ([rendered](https://github.com/alamb/arrow-datafusion/blob/alamb/prepare_37.1.0/dev/changelog/37.1.0.md))

### CODE REVIEW

**Comment by alamb** [comment]
Note that the security-audit CI check is failing

https://github.com/apache/arrow-datafusion/actions/runs/8737098473/job/23973329903?pr=10128

```
error: 1 vulnerability found!
Crate:     gix-transport
Version:   0.39.0
Title:     gix-transport indirect code execution via malicious username
Date:      2024-04-[13](https://github.com/apache/arrow-datafusion/actions/runs/8737098473/job/23973329903?pr=10128#step:4:14)
ID:        RUSTSEC-2024-0335
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0335
Solution:  Upgrade to >=0.42.0
Dependency tree:
gix-transport 0.39.0
├── gix-protocol 0.42.0
│   └── gix 0.56.0
│       └── cargo 0.77.0
│           └── datafusion 37.1.0
│               ├── datafusion-wasmtest 37.1.0
│               ├── datafusion-substrait 37.1.0
│               ├── datafusion-sqllogictest 37.1.0
│               ├── datafusion-proto 37.1.0
│               │   └── datafusion-benchmarks 37.1.0
│               ├── datafusion-examples 37.1.0
│               ├── datafusion-docs-tests 37.1.0
│               └── datafusion-benchmarks 37.1.0
└── gix 0.56.0
```

This is due to a dev dependency on `cargo`  in datafusion for the `depcheck` binary

https://github.com/apache/arrow-datafusion/blob/d4eb72c30d45c0f3f359c64f41a6caed30abe750/datafusion/core/Cargo.toml#L133

We removed this dependency from main (38.0.0) but it is still on the `brach-37` https://github.com/apache/arrow-datafusion/pull/9865

Two options:
1. Merge the PR as is (with the CI check failure)
2. Remove the depcheck binary/ci/`cargo` dependnecy from the `branch-37` line to get CI passing cleanly

**Review by andygrove — APPROVED** [review]

**Comment by alamb** [comment]
I am going to merge without fixing the security CI failure on the 37 branch. If we want to make more releases from 37 we can fix it later

**Comment by alamb** [comment]
Hmm, I appear to have forgotten to merge this PR before sending out the vote thread 🤦

**Comment by alamb** [comment]
Created https://github.com/apache/arrow-datafusion/pull/10136 to port these changes to `main`

**Pull request merged**
