### PR TITLE
Fix regression by reverting Materialize dictionaries in group keys

### PR DESCRIPTION
**Pull request by alamb**
This closes https://github.com/apache/arrow-datafusion/issues/8738 by reverting https://github.com/apache/arrow-datafusion/pull/8291

~I am not sure if this is the right fix -- I need to write some more tests / understand the problem more fully, but I wanted to get the PR up as I had the code.~

To be clear, this change fixes a functional regression (a query that used to run no longer does), as descsribed in https://github.com/apache/arrow-datafusion/issues/8738

What I would like to do is to reopen https://github.com/apache/arrow-datafusion/issues/7647 and then we can work on reapply that change, ensuring the LogicalPlan and PhysicalPlan schemas match as well as maybe being more dilligent about performance testing

### CODE REVIEW

**Comment by alamb** [comment]
I believe we should proceed with this change, for the reasons explained in https://github.com/apache/arrow-datafusion/issues/7647#issuecomment-1879161073

**Comment by tustvold** [comment]
Do we have any empirical numbers to support this, recomputing dictionaries is extremely expensive and I would have thought it would outweigh any other overheads?

**Comment by alamb** [comment]
> Do we have any empirical numbers to support this, recomputing dictionaries is extremely expensive and I would have thought it would outweigh any other overheads?


To be clear, the core rationale to revert this change is fix the  functional regression (a query that used to run no longer does), as described in #8738

Once we have figure out how to avoid that functional regression with this change, we can also have a more reasonable discussion on performance. I will file a ticket to make some performance benchmarks

**Review by tustvold — APPROVED** [review]
I'm not a fan of this approach, but don't feel strongly

**Comment by alamb** [comment]
As I mentioned before, regressions in functionality I think take priority over (theorized) performance improvements which is what https://github.com/apache/arrow-datafusion/pull/8291 is

In retrospect, I should have insisted on some benchmarks showing improvements before I approved (and merged) https://github.com/apache/arrow-datafusion/pull/8291

To partly make up for this oversight, I plan to at least create said benchmarks so we can have a fact driven conversation rather than speculating

**Pull request merged**
