### PR TITLE
Update cli.md

### LINKED ISSUE #4239: Cannot query s3 data from datafusion-cli
**Describe the bug**

When following steps from user guide for cli:

https://github.com/apache/arrow-datafusion/blob/fc669d5892954cbd2612a272314785758a7cb176/docs/source/user-guide/cli.md?plain=1#L154-L187

Cannot create a table as it states.

**To Reproduce**

```bash
jeffrey:~/Code/arrow-datafusion/datafusion-cli$ export AWS_ACCESS_KEY_ID=****************
jeffrey:~/Code/arrow-datafusion/datafusion-cli$ export AWS_SECRET_ACCESS_KEY=****************
jeffrey:~/Code/arrow-datafusion/datafusion-cli$ export AWS_REGION=ap-southeast-2
jeffrey:~/Code/arrow-datafusion/datafusion-cli$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `/media/jeffrey/1tb_860evo_ssd/.cargo_target_cache/debug/datafusion-cli`
DataFusion CLI v14.0.0
❯ create external table test stored as parquet location 's3://tremendous-orange-fork/customer/part-0.parquet';
Execution("Generic S3 error: Missing region")
❯
```

**Expected behavior**

Be able to create a table from s3 and query it, per instructions in the user doc.

**Additional context**

User doc also states that `AWS_REGION` must be set as per:

https://github.com/apache/arrow-datafusion/blob/fc669d5892954cbd2612a272314785758a7cb176/docs/source/user-guide/cli.md?plain=1#L162-L164

However it seems this issue https://github.com/apache/arrow-rs/issues/2795 has been resolved and the fix merged a while back, and attempting the above steps without an `AWS_REGION` env var set still results in same error. Unsure whether user doc is wrong or there is another bug relating to `AWS_REGION`?

```bash
jeffrey:~/Code/arrow-datafusion/datafusion-cli$ export AWS_ACCESS_KEY_ID=****************
jeffrey:~/Code/arrow-datafusion/datafusion-cli$ export AWS_SECRET_ACCESS_KEY=****************
jeffrey:~/Code/arrow-datafusion/datafusion-cli$ export AWS_REGION=
jeffrey:~/Code/arrow-datafusion/datafusion-cli$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `/media/jeffrey/1tb_860evo_ssd/.cargo_target_cache/debug/datafusion-cli`
DataFusion CLI v14.0.0
❯ create external table test stored as parquet location 's3://tremendous-orange-fork/customer/part-0.parquet';
Execution("Generic S3 error: Missing region")
❯
```

### PR DESCRIPTION
**Pull request by psvri**
# Which issue does this PR close?

Closes #4239.

# Rationale for this change
Updated  S3 data source details in cli-usage docs.

# What changes are included in this PR?
Updated the cli usage for S3 data source.

# Are these changes tested?
NA

# Are there any user-facing changes?
No

### CODE REVIEW

**Comment by psvri** [comment]
Any reason why `*` used for creating items in markdown is reported as an error in prettier ?

**Comment by alamb** [comment]
> 
Any reason why * used for creating items in markdown is reported as an error in prettier ?



I don't know -- I simply run the command and check in the result

```shell
  npx prettier@2.7.1 --write \
    '{datafusion,datafusion-cli,datafusion-examples,dev,docs}/**/*.md' \
    '!datafusion/CHANGELOG.md' \
    README.md \
    CONTRIBUTING.md
```

**Review by alamb — APPROVED** [review]
Thanks @psvri  -- we just need to sort out the CI error as you point out and I think this one will be good to go

**Comment by psvri** [comment]
Thanks for sharing the commands.

Fixed the CI error in the recent commit.

**Review by xudong963 — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @psvri !

**Pull request merged**
