### PR TITLE
Extract CrossJoin, Repartition, Union in LogicalPlan

### LINKED ISSUE #1304: Extract `CrossJoin`, `Repartition`, `Union` in LogicalPlan as independent struct
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
There are some discussions in #1228

**Describe the solution you'd like**
like #1290

**Describe alternatives you've considered**
The task is mechanical, however, it is ideal for newcomers to familiarize themselves with datafusion's build, test, and PR processes.

**Additional context**
If you want to do it, please ping me and assign the task to you, avoiding collisions with other people.

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

Closes #1304 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Looks good to me, though the PR has some conflicts that need to be resolved before we can merge it.

Thank you @liukun4515  and @xudong963  for pushing this forward

**Comment by liukun4515** [comment]
> Looks good to me, though the PR has some conflicts that need to be resolved before we can merge it.
> 
> Thank you @liukun4515 and @xudong963 for pushing this forward

After this #1311 pr merged, i will address the conflicts.
@alamb

**Review by Jimexist — APPROVED** [review]
LGTM, thanks!

**Comment by alamb** [comment]
🎉

**Pull request merged**
