### PR TITLE
Fix #8507: Non-null sub-field on nullable struct-field has wrong nullity

### LINKED ISSUE #8507: non-null sub-field on nullable struct-field has wrong nullity.
### Describe the bug

If you have table schema like 
```
DFSchema {
    fields: [
        DFField {
            qualifier: Some(
                Bare {
                    table: "nexmark",
                },
            ),
            field: Field {
                name: "bid",
                data_type: Struct(
                    [
                        Field {
                            name: "auction",
                            data_type: Int64,
                            nullable: false,
                        },
                nullable: true,
          }
```
And run a query like `SELECT bid.auction FROM nexmark` you'll get an error when bid is null. Error looks like
```
ArrowError(InvalidArgumentError("Column 'nexmark.bid[datetime]' is declared as non-nullable but contains null values")) 
```
The problem is that the nullable() method only looks at the sub-fields nullability, ignoring that the parent field may be null.
https://github.com/apache/arrow-datafusion/blob/main/datafusion/expr/src/expr_schema.rs#L280.

### To Reproduce

_No response_

### Expected behavior

The expression should be nullable, as its parent may not be present.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marvinlanhenke**
## Which issue does this PR close?

Closes #8507.

## Rationale for this change

If parent struct is nullable; sub-fields should also be.

## What changes are included in this PR?

As suggested in #8507: 
I added a test to reproduce the bug with the schema described.
Then I introduced a simple guard clause to check if the parent col is nullable; if it is return early.

## Are these changes tested?
Change is tested by `test_nested_schema_nullability`.

## Are there any user-facing changes?
No.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you for this contribution @marvinlanhenke  -- it makes sense to me

**Comment by alamb** [comment]
@marvinlanhenke  it looks like there is a clippy error preventing a clean CI run: https://github.com/apache/arrow-datafusion/actions/runs/7299570999/job/19905117841?pr=8623

Is there any chance you can fix that so we can merge this PR?

**Comment by marvinlanhenke** [comment]
@alamb thanks for the approval - i just committed the `clippy-fix`

**Comment by alamb** [comment]
THanks again @marvinlanhenke

**Pull request merged**
