### PR TITLE
[Refactor] PipelineFixer physical optimizer rule removal

### PR DESCRIPTION
**Pull request by metesynnada**
# Which issue does this PR close?

Closes #.

# Rationale for this change

The current `JoinSelection` rule checks the `HashJoinExec` executors to ensure that the build side contains more rows. At the same time, the `PipelineFixer` checks for unboundedness in the children of the `HashJoinExec`, so it is also a join selection rule in essence. This PR unifies these elements to end up with a single join selection rule, providing a better strategy for memory usage limitation.

# What changes are included in this PR?

There is no new function or methodology. Just a code replacement.

# Are these changes tested?

With existing tests.

# Are there any user-facing changes?

No.

### CODE REVIEW

**Review by mustafasrepo — APPROVED** [review]
This PR is LGTM!.

**Comment by ozankabak** [comment]
Previously, join-manipulating planning code was in multiple files and were applied at different stages of physical optimization. This PR does away with that complexity and pays back a good deal of technical debt IMO 💯

**Review by Dandandan — APPROVED** [review]

**Comment by alamb** [comment]
The idea in this PR sounds great to me.  I don't plan to review the code, so from my perspective this PR is good to merge

**Comment by alamb** [comment]
Thank you very much @metesynnada  for making this improvement. I can't wait for DataFusion's joins to be so much better ❤️

**Pull request merged**
