### PR TITLE
Add optimizer rule to replace inlist with `or` chain for small expression list

### LINKED ISSUE #799: Add optimizer rule to replace inlist with `or` chain for small list
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
For TCP-H query 12, according to the profier about 16% (including IO) of the time is spent in the code in `InListExpr`.

The full query is:

```
select
    l_shipmode,
    sum(case
            when o_orderpriority = '1-URGENT'
                or o_orderpriority = '2-HIGH'
                then 1
            else 0
        end) as high_line_count,
    sum(case
            when o_orderpriority <> '1-URGENT'
                and o_orderpriority <> '2-HIGH'
                then 1
            else 0
        end) as low_line_count
from
    lineitem
        join
    orders
    on
            l_orderkey = o_orderkey
where
        l_shipmode in ('MAIL', 'SHIP')
  and l_commitdate < l_receiptdate
  and l_shipdate < l_commitdate
  and l_receiptdate >= date '1994-01-01'
  and l_receiptdate < date '1995-01-01'
group by
    l_shipmode
order by
    l_shipmode;
```

We can replace:

` x in (a, b)` 
with the equivalent of

`(x==a or x==b)`

for "small enough" lists for some performance improvement.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #799

 # Rationale for this change

Speeding up inlist with one or two expressions by converting to a normal boolean expression.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Dandandan** [comment]
Seems it is not faster (yet). Will do some more research

**Comment by jhorstmann** [comment]
Cool, this is interesting to me since in our query engine we started from the opposite approach of initially rewriting all IN expressions into comparison and OR and are now introducing specialized kernel for IN. Would be very interested in finding out where the threshold for this optimization is. The benefit is probably bigger for dictionary encoded data and numbers since the string comparison itself will involve some branches.

**Comment by alamb** [comment]
Possibly also related https://github.com/apache/arrow-datafusion/pull/813 as a different performance approach

**Comment by Dandandan** [comment]
I might tune this later at a later moment to be for empty/single items instead for which it really *should* be an improvement, and do some more profiling.
It could also be worse right now because of a slower kernel (how fast is the `or` ATM?)

**Comment by alamb** [comment]
Closing a seemingly stale PR -- please reopen if that was a mistake.

**Pull request closed without merging**
