### PR TITLE
Use multi-stage build dockerfile in datafusion-cli and reduce image size from 2.16GB to 89.9MB

### LINKED ISSUE #267: Use multi-stage build dockerfile in datafusion-cli
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

Currently the freshly built image size for `datafusion-cli` is over 2GiB. Improvement can be made by using a multi-stage build.

**Describe the solution you'd like**

Minimize image size of datafusion-cli by leveraging multistage build.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

We generally require a GitHub issue to be filed for all bug fixes and enhancements and this helps us generate change logs for our releases. You can link an issue to this PR using the GitHub syntax. For example `Closes #123` indicates that this PR will close issue #123.

Closes #267.

Old image size `2.16GB`, new image size is `89.9MB`

 # Rationale for this change
 Why are you proposing this change? If this is already explained clearly in the issue then this section is not needed.
 Explaining clearly why changes are proposed helps reviewers understand your changes and offer better suggestions for fixes.  

We should optimize for the docker image size of `datafusion-cli`. Using a multi-stage build would contribute to a cleaner build with minimal intermediate build artifacts.

# What changes are included in this PR?

There is no need to duplicate the description in the issue here but it is sometimes worth providing a summary of the individual changes in this PR.

# Are there any user-facing changes?

If there are user-facing changes then we may require documentation to be updated before approving the PR.

If there are any breaking changes to public APIs, please add the `breaking change` label.

### CODE REVIEW

**Comment by Jimexist** [comment]
related #228

**Comment by returnString** [comment]
I'm not sure whether there are any expectations around CLI performance in Docker, but it's probably worth seeing whether @andygrove's 2020 article on Rust/Alpine perf issues still holds true: https://andygrove.io/2020/05/why-musl-extremely-slow

**Comment by Jimexist** [comment]
> I'm not sure whether there are any expectations around CLI performance in Docker, but it's probably worth seeing whether @andygrove's 2020 article on Rust/Alpine perf issues still holds true: https://andygrove.io/2020/05/why-musl-extremely-slow

i guess dropping alpine part of the change is safer.

**Review by andygrove — APPROVED** [review]
:100:

**Review by returnString — APPROVED** [review]
Looks great, excellent savings especially if we're looking at publishing this to Docker Hub soonish :)

**Comment by alamb** [comment]
```
 docker build . -f  ./datafusion-cli/Dockerfile -t datafusion-cli
```

And then tried to run the image: 
```
docker run -it datafusion-cli
```

I got an error: 
```
(arrow_dev) alamb@ip-10-0-0-124:~/Software/arrow-datafusion$ docker run -it datafusion-cli
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:56:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Perhaps we need to update the entry point to be `/usr/local/bin/datafusion-cli` ?

**Comment by Jimexist** [comment]
@alamb I guess you would need to volume map the /data dir. the error message wasn't specific enough

**Comment by alamb** [comment]
Indeed @Jimexist  you are correct:

```
docker run -v /tmp:/data  -it datafusion-cli
```

works just fine

**Review by alamb — APPROVED** [review]

**Comment by houqp** [comment]
minor suggestion not related to this change. i recommend using github container registry instead of dockerhub to host public docker images. dockerhub's rate limit makes it impossible to use the image in any serious production or ci/cd pipeline.

**Comment by jorgecarleitao** [comment]
I agree with @houqp 👍

**Review by jorgecarleitao — APPROVED** [review]
Looks great.

Note that this makes it more difficult to use caching in docker builds on CI. I think that we can do that on a follow-up PR

**Pull request merged**
