### PR TITLE
Support using var/var_pop/stddev/stddev_pop in window expressions with custom frames

### PR DESCRIPTION
**Pull request by jonmmease**
# Which issue does this PR close?

Follow on to https://github.com/apache/arrow-datafusion/pull/4846 for `var`, `var_pop`, `stddev`, and `stddev_pop`. 

The actual `retract_batch` function was already implemented, but it looks like the `create_sliding_accumulator` implementations weren't added previously so it wasn't possible to use these aggregate functions in window expressions that use custom frames.

# Are these changes tested?
The test added in effc4728912684f63b2e4ce837ae1b1816796480 will fail until https://github.com/apache/arrow-datafusion/pull/4847 is merged and this branch is updated.

I'll mark this is draft until then.

# Are there any user-facing changes?
`var`, `var_pop`, `stddev`, and `stddev_pop` will now work in window expressions that use custom frames rather than raising an error.

### CODE REVIEW

**Comment by jonmmease** [comment]
Ok, this is ready to go now. Thanks!

**Review by ozankabak — APPROVED** [review]
LGTM, thank you!

**Comment by jonmmease** [comment]
Can this be merged? Thanks!

**Comment by alamb** [comment]
Nice -- thank you @jonmmease  and @ozankabak

**Pull request merged**
