### PR TITLE
Minor: Add implementation examples to ExecutionPlan::execute

### PR DESCRIPTION
**Pull request by tustvold**
## Which issue does this PR close?

Closes #.

### CODE REVIEW

**Review by comphead — COMMENTED** [review]
Awesome @tustvold, I still think we may need an example of dealing with async stream with `await` in sync context, as people asks for it pretty often

**Comment by tustvold** [comment]
Both the last two examples are showing how to use async in a sync context? Execute is sync?

**Comment by comphead** [comment]
> Both the last two examples are showing how to use async in a sync context? Execute is sync, get_batch and get_batch_stream are async?

Correct, let me clarify. The sorter example in #8010 also addresses 2 very frequently asked things with a working example: 
- how to debug/output underlying stream data for a given plan/node
- how to modify a stream

**Comment by tustvold** [comment]
I added an additional doc comment pointing people to the stream adaptors. I worry that the example in #8010 is misleading as it seems to suggest the only way to handle streams is to use a construction along the lines of `while let Some(..) = stream.next().await` which is most often not the best way to handle streams.

**Review by comphead — APPROVED** [review]
sounds good, thanks @tustvold

**Review by alamb — APPROVED** [review]
Thanks @tustvold and @comphead  -- this is a great improvement. I am also inspired to improve the doc even more and will make another PR to help as I think this is one of the more non obvious parts of DataFusion

**Comment by alamb** [comment]
This PR inspired me to write another: https://github.com/apache/arrow-datafusion/pull/8019

**Pull request merged**
