### PR TITLE
Minor: Change from `&mut SessionContext` to `&SessionContext` in substrait

### PR DESCRIPTION
**Pull request by my-vegetable-has-exploded**
## Which issue does this PR close?

#7836

### CODE REVIEW

**Review by andygrove — APPROVED** [review]

**Comment by andygrove** [comment]
@nseekhao @waynexia @comphead fyi

**Review by comphead — APPROVED** [review]
lgtm

**Review by Weijun-H — APPROVED** [review]
LGTM! Thanks @my-vegetable-has-exploded

**Comment by alamb** [comment]
Thanks everyone.

**Comment by my-vegetable-has-exploded** [comment]
Thanks everyone.

**Pull request merged**
