### PR TITLE
feat: enable serde of arrow-schema

### PR DESCRIPTION
**Pull request by jychen7**
# Which issue does this PR close?

from https://github.com/roapi/roapi/blob/roapi-v0.9.0/columnq/Cargo.toml#L14-L16, newly reference at  https://github.com/roapi/roapi/blob/c911f682df86b62f7dd35c0c685e84a9788c9ccb/columnq/Cargo.toml#L14-L17

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
Enabling features of transitive dependencies is a well documented and standard approach, I'm not sure why we would plumb this through?

**Comment by jychen7** [comment]
> I'm not sure why we would plumb this through

@tustvold  I believe you mean Datafusion does not use `serde` feature at all and asking why to include it. I think this PR would make downstream easier to use Datafusion, but I agree `serde` seems unnecessary to Datafusion.

I am going to close this PR. @houqp what do you think?

**Comment by houqp** [comment]
@jychen7 the optional feature needs to be added to the features section at https://github.com/apache/arrow-datafusion/blob/64941fa99e13459a99d2ec3f15cdd997fee41988/datafusion/core/Cargo.toml#L36.

Adding it in the dependency directly will force all datafusion users to enable serde, which adds unnecessary overheads to users who don't need it.

@tustvold as @jychen7 mentioned, this is mostly a minor UX improvement to datafusion users so they don't need to find out which downstream crate to toggle a feature and manually keep the version in sync with what's pinned in datafusion. Same idea why we have the `simd` and `pyarrow` feature flag in datafusion.

**Comment by jychen7** [comment]
@houqp that makes more sense. I will close this one then
@tustvold what do you think if we add a new feature called 'serde'?

**Pull request closed without merging**
