### PR TITLE
minor: remove python docs, now they're in another project

### LINKED ISSUE #2866: [Question] interested in helping with documentation
Hi all,
I want to help with the documentation and I can pull issues from here to work on, but I have questions about how docs should be organized for the python project.

Datafusion-python is now in datafusion-contrib, outside of Apache. However, it's documentation is in the datafusion project repo. This leads to a weird dependency where docs will be created in the main datafusion repo, for versions of the python project managed by datafusion-contrib/datafusion-python. 

For example:
* there's a mismatch between datafusion's [python doc](https://github.com/apache/arrow-datafusion/blob/master/docs/source/python/index.rst) and the same documentation in the datafusion-python repo ([readme](https://github.com/datafusion-contrib/datafusion-python/blob/main/README.md))
* there are warnings when building the datafusion project docs that require changes to datafusion-python to fix. this is awkward.

It would be better if the docs for the datafusion-python project could be managed and published from that project, for consistency and ease of updating and possibly versioning of the docs in the future. Do you agree? Any ideas how to accomplish that? I'm willing to put in the work if there's agreement how to proceed.

### PR DESCRIPTION
**Pull request by kmitchener**
# Which issue does this PR close?

Closes #2866 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by kmitchener** [comment]
@andygrove PTAL

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @kmitchener. Once we have published the Python docs we should update here with a link to them.

**Comment by alamb** [comment]
Thanks @kmitchener  -- can you remind me where the docs are now?

**Comment by kmitchener** [comment]
hey @alamb, sure, they've been moved to the arrow-datafusion-python project, in this PR https://github.com/apache/arrow-datafusion-python/pull/23

**Pull request merged**
