### PR TITLE
build(deps): update sqlparser requirement from 0.30 to 0.32 w/ API update

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/pull/5451

# Rationale for this change
New version of sqlparser was released and we need a few changes to DataFusion to acknowledge we don't support newly added syntax

# What changes are included in this PR?

Changes from @dependabot in https://github.com/apache/arrow-datafusion/pull/5451 and updates to make ti compile

# Are these changes tested?

Existing tests cover it

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by alamb** [comment]
@ursabot benchmark help

**Comment by alamb** [comment]
🤔  looks like some real problem in sql-parser upgrade -- I will investigate

**Comment by alamb** [comment]
Specifically

```

#[test]
fn table_with_column_alias() {
    let sql = "SELECT a, b, c
                   FROM lineitem l (a, b, c)";
    let expected = "Projection: a, b, c\
        \n  Projection: l.l_item_id AS a, l.l_description AS b, l.price AS c\
        \n    SubqueryAlias: l\
        \n      TableScan: lineitem";

    quick_test(sql, expected);
}

```

Fails with:

```


---- table_with_column_alias stdout ----
thread 'table_with_column_alias' panicked at 'called `Result::unwrap()` on an `Err` value: SQL(ParserError("Expected identifier, found: ,"))', datafusion/sql/tests/integration_test.rs:2412:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1113:23
   4: integration_test::quick_test
             at ./tests/integration_test.rs:2412:16
   5: integration_test::table_with_column_alias
             at ./tests/integration_test.rs:499:5
   6: integration_test::table_with_column_alias::{{closure}}
             at ./tests/integration_test.rs:491:30
   7: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by alamb** [comment]
Upstream issue: https://github.com/sqlparser-rs/sqlparser-rs/issues/826

**Comment by alamb** [comment]
@andygrove  if you have time to review this upgrade PR I would like to get it in prior to the release on Friday

**Review by appletreeisyellow — APPROVED** [review]

**Review by tustvold — APPROVED** [review]

**Comment by alamb** [comment]
Thank you @appletreeisyellow  and @tustvold !

**Pull request merged**
