### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by vchag**
Change-Id: I64d2169a616efb889b3e37e85450405729eed499

# Which issue does this PR close?
This PR is related to correcting a typo and not related to functionality issues.  

Closes #.
 # Rationale for this change
I made this change to ensure users don't get confused. Comments help new users like me understand the code.

### CODE REVIEW

**Comment by xudong963** [comment]
I noticed https://github.com/apache/arrow-datafusion/blob/bc42eadd5b03cc4e1c541f4e37ab5f54fa3db714/datafusion-common/src/dfschema.rs#L287 has the same typo, could you please fix it together?

**Review by alamb — APPROVED** [review]
Thanks @vchag  -- please let me know if you want to fix @xudong963 's suggestion in this PR or if I should merge this one as is

**Comment by vchag** [comment]
> xudong963

Thanks for pointing it out. I'll fix it.

**Comment by vchag** [comment]
> Thanks @vchag -- please let me know if you want to fix @xudong963 's suggestion in this PR or if I should merge this one as is

your welcome @alamb.  I fixed the typo in the other file. You can merge both of these changes.

**Review by xudong963 — APPROVED** [review]

**Pull request merged**
