### PR TITLE
Port test in union.rs to sqllogic

### LINKED ISSUE #6215: Port tests in `union.rs` to sqllogictest
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/arrow-datafusion/issues/6195. We are trying to keep the DataFusion code base clean and easy to contribute to and modify. Part of doing so is having a single location for most test coverage so new tests can be added easily and people can follow the existing patterns easily 

### Describe the solution you'd like

Port the tests in https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/tests/sql/union.rs to `union.slt` in https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests/test_files

Notes: 
1. Instructions for running sqllogitest are here: https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests
3. If you don't know how to port any particular test, please leave it in the .rs or ask on the pull request

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by parkma99**
# Which issue does this PR close?

Closes #6215 

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by jiangzhx — APPROVED** [review]
LGTM

**Review by jiangzhx — COMMENTED** [review]
how about use  `explain`
```
explain 
SELECT c1, c9 FROM aggregate_test_100 
UNION ALL 
SELECT c1, c3 FROM aggregate_test_100 
ORDER BY c9 DESC LIMIT 5
```
 to move all testcase to sqllogictest

**Comment by alamb** [comment]
> how about use explain

I agree -- we should move all the tests if possible. Thank you @parkma99  and @jiangzhx

**Comment by parkma99** [comment]
Ok，thanks

**Comment by jiangzhx** [comment]
> Ok，thanks

look good to me.
Thank you for your contribution. 😁

**Review by alamb — APPROVED** [review]
Thank you @parkma99 and @jiangzhx for the review!

**Pull request merged**
