### PR TITLE
Upgrade to sqlparser 0.22

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

N/A

 # Rationale for this change

Pick up these changes from sqlparser:

- Support OVERLAY expressions
- Support WITH TIMEZONE and WITHOUT TIMEZONE when parsing TIMESTAMP expressions
- Add ability for dialects to override prefix, infix, and statement parsing

# What changes are included in this PR?

Update

# Are there any user-facing changes?

No

### CODE REVIEW

**Review by Jimexist — APPROVED** [review]

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
Thanks @andygrove

**Comment by avantgardnerio** [comment]
Commenting to link ticket https://github.com/apache/arrow-datafusion/issues/3255 , because I think now that we treat all `timestamp with timezone` as UTC, we should be explicit about that in datafusion before a user complains.

**Comment by waitingkuo** [comment]
`timestamp without timezone` will be the same as `timestamp`, output `Timestamp<Nano, None>` ( if we align with postgresql) 

do you mean that `timetamp with timezone` to produce `Timestamp<Nano, "UTC">` ?

**Comment by avantgardnerio** [comment]
I think we should keep `timestamp without timezone` evaluating to `Timestamp<Nano, None>`. However, I think we should modify DataFusion to ensure `None` always means `UTC` for now as described in #3255.

**Pull request merged**
