### PR TITLE
Minor: Add negative test for SORT BY

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

related to https://github.com/apache/arrow-datafusion/issues/5247

# Rationale for this change

Add a small test for https://github.com/apache/arrow-datafusion/pull/5249

# What changes are included in this PR?
More tests more better

# Are these changes tested?
Yes
# Are there any user-facing changes?

### CODE REVIEW

**Review by xudong963 — APPROVED** [review]
I find the file contains some tests that don't contain `order by`, is it expected?

**Comment by alamb** [comment]
> I find the file contains some tests that don't contain order by, is it expected?

At least one is expected (to demonstrate that the query works the same with and without ORDER BY)

https://github.com/apache/arrow-datafusion/blob/4be56108d55ba301d1677e1a5554308a536479dd/datafusion/core/tests/sqllogictests/test_files/order.slt#L233-L238

Are there others that you had in mind?

**Review by Jefffrey — APPROVED** [review]
thanks 👍

**Comment by xudong963** [comment]
> to demonstrate that the query works the same with and without ORDER BY

Got

**Pull request merged**
