### PR TITLE
Minor: Remove the unreached simplification rule for `0 / 0`

### LINKED ISSUE #3849: Inconsistent Error Schema in DataFusion
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
It is a discrepancy in error schema. It is discussed in #3824 that how should we handle errors and this is the follow-up issue. For example, `A / 0` returns `DivideByZero` however `0 / 0` returns `NULL`

**Describe the solution you'd like**
Determine a consistent behavior.

### LINKED ISSUE #4669: inconsistent behavior for divide zero: divide_opt and divide_scalar
From this changes, I find some inconsistent behavior for `divide` about `zero`.

```
❯ \d left
+---------------+--------------+------------+-------------+-----------+-------------+
| table_catalog | table_schema | table_name | column_name | data_type | is_nullable |
+---------------+--------------+------------+-------------+-----------+-------------+
| datafusion    | public       | left       | c           | Int32     | YES         |
+---------------+--------------+------------+-------------+-----------+-------------+
1 row in set. Query took 0.054 seconds.
❯ select c/0 from left;
ArrowError(DivideByZero)
❯ select 10/0;
+----------------------+
| Int64(10) / Int64(0) |
+----------------------+
|                      |
+----------------------+
```

The difference is from the arrow-rs kernel `divide_scalar` and  `divide_opt`.

In the `divide_scalar`, it will check the `zero` for the right, but in the `divide_opt`, the result will be replaced with `NULL` if the right value is zero.

cc @alamb

_Originally posted by @liukun4515 in https://github.com/apache/arrow-datafusion/issues/4648#issuecomment-1354183892_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #3849 
Closes #4669 

Now both `0 / 0` and `10 / 0` will result in the same `DivideByZero` error.
```shell
DataFusion CLI v30.0.0
❯ select 0/0;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Divide by zero error
❯ select 10/0;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Divide by zero error

```
## Rationale for this change
The const evaluator will first eliminate the expression `0 / 0` and raise a DivideByZero error.
https://github.com/apache/arrow-datafusion/blob/ea9144e6597593c09a4ef0b71a4da1cdfaca8249/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L129-L130
Then this rule will never have a match.
https://github.com/apache/arrow-datafusion/blob/ea9144e6597593c09a4ef0b71a4da1cdfaca8249/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L709-L715

Furthermore, the behavior of this rule is inconsistent with the results of the following test case.
https://github.com/apache/arrow-datafusion/blob/ea9144e6597593c09a4ef0b71a4da1cdfaca8249/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L1666-L1675

## What changes are included in this PR?
Remove an unreached simplification rule.

## Are these changes tested?
N/A

## Are there any user-facing changes?
No

### CODE REVIEW

**Comment by alamb** [comment]
I believe CI will pass after merging up from `main` to get the change in  https://github.com/apache/arrow-datafusion/pull/7416

**Comment by alamb** [comment]
I believe CI will pass after merging up from `main` to get the change in  https://github.com/apache/arrow-datafusion/pull/7416

**Comment by alamb** [comment]
I took the liberty of merging up from main to get a fix for CI failure

**Review by alamb — APPROVED** [review]
This change makes sense to me -- thank you @jonahgao

**Review by Weijun-H — APPROVED** [review]

**Review by Weijun-H — APPROVED** [review]
LGTM

**Comment by alamb** [comment]
Thanks @jonahgao  and @Weijun-H

**Pull request merged**
