### PR TITLE
refactor: split expression pf planner into one part.

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Part of #4392.

I'm try into add `Binder` in planner, split the planner is a good begin for it. So I do it previously.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you @jackwener  -- this looks great. 🙏  the planner is in desperate need of some cleaning up

Something else that would help I think is to move the tests from `datafusion/sql/src/planner.rs` into `datafusion/sql/test/planner.rs` or similar to help parallelize the test compilation

Sadly I have just created a bunch of conflicts in in https://github.com/apache/arrow-datafusion/pull/4779 (also related to shrinking the planner)

Also related (and conflicting): https://github.com/apache/arrow-datafusion/pull/4785 https://github.com/apache/arrow-datafusion/pull/4787

**Comment by alamb** [comment]
> Thanks @alamb remind

Thank YOU!

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/pull/4785 https://github.com/apache/arrow-datafusion/pull/4787 are now both merged

**Comment by jackwener** [comment]
> #4785 #4787 are now both merged

Resolve conflict, thanks @alamb

**Review by liukun4515 — APPROVED** [review]
LGTM,
i would merge this pr first, otherwise there will be conflicts.

**Comment by alamb** [comment]
Thank you for this!

**Pull request merged**
