### PR TITLE
feat: implement substrait join filter support

### LINKED ISSUE #6866: Substrait: Add support for joins with filter
### Is your feature request related to a problem or challenge?

Currently, `datafusion-substrait` will return an error if there is a join relation in the logical plan with filter field that's not `None`.

To replicate:
```Rust
#[tokio::test]
async fn roundtrip_non_equi_inner_join() -> Result<()> {
    roundtrip("SELECT data.a FROM data JOIN data2 ON data.a <> data2.a").await
}
// ---- tests::roundtrip_non_equi_inner_join stdout ----
// Error: NotImplemented("join filter")
```

### Describe the solution you'd like

Correctly handle the case where join filter is not empty.

### Describe alternatives you've considered

N/A

### Additional context

The filter will be `Some(_)` for non-equi joins.

### PR DESCRIPTION
**Pull request by nseekhao**
# Which issue does this PR close?

Closes #6866 .

# Rationale for this change

Explained in issue.

# What changes are included in this PR?

* Parse DF join filter into Substrait's `post_join_filter` in producer
* Parse `post_join_filter` into join filter in consumer
* Test cases:
  * non-empty join expression, non-empty filter
  * empty join expression, non-empty filter
  * query with `exists` clause

# Are these changes tested?

Yes.

Please note that if a test case includes subquery aliases, the results will not be correct due to issue #6867 .

# Are there any user-facing changes?
No

### CODE REVIEW

**Comment by nseekhao** [comment]
Does anyone know what's the difference between the `tests/roundtrip_logical_plan.rs` file and the `tests/cases/roundtrip_logical_plan.rs` file?

**Comment by andygrove** [comment]
@waynexia fyi

**Review by waynexia — APPROVED** [review]
Looking great, thanks 👍

**Comment by waynexia** [comment]
> Does anyone know what's the difference between the `tests/roundtrip_logical_plan.rs` file and the `tests/cases/roundtrip_logical_plan.rs` file?

I just realized we have two different case files 🤣 It looks like this is a mistake from https://github.com/apache/arrow-datafusion/pull/6604. I'll reorganize those test cases later when I split our consumer/producer implementation into functionality-grouped style. I believe there are many duplications...

**Comment by alamb** [comment]
> I just realized we have two different case files 🤣 It looks like this is a mistake from https://github.com/apache/arrow-datafusion/pull/6604. I'll reorganize those test cases later when I split our consumer/producer implementation into functionality-grouped style. I believe there are many duplications...

I took a quick look at it looks to me like the tests are entirely duplicated. Proposed removing them here: https://github.com/apache/arrow-datafusion/pull/6894

**Pull request merged**
