### PR TITLE
[SQLLogicTest] Make schema validation ignore nullable and metadata attributes

### LINKED ISSUE #5231: [SQLLogicTest] Make schema validation ignore nullable and metadata attributes
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
SQLLogic test fails on schema validation when column has mixed null and non null values.
```
# log scalar function
query CC1 rowsort
select null union all select 1


Error: query failed: DataFusion error: Internal error: Schema mismatch. Previously had
Schema {
    fields: [
        Field {
            name: "NULL",
            data_type: Int64,
            nullable: false,
            dict_id: 0,
            dict_is_ordered: false,
            metadata: {},
        },
    ],
    metadata: {},
}

Got:
Schema {
    fields: [
        Field {
            name: "NULL",
            data_type: Int64,
            nullable: true,
            dict_id: 0,
            dict_is_ordered: false,
            metadata: {},
        },
    ],
    metadata: {},
}. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

**Describe the solution you'd like**
I think we can ignore `nullable` attribute from schema 

**Describe alternatives you've considered**
Workaround to split queries to avoid mixed nulls and nonnulls

**Additional context**

### PR DESCRIPTION
**Pull request by comphead**
# Which issue does this PR close?

Closes #5231 .

# Rationale for this change

# What changes are included in this PR?
Remove IMHO unnecessary schema check for SLT, this check prevents to run test cases having mixed nulls and non null values

# Are these changes tested?
Its tested, since all SLT tests running fine

# Are there any user-facing changes?

### CODE REVIEW

**Comment by comphead** [comment]
@melgenek https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/tests/sqllogictests/src/engines/datafusion/normalize.rs#L44
Please double check  if schema comparison is needed? Is there any real scenario that Dataframe has schema incosistency between first batches and other batches? 

I have noticed the only diff can be for nullable or metadata in optimizer, but this ignored like [equivalent_names_and_types](https://github.com/apache/arrow-datafusion/blob/master/datafusion/common/src/dfschema.rs#L345).

**Comment by melgenek** [comment]
I, unfortunately, cannot tell if this check is always needed. It was added in https://github.com/apache/arrow-datafusion/pull/4578/files#diff-4d4a58673140be1acf7a04b9aa71a29f106ebb75a256553e2a9ff13d9a3856f4. @alamb Could you please take a look.

**Review by alamb — APPROVED** [review]
LGTM -- thanks @comphead

**Comment by alamb** [comment]
>  I, unfortunately, cannot tell if this check is always needed. It was added in https://github.com/apache/arrow-datafusion/pull/4578/files#diff-4d4a58673140be1acf7a04b9aa71a29f106ebb75a256553e2a9ff13d9a3856f4. @alamb Could you please take a look.

We have seen this in the past where schemas differ only in nullability (hence `equivalent_names_and_types`)

It might be safer to change the check to verify the fields name and types (rather than `schema == schema`). What do you think @comphead  and @melgenek ?

**Comment by melgenek** [comment]
> It might be safer to change the check to verify the fields name and types (rather than schema == schema).

I re-opened this page to say the same thing 🙂 Totally agree.

**Comment by comphead** [comment]
> > I, unfortunately, cannot tell if this check is always needed. It was added in https://github.com/apache/arrow-datafusion/pull/4578/files#diff-4d4a58673140be1acf7a04b9aa71a29f106ebb75a256553e2a9ff13d9a3856f4. @alamb Could you please take a look.
> 
> We have seen this in the past where schemas differ only in nullability (hence `equivalent_names_and_types`)
> 
> It might be safer to change the check to verify the fields name and types (rather than `schema == schema`). What do you think @comphead and @melgenek ?

I'm still thinking the check is redundant, as batches within one query execution shouldn't have difference in types and fields. But to be safe I'll add the type/fields check today

**Comment by alamb** [comment]
> I'm still thinking the check is redundant, as batches within one query execution shouldn't have difference in types and fields. But to be safe I'll add the type/fields check today

right -- they definitely *SHOULD NOT* be different between batches, so I think it is good to be verifying them as part of the tests

**Review by alamb — APPROVED** [review]
Thanks @comphead 

cc @melgenek

**Pull request merged**
