### PR TITLE
Simplify error using thiserror crate

### PR DESCRIPTION
**Pull request by lewiszlw**
## Which issue does this PR close?

Simplify error using thiserror crate

### CODE REVIEW

**Review by jackwener — COMMENTED** [review]
It doesn't seem to have much benefits, but it adds a dependence

**Comment by lewiszlw** [comment]
Better readability and maintainability, and `thiserror` is de facto standard for error handling.

**Comment by tustvold** [comment]
> de facto standard for error handling

The only crate that currently depends on thiserror is apache-avro which is currently optional and likely to be removed once supported upstream - https://github.com/apache/arrow-rs/issues/4886.

I'm not against using thiserror, but it does seem a touch overkill for this use-case

**Comment by alamb** [comment]
Thanks again for this PR @lewiszlw  

The reason we have a template for PRs is to avoid getting PRs getting stuck like this while the reviewers don't understand the rationale / purpose for the change.

Perhaps you can fill out this section

> Rationale for this change


But as the other reviewers have said, it seems like all this PR does is add a new dependency without any corresponding gain in functionality. Perhaps we are missing something -- can you please let us know?

**Comment by alamb** [comment]
Marking as draft as this PR is no longer waiting on feedback

**Comment by lewiszlw** [comment]
This pr just for simplifing code and improving readability. Many open source projects use `thiserror` for error handling. I think it's a good choice. If you have concern, feel free to close the pr.

**Pull request closed without merging**
