### PR TITLE
Use upstream delimited stream

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
FYI any "no space left on device" CI errors should be fixed by merging up from master to get https://github.com/apache/arrow-datafusion/pull/5047

**Review by alamb — APPROVED** [review]
Thank you @tustvold 

FYI for anyone else following along, it was upstreamed in  https://github.com/apache/arrow-rs/pull/3341

**Comment by alamb** [comment]
There seems to be a few errors in CI for this PR --

**Comment by tustvold** [comment]
I hope to replace this with the new CSV and JSON Decoder abstractions in the next release of arrow, so closing this for now

**Pull request closed without merging**
