### PR TITLE
Revert "Minor: remove unnecessary projection in `single_distinct_to_g…

### PR DESCRIPTION
**Pull request by NGA-TRAN**
…roup_by` rule (#8061)"

This reverts commit 15d8c9bf48a56ae9de34d18becab13fd1942dc4a.

## Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/8175
Closes https://github.com/apache/arrow-datafusion/pull/8178

## Rationale for this change

Revert the change as it introduced bugs

### CODE REVIEW

**Comment by NGA-TRAN** [comment]
@alamb @haohuaijin

**Review by alamb — APPROVED** [review]
Thank you @NGA-TRAN . Since this is a bug fix for a regression, I plan to merge it asap. 

I also added a regression test in in 346616898b to prevent future breakages

**Comment by alamb** [comment]
Looks like @NGA-TRAN  and I both added the test (sorry I didn't see https://github.com/apache/arrow-datafusion/pull/8178) . Since this one is green let's merge it .

**Comment by alamb** [comment]
Thanks again @NGA-TRAN

**Comment by haohuaijin** [comment]
Thanks for this fix @NGA-TRAN @alamb . I apologize for introducing this bug. The issue arises from mishandling aliases in the group by clause. Consequently, any queries like the following will result in errors in #8061：
```sql
select a+1 as alias, count(distinct b) from t group by alias
```
Thanks again @NGA-TRAN @alamb

**Pull request merged**
