### PR TITLE
Support CREATE OR REPLACE TABLE

### LINKED ISSUE #2605: Support `CREATE OR REPLACE TABLE`
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
DataFusion already supports `CREATE TABLE AS SELECT`

When working with tables it is nice to be able to replace them when they already exist

**Describe the solution you'd like**

I would like the following SQL to run rather than produce an error:

```sql
❯ CREATE TABLE valuetable AS VALUES(1,'HELLO'),(12,'DATAFUSION');
+---------+------------+
| column1 | column2    |
+---------+------------+
| 1       | HELLO      |
| 12      | DATAFUSION |
+---------+------------+
2 rows in set. Query took 0.016 seconds.
❯ CREATE OR REPLACE TABLE valuetable AS VALUES(1,'HELLO THERE');
Execution("Table '\"valuetable\"' already exists")
```

The result should be that `valuetable` now contains a single row 👍 
```
+---------+------------+
| column1 | column2    |
+---------+------------+
| 1       | HELLO THERE      |
```

### PR DESCRIPTION
**Pull request by AssHero**
# Which issue does this PR close?
Closes  #2605 

 # Rationale for this change
replace the table content if table already exits
❯ create table xx as values(1,2),(3,4);
+---------+---------+
| column1 | column2 |
+---------+---------+
| 1       | 2       |
| 3       | 4       |
+---------+---------+
2 rows in set. Query took 0.004 seconds.

❯ create or replace table xx as values(5,6);
+---------+---------+
| column1 | column2 |
+---------+---------+
| 5       | 6       |
+---------+---------+
1 row in set. Query took 0.004 seconds.

if 'if not exists' and 'or replace' are both specified, treat as 'or replace'
❯ create or replace table if not exists xx as values(7,8);
+---------+---------+
| column1 | column2 |
+---------+---------+
| 7       | 8       |
+---------+---------+
1 row in set. Query took 0.002 seconds.

# What changes are included in this PR?
adjust rules for create table in context.rs

### CODE REVIEW

**Review by Ted-Jiang — COMMENTED** [review]
@AssHero Thanks for your work 👍
Maybe you can add some test like 
https://github.com/apache/arrow-datafusion/blob/0c4ffd4f7b064a8f4e4a167e2e4c913389056968/datafusion/core/tests/sql/create_drop.rs#L22-L46

**Comment by AssHero** [comment]
> 



> > if 'if not exists' and 'or replace' are both specified, treat as 'or replace'
> 
> I personally feel weird about `IF NOT EXIST` coexist with `OR REPLACE`. They are asking for two different behaviors. Should we reject this kind of query like others ( [1](https://docs.microsoft.com/en-us/azure/databricks/sql/language-manual/sql-ref-syntax-ddl-create-table-using#parameters), [2](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#:~:text=collate_specification%5D%0A%5BOPTIONS(schema_option_list)%5D-,Arguments,-IF%20NOT%20EXISTS) )?

'create or replace if not exists' is not supported in MySQL/PG, and is not permitted in databricks. 
we can have a disscussion about how to deal with it.

**Comment by andygrove** [comment]
Thanks for the contribution @AssHero. I also would like to see `IF NOT EXISTS` and `OR REPLACE` as separate options that cannot be used together. LGTM otherwise.

**Review by waynexia — APPROVED** [review]

**Review by alamb — APPROVED** [review]
Looks great -- thank you @AssHero, @Ted-Jiang  and @waynexia

**Review by Ted-Jiang — APPROVED** [review]

**Pull request merged**
