### PR TITLE
Fix: dataframe_subquery example Optimizer rule `common_sub_expression_eliminate` failed

### LINKED ISSUE #8015: Test `dataframe_subquery` fails
### Describe the bug

When running datafreme's subquery-related test class, an exception will be thrown. The reason for the error is that no optimization rules are matched.
```
Error: Context("Optimizer rule 'common_sub_expression_eliminate' failed", SchemaError(FieldNotFound { field: Column { relation: Some(Bare { table: "t1" }), name: "c1" }, valid_fields: [Column { relation: Some(Bare { table: "t2" }), name: "c1" }, Column { relation: Some(Bare { table: "t2" }), name: "c2" }, Column { relation: Some(Bare { table: "t2" }), name: "c3" }, Column { relation: Some(Bare { table: "t2" }), name: "c4" }, Column { relation: Some(Bare { table: "t2" }), name: "c5" }, Column { relation: Some(Bare { table: "t2" }), name: "c6" }, Column { relation: Some(Bare { table: "t2" }), name: "c7" }, Column { relation: Some(Bare { table: "t2" }), name: "c8" }, Column { relation: Some(Bare { table: "t2" }), name: "c9" }, Column { relation: Some(Bare { table: "t2" }), name: "c10" }, Column { relation: Some(Bare { table: "t2" }), name: "c11" }, Column { relation: Some(Bare { table: "t2" }), name: "c12" }, Column { relation: Some(Bare { table: "t2" }), name: "c13" }] }))
```

### To Reproduce

 cargo run --example dataframe_subquery 

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by smallzhongfeng**
## Which issue does this PR close?

Closes #8015.

## Rationale for this change

make cargo run --example dataframe_subquery run

## What changes are included in this PR?

Use `out_ref_col` instead of `col`.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Review by haohuaijin — APPROVED** [review]
LGTM, thank you @smallzhongfeng

**Review by alamb — APPROVED** [review]
Thank you @smallzhongfeng 

I wonder if there is some way to add these examples to the CI / ensure they are passing (so we don't accidentally break them again without knowing it) 🤔

**Comment by smallzhongfeng** [comment]
> Thank you @smallzhongfeng
> 
> I wonder if there is some way to add these examples to the CI / ensure they are passing (so we don't accidentally break them again without knowing it) 🤔

In fact, I am currently doing this, but the method is relatively simple, which is to traverse all the rs files in the example directory through the shell, and then execute them in sequence. I don’t know if you need it. 🤔

**Comment by smallzhongfeng** [comment]
But currently, you can only run test cases based on local or memory, and tests using external storage may need to be skipped. : (

**Comment by haohuaijin** [comment]
the test like `flight_server` also need be skip, those test are start a server.

**Pull request merged**
