### PR TITLE
Port remaining information_schema rust tests to sqllogictests

### PR DESCRIPTION
**Pull request by palash25**
# Which issue does this PR close?

Closes: #6301

# Rationale for this change

This ports the remaining information_schema tests to sqllogic tests

# What changes are included in this PR?

The file containing rust tests for information schema has been completely deleted. And the 3 rust tests from that file have been ported to sql logic tests residing in a separate `.slt` file

# Are these changes tested?
Yes i did run `cargo test` there were a few ignored tests but no failures

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by palash25** [comment]
I ported these tests to a new .slt file since one of the tests creates multiple catalogs it changes the results of some existing tests and causes a few errors in the `information_schema.slt` file because there I could not find a way to clean up the created catalogs.

I was not able to port two things because I wasn't able to figure out a valid SQL syntax to do so:
- how to create a temporary table described [here](https://github.com/apache/arrow-datafusion/pull/7050/files#diff-c56811e83126f556f1062be29382b4e416a0e1c248a587cf8524645bfc2d7a66L139) ?  
- how to set nullable/non-nullable fields when using the `arrow_cast()` syntax for creating columns  https://github.com/apache/arrow-datafusion/pull/7050/files#diff-af1ad1d88be48a9e9f0fb325594e979824f319ab3c4678b124e2761dca7d6c9dR157
@alamb if you or any other maintainer could help me out with these it would be a great help

**Comment by palash25** [comment]
thank you, i didn't know we could use rust code with logic tests, i will take a look at this tomorrow and try to finish it up

**Comment by palash25** [comment]
@alamb its ready for review. I used rust code to set things up for two of the tests as you suggested:
- one for creating local temporary table
- the other for setting nullable fields correctly

I had to split the tests into separate .slt files because even though i was able to set things up correctly with setup.rs there was no way to cleanup things properly and that would mess with the output of some other test. Hope thats ok.

**Review by alamb — COMMENTED** [review]
This looks great @palash25  -- thank you very much 🙏

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
I took the liberty of merging up from main and fixing the clippy error on this PR. Hopefully we can get it merged tomorrow. Thanks again @palash25

**Comment by palash25** [comment]
thanks for the clippy fixes, i didn't notice them. I just pushed a small commit removing unnecessary comments that were left out in the original commit. Looking forward to contributing more in the future, it was a really nice experience to contribute to this project. 😄

**Comment by alamb** [comment]
> Looking forward to contributing more in the future, it was a really nice experience to contribute to this project. 😄

Thank you for saying so. We strive to make it pleasant and have people work well together as a community so it is nice to have that awknowledged

**Pull request merged**
