### PR TITLE
Merges master and integrates arrow2/parquet2 0.10

### PR DESCRIPTION
**Pull request by Igosuki**
# Which issue does this PR close?
.

 # Rationale for this change
Stabilize the branch around arrow2 0.10, which has fixes for nested data structs

### CODE REVIEW

**Comment by houqp** [comment]
Thanks @Igosuki I am going to try finding time going over it this week. Also working on a local fix for the json fileformat plan at the moment and will rebase my fix once this PR is fixed.

I think the commit still looks wrong to me: master commits got merged into a single commit https://github.com/apache/arrow-datafusion/pull/2003/commits/cbaf9db8e2cb40f69cb532b71206eec47a119d7d. I will help take a look into how to better unsquash these commits after this PR is merged as well.

**Comment by Igosuki** [comment]
I should probably have used the new three way merge you talked about

**Comment by houqp** [comment]
no worries, we can give it a try next time we catch up to master :)

**Comment by houqp** [comment]
@Igosuki I found a way squashed all the arrow2 related commits into a single one so we can unsquash all new master commits in the arrow2 branch so we can start using 3 way merge going forward to reduce merge conflicts.

The arrow2 branch has been force updated including the changes you have in this PR. I will send the json test fix later this week to the arrow2 branch and let you know.

**Comment by houqp** [comment]
FYI, I also pinned `parquet-format-async-temp` version to 0.2 to unblock the build.

**Comment by Igosuki** [comment]
Nice !

**Pull request closed without merging**
