### PR TITLE
Better Equivalence (ordering and exact equivalence) Propagation through ProjectionExec

### PR DESCRIPTION
**Pull request by mustafasrepo**
## Which issue does this PR close?

Improves the situation on #8064.

## Rationale for this change

In the [PR8281](https://github.com/apache/arrow-datafusion/pull/8281) we added support for ordering requirement analysis for complex expressions.

However, in current codebase some ordering information got lost during the projection of complex expressions.

## What changes are included in this PR?
This PR adds support for better ordering information propagation support for complex expressions through `ProjectionExec`.
Consider the case where we have table with columns `a,b,c,d,e` and assume that `[a ASC, b ASC]`, `[c ASC]` is valid orderings for this table.

If were to apply the projection (`a`, `c`, `b+c`) on top of this table valid orderings after projection are: `[a ASC, b+c ASC]`, `[c ASC]`. However, in current code base we can propagate only `[a ASC]`, `[c ASC]`. This PR enables us to propagate complex expression orderings better through `ProjectionExec`. You can examine unit tests for other examples of this PR's support.

## Are these changes tested?
Yes extensive unit and random test is added. Most of the changes comes from test or test util codes.

### CODE REVIEW

**Review by metesynnada — APPROVED** [review]
LGTM.

**Review by alamb — COMMENTED** [review]
Thanks @mustafasrepo  and @metesynnada 

Let me know if you want an extra review of this PR

One thing I noticed is that `datafusion/physical-expr/src/equivalence.rs` is getting quite massive (over 5000 lines long now). What do you think about breaking it up into smaller modules? I think that would make the code easier to reason about as well as help solidify the APIs a bit more. 

I did some version of that in https://github.com/apache/arrow-datafusion/pull/8235 but @ozankabak  rightly pointed out that such a refactor would likely cause non trivial merge conflicts if there was other work underway.

**Comment by ozankabak** [comment]
> Let me know if you want an extra review of this PR

I also reviewed this so it may be a better use of your time to review other PRs, but if you have some extra time on your hands, why not 🙂 

> I did some version of that in #8235 but @ozankabak rightly pointed out that such a refactor would likely cause non trivial merge conflicts if there was other work underway.

This was the last major work item on this code, it will be good to go for a refactor after we merge this 🚀

**Comment by alamb** [comment]
> but if you have some extra time on your hands, why not 🙂

😆  I don't think it needs any more review if it has already been reviewed by three committers

**Pull request merged**
