### PR TITLE
Update TPC-H benchmark to show physical plan when debug mode is enabled

### LINKED ISSUE #385: DataFusion benchmarks should show physical plan when debug is enabled
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When we run the benchmarks with `--debug` we see the logical plan and optimized logical plan but we do not see the physical plan.

**Describe the solution you'd like**
I would like to see the physical plan as well.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Closes #385 .

 # Rationale for this change

When we run the benchmarks with `--debug` we see the logical plan and optimized logical plan but we do not see the physical plan. This PR updates debug mode to also show the physical plan.

# What changes are included in this PR?

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by andygrove** [comment]
Windows build failing with:

```
rustup: D:\a\_temp\297de9db-5464-4aa4-af8d-ef568eeef2fe.ps1:3
Line |
   3 |  rustup default stable
     |  ~~~~~~
     | The term 'rustup' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
```

**Review by Dandandan — APPROVED** [review]
Looks good

**Comment by Dandandan** [comment]
Windows CI failure is unrelated, was happening in other PRs too.

**Comment by alamb** [comment]
I restared the windows CI check -- hopefully we'll get a passing run

**Pull request merged**
