### PR TITLE
The CLI panics when passing an invalid explain query

### LINKED ISSUE #4378: The CLI panics when passing an invalid `explain` query
**Describe the bug**
```sql
❯ explain explain select 1;
thread 'main' panicked at 'Explain can not be created from utils::from_expr', 
./datafusion/expr/src/utils.rs:573:13
```

Related code: https://github.com/apache/arrow-datafusion/blob/ba73c8180ebd874614cabc33be8cbb0d1db52518/datafusion/expr/src/utils.rs#L565-L578

**To Reproduce**

**Expected behavior**
Return an error instead of panicking.

**Additional context**

### PR DESCRIPTION
**Pull request by comphead**
# Which issue does this PR close?

Closes #4378 .

# Rationale for this change

# What changes are included in this PR?
Replace panics in favor if Error

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by comphead** [comment]
Hi @HaoYang670 please check the PR
But tbh the optimizer doesn't respect errors now so the error message looks like 
```
DataFusion CLI v14.0.0
❯ explain explain select 1;
Internal("Unsupported logical plan: Explain must be root of the plan")
```

**Review by jackwener — APPROVED** [review]

**Comment by HaoYang670** [comment]
Could we add a test for this?

**Comment by HaoYang670** [comment]
> Hi @HaoYang670 please check the PR But tbh the optimizer doesn't respect errors now so the error message looks like
> 
> ```
> DataFusion CLI v14.0.0
> ❯ explain explain select 1;
> Internal("Unsupported logical plan: Explain must be root of the plan")
> ```

Thank you for your contribution @comphead .
This is because the error is generated in the logical optimizer, but it is ignored as the configuration `datafusion.optimizer.skip_failed_rules` is set to `true in default: 
https://github.com/apache/arrow-datafusion/blob/49166ea55f317722ab7a37fbfc253bcd497c1672/datafusion/optimizer/src/optimizer.rs#L248-L265

And the error message printed in CLI is created when generating physical plan:
https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/physical_plan/planner.rs#L1093-L1095

Generally, we don't want to return an internal error to user, because it means that there are bugs in our project.
For the `expain explain ... ` query, if it is invalid, we should return an error when parsing it, instead of when optimizing it.

cc @andygrove. Should this bug be fixed in sqlparser-rs or in datafusion?

**Comment by jackwener** [comment]
Agree with @HaoYang670 , look like it should be fixed in sqlparser-rs.

**Comment by andygrove** [comment]
I agree that the parser bug should be fixed in sqlparser-rs. It would also be nice to have a unit test for this change.

**Comment by comphead** [comment]
Thanks @HaoYang670 @andygrove @jackwener added test

**Review by alamb — APPROVED** [review]
Thank you @HaoYang670

**Pull request merged**
