### PR TITLE
Fix propagation of optimized predicates on nested projections

### LINKED ISSUE #3073: incorrect `where` clause comparison while using table alias
**Describe the bug**

**To Reproduce**

```bash
DataFusion CLI v10.0.0
❯ select * from (select 1 as a) f where f.a=2;
+---+
| a |
+---+
| 1 |
+---+
1 row in set. Query took 0.000 seconds.
```

while this works in postgresql
```bash
willy=# select * from (select 1 as a) f where f.a=2;
 a 
---
(0 rows)
```

**Expected behavior**

should output 0 row

**Additional context**

### PR DESCRIPTION
**Pull request by isidentical**
# Which issue does this PR close?

Closes #3073.

 # Rationale for this change

This PR prevents the removal of predicates without referencing columns (`WHERE FALSE`, `WHERE 1=1`, etc.) that might have been created during the column name replacing phase (on filter pushdown optimizer when dealing with projections specifically).

# What changes are included in this PR?
Columnless predicates are now collected into a separate entity, stripped away from the actual list of filters when switching the projection/filter and then re-applied.

# Are there any user-facing changes?
This should fix the bug referenced in #3073

### CODE REVIEW

**Review by andygrove — COMMENTED** [review]
The changes look reasonable to me, but I am not very familiar with some of this code so will need to look closer. I will make time in the next day or two.

**Comment by Dandandan** [comment]
I'm not sure if this fixes the bug in issue #3073? I'm not totally convinced we should not propagate filters without column (e.g. constants), the result should remain the same whether it is propagated or not. Issue #3073 seems to be about a filter expression *with* a column, that somehow doesn't filter the row out.

Could we add a test for #3073 here?

**Review by Dandandan — CHANGES_REQUESTED** [review]
Add test for #3037 and explain why changes are needed

**Comment by isidentical** [comment]
> Issue https://github.com/apache/arrow-datafusion/issues/3073 seems to be about a filter expression with a column, that somehow doesn't filter the row out.

@Dandandan since the example in #3073 uses an in-memory table, the filter `where f.a=2` got replaced with `where 1=2` in a step of the optimizer (which, at least for me, makes perfect sense) when we are rewriting columns here:
https://github.com/apache/arrow-datafusion/blob/873b071dff1a6099d30abdd24437e083a60e2686/datafusion/optimizer/src/filter_push_down.rs#L396

> I'm not sure if this fixes the bug in issue https://github.com/apache/arrow-datafusion/issues/3073? I'm not totally convinced we should not propagate filters without column (e.g. constants), the result should remain the same whether it is propagated or not.

There is already a similar work done by an earlier step of the filter pushdown optimizer which ensures that `WHERE 1=2` (and other variants of constant/columns-less filters) are not propagated (since we can't rewrite them if there are no earlier projections to propagate, unlike regular filters). The main thing this PR does is allow this check to be also carried out in `Projection` part where filters might change due to how we propagate constants. 
https://github.com/apache/arrow-datafusion/blob/873b071dff1a6099d30abdd24437e083a60e2686/datafusion/optimizer/src/filter_push_down.rs#L358-L368

**Comment by isidentical** [comment]
> Add test for https://github.com/apache/arrow-datafusion/pull/3037 and explain why changes are needed

Definitely, will be working on that!

**Comment by Dandandan** [comment]
> > Issue https://github.com/apache/arrow-datafusion/issues/3073 seems to be about a filter expression with a column, that somehow doesn't filter the row out.
> 
> @Dandandan since the example in #3073 uses an in-memory table, the filter `where f.a=2` got replaced with `where 1=2` in a step of the optimizer (which, at least for me, makes perfect sense) when we are rewriting columns here:
> https://github.com/apache/arrow-datafusion/blob/873b071dff1a6099d30abdd24437e083a60e2686/datafusion/optimizer/src/filter_push_down.rs#L396
> 
> > I'm not sure if this fixes the bug in issue https://github.com/apache/arrow-datafusion/issues/3073? I'm not totally convinced we should not propagate filters without column (e.g. constants), the result should remain the same whether it is propagated or not.
> 
> There is already a similar work done by an earlier step of the filter pushdown optimizer which ensures that `WHERE 1=2` (and other variants of constant/columns-less filters) are not propagated (since we can't rewrite them if there are no earlier projections to propagate, unlike regular filters). The main thing this PR does is allow this check to be also carried out in `Projection` part where filters might change due to how we propagate constants. 
> https://github.com/apache/arrow-datafusion/blob/873b071dff1a6099d30abdd24437e083a60e2686/datafusion/optimizer/src/filter_push_down.rs#L358-L368
> 

Isn't the issue then that the propagated filters without column are not added to the plan at all, even when we are at the bottom of a plan? E.g. a propagated `where false` still should be present regardless of whether it has columns in it.

**Comment by isidentical** [comment]
> Isn't the issue then that the propagated filters without column are not added to the plan at all, even when we are at the bottom of a plan? E.g. a propagated where false still should be present regardless of whether it has columns in it.

Exactly, at least that is my understanding of this issue. I thought as is, it would be similar to the existing behaviour from #225 but this time done on the projection level rather than filter level.


If it makes sense, I can also change the logic in `issue_filters` so that when pushing down we can issue filters for both used filters + all the column-less filters.
https://github.com/apache/arrow-datafusion/blob/873b071dff1a6099d30abdd24437e083a60e2686/datafusion/optimizer/src/filter_push_down.rs#L125-L145

**Comment by isidentical** [comment]
@Dandandan I did a re-implementation using the approach I've described below (handling this on the `issue_filters` level rather than individual plans) [in here](https://github.com/isidentical/arrow-datafusion/pull/1). I'd be happy to include it here it makes more sense.

**Comment by Dandandan** [comment]
Yes, this makes most sense, and simplifies the implementation quite a bit.

**Review by Dandandan — APPROVED** [review]
LGTM, thanks @isidentical !

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
Thanks again @isidentical

**Review by alamb — COMMENTED** [review]
This looks like a great change -- I think it is a very positive sign when we fix bugs by deleting code 👍 

Thanks @isidentical  and @Dandandan

**Pull request merged**
