### PR TITLE
MINOR: Minimal website

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

This adds a minimal index.md as a placeholder. We will create PRs for real content.

 # Rationale for this change

Test that the website publishes.

# What changes are included in this PR?

Placeholder index.md

# Are there any user-facing changes?

No

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Eventually I would like to see the SQL guide and the README.md file incorporated into this website.

Is that your plan too @andygrove ?

**Comment by Jimexist** [comment]
@alamb is this direction a go?

**Comment by alamb** [comment]
@Jimexist  I am not sure what happened to this PR and do not remember the any reason to have closed it :( Maybe I meant to click merge rather than close ...

**Comment by alamb** [comment]
I think bringing this back would be a good idea

**Pull request closed without merging**
