### PR TITLE
Rename `ParamValues::{LIST -> List,MAP -> Map}`

### LINKED ISSUE #8610: `ParamValues::{LIST,MAP}` does not conform to the standard naming convention
### Describe the bug

The standard naming convention ([RFC 430](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case)) says enum variants should be named by `UpperCamelCase`. Most existing enum types in DataFusion conform to this convention, but `ParamValues` does not.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kawadakk**
## Which issue does this PR close?

Closes #8610.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
I agree this is a nice improvement. Thank you @kawadakk 
cc @Asura7969

**Comment by alamb** [comment]
Marking as API change as the names of the `enum` are `pub`

**Comment by Asura7969** [comment]
this looks great❤️

**Comment by alamb** [comment]
Thanks again @kawadakk

**Pull request merged**
