### PR TITLE
feat: date_bin output type same with input type

### PR DESCRIPTION
**Pull request by jiacai2050**
# Which issue does this PR close?

Closes #.

# Rationale for this change
Follow up for #5818 

# What changes are included in this PR?

Update `date_bin`'s signature to  return same date type as input.

# Are these changes tested?
sql logical test

# Are there any user-facing changes?
Before this PR, date_bin will always return `Timestamp(Nanosecond, None)`, after this, it will return date time according to input.

### CODE REVIEW

**Comment by jackwener** [comment]
I add a `api change` label because it change original behavior.

**Review by jackwener — APPROVED** [review]
cc @alamb @liukun4515 @mingmwang @yjshen

**Comment by alamb** [comment]
Thank you @jiacai2050  -- this looks great to me. It appears to have some logical conflicts with https://github.com/apache/arrow-datafusion/pull/5982 from @NGA-TRAN  -- I am trying to resolve them locally on a branch

**Comment by alamb** [comment]
I took the liberty of resolving the conflicts and updating the tests to cover arrays -- hopefully that is ok @jiacai2050

**Pull request merged**
