### PR TITLE
Hotfix: Test in information_schema.slt fails

### LINKED ISSUE #7285: Test in information_schema.slt fails consistently
### Describe the bug

After #7270, test in `information_schema.slt` fails consistently.
https://github.com/apache/arrow-datafusion/actions/runs/5858702865/job/15883449656

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sarutak**
## Which issue does this PR close?
Closes #7285 

## Rationale for this change
This PR aims to fix an issue that test in `information_schema.slt` fails consistently after #7270.
https://github.com/apache/arrow-datafusion/actions/runs/5858702865/job/15883174290

## Are these changes tested?
GitHub Actions.

## Are there any user-facing changes?
No.

### CODE REVIEW

**Review by viirya — COMMENTED** [review]
Another place:

```
--- a/docs/source/user-guide/configs.md
+++ b/docs/source/user-guide/configs.md
@@ -64,7 +64,7 @@ Environment variables are read during `SessionConfig` initialisation so they mus
 | datafusion.execution.parquet.statistics_enabled            | page                      | Sets if statistics are enabled for any column Valid values are: "none", "chunk", and "page" These values are not case sensitive.                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
 | datafusion.execution.parquet.max_statistics_size           | 4096                      | Sets max statistics size for any column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
 | datafusion.execution.parquet.max_row_group_size            | 1048576                   | Sets maximum number of rows in a row group                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
-| datafusion.execution.parquet.created_by                    | datafusion version 28.0.0 | Sets "created by" property                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+| datafusion.execution.parquet.created_by                    | datafusion version 29.0.0 | Sets "created by" property                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
```

**Comment by sarutak** [comment]
Yeah, I noticed too...

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Merged to restore CI. Thanks @sarutak

**Comment by alamb** [comment]
Thank you @sarutak  and @viirya

**Pull request merged**
