### PR TITLE
add untyped null

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by houqp — APPROVED** [review]

**Comment by Dandandan** [comment]
I am not sure anymore this is a good idea.

The problem with introducing `null` as scalar is that we lose the type information on the scalar (making everything type `Null`). In order to make this work, the value should be converted to an array of the original type afterwards.

**Comment by houqp** [comment]
That's a good point @Dandandan

**Comment by Jimexist** [comment]
> I am not sure anymore this is a good idea.
> 
> 
> 
> The problem with introducing `null` as scalar is that we lose the type information on the scalar (making everything type `Null`). In order to make this work, the value should be converted to an array of the original type afterwards.

The alternative I think is to infer types for null during planning

**Comment by alamb** [comment]
I think that during planning we should treat the type of any `ScalarValue::*(None)` as `DataType::Null` and coerce them appropriately to the needed types as part of physical planning.

@Jimexist  I think added the needed casting logic in arrow-rs at https://github.com/apache/arrow-rs/pull/884 (though that didn't make it into 6.1.0 -- so I suppose we have to wait a bit longer -- though maybe I'll end up making a 6.2.0 before 6.1.0 gets through the voting process 🤣 )

Once we can cast from `DataType::Null` I think we'll be able to make this work in DataFusio

**Comment by liukun4515** [comment]
any progress, is there any context or doc for this?
@Jimexist

**Comment by alamb** [comment]
I had effectively changed `Expr::Scalar` to report its type as `DataType::Null` its interior `ScalarValue::is_null()` returned true. That seemed fairly promising but I got blocked by the lack of null cast kernels in Arrow. 

Now I think we have those kernels it would be useful to try again -- but I am not sure when I will have the time again

**Comment by alamb** [comment]
I am trying to clean up the list of PRs to review in DataFusion so marking old ones as stale. Please let us know if you plan to work on this soon. Otherwise we will close it down and reopen it when the time is right.

**Comment by alamb** [comment]
Closing stale PRs, please reopen if this was a mistake and you plan to keep working on this one

**Pull request closed without merging**
