### PR TITLE
rewrite `array_append/array_prepend` to remove deplicate codes 

### PR DESCRIPTION
**Pull request by Veeupup**
## Which issue does this PR close?

One issue from #7988  `array_append` && `array_prepend`.

### CODE REVIEW

**Comment by Veeupup** [comment]
@jayzhan211 PTAL ^ . ^

**Comment by alamb** [comment]
Thanks @Veeupup  -- I'll check it out shortly

**Review by Weijun-H — COMMENTED** [review]
Thank you @Veeupup ! Could you also move the related tests to sqllogictest?

**Comment by jayzhan211** [comment]
My expected way for array_append/array_prepend is building array via MutableArrayData, so I need to think about whether row converter is the better choice or not.

**Comment by jayzhan211** [comment]
I wrote another function with MutableArrayData and it is a lot faster. 30000 micro second vs 300 micro second. @Veeupup  Can you also try with MutableArrayData and compare it yourself, if you also got the same result, we can go with MutableArrayData approach.

**Comment by Veeupup** [comment]
> Thank you @Veeupup ! Could you also move the related tests to sqllogictest?

Sure！ I'll make it later

**Comment by Veeupup** [comment]
> I wrote another function with MutableArrayData and it is a lot faster. 30000 micro second vs 300 micro second. @Veeupup  Can you also try with MutableArrayData and compare it yourself, if you also got the same result, we can go with MutableArrayData approach.

Appreciate your advice！ I'll try this way and benchmark it then

**Comment by Veeupup** [comment]
> Thank you @Veeupup ! Could you also move the related tests to sqllogictest?

hi @Weijun-H ! it seems that I do not need to do anything? (Or just remove ut `fn test_array_prepend`  and `fn test_array_append`)

 I have checked the `sqllogictests` with array_append/prepend, and it seems that `sqllogictests` already have these cases.

**Comment by Veeupup** [comment]
@jayzhan211  I have implemented the array_append in MutableArray and RowConverter and it shows that Mutable performs better too.

Here are the benchmarks for sqllogictests:

| MutableArray | RowConverter |
| ------------ | ------------ |
|  29.297µs |  93.433µs |
|  20.555µs |  32.201µs | 
|  19.251µs |  86.561µs |
|  102.495µs |  143.772µs |
|  58.49µs |  35.456µs |
|  56.035µs |  33.316µs |
|  45.607µs |  79.701µs |
|  23.508µs |  33.592µs |
|  22.87µs |  37.584µs |
|  39.27µs |  56.071µs |
|  23.973µs |  35.368µs |
|  24.97µs |  37.753µs |
|  44.644µs |  59.515µs |
|  26.602µs |  35.498µs |
|  22.272µs |  37.957µs |
|  97.846µs |  169.643µs |
|  107.068µs |  123.551µs |
|  55.058µs |  178.546µs |
|  45.853µs |  109.962µs |
|  82.722µs |  90.556µs |
|  43.62µs |  44.157µs |

**Comment by alamb** [comment]
Very nice!

**Review by alamb — APPROVED** [review]
Thank you @Veeupup  and @jayzhan211 -- this looks a lot nicer to me. I think there is even more performance to be gained here by avoiding `concat` (and using ArrayData to build up the final output) but this is a lot better than what we have currently.

Thanks a lot 🙏

**Pull request merged**
