### PR TITLE
separate contributors guide

### LINKED ISSUE #3127: docs: proposal for consolidating docs into a Contributor Guide
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

Separate the documentation site into "User Guide" and "Contributor Guide"
Merge CONTRIBUTING.md into Contributor Guide making one location to find all the docs relating to how to contribute to DF

**Describe alternatives you've considered**

**Additional context**

Current site nav:
image

Proposed new site nav:
image

### PR DESCRIPTION
**Pull request by kmitchener**
# Which issue does this PR close?

Closes #3127 .

 # Rationale for this change

# What changes are included in this PR?

See the issue

# Are there any user-facing changes?

### CODE REVIEW

**Comment by kmitchener** [comment]
@andygrove wdyt? 

Maybe Roadmap docs are actually part of the user guide? As a user of DataFusion, I'm interested in what the roadmap is, but it's less relevant for _how_ to contribute to DF.

Anyway, looking for early feedback whether to abandon this approach or not

**Review by andygrove — APPROVED** [review]
LGTM

**Comment by andygrove** [comment]
I was working on https://github.com/apache/arrow-datafusion/pull/3129before I saw this. We should probably merge yours first.

**Comment by andygrove** [comment]
> Maybe Roadmap docs are actually part of the user guide? As a user of DataFusion, I'm interested in what the roadmap is, but it's less relevant for _how_ to contribute to DF.

I like the approach in this PR. I see the roadmap as part of the developer resources. We can always link to it from the user guide as well though.

**Comment by kmitchener** [comment]
I'm going to mark it ready for review then and we can continue with more changes on top once it's been merged in.

**Pull request merged**
