### PR TITLE
Use atomics for SQLMetric implementation, remove unused name field

### PR DESCRIPTION
**Pull request by returnString**
As mentioned in apache/arrow#10049 as a potential followup, this PR simplifies metrics management in physical ops by removing the need for a mutex around `SQLMetric` instances, instead using atomics to track metric values.

I've also removed the `name` field as this info is duplicated by `ExecutionPlan::metrics` returning a string-keyed map. Happy to revert that portion of the change if people feel strongly about it though!

It might be possible to futher simplify this by removing the `Arc` allocs and sharing `SQLMetric` instances as `Sync` references if the existing lifetime setup plays nicely with it, but I didn't want to spend _too_ much time digging into this; I think this PR as-is gives us the immediate win of not needing to deal with mutexes :)

### CODE REVIEW

**Comment by returnString** [comment]
Probably one for @andygrove, if you have some time :)

**Review by andygrove — APPROVED** [review]
:heart:

**Review by Dandandan — APPROVED** [review]
Looking quite a bit cleaner! :sunglasses:

**Comment by andygrove** [comment]
Closes https://github.com/apache/arrow-datafusion/issues/30

**Review by alamb — COMMENTED** [review]
Thank you @returnString

**Pull request merged**
