### PR TITLE
Do not allow HAVING clause in non-aggregate queries

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/2460

 # Rationale for this change

Neither Postgres nor Spark supports the use of the `HAVING` clause in non-aggregate queries.

I am also motivated to reduce complexity in the aggregate code while we fix some issues there.

# What changes are included in this PR?

Stop allowing the use of `HAVING` in non-aggregate queries.

# Are there any user-facing changes?

Yes, users will need to use `WHERE` instead of `HAVING` for non-aggregate queries.

### CODE REVIEW

**Review by jdye64 — CHANGES_REQUESTED** [review]
LGTM - The logic `!group_by_exprs.is_empty() || !aggr_exprs.is_empty()` seems to allow for `HAVING` clauses if aggregate expressions are present, however might it be worth adding another test that does have a aggregate and `HAVING` clause?

**Comment by jdye64** [comment]
Seems [test](https://github.com/apache/arrow-datafusion/blob/cc496f87caf8d13e4c17025e0d3b86643a21a243/datafusion/core/tests/sql/group_by.rs#L194) needs to be updated to expect the error

**Comment by andygrove** [comment]
> LGTM - The logic `!group_by_exprs.is_empty() || !aggr_exprs.is_empty()` seems to allow for `HAVING` clauses if aggregate expressions are present, however might it be worth adding another test that does have an aggregate and `HAVING` clause? Could be another simple check in an existing test even.

Yes that's a great point. I checked and there is already a test to cover this case:

``` rust
#[test]
fn select_aggregate_with_having_that_reuses_aggregate() {
    let sql = "SELECT MAX(age)
               FROM person
               HAVING MAX(age) < 30";
    let expected = "Projection: #MAX(person.age)\
                    \n  Filter: #MAX(person.age) < Int64(30)\
                    \n    Aggregate: groupBy=[[]], aggr=[[MAX(#person.age)]]\
                    \n      TableScan: person projection=None";
    quick_test(sql, expected);
}
```

**Review by jdye64 — APPROVED** [review]

**Review by alamb — APPROVED** [review]
I don't mind this change, but I think technically postgres supports HAVING in queries without aggregates:

```sql
❯ select * from andrew having substr(location, 4) = 'et_sound';
+-----------------+-------------+-------+-----------------+----------------+------------+
| measurement     | location    | state | surface_degrees | bottom_degrees | timestamp  |
+-----------------+-------------+-------+-----------------+----------------+------------+
| h2o_temperature | puget_sound | WA    | 55.8            | 40.2           | 1568756160 |
| h2o_temperature | puget_sound | WA    | 55.8            | 40.2           | 1600756160 |
+-----------------+-------------+-------+-----------------+----------------+------------+
2 rows in set. Query took 0.013 seconds.
```

**Comment by andygrove** [comment]
> I don't mind this change, but I think technically postgres supports HAVING in queries without aggregates:
> 
> ```sql
> ❯ select * from andrew having substr(location, 4) = 'et_sound';
> +-----------------+-------------+-------+-----------------+----------------+------------+
> | measurement     | location    | state | surface_degrees | bottom_degrees | timestamp  |
> +-----------------+-------------+-------+-----------------+----------------+------------+
> | h2o_temperature | puget_sound | WA    | 55.8            | 40.2           | 1568756160 |
> | h2o_temperature | puget_sound | WA    | 55.8            | 40.2           | 1600756160 |
> +-----------------+-------------+-------+-----------------+----------------+------------+
> 2 rows in set. Query took 0.013 seconds.
> ```

hmm ok maybe we should not make this change then. Here is the test I was running in postgres:

```
postgres=# select id, name from book having price < 6;
ERROR:  column "book.id" must appear in the GROUP BY clause or be used in an aggregate function
```

This was with postgres 14.2

**Comment by alamb** [comment]
> hmm ok maybe we should not make this change then. Here is the test I was running in postgres:

Ah, that makes sense as `price` wasn't in the select list (which is technically supposed to be evaluated before the HAVING)

 I bet this would work:

```sql
select id, name, price from book having price < 6;
```

**Comment by andygrove** [comment]
> > hmm ok maybe we should not make this change then. Here is the test I was running in postgres:
> 
> Ah, that makes sense as `price` wasn't in the select list (which is technically supposed to be evaluated before the HAVING)
> 
> I bet this would work:
> 
> ```sql
> select id, name, price from book having price < 6;
> ```

That also fails for me:

```
postgres=# select id, name, price from book having price < 6;
ERROR:  column "book.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select id, name, price from book having price < 6;
```

**Comment by alamb** [comment]
> That also fails for me:

I am stumped 🤔

**Comment by drusso** [comment]
Hi Andrew and Andy. This behaviour dates back to the [initial](https://github.com/apache/arrow/pull/9364) implementation, so I can try to provide some context. The [select_with_having](https://github.com/apache/arrow-datafusion/blob/6786203ea8c9c4cfe604f74a5cece8e829fb56c8/datafusion/core/src/sql/planner.rs#L2818) and [select_with_having_referencing_column_not_in_select](https://github.com/apache/arrow-datafusion/blob/6786203ea8c9c4cfe604f74a5cece8e829fb56c8/datafusion/core/src/sql/planner.rs#L2829) cases are there, almost certainly, because those queries are valid in MySQL 8. I used both Postgres and MySQL as a reference for the implementation, and in this particular case, opted for the MySQL behaviour, since it's the more permissive of the two. I think since then, Postgres has been adopted as the reference.

**Comment by alamb** [comment]
Thank you for the context @drusso   -- I do not have a strong preference one way or the other in terms of switching behaviors / merging this PR

**Comment by andygrove** [comment]
Thanks @drusso that is helpful. I think I will go ahead and close this PR in the next day or two unless anyone objects. Moving back to draft for now.

**Pull request closed without merging**
