### PR TITLE
Fix Decimal256 scalar display string in sqllogictest

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

A followup to #7048.

## Rationale for this change

In #7048, one question is the display string of Decimal256 scalar is different to Decimal128 in sqllogictest. This patch fixes it.

### CODE REVIEW

**Comment by viirya** [comment]
The pyarrow failure is unrelated:

```
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```

**Comment by alamb** [comment]
I believe CI will pass after merging up from `main` to get the change in  https://github.com/apache/arrow-datafusion/pull/7416

**Review by alamb — APPROVED** [review]
makes sense to me - thank you!

**Comment by viirya** [comment]
Thanks @alamb

**Pull request merged**
