### PR TITLE
Update quarterly_roadmap.md

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by yjshen** [comment]
We have implemented file-based shuffle with memory management in Blaze. I could have that PRed if it aligns with the goal of Ballista.

**Comment by yahoNanJing** [comment]
Thanks very much @yjshen. Could you help raise a PR for that? 😄

**Comment by andygrove** [comment]
I think it might be better to move the Ballista roadmap to the Ballista project now

**Comment by yahoNanJing** [comment]
@andygrove, agree.

**Comment by andygrove** [comment]
I created a PR https://github.com/apache/arrow-ballista/pull/318 to add the Ballista roadmap to the Ballista repo

**Pull request closed without merging**
