### PR TITLE
fix 226, make `concat`, `concat_ws`, and `random` work with `Python` crate

### LINKED ISSUE #226: `Concat` from Dataframe API no longer accepts multiple expressions
The function has signature `concat(Expr)`, while some time ago it had the signature `concat(&[Expr])`.

I think that it makes sense to be `concat(&[Expr])`, as we AFAIK we hope to concatenate more than one expression.

Found while trying to bump python-datafusion to latest DataFusion.

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #226

 # Rationale for this change

- `concat` and `concat_ws` no longer works

# What changes are included in this PR?

- fix concat
- fix concat_ws
- fix random
- add unit tests

# Are there any user-facing changes?

### CODE REVIEW

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Thanks a lot, @Jimexist !

**Review by alamb — APPROVED** [review]
Thanks @Jimexist ! Looks good to me -- we often add a `pub use` in the `logical_plan/expr.rs` for functions such as `concat`, `concat_ws`, and `random` which might be useful too

https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/logical_plan/mod.rs#L38-L48

**Comment by Jimexist** [comment]
> Thanks @Jimexist ! Looks good to me -- we often add a `pub use` in the `logical_plan/expr.rs` for functions such as `concat`, `concat_ws`, and `random` which might be useful too
> 
> https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/logical_plan/mod.rs#L38-L48

i think it's already in that `pub use` list

**Review by Dandandan — APPROVED** [review]

**Comment by alamb** [comment]
> i think it's already in that pub use list

Good call -- sorry I missed that

**Pull request merged**
