### PR TITLE
Make the required distribution of NestedLoopJoinExec consistent with CrossJoinExec

### LINKED ISSUE #5022: NestedLoopJoin will panic when right child contains RepartitionExec
**Describe the bug**
When I work on #4866, I find some `NestedLoopJoin`s will panic.
```sql
# create tables -- t.csv is an empty file.
❯ CREATE EXTERNAL TABLE t1 (t1_id INT, t1_name text, t1_int INT) STORED AS CSV LOCATION 't.csv';
❯ CREATE EXTERNAL TABLE t2 (t2_id INT, t2_name text, t2_int INT) STORED AS CSV LOCATION 't.csv';
# target_partitions
> set datafusion.execution.target_partitions = 4;
```

```sql
❯ explain select * from t1 inner join t2 on t1.t1_id > t2.t2_id where t1.t1_id > 10 and t2.t2_int > 10;
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                  |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: t1.t1_id, t1.t1_name, t1.t1_int, t2.t2_id, t2.t2_name, t2.t2_int                                                                                          |
|               |   Inner Join:  Filter: t1.t1_id > t2.t2_id                                                                                                                            |
|               |     Filter: t1.t1_id > Int32(10)                                                                                                                                      |
|               |       TableScan: t1 projection=[t1_id, t1_name, t1_int], partial_filters=[t1.t1_id > Int32(10)]                                                                       |
|               |     Filter: t2.t2_int > Int32(10)                                                                                                                                     |
|               |       TableScan: t2 projection=[t2_id, t2_name, t2_int], partial_filters=[t2.t2_int > Int32(10)]                                                                      |
| physical_plan | ProjectionExec: expr=[t1_id@0 as t1_id, t1_name@1 as t1_name, t1_int@2 as t1_int, t2_id@3 as t2_id, t2_name@4 as t2_name, t2_int@5 as t2_int]                         |
|               |   NestedLoopJoinExec: join_type=Inner, filter=BinaryExpr { left: Column { name: "t1_id", index: 0 }, op: Gt, right: Column { name: "t2_id", index: 1 } }              |
|               |     CoalesceBatchesExec: target_batch_size=8192                                                                                                                       |
|               |       FilterExec: t1_id@0 > 10                                                                                                                                        |
|               |         RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1                                                                                          |
|               |           CsvExec: files={1 group: [[home/work/tools/datafusion-test-data/join-context/t1.csv]]}, has_header=false, limit=None, projection=[t1_id, t1_name, t1_int]   |
|               |     CoalescePartitionsExec                                                                                                                                            |
|               |       CoalesceBatchesExec: target_batch_size=8192                                                                                                                     |
|               |         FilterExec: t2_int@2 > 10                                                                                                                                     |
|               |           RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1 -- panic in RepartitionExec                                                                                          |
|               |             CsvExec: files={1 group: [[home/work/tools/datafusion-test-data/join-context/t1.csv]]}, has_header=false, limit=None, projection=[t2_id, t2_name, t2_int] |
|               |                                                                                                                                                                       |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

This sql will panic:
```sql
❯ select * from t1 inner join t2 on t1.t1_id > t2.t2_id where t1.t1_id > 10 and t2.t2_int > 10;
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
thread 'tokio-runtime-worker' panicked at 'partition not used yet', /home/work/arrow-datafusion/datafusion/core/src/physical_plan/repartition/mod.rs:426:14
0 rows in set. Query took 0.015 seconds.
```

**To Reproduce**
See above.

**Expected behavior**
The join should work.

It seems the partition of right child may execute one more time in `NestedLoopJoin`, if it has multiple output partitions. It is ok in most time, but when meets `RepartitionExec` it will panic. 

  
**Additional context**

### PR DESCRIPTION
**Pull request by ygf11**
# Which issue does this PR close?

Closes #5022.

# Rationale for this change

1. Currently the required distribution of `NestedLoopJoinExec` is not consistent with `CrossJoinExec`, and some optimizations(`JoinSelection`) already done for `CrossJoinExec` will not take effect for `NestedLoopJoinExec`. 
2. `NestedLoopJoinExec` will collect both left and right to a single partition for `Full` join, this may cause performance issue. 

We can always collect left for `NestedLoopJoinExec` like `CrossJoinExec` does. This will also fix #5022.

# What changes are included in this PR?

1. Always collect left side for `NestedLoopJoinExec` like `CrossJoinExec` does.
2. For `LEFT/LEFT-SEMI/LEFT-ANTI/FULL`, we need generate the additional data for the unmatched rows, so maintain a global state of `visited_left_side` in `NestedLoopJoinExec`.
3. Merge partition state - `visited_left_side` to global after one partition is finished.  
4. Generate the additional data for the unmatched rows based on `global state` after all partitions are finished.

# Are these changes tested?
Yes.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by liukun4515** [comment]
why the distribution should be consistent between NLJ and Cross-join?
When I first implement the NLJ, I didn't consider the `JoinSelection` for the NLJ, I think it is an optimization for NLJ.
I think it is not a good way to change the rule of distribution to fix the bug of https://github.com/apache/arrow-datafusion/issues/5022

In many join type, we should have the all data for the left side or the all data for the right side.

**Comment by liukun4515** [comment]
> # Which issue does this PR close?
> Closes #5022.
> 
> # Rationale for this change
> 1. Currently the required distribution of `NestedLoopJoinExec` is not consistent with `CrossJoinExec`, and some optimizations(`JoinSelection`) already done for `CrossJoinExec` will not take effect for `NestedLoopJoinExec`.
> 2. `NestedLoopJoinExec` will collect both left and right to a single partition for `Full` join, this may cause performance issue.
> 
> We can always collect left for `NestedLoopJoinExec` like `CrossJoinExec` does. This will also fix #5022.
> 

I think it will bring other performance issue for other `join type` when we always collect the left the NLJ.

I think the current required distribution for the NLJ will cause performance issue, but it will cause error or panic for the implementation.

We should take more time to find the root cause for the panic issue https://github.com/apache/arrow-datafusion/issues/5022
> # What changes are included in this PR?
> 1. Always collect left side for `NestedLoopJoinExec` like `CrossJoinExec` does.
> 2. For `LEFT/LEFT-SEMI/LEFT-ANTI/FULL`, we need generate the additional data for the unmatched rows, so maintain a global state of `visited_left_side` in `NestedLoopJoinExec`.
> 3. Merge partition state - `visited_left_side` to global after one partition is finished.
> 4. Generate the additional data for the unmatched rows based on `global state` after all partitions are finished.
> 
> # Are these changes tested?
> Yes.
> 
> # Are there any user-facing changes?

**Comment by liukun4515** [comment]
From the partition mode in the datafusion
```
/// Partitioning mode to use for hash join
pub enum PartitionMode {
    /// Left/right children are partitioned using the left and right keys
    Partitioned,
    /// Left side will collected into one partition
    CollectLeft,
    /// When set to Auto, DataFusion optimizer will decide which PartitionMode mode(Partitioned/CollectLeft) is optimal based on statistics.
    /// It will also consider swapping the left and right inputs for the Join
    Auto,
}
```
which is used in the hash join.

**Comment by ygf11** [comment]
> When I first implement the NLJ, I didn't consider the JoinSelection for the NLJ, I think it is an optimization for NLJ.

Yes, it is an optimization. The `JoinSelection` will choose smaller side(`total_byte_size`) as left side(NLJ has not been supported).

> why the distribution should be consistent between NLJ and Cross-join?

For `JoinSelection`, after I think more, I think the benefit of the consistent is we can reuse the optimize logic of `CrossJoin`. Even they are not consistent, we can still add similar optimization for `NestedLoopJoin` in `JoinSelection`.

So the main improvement of this pr is `NestedLoopJoinExec` will build one side data, not two sides for `Full` join. This can improve performance.

> I think it will bring other performance issue for other join type when we always collect the left the NLJ.

Since `JoinSelection` will swap the orders, so there is no difference between build-left and build-right.

**Comment by liukun4515** [comment]
I think we can make this https://github.com/apache/arrow-datafusion/issues/5022#issuecomment-1407296431 clear first, and figure out why the repartition exec can not be called twice

**Comment by liukun4515** [comment]
> Thanks @liukun4515, your question make me think more.
> 
> > When I first implement the NLJ, I didn't consider the JoinSelection for the NLJ, I think it is an optimization for NLJ.
> 
> Yes, it is an optimization. The `JoinSelection` will choose smaller side(`total_byte_size`) as left side for `CrossJoinExec` (NLJ has not been supported).
> 

😭, in other database, the `cross join` is one of type of join type, but we split them into two set `cross join type` and `other join type` in the datafusion.

The `JoinSelection` for the `cross join` can bring benefit for the `nested loop join`, but I think it will bring constraint for the distribution of the left side and right side.


The `cross join` type just contain one type of join, but the NLJ contains many other join types, maybe different join type can get benefit from the different required distribution.

we can ignore the changes of distribution for the left and right and the physical optimization of `JoinSelection`, because without the optimization, the physical exec/plan should be able to executed.

we can discuss this https://github.com/apache/arrow-datafusion/issues/5022#issuecomment-1407306585 issue, why the `RepartitionExec` can't be called twice for the same partition. If this issue can be resolved, the physical plan can be executed successfully.

> > why the distribution should be consistent between NLJ and Cross-join?
> 
> For `JoinSelection`, after I think more, I think the benefit of the consistent is we can reuse the optimize logic of `CrossJoin`. Even they are not consistent, we can still add similar optimization for `NestedLoopJoin` in `JoinSelection`.
> 
> So the main improvement of this pr is `NestedLoopJoinExec` will build one side data, not two sides for `Full` join. This can improve performance.
> 
> > I think it will bring other performance issue for other join type when we always collect the left the NLJ.
> 
> Since `JoinSelection` will swap the orders, so there is no difference between build-left and build-right.

I think we can change the `required_input_distribution` to optimize the performance for the `Full` or other join type, if change the implementation like your code in this pr and bring a global `visited bit map` of `state: Arc<Mutex<NestedLoopJoinState>>`. But the global lock of state will bring some negative effects.

**Comment by ygf11** [comment]
> I think we can change the required_input_distribution to optimize the performance for the Full or other join type, if change the implementation like your code in this pr and bring a global visited bit map of state: Arc<Mutex<NestedLoopJoinState>>. But the global lock of state will bring some negative effects.

Compare to the improvement, I think the negative effects of global lock is trivial.
Because it will not be visited very frequently:
1. For joins that do not need global state (inner/right/right-semi/right-anti), the `NestedLoopJoinStream` will never visit the global state.
2. The global state will be locked and updated when a partition finishes, and only visited once for the partition. So the lock competition will not be very intense.

**Pull request closed without merging**
