### PR TITLE
fix clippy

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Find in #4185 .

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by jackwener** [comment]
@alamb

**Comment by jackwener** [comment]
failed CI is fix already by #4189

**Comment by alamb** [comment]
I wonder if this is clippy failures on a newer rust version (e.g. unstable)?

Can you please rebase / merge this branch to master ?

The changes look good to me. Thank you @jackwener

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @jackwener

**Pull request merged**
