### PR TITLE
[Minor] Cleanup `SumAccumulator`

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by mingmwang** [comment]
LGTM

**Comment by mustafasrepo** [comment]
Thanks @Dandandan for this PR. As fas as I know, `count` stores the element number in the sum. When count is 0, we should produce `NULL`. Consider expression `SUM(inc_col) OVER(ORDER BY ts ASC ROWS BETWEEN 2 FOLLOWING AND 3 FOLLOWING) as sum1` for the last 2 results we should produce `NULL`. However, without storing count, we cannot differentiate `NULL`, and `0`. In the failing test, this can be seen also. (Executor produces 0, where it should have been produced `NULL`)

Maybe there is way to accomplish this without storing count. I just wanted to mention, current use of it.

**Comment by Dandandan** [comment]
> Thanks @Dandandan for this PR. As fas as I know, `count` stores the element number in the sum. When count is 0, we should produce `NULL`. Consider expression `SUM(inc_col) OVER(ORDER BY ts ASC ROWS BETWEEN 2 FOLLOWING AND 3 FOLLOWING) as sum1` for the last 2 results we should produce `NULL`. However, without storing count, we cannot differentiate `NULL`, and `0`. In the failing test, this can be seen also. (Executor produces 0, where it should have been produced `NULL`)
> 
> Maybe there is way to accomplish this without storing count. I just wanted to mention, current use of it.

Thanks. Yeah - I just saw this usage of it and the related failing test.

One way to accomplish it would be differentating window and conventional aggregations, or maybe it could be handled inside the window function code itself 🤔

**Comment by ozankabak** [comment]
> One way to accomplish it would be differentating window and conventional aggregations, or maybe it could be handled inside the window function code itself 🤔

I suspect this will result in more complexity than what we started with. But one can never be sure without trying and playing around.

**Comment by Dandandan** [comment]
> > One way to accomplish it would be differentating window and conventional aggregations, or maybe it could be handled inside the window function code itself 🤔
> 
> I suspect this will result in more complexity than what we started with. But one can never be sure without trying and playing around.

Playing a bit with the code, my feeling is that usage of the accumulator in window functions is suboptimal, because of producing a `ScalarValue` for each output.
I think when moving to more specialized kernels for (moving) sum/avg/count we could remove the usage of `SumAccumulator` and remove the `count` from it.

**Comment by Dandandan** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/5948

**Pull request closed without merging**
