### PR TITLE
Test arrow without null (DEMO)

### PR DESCRIPTION
**Pull request by alamb**
Testing https://github.com/apache/arrow-rs/pull/1942 

Use code on https://github.com/apache/arrow-rs/pull/1943

Not meant for merging

### CODE REVIEW

**Comment by viirya** [comment]
The failed cases looks not like an attempt to really want to cast other datatype (Utf8) to Null. Looks like an incorrect type coercion rule for `NULL IN ('a','b')`. It tries to cast from utf8 to null, but seems it is more correct to cast from null to utf8.

**Comment by alamb** [comment]
> 
The failed cases looks not like an attempt to really want to cast other datatype (Utf8) to Null. Looks like an incorrect type coercion rule for NULL IN ('a','b'). It tries to cast from utf8 to null, but seems it is more correct to cast from null to utf8.



I agree @viirya  -- I'll try and find time to look at this later if no one else does. I have a few more things to deal with the fallout from upgrade to arrow 17 https://github.com/apache/arrow-datafusion/pull/2778

**Comment by viirya** [comment]
> I agree @viirya -- I'll try and find time to look at this later if no one else does. I have a few more things to deal with the fallout from upgrade to arrow 17 #2778

I may take a look in this weekend.

**Comment by alamb** [comment]
For others -- proposed fix PR is in https://github.com/apache/arrow-datafusion/pull/2794

**Pull request closed without merging**
