### PR TITLE
Simplify redundant predicates

### LINKED ISSUE #3895: Simplify `a AND a` and `a OR a`.
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Some features like https://github.com/apache/arrow-datafusion/pull/3859 may find / introduce seemingly nonsensical predicates like `a AND a` -- in this case the expression simplifier should remove them. 

**Describe the solution you'd like**
Add rewrite rules to rewrite
`a AND a` --> `a`
`a OR a` --> `a`

Rewrite rules are https://github.com/apache/arrow-datafusion/blob/feff5dc/datafusion/optimizer/src/simplify_expressions.rs#L793

### PR DESCRIPTION
**Pull request by src255**
Write rules to simplify both `a OR a` and `a AND a` to `a`.

Hello! I wanted to help with issue #3895. This is my attempt, but I'm not sure if this is the desired comparison of the `left` and `right` fields of the `BinaryExpr` struct. I hope this helps and I would appreciate any feedback!
# Which issue does this PR close?

Closes #3895 .

### CODE REVIEW

**Comment by isidentical** [comment]
Thank you for the PR @src255, I think it looks pretty good as is (an example comparison is available inside `expr_contains`). I think all you have to do next is add some tests (a very similiar example is `test_simplify_optimized_plan`). One thing to note is, I think we might have `a AND a` already so might make sense to check if the test fails first and gets fixed with your revision. But `a OR a` should be still good.

**Comment by src255** [comment]
Thanks for the feedback. Here is the new test I wrote with `test_simplify_optimized_plan` as a guide:
```rust
#[test]
fn test_simplify_optimized_plan_with_or() {
    let table_scan = test_table_scan();
    let plan = LogicalPlanBuilder::from(table_scan)
        .project(vec![col("a")])
        .unwrap()
        .filter(or(col("b").gt(lit(1)), col("b").gt(lit(1))))  // use `or` instead of `and`
        .unwrap()
        .build()
        .unwrap();

    assert_optimized_plan_eq(
        &plan,
        "\
        Filter: test.b > Int32(1)\
        \n  Projection: test.a\
        \n    TableScan: test",
    );
}
```
After running this test, I noticed that both `test_simplify_optimized_plan_with_or` and `test_simplify_optimized_plan` pass without my changes (`OR` and `AND` changes commented out)! Perhaps the optimizer is already making *both* simplifications: 
- `a OR a` --> `a`
- `a AND a` --> `a`.

**Comment by isidentical** [comment]
Thanks for checking it out. That seems to be true (the simplification below) 🤔 (which probably means somewhere in the #3859 we are missing something else, cc: @alamb @Ted-Jiang).

https://github.com/apache/arrow-datafusion/blob/e534c2536858cf18aac219c33b0bddef54c7f214/datafusion/optimizer/src/simplify_expressions.rs#L768-L779

**Comment by alamb** [comment]
Thanks for the test and investigation @src255  and @isidentical -- clearly I got something wrong.

**Review by alamb — APPROVED** [review]

**Pull request merged**
