### PR TITLE
Fix ambiguous reference error in filter plan

### LINKED ISSUE #1411: Ambiguous reference to aliased column
Quoted from @houqp:

> .filter(df.column("bool_col")) should ignore the projection alias and only use the actual bool_col table column to evaluate the predicate. This is be behavior I see in postgres. For example SELECT id+1 as id2 FROM test where id2 > 2 results in error: column "id2" does not exist.

To reproduce:

```python
import datafusion as df

# bool_col is an integer here, convert it to be actually boolean
bool_col = (df.column("bool_col") == df.literal(1)).alias("bool_col")
result = table.select(bool_col).filter(df.column("bool_col"))
result.collect()
```

raises

```
Exception: Error during planning: Ambiguous reference to field named 'bool_col'
```

_Originally posted by @kszucs in https://github.com/ibis-project/ibis/pull/2918#discussion_r749318005_

### PR DESCRIPTION
**Pull request by jonmmease**
# Which issue does this PR close?
Closes #1411.  

cc @kszucs

 # Rationale for this change
This PR adds an initially failing test in a060b40f14f6a28945d0e15c2ae893136a9d55b9 that reproduces the behavior described in #1411.

The change in 2042fbb8e16cd5908563c0f8faafe000f02ec029 may not be correct overall, but it addresses this particular failure.

The core issue seems to be that filter optimization examines fields across all plans and then fails because there is an ambiguity. At least in the DataFrame context, I would expect there to be no ambiguity since only one of the columns is projected prior to filtering.

### CODE REVIEW

**Comment by jonmmease** [comment]
unsurprisingly, this change causes a failure in the `execution::context::tests::unprojected_filter` test.

I'm not sure what the correct behavior here is.  Should the projected schema take precedence to resolve ambiguity and then fall back to the combined schema if a column reference is not found?

**Comment by alamb** [comment]
> I'm not sure what the correct behavior here is. Should the projected schema take precedence to resolve ambiguity and then fall back to the combined schema if a column reference is not found?

That sounds reasonable to me at a high level

@houqp  wrote up the desired output name semantics here:  https://arrow.apache.org/datafusion/specification/output-field-name-semantic.html

which might serve to guide you in your question

**Comment by alamb** [comment]
(thank you @jonmmease  for raising this PR)

**Comment by houqp** [comment]
thank you @jonmmease for taking on this, I agree with @alamb that the order you outlined in your comment sounds like a good order to me.

**Comment by jonmmease** [comment]
This error poppup up in https://github.com/apache/arrow-datafusion/runs/5470235871?check_suite_focus=true:

```
 failures:

---- datasource::file_format::avro::tests::test stdout ----
thread 'datasource::file_format::avro::tests::test' panicked at 'Local file metadata: Os { code: 2, kind: NotFound, message: "No such file or directory" }', datafusion/src/datasource/object_store/local.rs:178:40


failures:
    datasource::file_format::avro::tests::test
```

Maybe something flaky?

**Comment by alamb** [comment]
> Maybe something flaky?


I think this is related to the fact that somehow this PR has changes to the `testing` repo which I suspect was not intended:

Screen Shot 2022-03-08 at 3 06 16 PM

**Comment by jonmmease** [comment]
Thanks @alamb, not sure how that got in there :facepalm:   Should be reverted now

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
Thanks @jonmmease

**Review by alamb — APPROVED** [review]
Thanks @jonmmease

**Pull request merged**
