### PR TITLE
Remove references to Ballista Docker images published to ballistacompute Docker Hub repo

### LINKED ISSUE #325: Remove references to ballistacompute Docker Hub repo
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Now that Ballista is part of Arrow DataFusion, we need to remove references to the legacy Docker Hub repo and make sure everything can be built entirely from the DataFusion repo.

**Describe the solution you'd like**
There should be no dependency on existing Docker images.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Builds on https://github.com/apache/arrow-datafusion/pull/322 and closes #325.

 # Rationale for this change

It should be possible to build Ballista from this repo without depending on any previously published Ballista Docker base images.

# What changes are included in this PR?

Remove references to ballistacompute images.

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by andygrove** [comment]
@edrevo fyi

**Review by jorgecarleitao — COMMENTED** [review]
LGTM. Thanks, @andygrove !

**Review by edrevo — APPROVED** [review]
Does this mean there aren't going to be any official ballista docker images?

**Comment by andygrove** [comment]
> Does this mean there aren't going to be any official ballista docker images?

No, I'd like to publish official Docker images in addition to letting users build and publish their own images. See https://github.com/apache/arrow-datafusion/issues/228

**Pull request merged**
