### PR TITLE
Always increment timer on record

### PR DESCRIPTION
**Pull request by tustvold**
# Rationale for this change

#2261 added a test that elapsed_compute was recorded in metrics, unfortunately in the case of LocalLimitExec and GlobalLimitExec the operator body is too small to reliable take time, and as such this test is flaky

* https://github.com/apache/arrow-datafusion/runs/6100177086?check_suite_focus=true
* https://github.com/apache/arrow-datafusion/runs/6100277301?check_suite_focus=true
* https://github.com/apache/arrow-datafusion/runs/6100969854?check_suite_focus=true

Additionally when rendering plan metrics, a value if 0 is translated to "NOT RECORDED" - https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/physical_plan/metrics/value.rs#L540

# What changes are included in this PR?

This changes `Time::add_duration` and `Time::add` to always record at least one nanosecond. 

# Are there any user-facing changes?

Yes, calling `Timer::add_duration` will now always record at least 1 nanosecond

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you

**Comment by alamb** [comment]
ITS TOO FAST!

**Comment by yjshen** [comment]
Thanks for the fixing!

I found this test flaky and added the [assertion failure message](https://github.com/apache/arrow-datafusion/pull/2261/commits/ab153760f8439d5859d529d02a3f598fb4433129) in #2261 but failed to reproduce it in later trials.

Previous failure before the assertion log:
https://github.com/apache/arrow-datafusion/runs/6091653680?check_suite_focus=true

**Comment by yjshen** [comment]
I manually rerun all failure checks for the latest PRs because of this flaky test.

**Pull request merged**
