### PR TITLE
Move `data-access` crate into `datafusion` directory

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/2424

 # Rationale for this change

Make the project more consistent. All of the other datafusion sub-crates are under the datafusion directory and there appears to be no reason for `data-access` to be different.

# What changes are included in this PR?

- Move `data-access` crate into `datafusion` directory
- Bump `data-access` version from 1.0.0 to 7.0.0 for consistency with other crates
- Update release scripts

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by jychen7** [comment]
nice, LGTM

**Comment by yahoNanJing** [comment]
Hi @andygrove, according to #2076, the reason to move the data-access crate out of the datafusion directory is to make it possible for other crates, like **datafusion-objectstore-s3** and **datafusion-objectstore-hdfs**, to depend on only this crate rather than the whole datafusion crate. Then the datafusion crate may also be able to depend on the object store extensions. 

In summary, the data-access crate should not depend on the datafusion. The dependencies should be like follows:
```
datafusion
     |        \
     |          \
     |            datafusion-objectstore-extensions
     |            /
     |          /
data-access
```

**Comment by jychen7** [comment]
it looks like this PR just change the data-access code location (for easier crate building). But it doesn't change dependencies.

**Comment by andygrove** [comment]
> it looks like this PR just change the data-access code location (for easier crate building). So it doesn't change dependencies

Yes,  that is correct. This PR just moves the code and bumps the version from 1.0.0 to 7.0.0 for consistency with other DataFusion crates.

**Review by yjshen — APPROVED** [review]

**Comment by andygrove** [comment]
Thanks for the review @yjshen

**Pull request merged**
