### PR TITLE
Fix hash join non compat issues

### LINKED ISSUE #2877: hash_join panics when join keys have different data types
**Describe the bug**

There are several places where hash_join can panic in version 9.0.0 when I run SQL queries.

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-9.0.0/src/physical_plan/hash_join.rs:973:17
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-9.0.0/src/physical_plan/hash_join.rs:979:17
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-9.0.0/src/physical_plan/hash_join.rs:1045:17
```

**To Reproduce**
I am experimenting with SQL query fuzzing. Here is one query that failed:

```sql
SELECT _c438, _c439, _c440, _c441, _c442, _c443
FROM (
  (
    (SELECT test1.c0 AS _c438, test1.c1 AS _c439, test1.c2 AS _c440, test1.c3 AS _c441, test1.c4 AS _c442, test1.c5 AS _c443
      FROM (test1))
    FULL JOIN
    (SELECT test1.c0 AS _c444, test1.c1 AS _c445, test1.c2 AS _c446, test1.c3 AS _c447, test1.c4 AS _c448, test1.c5 AS _c449
      FROM (test1))
    ON _c438 = _c446)
  RIGHT JOIN
  (SELECT test0.c0 AS _c450, test0.c1 AS _c451, test0.c2 AS _c452, test0.c3 AS _c453, test0.c4 AS _c454, test0.c5 AS _c455
    FROM (test0))
  ON _c441 = _c451);
```

```
ArrowError(ExternalError("Arrow error: External error: Execution error: Join Error: task 5672 panicked"))
```

Data files are here - https://github.com/andygrove/sqlfuzz/tree/main/testdata

**Expected behavior**
Should not panic

**Additional context**

### PR DESCRIPTION
**Pull request by comphead**
# Which issue does this PR close?

Closes #2877 .

 # Rationale for this change

Currently hash join fails if two arms has different but castable avlues.

# What changes are included in this PR?

The entire idea is to try to cast automatically values if possible. 

# Are there any user-facing changes?

### CODE REVIEW

**Comment by comphead** [comment]
@alamb I'm trying to create a block that can coerce and cast left and right ArrayRefs returning casted ones. This can be useful in different places where 2 castable but not same datatypes involved. Example `i32` and `i8`. Without cast the downcast_ref will eventually fail on unwrap. I tried to put cast logic to function, but there are many lifetimes limitations in Rust, appreciate if you can help

**Comment by Dandandan** [comment]
I think a good approach might be to have the cast part of the logical planner, so the join expression becomes in the form `col1::TEXT = col2 AND col2::`. That shouldn't be really very join specific 

I believe we should already have most of the logic there for casting to a common type for expressions.

**Comment by comphead** [comment]
> I think a good approach might be to have the cast part of the logical planner, so the join expression becomes in the form `col1::TEXT = col2 AND col2::`. That shouldn't be really very join specific
> 
> I believe we should already have most of the logic there for casting to a common type for expressions.

Yes, that is something we discussed with @alamb, that other sql engines have cast as part of planner if join arms are not the same datatype but still castable.

So what your idea @Dandandan, to try move cast into the planner?

**Comment by comphead** [comment]
Oh I see, there is a `fn binary_cast` which already does the same but on physical expr level, let me try to reuse it for joins in planner

**Comment by alamb** [comment]
Thanks @Dandandan  -- yes I think `binary_rule` (and the coercion logic in general) is probably what is needed here

**Comment by comphead** [comment]
@Dandandan @alamb is anywhere documentation on planner? I have implemented the cast in planner in `LogicalPlan::Join` branch, and now can see physical expression contains `TryCast` but in this case the join still fails with old error, looks like real cast is lazy and gets computed after hash_join computes its indexes (which is in ExecutionPlan phase). Please ping me where its possible to find in what sequence plans are executed

**Comment by alamb** [comment]
> @Dandandan @alamb is anywhere documentation on planner? 

I don't know of any real documentation on the planner 

Note there is a discussion about the current location of inserting type coercion, which is currently in the physical planner rather than the logical planner) on  https://github.com/apache/arrow-datafusion/issues/3031 with @andygrove  and @liukun4515 

Perhaps this is another example / rationale to move calling the type coercion logic from the physical planner to the logical planner 🤔

**Comment by liukun4515** [comment]
> > @Dandandan @alamb is anywhere documentation on planner?
> 
> I don't know of any real documentation on the planner
> 
> Note there is a discussion about the current location of inserting type coercion, which is currently in the physical planner rather than the logical planner) on #3031 with @andygrove and @liukun4515
> 
> Perhaps this is another example / rationale to move calling the type coercion logic from the physical planner to the logical planner 🤔

I will take a look this pr and issue later today or tomorrow

**Comment by comphead** [comment]
Thanks @alamb @liukun4515 
Imho its preferable to coerce in logical plan, and we probably have to avoid any kind of `downcast` before coercion. That looks like a beefy change

**Comment by liukun4515** [comment]
> Thanks @alamb @liukun4515 Imho its preferable to coerce in logical plan, and we probably have to avoid any kind of `downcast` before coercion. That looks like a beefy change. I'm happy to give a hand if needed

Thank you @comphead , We discussed about the migration the coercion rule from physical phase to logical phase https://github.com/apache/arrow-datafusion/issues/3031 and other issue.

But I need to take look at this issue and pr first, how and where to migrate the coercion is another thing.

**Comment by alamb** [comment]
Closing as this PR is over a year old. Please feel free to reopen it / rebase it if you plan to keep working on it

**Pull request closed without merging**
