### PR TITLE
ObjectStoreRegistry get_by_uri now returns correct path when "scheme" is provided

### LINKED ISSUE #2525: Bug: ObjectStoreRegistry get_by_uri does not return correct path when "scheme" is provided
**Describe the bug**
object_store_registry.get_by_uri does not work as expected.

**To Reproduce && Expected behavior**
```rust
    #[test]
    fn test_get_by_uri_s3() {
        let sut = ObjectStoreRegistry::default();
        sut.register_store("s3".to_string(), Arc::new(LocalFileSystem {}));
        let uri = "s3://bucket/key";
        let (_, path) = sut.get_by_uri(uri).unwrap();
        assert_eq!(path, "bucket/key");
    }

    #[test]
    fn test_get_by_uri_file() {
        let sut = ObjectStoreRegistry::default();
        let uri = "file:///bucket/key";
        let (_, path) = sut.get_by_uri(uri).unwrap();
        assert_eq!(path, "/bucket/key");
    }

    #[test]
    fn test_get_by_uri_local() {
        let sut = ObjectStoreRegistry::default();
        let uri = "/bucket/key";
        let (_, path) = sut.get_by_uri(uri).unwrap();
        assert_eq!(path, "/bucket/key");
    }
```

**Additional context**
This issue is not uncovered with local files, because LocalFileSystem does some additional "magic" to workaround the issue:

```rust
impl ObjectStore for LocalFileSystem {
    async fn list_file(&self, prefix: &str) -> Result<FileMetaStream> {
        let prefix = if let Some((_scheme, path)) = prefix.split_once("://") {
            path
        } else {
            prefix
        };
        list_all(prefix.to_owned()).await
    }
```

### PR DESCRIPTION
**Pull request by timvw**
# Which issue does this PR close?
Closes #2525.

### CODE REVIEW

**Comment by andygrove** [comment]
Our changelogs are generated from issue and PR titles so I updated the title to be more descriptive

**Review by andygrove — APPROVED** [review]
I am not familiar with how this is intended to be used but LGTM

**Comment by alamb** [comment]
LGTM too

**Comment by alamb** [comment]
Thank you @timvw

**Pull request merged**
