### PR TITLE
fix 621, where unnamed window functions shall be differentiated by partition and order by clause

### LINKED ISSUE #621: unqualified window functions shall differentiate given partition and order by clause
**Describe the bug**

given window functions on the same col with same function but different partition by and order by, the schema is failing due to conflict.

**To Reproduce**

```
> select max(c1) over () max_c1, max(c1) over (partition by c2) max_c1_c2 from test;
Plan("Schema contains duplicate unqualified field name 'MAX(test.c1)'")
```

**Expected behavior**

it shall work

**Additional context**

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #621

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by houqp** [comment]
should we update physical column name as well for better readability in the query output? https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/planner.rs#L137-L139

**Comment by Jimexist** [comment]
> should we update physical column name as well for better readability in the query output? https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/planner.rs#L137-L139

i think this is more of the strategy on how we name unnamed columns in the schema. for window functions without an alias, it'll be created with a unique name, given the function type, arg name, partition by clause, order by clause, and window frames. any of these are equivalent then the columns can be thought of the same and thus deduplicated in the projection phase, otherwise they will be planned separately.

**Comment by Jimexist** [comment]
Postgres is totally okay with dup names in the projection phase:

```
[postgres] # select max(c1) over (), max(c1) over (), max(c1) over (partition by c1) from test limit 3;
 max | max | max
-----+-----+-----
 e   | e   | a
 e   | e   | a
 e   | e   | a
(3 rows)
```

**Comment by Jimexist** [comment]
if we are okay with dup names then i guess just keeping the function name would be enough

**Comment by houqp** [comment]
We do allow query outputs (i.e. record batch schema and physical plan schema) to contain columns with same names. This is quite common in join queries where more than one relations contain the same column name.

My previous comment was more around the inconsistency on how window function names are generated in logical plane v.s. physical plane. For example, in physical plane, we don't take `partition by clause, order by clause, and window frames` into account when creating the column name. If we don't want to maintain this consistency, I think we should update this invariant instead: https://github.com/apache/arrow-datafusion/blob/master/docs/specification/invariants.md#the-physical-schema-is-invariant-under-planning.

https://github.com/apache/arrow-datafusion/blob/master/docs/specification/output-field-name-semantic.md contains some rules on how we want to generate field names for physical schema. We don't have any rules for window functions at the moment, so maybe worth formalize it in that document as well.

**Review by alamb — APPROVED** [review]
Looks good to me

**Comment by Jimexist** [comment]
> We do allow query outputs (i.e. record batch schema and physical plan schema) to contain columns with same names. This is quite common in join queries where more than one relations contain the same column name.
> 
> 
> 
> My previous comment was more around the inconsistency on how window function names are generated in logical plane v.s. physical plane. For example, in physical plane, we don't take `partition by clause, order by clause, and window frames` into account when creating the column name. If we don't want to maintain this consistency, I think we should update this invariant instead: https://github.com/apache/arrow-datafusion/blob/master/docs/specification/invariants.md#the-physical-schema-is-invariant-under-planning.
> 
> 
> 
> https://github.com/apache/arrow-datafusion/blob/master/docs/specification/output-field-name-semantic.md contains some rules on how we want to generate field names for physical schema. We don't have any rules for window functions at the moment, so maybe worth formalize it in that document as well.

Thanks for the advice let me address in another pull request

**Pull request merged**
