### PR TITLE
Split equivalence code into smaller modules.

### LINKED ISSUE #8633: Split equivalence code into smaller modules
### Is your feature request related to a problem or challenge?

As equivalence and ordering become ever more important, I would like to break the code up into smaller modules to make it harder to handle.

At almost 3000 lines with several large classes that are overlapping. the existing equivalence.rs is hard to understand.

I would like to break it up into smaller modules.

In fact I didn't even realize there were so many equivalence tracking structures until I started looking at the code more closely.

### Describe the solution you'd like

Move `EquivalenceClass`, `EquivalenceGroup`, `OrderingEquivalenceClass`, `ProjectionMapping`, `EquivalenceProperties`; and into their own modules, updating any internal apis if necessary

I made a PR (that has gone stale) that did this: https://github.com/apache/arrow-datafusion/pull/8235

### Describe alternatives you've considered

_No response_

### Additional context

I think this is a relatively good first issue as there is a PR that shows how to do it and it is mostly a software engineering exercise in moving code around rather than requiring deep DataFusion knowledge

### PR DESCRIPTION
**Pull request by tushushu**
## Which issue does this PR close?

Closes #8633 .

## What changes are included in this PR?
The `datafusion/physical-expr/src/equivalence.rs` has been split into several files along with the tests.

## Are these changes tested?
The previous tests are still kept, and no more tests added.

### CODE REVIEW

**Comment by tushushu** [comment]
I am going to clear the errors in `datafusion/physical-expr/src/equivalence/mod.rs`.

**Comment by tushushu** [comment]
@alamb This PR is ready for a review, and would you guys take a look?

**Comment by ozankabak** [comment]
Thanks @tushushu, we will check it out and circle back with suggestions (if any)

**Review by mustafasrepo — APPROVED** [review]
Thanks @tushushu for this PR. This is very nice cleanup. LGTM!.

**Comment by alamb** [comment]
This is a pretty epic first PR @tushushu  ❤️

**Pull request merged**
