### PR TITLE
Use `_dyn` and `_scalar_dyn` for operations `like`, `ilike`, `nlike`, and `nilike` to support `Dictionary` and `LargeStringArray`

### LINKED ISSUE #5222: Use `_dyn` and `_scalar_dyn` for operations `like`, `ilike`, `nlike`, and `nilike` to support Dictionary and LargeStringArray
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

DataFusion doesn't allow Dictionaries or LargeStringArrays in like comparison operations.  This functionality is already included in Arrow.

**Describe the solution you'd like**

Arrow provides operations on StringArray / LargeStringArray, or DictionaryArray with values StringArray / LargeStringArray, with support for comparisons against another array or a scalar.  The current `Like` implementation doesn't support all of these combinations.  In addition, the check in the physical expressions doesn't use coercion rules when validating the request.

### PR DESCRIPTION
**Pull request by snmvaughan**
# Which issue does this PR close?

Closes #5222. 

Currently a work in progress that handles the scalar case.

# What changes are included in this PR?

Replaces a simple check for equality with a coercion based check.  Replaces `DataType::Utf8` only implementation with the Arrow dyn implementations.

# Are these changes tested?

Existing tests pass.  I'll supplement the tests with additional types.

# Are there any user-facing changes?

No

### CODE REVIEW

**Review by comphead — COMMENTED** [review]
@snmvaughan would be great to have a test showing `like*` now supports `Dictionary` and `LargeStringArray`

**Comment by snmvaughan** [comment]
@comphead Those were the additional tests I planned to add today.

**Comment by alamb** [comment]
FWIW I am hoping the `arrow_cast` function (from https://github.com/apache/arrow-datafusion/pull/5166) makes it easier to write such tests (as we can we can do it with (only0 SQL)

**Comment by alamb** [comment]
Update here is that `arrow_cast` is now available on main so it should be straightforward to write tests using https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests

Perhaps we could add some tests to 
https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/tests/sqllogictests/test_files/predicates.slt

Here is an example of casting an expression to a Dictionary type using 

https://github.com/apache/arrow-datafusion/blob/3ccf1aebb6959fbc6bbbf74d2821522ddfd7d484/datafusion/core/tests/sqllogictests/test_files/arrow_typeof.slt#L127

**Comment by alamb** [comment]
Since this has been open for more than a year, closing it down. Feel free to reopen if/when you keep working on it.

**Pull request closed without merging**
