### PR TITLE
Re-enable TPCH query 6 (#4024)

### LINKED ISSUE #4024: benchmark q6 producing incorrect result
**Describe the bug**

```
---- tests::verify_q6 stdout ----
Running benchmarks with the following options: DataFusionBenchmarkOpt { query: 6, debug: false, iterations: 1, partitions: 2, batch_size: 8192, path: "/home/andy/git/apache/arrow-datafusion/benchmarks/data", file_format: "tbl", mem_table: false, output_path: None, disable_statistics: false }
Query 6 iteration 0 took 2977.2 ms and returned 1 rows
Query 6 avg time: 2977.24 ms
thread 'tests::verify_q6' panicked at 'assertion failed: `(left == right)`
  left: `["123141078.23"]`,
 right: `["75207429.08"]`', benchmarks/src/bin/tpch.rs:1004:13
```

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Closes #4024

# Rationale for this change

#4199 might have resolved this :crossed_fingers: (my laptop is too piddly to confirm locally)

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by tustvold** [comment]
Sadly it would appear not :cry:

**Comment by andygrove** [comment]
Getting close ... I think there are still some decimal rounding issues to be resolved

```
   left: `"Decimal128(Some(12314107823),15,2)"`,
 right: `"Decimal128(Some(12314055479),15,2)"`', benchmarks/src/bin/tpch.rs:1208:31
 ```

**Comment by viirya** [comment]
Maybe related to decimal casting rounding issue https://github.com/apache/arrow-rs/issues/1043#issuecomment-1313193183

**Comment by Dandandan** [comment]
Looking at the plan, it looks like the decimal filter values is coming through nicely (though I think that we should see if we can default DataFusion to `parse_float_as_decimal=true` in the parser).

So my guess is that either the multiplication of `lineitem.l_extendedprice * lineitem.l_discount` is causing the error or the `SUM` aggregation is causing it.

```
ProjectionExec: expr=[SUM(lineitem.l_extendedprice * lineitem.l_discount)@0 as revenue], metrics=[output_rows=1, elapsed_compute=250ns, spill_count=0, spilled_bytes=0, mem_used=0]
  AggregateExec: mode=Final, gby=[], aggr=[SUM(lineitem.l_extendedprice * lineitem.l_discount)], metrics=[output_rows=1, elapsed_compute=665ns, spill_count=0, spilled_bytes=0, mem_used=0]
    CoalescePartitionsExec, metrics=[output_rows=2, elapsed_compute=1µs, spill_count=0, spilled_bytes=0, mem_used=0]
      AggregateExec: mode=Partial, gby=[], aggr=[SUM(lineitem.l_extendedprice * lineitem.l_discount)], metrics=[output_rows=2, elapsed_compute=1.550495ms, spill_count=0, spilled_bytes=0, mem_used=0]
        CoalesceBatchesExec: target_batch_size=8192, metrics=[output_rows=114160, elapsed_compute=1.228926ms, spill_count=0, spilled_bytes=0, mem_used=0]
          FilterExec: l_shipdate@3 >= 8766 AND l_shipdate@3 < 9131 AND l_discount@2 >= Some(5),15,2 AND l_discount@2 <= Some(7),15,2 AND l_quantity@0 < Some(2400),15,2, metrics=[output_rows=114160, elapsed_compute=20.476516ms, spill_count=0, spilled_bytes=0, mem_used=0]
            RepartitionExec: partitioning=RoundRobinBatch(2), input_partitions=1, metrics=[fetch_time=1.795540669s, repart_time=1ns, send_time=24.394149ms]
              CsvExec: files={1 group: [[Users/danielheres/Code/arrow-datafusion/benchmarks/tpch-dbgen/lineitem.tbl]]}, has_header=false, limit=None, projection=[l_quantity, l_extendedprice, l_discount, l_shipdate], metrics=[output_rows=6001215, elapsed_compute=1ns, spill_count=0, spilled_bytes=0, mem_used=0, time_elapsed_scanning_total=1.819781372s, time_elapsed_scanning_until_data=4.780458ms, time_elapsed_processing=1.79542109s, time_elapsed_opening=59.708µs]
```

**Comment by Dandandan** [comment]
Looks like multiplication is wrong for decimals:
https://github.com/apache/arrow-rs/issues/3645

**Comment by Dandandan** [comment]
Completed in main :)

**Pull request closed without merging**
