### PR TITLE
Automate postrelease publishing to Homebrew

### LINKED ISSUE #3506: Automate the pushing of releases to Homebrew
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

The release to Homebrew needs to be automated

**Describe the solution you'd like**

Modify the Homebrew post-release script in Arrow and add it.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by iajoiner**
# Which issue does this PR close?

Closes #3506.

 # Rationale for this change

# What changes are included in this PR?

`dev/release/publish_homebrew.sh`
# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by iajoiner** [comment]
@andygrove @alamb This will be in draft until DataFusion 13.0.0 gets released because we will test it then.

**Comment by andygrove** [comment]
Thanks @iajoiner. LGTM. Could you update the release instructions (`dev/release/README.md`) as well as part of this PR? Once that is done we should go ahead and merge this. If we hit any issues when releasing 13.0.0 we can PR any fixes needed.

**Comment by iajoiner** [comment]
@andygrove Sure! I will do that today.

**Comment by iajoiner** [comment]
@andygrove Here we go!

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @iajoiner. Could you fix the conflicts?

**Comment by iajoiner** [comment]
@andygrove Sure! Done!

**Pull request merged**
