### PR TITLE
FOLLOWUP: remove `optimize()`

### PR DESCRIPTION
**Pull request by jackwener**
# Which issue does this PR close?

Related to https://github.com/apache/arrow-datafusion/pull/4619

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
This PR appears to have many conflicts 🤔 

Screenshot 2022-12-14 at 3 29 14 PM

**Comment by jackwener** [comment]
a little strange some many conflict.
But I have fixed conflict, thanks @alamb remind.

**Review by tustvold — APPROVED** [review]
Due to the high-probability of further merge conflicts, I'm going to get this one in

**Comment by alamb** [comment]
🎉

**Comment by alamb** [comment]
> It's a little strange so many conflict. When I fix conflict, just exist 2 file conflict.😂

Github's UI is quite strange sometimes

**Pull request merged**
