### PR TITLE
Minior: Add negative tests about log function

### PR DESCRIPTION
**Pull request by caicancai**
## Which issue does this PR close?

Fractions in the log function are an important test because the results of 2.0/3 and 2/3 are completely different

### CODE REVIEW

**Comment by caicancai** [comment]
I have a question about log10(0). In arrow-datafusion, log10(0) returns infinity. From a mathematical point of view, I think there is no problem. However, I tested that mysql returns null and postgres returns error. , consider modifying the arrow-datafusion part

**Comment by gruuya** [comment]
> In arrow-datafusion, logX(0) returns -Infinity.
> consider modifying the arrow-datafusion part.

On a similar note the log with base zero returns zero
```sql
❯ select log(0, 3);
+------------------------+
| log(Int64(0),Int64(3)) |
+------------------------+
| 0.0                    |
+------------------------+

```
Mathematically that's undefined, while in Postgres/DuckDB it leads to an error (`cannot take logarithm of zero`).

**Comment by caicancai** [comment]
> > In arrow-datafusion, logX(0) returns -Infinity.
> > consider modifying the arrow-datafusion part.
> 
> On a similar note the log with base zero returns zero
> 
> ```sql
> ❯ select log(0, 3);
> +------------------------+
> | log(Int64(0),Int64(3)) |
> +------------------------+
> | 0.0                    |
> +------------------------+
> ```
> 
> Mathematically that's undefined, while in Postgres/DuckDB it leads to an error (`cannot take logarithm of zero`).



> Mathematically that's undefined, while in Postgres/DuckDB it leads to an error (`cannot take logarithm of zero`).

I think log2, log10, and log should be the same set of functions, which is fine, and maybe we all feel that the current handling of log10(0) could be improved

**Comment by Jefffrey** [comment]
FYI some relevant previous discussion/work on log:

- https://github.com/apache/arrow-datafusion/issues/5259
- https://github.com/apache/arrow-datafusion/pull/5316

**Comment by caicancai** [comment]
> FYI some relevant previous discussion/work on log:
> 
>     * [Make `log` function to be in sync with PostgresSql #5259](https://github.com/apache/arrow-datafusion/issues/5259)
> 
>     * [[DOC] Update math expression documentation  #5316](https://github.com/apache/arrow-datafusion/pull/5316)

Thank you for your reply. I'm sorry that I didn't notice the content in the document before.

**Review by alamb — APPROVED** [review]
Thank you @caicancai  for adding the tests to document this feature more fully in code

I am hoping this type of "what should `log` do in corner cases" will have a better story once we have done #8045 -- and thus if someone wants a different set of `log` function behavior they can just register a different `log` UDF

**Comment by caicancai** [comment]
> Thank you @caicancai for adding the tests to document this feature more fully in code
> 
> I am hoping this type of "what should `log` do in corner cases" will have a better story once we have done #8045 -- and thus if someone wants a different set of `log` function behavior they can just register a different `log` UDF

so cool, I think this is a very good idea, as a single sql engine can output the corresponding result expected by the user according to the user's custom behavior, which means that we do not need to adapt the negative test of each function in any dialect, but only need to concentrate on adapting most of the common functions

**Review by comphead — APPROVED** [review]
lgtm thanks @caicancai

**Pull request merged**
