### PR TITLE
substitute `parking_lot::Mutex` for `std::sync::Mutex`

### PR DESCRIPTION
**Pull request by xudong963**
# Which issue does this PR close?

As the title.

 # Rationale for this change

I did a simple benchmark and found there are some performance improvements.

|  query   | parking_lot::Mutex  | std::sync::Mutex |
|  ----  | ----  | ---- |
|  1 | 2889.14 ms | 2881.76 ms|
| 3  | 3047.44 ms |3079.82 ms|
| 5|2714.37 ms|2816.34 ms|
|6| 2469.22 ms|2529.96 ms|
|7| 4127.99 ms|4176.91 ms|
|10| 2664.02 ms|2806.26 ms|
|12|3519.28 ms|3580.24 ms|
|13| 728.52 ms|845.60 ms|

cc @alamb @houqp

### CODE REVIEW

**Comment by xudong963** [comment]
**cause**: I just I'm just wondering if `parking_lot` is really fast 😄 if really, I'll dig into it.
**procedure**: I use DF to do an experiment to verify my curiosity.
**result**: Performance has really improved, so I think we can use it!

**Comment by Dandandan** [comment]
Interesting, wasn't expecting we are using mutexes in performance critical areas - maybe that's also something to look into.

If we go down the route of using `parking_lot`, something to consider is also enabling the feature for `tokio`.

https://docs.rs/tokio/latest/tokio/#internal-features

**Review by alamb — APPROVED** [review]
Looks like a solid change to me. Nice work @xudong963 

Like @Dandandan  I am also interested in what performance critical code is using a `Mutex` so much that it shows up in the end to end timings. 

The only thing I saw in this PR that was even slightly suspicious is the use in `metrics` 🤔

**Comment by xudong963** [comment]
Me too @Dandandan @alamb. I'll do the performance analysis and find the performance-critical areas.

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @xudong963

**Pull request merged**
