### PR TITLE
Expose RowAccumulator in physical_plan

### LINKED ISSUE #3138: Make RowAccumulator public
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I'd like to implement `AggregateExpr` wrappers with side effects and it would be great if `RowAccumulator` is available outside the crate so that my wrapped `AggregateExpr`s can mirror the raw ones in Datafusion-related behavior.

**Describe the solution you'd like**
Make `RowAccumulator` public.

**Describe alternatives you've considered**
Currently I have to turn `RowAccumulator` off.

**Additional context**
None

### PR DESCRIPTION
**Pull request by iajoiner**
# Which issue does this PR close?

Closes #3138.

 # Rationale for this change

# What changes are included in this PR?

Expose RowAccumulator to the public in physical_plan so that other crates can implement `AggregateExpr` with that feature.

# Are there any user-facing changes?

Expose RowAccumulator to the public in physical_plan.

### CODE REVIEW

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @iajoiner !

**Review by alamb — COMMENTED** [review]
You may also want to consider a `pub use` in https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/physical_plan/mod.rs so you can use this directly from the `datafusion` crate (rather than having to use the `datafusion-physical-plan` crate as well)

**Comment by iajoiner** [comment]
@alamb Thanks! Actually that's precisely what I did. I think it is appropriate for `RowAccumulator` to be located where `Accumulator` is.

**Review by andygrove — APPROVED** [review]

**Comment by alamb** [comment]
> @alamb Thanks! Actually that's precisely what I did. I think it is appropriate for RowAccumulator to be located where Accumulator is.

🤦  -- I misread the diff 😢

**Pull request merged**
