### PR TITLE
Unvendor archery, clean up old files in dev

### PR DESCRIPTION
**Pull request by Jimexist**
# Which issue does this PR close?

Closes #.

following the changes at https://github.com/apache/arrow-rs/pull/459

 # Rationale for this change

install https://arrow.apache.org/docs/developers/archery.html from GitHub repo

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
This may also need this change: https://github.com/apache/arrow-rs/pull/482/files (as apparently the apache licence header check / RAT was calling archery)

**Comment by alamb** [comment]
I think this is a nice change -- however, it seems to delete everything in `dev` -- and it appears there may be some stuff in there that is used but not part of CI (e.g. the ballista docker files that were changed in https://github.com/apache/arrow-datafusion/pull/597)

@andygrove @edrevo  is there some place we can figure out what is used by Ballista?

**Comment by edrevo** [comment]
everything under `dev/docker` and `dev/integration-tests.sh`.

**Comment by Jimexist** [comment]
> everything under `dev/docker` and `dev/integration-tests.sh`.

i have brought back these files

**Review by alamb — APPROVED** [review]
I think this is a good change. Thank you @Jimexist

**Comment by alamb** [comment]
My apologies to anyone for whom this messes up their workflow. Onward! 🚀

**Comment by yjshen** [comment]
@Jimexist `dev/integration-tests.sh` relies on `./dev/build-ballista-docker.sh` and some other scripts transitively. They should be brought back. cc @alamb

**Comment by Jimexist** [comment]
> @Jimexist `dev/integration-tests.sh` relies on `./dev/build-ballista-docker.sh` and some other scripts transitively. They should be brought back. cc @alamb

see what i can do with https://github.com/apache/arrow-datafusion/pull/648

**Pull request merged**
