### PR TITLE
WIP: Remove redundant repartitioning

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/4925

See issue for full description of the problem that this PR resolves.

# Rationale for this change

Why repartition twice when we can repartition once?

## Test Approach

```bash
./target/release/tpch benchmark datafusion --format parquet --partitions 48 --path /mnt/bigdata/tpch/sf10-parquet/ --query 2 --iterations 10 --debug
```

## Before

Before this PR we have 2 instances of `RepartitionExec` in the plan for each table that is an input to a join.

```
CoalesceBatchesExec: target_batch_size=8192, metrics=[output_rows=0, elapsed_compute=20.396µs, spill_count=0, spilled_bytes=0, mem_used=0]
  RepartitionExec: partitioning=Hash([Column { name: "r_regionkey", index: 0 }], 48), metrics=[fetch_time=69.603684ms, send_time=48ns, repart_time=48ns]
    RepartitionExec: partitioning=RoundRobinBatch(48), metrics=[fetch_time=479.696µs, send_time=1ns, repart_time=1ns]
      CoalesceBatchesExec: target_batch_size=8192, metrics=[output_rows=0, elapsed_compute=320ns, spill_count=0, spilled_bytes=0, mem_used=0]
        FilterExec: r_name@1 = EUROPE, metrics=[output_rows=0, elapsed_compute=1ns, spill_count=0, spilled_bytes=0, mem_used=0]
          ParquetExec: ...
```

Query time before this PR:

```
Query 2 avg time: 479.53 ms
```

## After

With this PR we only have 1 instance of RepartitionExec

```
CoalesceBatchesExec: target_batch_size=8192, metrics=[output_rows=0, elapsed_compute=6.855µs, spill_count=0, spilled_bytes=0, mem_used=0]
  RepartitionExec: partitioning=Hash([Column { name: "r_regionkey", index: 0 }], 48), metrics=[fetch_time=322.318µs, send_time=1ns, repart_time=1ns]
    CoalesceBatchesExec: target_batch_size=8192, metrics=[output_rows=0, elapsed_compute=281ns, spill_count=0, spilled_bytes=0, mem_used=0]
      FilterExec: r_name@1 = EUROPE, metrics=[output_rows=0, elapsed_compute=1ns, spill_count=0, spilled_bytes=0, mem_used=0]
        ParquetExec: ...
```

Query time after this PR:

```
Query 2 avg time: 457.25 ms
```

# What changes are included in this PR?

New physical optimizer rule

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Dandandan** [comment]
The repartitioning isn't really redundant though? 
Suppose we only read from one parquet file and do repartition by hash after, we would gain parallelism by first doing a (fast) round robin partition, and a (slower) hash repartition which can now be parallelized.

The round robin repartitioning however would benefit from being also down the `FilterExec` in this case.

**Comment by andygrove** [comment]
> The repartitioning isn't really redundant though? Suppose we only read from one parquet file and do repartition by hash after, we would gain parallelism by first doing a (fast) round robin partition, and a (slower) hash repartition which can now be parallelized.

That's a good point. The round-robin partitioning is not so fast in Ballista because it introduces an extra query stage with shuffles. Maybe this optimization should just be added in Ballista rather than in DataFusion?

> 
> The round robin repartitioning however would benefit from being also down the `FilterExec` in this case, so the filtering can benefit from more parallelism as well.

Yes, I also just noticed that.

**Comment by andygrove** [comment]
I'm unsure now if there is value in continuing with this. Will give it some more thought.

**Comment by Dandandan** [comment]
As far as I remember we are removing the round robin repartitioning in Ballista? (so not introducing a new stage)

**Comment by andygrove** [comment]
Ballista already removes these round-robin repartitions so closing this

**Pull request closed without merging**
