### PR TITLE
impl binary ops between binary arrays and scalars

### LINKED ISSUE #3117: eq operator doesn't work on binary data
Hello,

I am trying to use datafusion to query multiple parquet files.

Comparing a binary column with binary literal using eq operator doesn't work.

I expect this to just work since eq works on strings. 

I have this code:
```rust
let address = prefix_hex::decode::<Vec<u8>>(&self.address).map_err(Error::InvalidHexInAddress)?;
let mut expr = col("log.address").eq(lit(address));
```
and I get this error:
```
failed to execute query:\nArrow error: External error: Arrow error: External error: Execution error: Arrow error: External error: Arrow error: External error: Execution error: Arrow error: External error:
Internal error: Data type Binary(\"161,250,161,19,203,229,52,54,223,40,255,10,238,84,39,92,19,180,9,117\") not supported for scalar operation 'eq' on dyn array.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

I tracked the error message to [here](https://github.com/apache/arrow-datafusion/blob/3eb55e9a0510d872f6f7765b1a5f17db46486e45/datafusion/physical-expr/src/expressions/binary.rs#L642)

Shouldn't there be a match arm for `Binary` data?

### PR DESCRIPTION
**Pull request by ozgrakkurt**
closes #3117

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you for the contribution @ozgrakkurt ! 

Looks like this PR has a clippy errors


Also, can you please add some tests for this? Specifically, it would be great to get an end to end test 

Perhaps: 
1. make a RecordBatch with a BinaryArray and LargeBinaryArray (like this example: https://github.com/apache/arrow-datafusion/blob/3eb55e9a0510d872f6f7765b1a5f17db46486e45/datafusion/row/src/lib.rs#L351)
2. Write a query that does `SELECT binary_col='foo', binary_col = other_binary_col, large_binary_col = 'bar', large_binary_col = other_large_binary_col`, following the model https://github.com/apache/arrow-datafusion/blob/834924f274d9e04444030b8eb3e07e1035fcd3cf/datafusion/core/tests/sql/functions.rs#L114-L143

Also, it appears that the `fmt` CI check has failed: https://github.com/apache/arrow-datafusion/runs/7839919855?check_suite_focus=true

to fix you probably need to run `cargo fmt` and check it in!

Thank you so much!

**Comment by alamb** [comment]
It looks like all this PR needs is some tests. @ozgrakkurt  is that something you can help with?

**Comment by ozgrakkurt** [comment]
Hey @alamb Sorry for late follow up, I was busy with my full time job,

Currently can't put binary literals into sql. Does creating a logical plan to test this sound ok?
Also where should I put this test?

**Comment by alamb** [comment]
> Hey @alamb Sorry for late follow up, I was busy with my full time job,


I totally understand -- no worries. I was out last week anyways :)

> Currently can't put binary literals into sql. Does creating a logical plan to test this sound ok?

I think that would be ok. An alternate would be to use a function that creates a `BinaryArray` such as `sha256`. So maybe something like this (untested):

```sql
select sha256('foo') = sha256('bar')
```

**Comment by ozgrakkurt** [comment]
@alamb apparently sha functions also only accept string. created an issue here: https://github.com/apache/arrow-datafusion/issues/3308

**Comment by ozgrakkurt** [comment]
I suggest I add support for binary to those functions in this PR as well (which should be easy) and create the test using them

**Comment by ozgrakkurt** [comment]
closes #3308

**Comment by ozgrakkurt** [comment]
@alamb should be ready to review

**Review by alamb — APPROVED** [review]
Looks good to me

**Comment by ozgrakkurt** [comment]
@alamb committing fix for digest function signature and formatting errors

**Comment by ozgrakkurt** [comment]
@alamb sorry, can you review again

**Comment by ozgrakkurt** [comment]
tests are failing because of https://github.com/apache/arrow-datafusion/issues/3327

**Comment by ozgrakkurt** [comment]
@alamb can you merge this when you have time?

**Review by alamb — APPROVED** [review]
Thanks @ozgrakkurt

**Pull request merged**
