### PR TITLE
[MINOR] Update arrow-rs dependencies

### PR DESCRIPTION
**Pull request by alamb**
Bring in the latest arrow-rs branch

I will eventually automate this process, but for now I will do it manually.

### CODE REVIEW

**Review by jorgecarleitao — APPROVED** [review]
Doing it manually is also fine; this is easy this time because there weren't any backward incomp. changes.

**Comment by Dandandan** [comment]
@alamb I think you also need to update the other crates

**Comment by alamb** [comment]
>  @alamb I think you also need to update the other crates
Good call @Dandandan  will do

**Comment by andygrove** [comment]
Please take a look at the related https://github.com/apache/arrow-datafusion/pull/23

**Comment by andygrove** [comment]
@alamb Would it make sense for DataFusion to re-export Arrow so that dependent crates automatically get the same Arrow version?

**Comment by returnString** [comment]
> @alamb Would it make sense for DataFusion to re-export Arrow so that dependent crates automatically get the same Arrow version?

This would make things much easier for consumers, +1 from me :)

On the automation front, has anyone else used Dependabot for this kind of thing before? I've started using it recently for Python, Rust, and the actual actions in my GHA workflows, and it's really nice, e.g. [open dependency PRs for my convergence crates](https://github.com/reservoirdb/convergence/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies) as defined with some [trivial metadata](https://github.com/reservoirdb/convergence/blob/main/.github/dependabot.yml).

**Comment by alamb** [comment]
> @alamb Would it make sense for DataFusion to re-export Arrow so that dependent crates automatically get the same Arrow version?
> This would make things much easier for consumers, +1 from me :)

Good idea @andygrove  and @returnString  -- I filed https://github.com/apache/arrow-datafusion/issues/36 to do so

> On the automation front, has anyone else used Dependabot for this kind of thing before? 

I have not, but it sounds like a good idea to me. Filed https://github.com/apache/arrow-datafusion/issues/37

**Pull request merged**
