### PR TITLE
fix: return error for  unsupported SQL

### LINKED ISSUE #3873: Default physical planner generates empty relation for DROP TABLE, CREATE MEMORY TABLE, etc
**Describe the bug**
When we ran some unsupported DDL in our system

```sql
drop table foo
```

The output would be an empty table (rather than an unsupported error):
```
++
++
```

However, running `CREATE EXTERNAL TABLE` results in an error as expected.

**To Reproduce**
Try and run `drop table` (not through the datafusion CLI which handles these `LogicalPlan` variants specially)

**Expected behavior**
The physical planner should generate an error for DDL statements that have a `LogicalPlan` variant as it does for `CREATE EXTERNAL TABLE` 

https://github.com/apache/arrow-datafusion/blob/b654fdea697b9aec1cb487e292dd288e5c9d09e3/datafusion/core/src/physical_plan/planner.rs#L1024-L1057

**Additional context**
We saw this in IOx https://github.com/influxdata/influxdb_iox/issues/5802 and worked around it in https://github.com/influxdata/influxdb_iox/pull/5876 by explicitly generating the errors

### PR DESCRIPTION
**Pull request by Kikkon**
# Which issue does this PR close?

Closes #3873 

 # Rationale for this change

Refer to this issue #3873 

# What changes are included in this PR?

Make some unsupported SQL queries return errors
# Are there any user-facing changes?

no.

### CODE REVIEW

**Comment by alamb** [comment]
Looks good @Kikkon  -- thank you!

Is there any chance you can write some tests for this code?

**Comment by Kikkon** [comment]
> Is there any chance you can write some tests for this code?

Sure, I will add tests later.

**Review by xudong963 — APPROVED** [review]
Thanks @Kikkon

**Comment by Kikkon** [comment]
Some tests related to create view depend on physical plan & logical plan, change to use only logical plan

**Review by alamb — APPROVED** [review]
Looks great -- thank you @Kikkon

**Pull request merged**
