### PR TITLE
remove hard coded partition count in ballista logicalplan deserialization

### PR DESCRIPTION
**Pull request by xudong963**
# Which issue does this PR close?

Closes #https://github.com/apache/arrow-datafusion/pull/972

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by houqp — APPROVED** [review]
cc @rdettai @yjshen

**Comment by houqp** [comment]
Looks like we only changed the function argument name, so it should be backwards compatible :+1:

**Comment by rdettai** [comment]
Looks great! I still find the `target_partitions` a bit confusing. Could we maybe add more details to the comments in `ExecutionConfig` ? Thanks for your work!

**Review by alamb — APPROVED** [review]
I think this looks great -- thank you @xudong963  !

Adding some more doc strings would be useful as @rdettai  but I think it can also be done as a follow on PR. 

Thanks again for sticking with this

**Comment by xudong963** [comment]
Thanks for your help!
 Looking forward to contributing more PRs.

**Comment by xudong963** [comment]
> Could we maybe add more details to the comments in `ExecutionConfig`?

/// Number of partitions for query execution. Increasing partitions may increase concurrency.
/// The partition number can be much larger than the parallelism, then tasks for extra partitions will be queued.
/// So increasing partitions don't increase concurrency in the situation.

Please help me check if the comments are correct and detail @rdettai, I will add it in the next PR.

**Comment by rdettai** [comment]
I think that the current DataFusion default collection method does start all the tasks in parallel. I will try to go through all the places where the parameter is used to try to synthesize more precisely what it means.

**Pull request merged**
