### PR TITLE
Add hash_join_single_partition_threshold_rows config

### LINKED ISSUE #8405: `collection_size_threshold` incorrectly used in `supports_collect_by_size`
### Describe the bug

In `supports_collect_by_size`, `collection_size_threshold` to compare the threshold for both `total_byte_size` (correct), but incorrectly as fallback for `num_rows`.
This leads to large planning differences for when estimated size is / is not available.

### To Reproduce

Read the code.

### Expected behavior

As a first step, introduce `hash_join_single_partition_threshold_rows`, being number of times (e.g. 10x) smaller than the number of bytes. Adapt `hash_join_single_partition_threshold` as well (may need to increase it).

We also can improve the estimation of size by improving the estimation. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by maruschin**
## Which issue does this PR close?

Closes #8405.

### CODE REVIEW

**Comment by alamb** [comment]
@korowa  may also be interested in this

**Comment by Dandandan** [comment]
Change looks good to me in general, could you also update the tests @maruschin so we can check the new behavior?

**Comment by maruschin** [comment]
Hi @Dandandan, I fixed the tests and refactored variables, making the names more explicit.

In general, the tests have not changed.
We apparently do not test the case when there is no statistics in bytes and there are statistics in rows.

**Comment by alamb** [comment]
@Dandandan as the author of https://github.com/apache/arrow-datafusion/issues/8405 would you possibly have time to review this PR again? If not I will find time to do so

**Comment by Dandandan** [comment]
To me the change looks good, I think it makes sense to run the (TPC-H) benchmarks once more to catch regressions.

**Comment by alamb** [comment]
> To me the change looks good, I think it makes sense to run the (TPC-H) benchmarks once more to catch regressions.

I will do so

**Comment by alamb** [comment]
I merged this branch with `main` and am running tests on it now

**Comment by alamb** [comment]
Here is the result of the benchmarks when I ran them. My conclusion is that there is no measurable difference in performance due to this branch so it should be good to go

```
--------------------
Benchmark tpch.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃ main_base ┃ collect_fix ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 1     │  327.85ms │    328.00ms │     no change │
│ QQuery 2     │   93.09ms │     94.13ms │     no change │
│ QQuery 3     │  172.44ms │    168.23ms │     no change │
│ QQuery 4     │  102.36ms │     98.83ms │     no change │
│ QQuery 5     │  199.92ms │    210.24ms │  1.05x slower │
│ QQuery 6     │   95.04ms │     97.14ms │     no change │
│ QQuery 7     │  269.17ms │    282.54ms │     no change │
│ QQuery 8     │  241.80ms │    225.48ms │ +1.07x faster │
│ QQuery 9     │  357.00ms │    286.67ms │ +1.25x faster │
│ QQuery 10    │  324.27ms │    278.82ms │ +1.16x faster │
│ QQuery 11    │   76.61ms │     79.25ms │     no change │
│ QQuery 12    │  155.77ms │    161.19ms │     no change │
│ QQuery 13    │  325.53ms │    346.48ms │  1.06x slower │
│ QQuery 14    │  127.94ms │    126.09ms │     no change │
│ QQuery 15    │  151.43ms │    167.27ms │  1.10x slower │
│ QQuery 16    │  103.59ms │    104.93ms │     no change │
│ QQuery 17    │  291.58ms │    306.44ms │  1.05x slower │
│ QQuery 18    │  469.92ms │    394.92ms │ +1.19x faster │
│ QQuery 19    │  201.67ms │    205.44ms │     no change │
│ QQuery 20    │  161.96ms │    159.41ms │     no change │
│ QQuery 21    │  323.94ms │    330.82ms │     no change │
│ QQuery 22    │   80.45ms │     82.82ms │     no change │
└──────────────┴───────────┴─────────────┴───────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Benchmark Summary          ┃           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ Total Time (main_base)     │ 4653.33ms │
│ Total Time (collect_fix)   │ 4535.15ms │
│ Average Time (main_base)   │  211.51ms │
│ Average Time (collect_fix) │  206.14ms │
│ Queries Faster             │         4 │
│ Queries Slower             │         4 │
│ Queries with No Change     │        14 │
└────────────────────────────┴───────────┘

--------------------
Benchmark tpch.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃ main_base ┃ collect_fix ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 1     │  327.85ms │    328.00ms │     no change │
│ QQuery 2     │   93.09ms │     94.13ms │     no change │
│ QQuery 3     │  172.44ms │    168.23ms │     no change │
│ QQuery 4     │  102.36ms │     98.83ms │     no change │
│ QQuery 5     │  199.92ms │    210.24ms │  1.05x slower │
│ QQuery 6     │   95.04ms │     97.14ms │     no change │
│ QQuery 7     │  269.17ms │    282.54ms │     no change │
│ QQuery 8     │  241.80ms │    225.48ms │ +1.07x faster │
│ QQuery 9     │  357.00ms │    286.67ms │ +1.25x faster │
│ QQuery 10    │  324.27ms │    278.82ms │ +1.16x faster │
│ QQuery 11    │   76.61ms │     79.25ms │     no change │
│ QQuery 12    │  155.77ms │    161.19ms │     no change │
│ QQuery 13    │  325.53ms │    346.48ms │  1.06x slower │
│ QQuery 14    │  127.94ms │    126.09ms │     no change │
│ QQuery 15    │  151.43ms │    167.27ms │  1.10x slower │
│ QQuery 16    │  103.59ms │    104.93ms │     no change │
│ QQuery 17    │  291.58ms │    306.44ms │  1.05x slower │
│ QQuery 18    │  469.92ms │    394.92ms │ +1.19x faster │
│ QQuery 19    │  201.67ms │    205.44ms │     no change │
│ QQuery 20    │  161.96ms │    159.41ms │     no change │
│ QQuery 21    │  323.94ms │    330.82ms │     no change │
│ QQuery 22    │   80.45ms │     82.82ms │     no change │
└──────────────┴───────────┴─────────────┴───────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Benchmark Summary          ┃           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ Total Time (main_base)     │ 4653.33ms │
│ Total Time (collect_fix)   │ 4535.15ms │
│ Average Time (main_base)   │  211.51ms │
│ Average Time (collect_fix) │  206.14ms │
│ Queries Faster             │         4 │
│ Queries Slower             │         4 │
│ Queries with No Change     │        14 │
└────────────────────────────┴───────────┘
```

**Review by alamb — APPROVED** [review]
Thanks agian @maruschin

**Comment by Dandandan** [comment]
Thanks for checking it @alamb and for the PR @maruschin

**Pull request merged**
