### PR TITLE
MINOR: Enable multi-statement benchmark queries

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

N/A

 # Rationale for this change

q15.sql contains two SQL statements and this was not supported by the benchmark runner

# What changes are included in this PR?

Support multiple queries per file

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by matthewmturner** [comment]
When running Q15 do we get a new error now? Something like `CREATE VIEW` isnt implemented?

**Comment by matthewmturner** [comment]
If we get this merged first i can enable Q15 in #2279

**Comment by andygrove** [comment]
> When running Q15 do we get a new error now? Something like `CREATE VIEW` isnt implemented?

Yes, exactly that!

**Comment by andygrove** [comment]
> LGTM.
> 
> An off-topic question: I've noticed there were instructions on how to [get golden files](https://github.com/apache/arrow-datafusion/pull/34/files#diff-576c27794bae284efc278336a16d0649aaf599973a64d4b65dc67bc99bb7f000L37-L40) and get results verified but removed before. Do you think it's the time to add goldens and enable `verify_query` [here](https://github.com/apache/arrow-datafusion/blob/master/benchmarks/src/bin/tpch.rs#L914) for tpc-h?
> 
> Currently, these tests are skipped `TPCH_DATA environment variable not set, skipping test `

The current approach is for developers to use the tpch toolkit to generate the expected answers locally and then set this env var to enable those tests. It would be nice if we could enable CI to do this as well.

**Pull request merged**
