### PR TITLE
Use code points instead of grapheme clusters for string functions

### LINKED ISSUE #3049: Simplify / speed up implementation of character_length to unicode points
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
It looks like postgresql and spark have a different, (probably much faster) implementation of calculating the string length, which doesn't depend on calculating the grapheme clusters, but on utf8 code points.

As an example: `select length('ä')`
PostgreSQL | Spark | DataFusion
| Postgres | Spark | DataFusion |
|----------|-------|------------|
| 2        | 2     | 1          |

**Describe the solution you'd like**
Probably `.chars().count()` is a faster solution and matches the implementation of PostgreSQL (and Spark).
It can be applied to other string functions as well.

**Describe alternatives you've considered**
Accepting our own implementation being slower but "superior" to other solutions.

**Additional context**
This came up as being quite slow when profiling this benchmark: https://github.com/DataPsycho/data-pipelines-in-rust/tree/main/amazon_review_pipeline 
We're using the `grapheme` option in other places as well, maybe here we could use the faster

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #3049

 # Rationale for this change

Matching PostgreSQL, Spark and  improve performance. Overall simplification.

# What changes are included in this PR?

Moves most functions, except `rpad`, `lpad` and `translate` to use code points rather than grapheme clusters.
Also code simplification & avoiding some allocations.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
cc @ovr

**Comment by Dandandan** [comment]
@alamb @andygrove this is reviewable now.

**Comment by andygrove** [comment]
LGTM. I assume there should be a documentation update as well as part of this PR? Perhaps the rustdoc for `fn character_length` should explain how this is now implemented?

**Review by alamb — APPROVED** [review]
Looks like a nice simplification and improvement to me ❤️  Thank you @Dandandan 

cc @ovr  who I think contributed the original implementation

**Comment by ovr** [comment]
> cc @ovr who I think contributed the original implementation

LGTM, but I am not an original author 😄

**Comment by Dandandan** [comment]
I think this was @seddonm1

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @Dandandan

**Comment by devanshu0987** [comment]
Hi @Dandandan OR @alamb, is it possible to share historical reasons as to why lpad and rpad were not covered in this PR? 
Should we make this contract change and make it Postgres compatible, or is this a deliberate choice?

For lpad, 3 arguments, `(string, length, fill)`: string is split on Grapheme clusters, and fill is iterated on code points.
While, as you mentioned, Postgres has code point splits for both `string` and `fill` equivalents.

`datafusion/functions/src/unicode/lpad.rs`
```
let graphemes = string.graphemes(true).collect::<Vec<&str>>();
let fill_chars = fill.chars().collect::<Vec<char>>();
```

Datafusion result
```
> select lpad('á', 1);
+--------------------------+
| lpad(Utf8("á"),Int64(1)) |
+--------------------------+
| á                        |
+--------------------------+
1 row(s) fetched. 
Elapsed 0.075 seconds.
```

Postgres result
```
select lpad('á', 1);

"lpad"
"a"
```

**Comment by alamb** [comment]
I don't know that there was any reason not to include `lpad` / `rpad` (I don't think it was a deliberate choice)

**Pull request merged**
