### PR TITLE
Remove the PhysicalSortExpr restriction on union get meet

### LINKED ISSUE #6272: Remove the PhysicalSortExpr restriction on union get meet
### Is your feature request related to a problem or challenge?

Union get meet can only consider sort option and corresponding vector index during comparison. No need to check for PhysicalExpr equality.

### Describe the solution you'd like

If the PhysicalSortExpr's can be downcasted to Column, compare the Column's indexes and sort options. Otherwise, the existing comparison can be sustained.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by berkaysynnada**
# Which issue does this PR close?

Closes #6272 .

# Rationale for this change

Union get meet can only consider sort option and corresponding vector index during comparison. No need to check for PhysicalExpr equality.

# What changes are included in this PR?

If the PhysicalSortExpr's can be downcasted to Column, compare the Column's indexes and sort options. Otherwise, the existing comparison is sustained.

# Are these changes tested?

Existing tests are sufficient.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by mingmwang** [comment]
Nice optimization

**Comment by mingmwang** [comment]
@berkaysynnada 

Can you extend the optimization to non-column cases?

For example

```sql
select a + b from table_2 order by a + b
union all
select x + y from table_2  order by x + y
```

**Comment by berkaysynnada** [comment]
> 

My last commit can succeed in the cases of your example. However, for the cases like (a+b+c), the build order of the binary expression is important. We can get false negative results. Actually, I think this is a general problem with binary expression structure.

**Comment by berkaysynnada** [comment]
> @berkaysynnada
> 
> Can you extend the optimization to non-column cases?
> 
> For example
> 
> ```sql
> select a + b from table_2 order by a + b
> union all
> select x + y from table_2  order by x + y
> ```



> @berkaysynnada
> 
> Can you extend the optimization to non-column cases?
> 
> For example
> 
> ```sql
> select a + b from table_2 order by a + b
> union all
> select x + y from table_2  order by x + y
> ```

My last commit can succeed in the cases of your example. However, for the cases like a+b+c (having two or more depth), the build order of the binary expression is important. We can get false negative results. Actually, I think this is a general problem with binary expressions in Datafusion.

**Review by alamb — COMMENTED** [review]
Is there and SQL / plan level test that could be written that would cover this code? It seems like a neat optimization but I don't fully understand how to map it to how it would affect queries

**Comment by berkaysynnada** [comment]
> Is there and SQL / plan level test that could be written that would cover this code? It seems like a neat optimization but I don't fully understand how to map it to how it would affect queries

This PR optimizes the plan such:
```
query TT
explain
SELECT c1 FROM(
(   
    SELECT c1 FROM t1
)  
UNION ALL
(   
    SELECT c1a FROM t2
))
ORDER BY c1
----
logical_plan
  Sort: t1.c1 ASC NULLS LAST
    Union
      TableScan: t1 projection=[c1]
      Projection: t2.c1a AS t1.c1
        TableScan: t2 projection=[c1a]
physical_plan
  SortPreservingMergeExec: [c1@0 ASC NULLS LAST]
    UnionExec
      CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/testing/data/csv/aggregate_test_100.csv]]}, projection=[c1], output_ordering=[c1@0 ASC NULLS LAST], has_header=true
        ProjectionExec: expr=[c1a@0 as t1.c1]
      CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/testing/data/csv/aggregate_test_100.csv]]}, projection=[c1a], output_ordering=[c1a@0 ASC NULLS LAST], has_header=true
```

However, the main version results such:
```
logical_plan
  Sort: t1.c1 ASC NULLS LAST
    Union
      TableScan: t1 projection=[c1]
      Projection: t2.c1a AS t1.c1
        TableScan: t2 projection=[c1a]
physical_plan
  SortPreservingMergeExec: [c1@0 ASC NULLS LAST]
    UnionExec
      CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/testing/data/csv/aggregate_test_100.csv]]}, projection=[c1], output_ordering=[c1@0 ASC NULLS LAST], has_header=true
      SortExec: expr=[c1@0 ASC NULLS LAST]
        ProjectionExec: expr=[c1a@0 as t1.c1]
          CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/testing/data/csv/aggregate_test_100.csv]]}, projection=[c1a], output_ordering=[c1a@0 ASC NULLS LAST], has_header=true
```

**Review by ozankabak — APPROVED** [review]
I went over the code and checked in a commit simplifying it a little bit.

It looks good to me at this point, feel free to merge when you like.

**Comment by alamb** [comment]
Thanks @berkaysynnada and @ozankabak

**Comment by alamb** [comment]
For some reason github claims this PR has conflicts that must be resolved 🤔  since I can't push changes to your branch to resolve this myself, @ozankabak  or @berkaysynnada  can you please resolve the problem? I will then merge it

Screenshot 2023-05-09 at 7 45 10 PM

**Comment by ozankabak** [comment]
Done, thank you

**Review by mingmwang — APPROVED** [review]
LGTM

**Pull request merged**
