### PR TITLE
Prepare 30.0.0 release

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

N/A

## Rationale for this change

Time for a new release

## What changes are included in this PR?

- Bump version
- [Changelog](https://github.com/andygrove/arrow-datafusion/blob/prep-30/dev/changelog/30.0.0.md)

### CODE REVIEW

**Comment by andygrove** [comment]
configs.md check is failing:

```
-| datafusion.execution.parquet.created_by                    | datafusion version 29.0.0 | Sets "created by" property                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+| datafusion.execution.parquet.created_by                    | datafusion version 30.0.0 | Sets "created by" property    
```

**Comment by alamb** [comment]
I merged up from main to resolve a conflict

**Review by alamb — APPROVED** [review]
LGTM -- thanks @andygrove

**Comment by vincev** [comment]
I have noticed [crates.io](https://crates.io/crates/datafusion) is showing 0.28, will you publish 0.30?

**Comment by alamb** [comment]
There was a problem publishing `29.0.0`: https://github.com/apache/arrow-datafusion/issues/7281


`30.0.0` is out for approval and is waiting the ASF mandated 3 day waiting period prior to publishing: https://lists.apache.org/thread/bb4jk3pzqptkcz1vmmo7yvnoo9xwfjkq

So hopefully `0.30.0` should be on crates.io soon

**Pull request merged**
