### PR TITLE
[maint-16.x] Prep for release

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Part of https://github.com/apache/arrow-datafusion/issues/4948

# Rationale for this change

Patch release to fix regressions

# What changes are included in this PR?

Bump version numbers

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by andygrove** [comment]
@jonmmease @alamb PTAL

I could not get the changelog script to generate an accurate changelog for this patch release and do not have time to debug that right now.

**Comment by andygrove** [comment]
I filed https://github.com/apache/arrow-datafusion/issues/4985 for the changelog issue. I will look at this when I have more time.

**Comment by alamb** [comment]
> I filed https://github.com/apache/arrow-datafusion/issues/4985 for the changelog issue. I will look at this when I have more time.

Maybe for this release we can make the changelog manually given there are only a few PRs that went in

**Review by alamb — APPROVED** [review]
LGTM

**Pull request merged**
