### PR TITLE
move InList related simplify to one place

### LINKED ISSUE #8970: Additional `IN` / `NOT IN` simplifications
In the following on PR, I think we can move inlist related simplifier logic to `inlist_simplifier`.
Steps in inlist_simplifier
1. early stage simplification like `expr IN () --> false`, `null IN/NOT IN`
2. convert long OR chain or AND chain to InList expressions like what `or_in_list_simplifier` does
3. shorten InList expressions like what `inlist_simplifier` in this PR does
4. convert final inlist to OR chain or AND chain if len < 3. Move inlist related simplifier out from `expr_simplifier`

In this way, when the logic grows more complex, we can easily find out related conversion about specific Expr

_Originally posted by @jayzhan211 in https://github.com/apache/arrow-datafusion/issues/8949#issuecomment-1906115890_

### PR DESCRIPTION
**Pull request by guojidan**
## Which issue does this PR close?

Part of #8970.

## Rationale for this change

move all InList related simplify to one place

## Are these changes tested?

no

## Are there any user-facing changes?

no

### CODE REVIEW

**Comment by alamb** [comment]
Hi @guojidan  -- I wonder if you are still working on this PR? What do you think about moving all the rewrites into the same pass?

**Comment by guojidan** [comment]
> Hi @guojidan -- I wonder if you are still working on this PR? What do you think about moving all the rewrites into the same pass?

all rewrites means all `inlist` rewrites?

**Comment by alamb** [comment]
> all rewrites means all inlist rewrites?

Yes, sorry this is what i meant -- all the InList code

**Review by alamb — APPROVED** [review]
Thank you @guojidan  -- this looks good to me. I think as a follow on PR it would be nice to consolidate all the `InList` rewrites into a single pass (rather than `ShortenInListSimplifier` and `InListSimplifier` but this PR seems like a good step in that direction

Thanks again@

**Comment by alamb** [comment]
In my opinion we could merge this PR or if you prefer you could consolidate the passes into a single Struct as part of this PR as well. Let me know what you you prefer.

**Comment by guojidan** [comment]
> In my opinion we could merge this PR or if you prefer you could consolidate the passes into a single Struct as part of this PR as well. Let me know what you you prefer.

Hi @alamb , consolidate `ShortenInListSimplifier` and `InListSimplifier` need more time(because they will have logical conflicts), So I want deal them in other PR 😄

**Comment by alamb** [comment]
Thanks again @guojidan !

**Pull request merged**
