### PR TITLE
Parquet limit pushdown (#5404)

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

Relates to #5404

# Rationale for this change

https://github.com/apache/arrow-rs/pull/3633 added the ability to push down limits to the parquet reader. This is particularly important when filter pushdown is enabled on `ParquetOptions` (soon to be default), as it allows the limit to be applied before late materialization, which has significant performance benefits

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you @tustvold  -- it would be nice to have a test for this, but I am not sure there is any way to test this really (other than performance benchmarks).

**Review by jackwener — APPROVED** [review]
A nice job. Thank you @tustvold

**Comment by jackwener** [comment]
> Thank you @tustvold -- it would be nice to have a test for this, but I am not sure there is any way to test this really (other than performance benchmarks).

There is tpch in the current benchmarks, we may consider adding clickbench?

**Comment by alamb** [comment]
> There is tpch in the current benchmarks, may we consider adding clickbench?

It is a good idea @jackwener  -- I have it on my list this week to do some more organizing related to benchmarking. I definitely agree that clickbench would be super helpful

**Pull request merged**
