### PR TITLE
doc: fix site sidebar logo position

### LINKED ISSUE #5935: doc site sidebar icon is glitched/bugged
### Describe the bug

On documentation site: https://arrow.apache.org/datafusion/index.html

Sidebar is glitched with the logo at the bottom obscuring links, see:

image

(this is bottom of page)

Can't see contributor guide links, unless expand another menu which then pushes them into visibility:

image

Can reproduce by adjusting size of browser window, can see the datafusion logo kinda floats around:

image

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

Firefox on linux

### PR DESCRIPTION
**Pull request by Jefffrey**
# Which issue does this PR close?

Closes #5935

# Rationale for this change

Fix site sidebar logo position to respect the scrolling sidebar and always remain below it (and not overlap)

# What changes are included in this PR?

Example:

image

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Jefffrey** [comment]
Web design isn't my forte but this seems to solve the issue

**Review by alamb — APPROVED** [review]
>  Web design isn't my forte 

😆  me neither -- I am well out of my league here.

I tested locally and when i had the screen fairly small with this change there was no padding around the logio


# https://arrow.apache.org/datafusion/
Screenshot 2023-04-13 at 2 32 22 PM

# This PR
Screenshot 2023-04-13 at 2 32 53 PM

That being said, when there was enough width things seemed to be good with this PR

Screenshot 2023-04-13 at 2 36 37 PM

So I think while not perfect this is a step in the right direction. Thank you @Jefffrey

**Review by jackwener — APPROVED** [review]
Thank you @Jefffrey

**Comment by Jefffrey** [comment]
Padding added to left & right sides now

image

cc @alamb

**Comment by alamb** [comment]
I took it for a spin locally, and it worked great. Thank you @Jefffrey !

**Pull request merged**
