### PR TITLE
fix: skip EliminateCrossJoin rule if inner join with filter is found

### LINKED ISSUE #7530: Incorrect results for nested joins after applying EliminateCrossJoin rule
### Describe the bug

This bug is very similar to #4844 - The EliminateCrossJoin rule discards the Filter rules of InnerJoin.
The fix for the previous bug (#4869) was to skip the rule if an InnerJoin with a Filter was found.
Unfortunately the fix only checks the top InnerJoin, so nested InnerJoins are not checked and might lose their filter condition 

### To Reproduce

Add the below test to eliminate_cross_join.rs:

```rs
    #[test]
    fn eliminate_cross_not_possible_nested_inner_join_with_filter() -> Result<()> {
        let t1 = test_table_scan_with_name("t1")?;
        let t2 = test_table_scan_with_name("t2")?;
        let t3 = test_table_scan_with_name("t3")?;

        // could not eliminate to inner join with filter
        let plan = LogicalPlanBuilder::from(t1)
            .join(
                t3,
                JoinType::Inner,
                (vec!["t1.a"], vec!["t3.a"]),
                Some(col("t1.a").gt(lit(20u32))),
            )?
            .join(t2, JoinType::Inner, (vec!["t1.a"], vec!["t2.a"]), None)?
            .filter(col("t1.a").gt(lit(15u32)))?
            .build()?;

        let formatted = plan.display_indent_schema().to_string();
        let before_optimization: Vec<&str> = formatted.trim().lines().collect();

        assert_optimized_plan_eq(&plan, before_optimization);

        Ok(())
    }
```

The test will fail in `assert_optimized_plan_eq` with this error:
```
expected:

[
    "Filter: t1.a > UInt32(15) [a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32]",
    "  Inner Join: t1.a = t2.a [a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32]",
    "    Inner Join: t1.a = t3.a Filter: t1.a > UInt32(20) [a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32]",
    "      TableScan: t1 [a:UInt32, b:UInt32, c:UInt32]",
    "      TableScan: t3 [a:UInt32, b:UInt32, c:UInt32]",
    "    TableScan: t2 [a:UInt32, b:UInt32, c:UInt32]",
]
actual:

[
    "Filter: t1.a > UInt32(15) [a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32]",
    "  Inner Join: t1.a = t2.a [a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32]",
    "    Inner Join: t1.a = t3.a [a:UInt32, b:UInt32, c:UInt32, a:UInt32, b:UInt32, c:UInt32]",
    "      TableScan: t1 [a:UInt32, b:UInt32, c:UInt32]",
    "      TableScan: t3 [a:UInt32, b:UInt32, c:UInt32]",
    "    TableScan: t2 [a:UInt32, b:UInt32, c:UInt32]",
]
```
expected is the plan before the optimization is applied and actual is the plan after the optimization is applied.
You can see nested Inner join filter was incorrectly dismissed (t1.a > UInt32(20))

### Expected behavior

In case the InnerJoin has a Filter the rule should be skipped or optimized correctly

### Additional context

#4866 will probably fix this bug but I think a quicker fix is needed to be applied here in order to regain query results correctness.

### PR DESCRIPTION
**Pull request by epsio-banay**
## Which issue does this PR close?

Closes #7530

## Rationale for this change

Explained in issue

## What changes are included in this PR?

EliminateCrossJoin optimization rule should be skipped for InnerJoin with filter, this PR fixes a bug were nested InnerJoins with filter do not cause the rule to be skipped.

## Are these changes tested?

yes see `eliminate_cross_not_possible_nested_inner_join_with_filter`

## Are there any user-facing changes?

There are no API changes but query results might differ.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you for the contribution @epsio-banay -- @jackwener  or @liukun4515  would you have time to review this PR?

**Comment by jackwener** [comment]
Thanks @epsio-banay , good catch.

I will review this PR carefully tomorrow.

BTW, I'm thinking about this whole method. I think we don't need differentiate between handling equal conditions and non-equal conditions, because multi join is a Query Graph, both equal conditions and non-equal conditions are edges in Graph. But I also think this is a longer -term problem.

**Review by jackwener — APPROVED** [review]
Thanks @epsio-banay , good catch!

LGTM.

BTW, I'm thinking about this whole method. I think we don't need differentiate between handling equal conditions and non-equal conditions, because multi join is a Query Graph and both equal conditions and non-equal conditions are edges in Graph. But I also think this is a longer-term problem. I prepare to do this job in 1-2 weeks.

**Comment by alamb** [comment]
>  because multi join is a Query Graph and both equal conditions and non-equal conditions are edges in Graph. But I also think this is a longer-term problem. I prepare to do this job in 1-2 weeks.

Representing the joins in a query as a JoinGraph would be very interesting. I wonder if you have an idea of where would it be done? 

It could be as a pass prior to the LogicalPlan:
```
sql text --> Sql AST --> JoinGraph --> LogicalPlan
```

or you could do it as part of an optimization pass,  like  this:

```
sql text --> Sql AST  --> LogicalPlan --(optimize with JoinGraph) --> LogicalPlan
```

**Comment by jackwener** [comment]
#7549 to trace it

**Comment by jackwener** [comment]
> Representing the joins in a query as a JoinGraph would be very interesting. I wonder if you have an idea of where would it be done?

Because we just want to rearrange `Inner/Outer join`, Use `MultiJoin` is enough.

```
          MultiJoin
       /    |    |    \
child   child   child   child .....
```

**Comment by alamb** [comment]
🤔   would a multi-join work for a query like

```sql
SELECT ..
  FROM A JOIN B ON (a.x=b.x)
     JOIN C ON (a.y = c.y AND b.z = c.z)
```

A join graph might look like this

```
(A) -- y -- (B)
   \       /
    x     z
     \   /
      (C)
```

Would a multi-join look like
```
JOIN (a.x=b.x, a.y=c.y, b.z=c.z)
  (A, B, C)
```

I guess then any reordering could happen as a translation from Multi-join to binary join 🤔

**Pull request merged**
