### PR TITLE
Fix code generation for json feature

### LINKED ISSUE #3366: Intermittent build error when changing selected features
**Describe the bug**

Now that codegen has been moved into the `proto/src/datafusion.rs` file, that file can have two different sets of contents depending on whether or not the `json` feature is selected (which some CI build & test have each way). When the feature flags are changed, the contents aren't necessarily regenerated, causing intermittent build issues.

**To Reproduce**

Run a regular build, then try to run the extra-long cargo check command from CI:

```
cargo check --workspace --benches --features avro,jit,scheduler,json
```

**Expected behavior**

Builds always work.

### PR DESCRIPTION
**Pull request by avantgardnerio**
# Which issue does this PR close?

Closes #3366.

 # Rationale for this change

We want stable builds, and I broke that.

# What changes are included in this PR?

Codegen into two separate files based upon selected features.

# Are there any user-facing changes?

Builds work more reliably.

### CODE REVIEW

**Comment by avantgardnerio** [comment]
@alamb and @andygrove let's get this in before users start seeing random build issues. Sorry I didn't catch this with the initial PR.

**Review by andygrove — APPROVED** [review]

**Comment by andygrove** [comment]
Thanks @avantgardnerio

**Comment by andygrove** [comment]
Is this something that we should have caught in CI?

**Comment by avantgardnerio** [comment]
> Is this something that we should have caught in CI?

Each CI job builds for a given feature set, then vaporizes the docker container. This is only something real users would encounter when switching feature sets back and forth, as I was doing trying to get a PR to pass all the tests.

**Pull request merged**
