### PR TITLE
Make parquet support optional for datafusion-common crate

### PR DESCRIPTION
**Pull request by jonmmease**
# Rationale for this change
Hi! This is a small PR that makes the `parquet` dependency of the new `datafusion-common` crate optional.  The motivation is that I'd like to depend on `datafusion-common` in the WebAssembly logic of [VegaFusion](https://vegafusion.io/), and the parquet dependency is the only thing preventing `datafusion-common` from compiling to WASM.

# What changes are included in this PR?
The `parquet` dependency in `datafusion-common` has been marked as `optional`, and feature gates are used in the `error.rs` file (following the pattern of the optional `avro` dependency).  This feature is then enabled by the `datafusion` crate.

# Are there any user-facing changes?
No

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]

**Comment by jonmmease** [comment]
Thanks for taking a look @Dandandan!  All green now

**Comment by Dandandan** [comment]
This is I think a uncontroversial change, so going ahead and merge this. 
Thanks @jonmmease for the contribution. VegaFusion looks really interesting!

**Comment by alamb** [comment]
This looks good. Very cool @jonmmease 

FWIW it might make sense to add a test for this to CI (e.g. something like `cargo check --no-default-features -p datafusion-common` so that we don't accidentally introduce a dependency again)

**Comment by jonmmease** [comment]
Thanks @alamb. That's a good idea. I'll play with it.

The other thing to test would be to check that the crate compiles successfully to the `wasm32-unknown-unknown` target with wasm-pack.  Would that be reasonable?  Over time, I would be interested in helping to get more of DataFusion working in the browser (c.f. https://github.com/apache/arrow-datafusion/issues/177), and having the smaller crates now seems like a good opportunity to make progress toward that goal incrementally.

**Comment by alamb** [comment]
> The other thing to test would be to check that the crate compiles successfully to the wasm32-unknown-unknown target with wasm-pack. Would that be reasonable?

Yes definitely! Thank you

**Pull request merged**
