### PR TITLE
Add datafusion-substrait crate to workspace

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Closes https://github.com/apache/arrow-datafusion/issues/4880

# Rationale for this change

We want `cargo build` to build all crates.

# What changes are included in this PR?

- Add to workspace
- Clippy fix

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by andygrove** [comment]
Windows build fails with:

```
error: failed to run custom build command for `substrait v0.2.0`

Caused by:
  process didn't exit successfully: `D:\a\arrow-datafusion\arrow-datafusion\target\debug\build\substrait-a6509fbb99b47d6b\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=FORCE_REBUILD

  --- stderr
  Error: "protobuf compilation failed: protoc failed: Missing input file.\r\n"
```

**Comment by andygrove** [comment]
I filed https://github.com/substrait-io/substrait-rs/issues/53

**Comment by andygrove** [comment]
@jdye64 @waynexia @nseekhao fyi

**Review by alamb — APPROVED** [review]
LGTM

**Pull request merged**
