### PR TITLE
Delete redundant code

### LINKED ISSUE #973: delete redundant code
https://github.com/apache/arrow-datafusion/blob/7932cb9373192ce2754b39c1f82f22c8a56b7266/datafusion/src/datasource/parquet.rs#L54

### PR DESCRIPTION
**Pull request by xudong963**
# Which issue does this PR close?

Closes #973

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by houqp** [comment]
@xudong963 Notice that `TableDescriptorBuilder::new` takes ownership of the passed in str:  https://github.com/apache/arrow-datafusion/blob/7932cb9373192ce2754b39c1f82f22c8a56b7266/datafusion/src/datasource/mod.rs#L169

I think it would be more efficient to propagate the `impl Into<String>` generic signature all the way into `TableDescriptorBuilder::build_table_desc`.

cc @yjshen to see if you have any opinion on this.

**Comment by xudong963** [comment]
now caller passes `path: &str` to `ParquetTable::try_new()`, so   `path.into()` make copy to generate String. if we propagate the impl Into<String> generic signature all the way into `TableDescriptorBuilder::build_table_desc`, we can avoid copy `TableDescriptorBuilder::new`. 

But if use `&str` in `ParquetTable::try_new()`, we can avoid copy in `ParquetTable::try_new()` and copy in `TableDescriptorBuilder::build_table_desc`.

Both will make one copy, but the second makes the code concise.

I am newly to rust, happy to point my mistake~

**Comment by houqp** [comment]
@xudong963 your analysis is correct :) However, the main benefit of that `impl Into<String>` generic argument is to give caller the flexibility to pass in the `path` variable either by reference or value.

When the caller is passing `path` as `&str`, then there will be no difference between these two versions as you mentioned.

When the caller pass in `path` as `String` type, then `ParquetTable::try_new(path: &str)` will end up with an extra copy because the signature forces it to write `ParquetTable::try_new(&path)`. While `ParquetTable::try_new(path: impl Into<String>)` will take ownership of `path` and avoid that copy entirely because `path.into` for String type will be optimized away by the compiler. This is useful when the caller knows it won't need to use the `path` variable anymore after calling `ParquetTable::try_new`, so it can safely pass it along by value.

https://phaazon.net/blog/blog/on-owning-borrowing-pub-interface has a good summary on this topic if you are into more detailed analysis.

**Comment by xudong963** [comment]
@houqp  Got it. Thanks for your introduction~
I will update the pr later.
By the way, （https://phaazon.net/blog/blog/on-owning-borrowing-pub-interface ） can't open.

**Pull request closed without merging**
