### PR TITLE
Arrow2 02092022

### PR DESCRIPTION
**Pull request by Igosuki**
# Which issue does this PR close?
None

Closes #.

 # Rationale for this change
Keep the arrow2 branch up to date 

# What changes are included in this PR?
Uses the improved parquet io code, switched to blocking FileWriter for writing parquet as File isn't AsyncWrite.

# Are there any user-facing changes?
Nope

### CODE REVIEW

**Comment by Igosuki** [comment]
Added a fix for avro projections

**Review by alamb — APPROVED** [review]

**Comment by houqp** [comment]
@Igosuki @alamb mind if I force update the arrow2 branch with the latest commit from this PR (79107650f5d04165aef6009a46d0289e615b34aa)? I am thinking it will be easier to manage long running branches using merge commits instead of squash commits so we can keep the full history from master in the arrow2 branch. Right now all commits from master branch got squashed into a single commit into the arrow2 branch every time we merge a PR.

**Comment by Igosuki** [comment]
Yep I actually did a merge with latest here
https://github.com/Igosuki/Arrow-Datafusion/tree/arrow2 should I make a new
PR ?
I now understand why it was so hard to merge all the time 😅

**Comment by alamb** [comment]
> mind if I force update the arrow2 branch with the latest commit from this PR 

I do not mind

**Comment by houqp** [comment]
@Igosuki that's great, I tried to manually unsquash the previous commit commits, but it turned out to be too much work and not worth it. I took a quick look at your arrow2 branch and it looks clean without those two squashed commits. I think we can just force push your arrow2 branch into the one in datafusion's repo, then use merge commits going forward for future catch ups. If you are ok with this approach, please feel free to send a PR, once reviewed by the community, I can help perform the force push to replace the current arrow2 branch.

https://git-scm.com/docs/gitfaq#long-running-squash-merge has guidance on how to best maintain long running branches, which should help explain why merge commits will help make future merges easier.

Once we have the arrow2 branch updated, I will get back to performance testing. I remember running into a performance regression around window queries, so that would be the next thing I will dig into.

**Pull request merged**
