### PR TITLE
bugfix: fix propagating empty_relation generates an illegal plan

### LINKED ISSUE #5218: Propagating empty_relation generate an illegal plan
**Describe the bug**

When the child node of union contains `EmptyRelation`, the plan generated by optimization rule `propagate_empty_relation` is wrong.

**To Reproduce**

1. query

```sql
create table m2(intt int) as select 1 as intt;

explain
SELECT 
  *
FROM 
  m2 
WHERE 
  false IS UNKNOWN 
UNION ALL 
SELECT 
  *
FROM 
  m2 
WHERE 
  NOT false IS UNKNOWN 
UNION ALL 
SELECT 
  *
FROM 
  m2 
WHERE 
  false IS UNKNOWN IS NULL;
```

2. result
```
+---------------+----------------------------------+
| plan_type     | plan                             |
+---------------+----------------------------------+
| logical_plan  | EmptyRelation                    |
| physical_plan | EmptyExec: produce_one_row=false |
|               |                                  |
+---------------+----------------------------------+
```

**Expected behavior**

```
+---------------+-------------------------------------------------+
| plan_type     | plan                                            |
+---------------+-------------------------------------------------+
| logical_plan  | Projection: m2.intt                             |
|               |   TableScan: m2 projection=[intt]               |
| physical_plan | ProjectionExec: expr=[intt@0 as intt]           |
|               |   MemoryExec: partitions=1, partition_sizes=[1] |
|               |                                                 |
+---------------+-------------------------------------------------+
```

**Additional context**

### PR DESCRIPTION
**Pull request by yukkit**
# Which issue does this PR close?

Closes #5218 .

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by jackwener — APPROVED** [review]
LGTM, Thanks you @yukkit.

**Comment by yukkit** [comment]
Can you help merge the pr, I'm going to use this commit @jackwener

**Comment by jackwener** [comment]
> Can you help merge the pr, I'm going to use this commit @jackwener

I can understand what you want. 

BUT, even if I merge this PR, you also can't use it right away because it doesn't in release version.

If you want to use `master branch` to get this PR (after this PR was merged), I don't recommend you this method, because `master branch` isn't stable branch, which may cause other problem.

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thank you @yukkit  and @jackwener

**Pull request merged**
