### PR TITLE
fix: Changed labeler.yml to latest format

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #.

## Rationale for this change

Labeler is broken now, e.g. https://github.com/apache/arrow-datafusion/actions/runs/7107345447/job/19348599271?pr=8419.

```
Run actions/labeler@v5.0.0
The configuration file (path: .github/workflows/dev_pr/labeler.yml) was found locally, reading from the file
Error: Error: found unexpected type for label 'development-process' (should be array of config options)
Error: found unexpected type for label 'development-process' (should be array of config options)
```

## What changes are included in this PR?

Tries to restore labeler CI by following latest format.

### CODE REVIEW

**Comment by viirya** [comment]
Hmm, does the change need to be merged to be effective?

**Comment by alamb** [comment]
Somehow is likely related to https://github.com/apache/arrow-datafusion/pull/8422

**Comment by viirya** [comment]
Let me merge this first to see if it works. Thanks @alamb

**Comment by alamb** [comment]
It seems to have worked!

**Comment by viirya** [comment]
Yea 🎉

**Pull request merged**
