### PR TITLE
Ensure most of links in docs are correct

### PR DESCRIPTION
**Pull request by HaoYang670**
# Which issue does this PR close?

Re #1741. I think we can only partially close it now. Because there are still some unsolved links in the docs (such as private struct and private functions)

 # Rationale for this change

run
```
cargo doc --document-private-items --no-deps --workspace 
```
and fix the warning.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by HaoYang670** [comment]
There are still 7 warnings when running `cargo doc`. However, I could not find a good solution in a short time. Need your help!

**Review by houqp — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @HaoYang670  -- I'll try and help sort out the nastier problems later today

**Comment by alamb** [comment]
I took a crack at the last warnings here: https://github.com/apache/arrow-datafusion/pull/1811

**Comment by matthewmturner** [comment]
thx @HaoYang670 :)

**Pull request merged**
