### PR TITLE
add notable project that are built with DataFusion to README

### PR DESCRIPTION
**Pull request by MrPowers**
# Which issue does this PR close?

N/A

# Rationale for this change

We should show a list of all the popular projects that are built with DataFusion so other developers are more confident about building their systems on DataFusion.

# What changes are included in this PR?

Updated the README.

# Are these changes tested?

N/A because no code changes.

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by ozankabak** [comment]
At some point it was decided to move this information to the website and out of the README file. Do you suggest going back to the old way of listing major users in the README file? If so, we should move that information from the website instead of arbitrarily picking three usages.

FWIW, I am personally OK with both a slim README file (status quo) and listing notable users in it.

**Comment by alamb** [comment]
Thank you @MrPowers !

Per slack thread, @Dandandan  points at https://arrow.apache.org/datafusion/user-guide/introduction.html#known-users

https://github.com/apache/arrow-datafusion/blob/b135a96a9647d0b7df6099bbd222e5280e75d0a8/docs/source/user-guide/introduction.md?plain=1#L91

If @MrPowers couln't find this easily, perhaps that tells us the information is not discoverable  / front and center enough 🤔  -- maybe we can at least leave a link to the known users section in the readme 🤔

**Comment by ozankabak** [comment]
> If @MrPowers couln't find this easily, perhaps that tells us the information is not discoverable / front and center enough 🤔 -- maybe we can at least leave a link to the known users section in the readme 🤔

Agreed

**Comment by alamb** [comment]
I plan to make an alternate proposal tomorrow. I just ran out of time today

**Comment by alamb** [comment]
Here is a proposal to add some more links to the main README to help people find content better but still retain the main content elsewhere. Comments / feedback welcome: https://github.com/apache/arrow-datafusion/pull/7102

**Pull request closed without merging**
