### PR TITLE
minor: port window tests to slt (part 2)

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Part of #4495 

# Rationale for this change

Goal is to make datafusion easier to maintain (e.g. these tests can be updated with `sqllogictest --complete`)

# What changes are included in this PR?

Port a bunch of lines of rust code to sqllogictest script

# Are these changes tested?
Yes

# Are there any user-facing changes?
No

### CODE REVIEW

**Comment by jackwener** [comment]
https://github.com/apache/arrow-datafusion/actions/runs/4269432821/jobs/7432635940

past `window.slt` exist unstable test, maybe we can resolve in this PR?

**Comment by jackwener** [comment]
look like this PR also meet this PR😂

**Comment by alamb** [comment]
Added a fix in 3c469cc hopefully

**Review by ozankabak — APPROVED** [review]
LGTM, thank you for tidying up these tests 👍

**Pull request merged**
