### PR TITLE
Add/Use projection in hashjoinexec

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by metesynnada** [comment]
I think output order, equivalence properties, etc. should also be refactored here. Nice PR btw. Do you think that there will be a performance increase?

**Comment by Dandandan** [comment]
> I think output order, equivalence properties, etc. should also be refactored here. Nice PR btw. Do you think that there will be a performance increase?

Yeah need to revisit this PR a bit later (or please continue on it if you like).
I expect a (modest) performance increase as we can skip  things like `take` and `coalescebatches` on the arrays that are not included.

**Comment by Dandandan** [comment]
The performance increase depends a bit on how many / what kind of columns are necessary in the output projection. For example, if we can skip `take` on some string-kernels and the benefit will be higher than in other cases.

**Comment by metesynnada** [comment]
> The performance increase depends a bit on how many / what kind of columns are necessary in the output projection. For example, if we can skip `take` on some string arrays then the benefit will be higher than in other cases.

Yeah, you are quite right, it will prevent unnecessary `compute::take` s in some cases. Do you also plan to change the `PushDownProjection` rule?

**Comment by Dandandan** [comment]
Yes this also involves changing the projection pushdown, which also should remove the then unnecessary `ProjectionExec` in most cases.

**Pull request closed without merging**
