### PR TITLE
Add delimiter for create external table

### LINKED ISSUE #2158: Add DELIMITER option with CREATE EXTERNAL TABLE for CSVs
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)
I would like to be able to specify a delimiter to use while reading in CSV files from SQL

**Describe the solution you'd like**
Add a DELIMITER parameter to CREATE EXTERNAL TABLE

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by matthewmturner**
# Which issue does this PR close?

Closes #2158 

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by matthewmturner** [comment]
@houqp @yjshen @xudong963 @alamb PTAL at your earliest convenience :)

**Comment by matthewmturner** [comment]
Disregard...ill clean up conflicts.

**Review by alamb — APPROVED** [review]
👨‍🍳  very nice @matthewmturner 👍

**Comment by alamb** [comment]
I don't think there is anything particularly controversial in this PR so merging it in

**Comment by matthewmturner** [comment]
@alamb Thank you. I wouldn't normally ping for review immediately after submitting like that - but was trying to demo something for someone that required the feature. Appreciate your responsiveness.

**Comment by alamb** [comment]
No worries -- I tend to batch review time so yours happened to be ready when my timeslice arrived

**Pull request merged**
