### PR TITLE
[task#9512] move from_unixtime, now, current_date, current_time to da…

### LINKED ISSUE #9512: Move  from_unixtime, now, current_date, current_time to datafusion-functions
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/arrow-datafusion/issues/9285 the from_unixtime, now, current_date, current_time datetime functions should be migrated to the new datafusion-functions crate in the new structure

### Describe the solution you'd like

Functions are migrated to the new crate and use the new patterns as described in https://github.com/apache/arrow-datafusion/issues/9286 & https://github.com/apache/arrow-datafusion/pull/9216,

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tangruilin**
…tafusion_functions

## Which issue does this PR close?

Closes part of #9512.

### CODE REVIEW

**Comment by Tangruilin** [comment]
now, current_date, current_time need to get query_execution_start_time.

But Now I see there is no `query_execution_start_time` in ScalarUDFImpl
@alamb

**Comment by Tangruilin** [comment]
> now, current_date, current_time need to get query_execution_start_time.
> 
> But Now I see there is no `query_execution_start_time` in ScalarUDFImpl @alamb

I Think `ExecutionProps` can be added into `ScalarUDF`.

**Comment by Tangruilin** [comment]
```rust
// TODO: add execution_props in ScalarUDF, so that we can get some params like query_execution_start_time
/// Create a physical expression of the UDF.
///
/// Arguments:
pub fn create_physical_expr(
    fun: &ScalarUDF,
    input_phy_exprs: &[Arc<dyn PhysicalExpr>],
    return_type: DataType,
) -> Result<Arc<dyn PhysicalExpr>> {
    Ok(Arc::new(ScalarFunctionExpr::new(
        fun.name(),
        fun.fun(),
        input_phy_exprs.to_vec(),
        return_type,
        fun.monotonicity()?,
        fun.signature().type_signature.supports_zero_argument(),
    )))
}
```

I think I can  add execution_props in ScalarUDF, so that we can get some params like query_execution_start_time in next PR

how do you think of it?

**Comment by alamb** [comment]
> how do you think of it?

I think we can use ScalarUdfImpl::simplify in this case: https://github.com/apache/arrow-datafusion/blob/b1d8082c6271e49c1de6e20002b853ca1503ffde/datafusion/expr/src/udf.rs#L373-L380

Specifically, the `SimplifyInfo` gets passed `ExecutionProps` https://github.com/apache/arrow-datafusion/blob/b1d8082c6271e49c1de6e20002b853ca1503ffde/datafusion/expr/src/simplify.rs#L39

Thus for a function like `now()`, that would look like
1. The `simplify()` call should rewrite now() to a `ScalarValue::TimestampNano`
2. The `invoke()` call should error with a "internal error"

Does that make sense?

**Comment by alamb** [comment]
(thank you for working on this, by the way @Tangruilin 🙏 )

**Comment by alamb** [comment]
Marking as draft as I think this PR is no longer waiting on feedback. Please mark it as ready for review when it is ready for another look

**Comment by Omega359** [comment]
Dup of https://github.com/apache/arrow-datafusion/pull/9537

**Comment by Tangruilin** [comment]
> Marking as draft as I think this PR is no longer waiting on feedback. Please mark it as ready for review when it is ready for another look

Maybe you need to close this

**Pull request closed without merging**
