### PR TITLE
Use standard make_null_array for CASE

### PR DESCRIPTION
**Pull request by alamb**
Closes https://github.com/apache/arrow-datafusion/issues/222

Shout out to @tustvold  who noticed this first.

 # Rationale for this change
1. remove code duplication 
1. Improve data type support for Case statement by using standard Arrow

# What changes are included in this PR?
Delete code and use arrow implementation

# Are there any user-facing changes?
no

### CODE REVIEW

**Comment by alamb** [comment]
Build is failing due to https://github.com/apache/arrow-rs/issues/238, which @ritchie46  has a PR up for 👍

**Review by Dandandan — APPROVED** [review]
😎 this will probably a bit faster as well (avoiding the builder)

**Review by returnString — APPROVED** [review]

**Review by jorgecarleitao — APPROVED** [review]
Great; much easier to read also. Thanks a lot, @alamb !

**Comment by alamb** [comment]
rebasing to pick up flatbuffers fix

**Pull request merged**
