### PR TITLE
change SQL literal numeric type from `Float64` to `Decimal128`

### LINKED ISSUE #3394: change SQL non-integer numeric literal type from Float64 to Decimal128
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

Per discussion on #166 , capturing for example `1.1` in the SQL literal as a Decimal results in accurate numbers, especially during expression simplification, where a Float can result in wrong data. Postgres also captures these literals as decimals.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by kmitchener**
# Which issue does this PR close?

Closes #3394 .

 # Rationale for this change

# What changes are included in this PR?

Per issue, switches SQL non-integer literals to Decimal128 instead of Float64.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by kmitchener** [comment]
@liukun4515 could you take a look at this conversion?

**Comment by andygrove** [comment]
Thanks for working on this @kmitchener. 

We really need to be able to parse numeric literals as either float or decimal. We don't need to do all of this in this PR, but we should make sure we file follow-on issues for anything not included here.

Per the ANSI SQL specification:

```
<signed numeric literal> ::=
[ <sign> ] <unsigned numeric literal>

<unsigned numeric literal> ::=
<exact numeric literal>
| <approximate numeric literal>

<exact numeric literal> ::=
<unsigned integer> [ <period> [ <unsigned integer> ] ]
| <period> <unsigned integer>

<sign> ::= <plus sign> | <minus sign>

<approximate numeric literal> ::= <mantissa> E <exponent>

<mantissa> ::= <exact numeric literal>

<exponent> ::= <signed integer>

<signed integer> ::= [ <sign> ] <unsigned integer>

<unsigned integer> ::= <digit>..
```

**Comment by kmitchener** [comment]
That's extremely helpful, thanks. What source are you using for the SQL specification?

**Comment by kmitchener** [comment]
In Postgres, these variants all get converted to decimals. https://dbfiddle.uk/CSN4-3op 

image

sqlparser-rs is doing something funky with the "e" notation, so I'll add some follow-on issues for that.

**Comment by alamb** [comment]
Is this pull request ready for review @kmitchener ? I ask because it is still marked as draft

**Comment by kmitchener** [comment]
> Is this pull request ready for review @kmitchener ? I ask because it is still marked as draft

Hi @alamb, no, it's still draft. I've learned a bit since this PR and am figuring out next steps and also working on other PRs that will make this final PR smaller. I can close this and submit a new PR when the change is finally ready if that's preferable? At this point, I need to make more changes before this is ready for review.

**Comment by alamb** [comment]
> . I've learned a bit since this PR and am figuring out next steps and also working on other PRs that will make this final PR smaller. I can close this and submit a new PR when the change is finally ready if that's preferable? At this point, I need to make more changes before this is ready for review.

Sounds good. I am just trying to keep tabs on PRs in this repo to keep them moving, which is why i asked. I'll close this one to signify it doesn't need any additional attention at this time. Thanks for all your help so far @kmitchener

**Pull request closed without merging**
