### PR TITLE
test: parquet use the byte array as the physical type to store decimal

### PR DESCRIPTION
**Pull request by smallzhongfeng**
# Which issue does this PR close?

Related to https://github.com/apache/arrow-datafusion/pull/2960

# Rationale for this change

Add one more test.

# What changes are included in this PR?

Add a test for parquet use the byte array as the physical type to store decimal.

# Are these changes tested?

# Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by smallzhongfeng** [comment]
PTAL. @liukun4515 :-)

**Comment by smallzhongfeng** [comment]
Could you help me review this, @alamb I'm not sure we need this test.

**Review by alamb — APPROVED** [review]
Thanks @smallzhongfeng -- I think this looks reasonable to me and is an improvement and the tests now document the current behavior. If we need to update the behavior at least it will be covered.

Thanks for the ping and sorry for the delay

**Comment by smallzhongfeng** [comment]
Thanks for you reivew! :-)

**Pull request merged**
