### PR TITLE
Update docs links to logical plans module.

### LINKED ISSUE #5036: Doc links to LogicalPlan in the core package need updating.
**Describe the bug**
While reading the docs I have noticed that some links to [logical plan](https://docs.rs/datafusion/16.0.0/datafusion/#parse-plan-optimize-execute) need updating.

**To Reproduce**
Click on the [Expr link](https://docs.rs/datafusion/16.0.0/datafusion/logical_plan::Expr) or other links to logical plan show resource not found.

### PR DESCRIPTION
**Pull request by vincev**
# Which issue does this PR close?

Closes #5036 .

# Rationale for this change

While browsing the docs I have noticed some links don't work.

# What changes are included in this PR?

This PR fixes some docs links to logical plan.

# Are these changes tested?

I have generated the docs locally and the links now work. 

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @vincev !

**Review by alamb — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Review by viirya — COMMENTED** [review]
Nice catch

**Comment by vincev** [comment]
> Nice catch

Thank you happy to help, it looks one check failed I am not sure what is causing the problem, it says `Too Many Requests`, maybe needs a rerun.

**Comment by viirya** [comment]
It looks unrelated error. Let me try to re-run the CI.

**Comment by alamb** [comment]
🎉

**Comment by alamb** [comment]
Thanks @vincev  and @viirya

**Pull request merged**
