### PR TITLE
Update datafusion versions

### PR DESCRIPTION
**Pull request by matthewmturner**
# Which issue does this PR close?

Re https://github.com/apache/arrow-datafusion/issues/1587

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by matthewmturner** [comment]
@alamb fyi

**Comment by alamb** [comment]
Thank you @matthewmturner

**Comment by Jimexist** [comment]
@alamb @matthewmturner do we need to bump the versions for:
- datafusion-common
- datafusion-expr

**Comment by matthewmturner** [comment]
@Jimexist yes, will do.

**Comment by alamb** [comment]
In https://github.com/apache/arrow-datafusion/pull/1803 for anyone following along

**Pull request merged**
