### PR TITLE
Support Time comparison 

### LINKED ISSUE #3157: Support Time comparison
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

we now have time but cannot be compared yet

```bash
DataFusion CLI v10.0.0
❯ select time '00:00:00';
+----------------------------------------------+
| CAST(Utf8("00:00:00") AS Time64(Nanosecond)) |
+----------------------------------------------+
| 00:00:00                                     |
+----------------------------------------------+
1 row in set. Query took 0.045 seconds.

❯ select time '00:00:00' = time '00:00:00';
ArrowError(NotYetImplemented("Comparing arrays of type Time64(Nanosecond) is not yet implemented"))

```

**Describe the solution you'd like**

support comparison for `Time64(Nanosecond)`

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by waitingkuo**
# Which issue does this PR close?

Closes #3157 

 # Rationale for this change

i added some test cases in advance

This depends on apache/arrow-rs#2458 

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
The relevant arrow feature has been released -- I wonder if this PR is still relevant?

**Comment by alamb** [comment]
> 
@alamb do you prefer to add these test cases? I could do the rebase and push again. Otherwise I think we could close the pr now as it's been solve.

I think these tests would be very valuable as our sql coverage of time is pretty low at the moment. Perhaps you could make a `time.slt` that is similar to  [`dates.slt`](https://github.com/apache/arrow-datafusion/blob/main/datafusion/sqllogictest/test_files/dates.slt) and [`timestamp.slt`](https://github.com/apache/arrow-datafusion/blob/main/datafusion/sqllogictest/test_files/timestamps.slt)?

**Comment by waitingkuo** [comment]
i'll do it

**Comment by alamb** [comment]
Closing as this PR is over a year old. Please feel free to reopen it / rebase it if you plan to keep working on it

**Pull request closed without merging**
