### PR TITLE
Remove `FromSlice` in favor of `From` impl in upstream arrow-rs code

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

Part of https://github.com/apache/arrow-datafusion/issues/1754 (see https://github.com/apache/arrow-datafusion/issues/1754#issuecomment-1579410979)

# Rationale for this change

I am trying to extract `physical_plan` into its own crate to improve modularity and compile times -- FromSlice is currently defined in the core crate and used in physical_plan

I am also trying to make sure the organization of the DataFusion crate is easier to understand for beginners (to make it easier to start) and thus the more we can rely on existing functionality (rather than something that is DataFusion specific) the better.

# What changes are included in this PR?

Remove the DataFusion specific `FromSlice` trait in favor of the arrow `From` impl

I also added some more docs in arrow-rs to try and make them easier to use: https://github.com/apache/arrow-rs/pull/4379#

# Are these changes tested?
Covered by existing tests 

# Are there any user-facing changes?
`from_slice` is no longer available (users should use the `From` impl in arrow-rs instead)

### CODE REVIEW

**Review by tustvold — APPROVED** [review]

**Comment by tustvold** [comment]
As an added bonus for non-nullable primitives this conversion will now be zero-copy

**Comment by alamb** [comment]
Since this is an API change I plan to leave it open for at least 24 hours in case anyone else wants to comment

**Comment by kazuyukitanimura** [comment]
Hi @alamb,
I was using `LargeBinaryArray::from_slice` for performance reasons (to avoid copying). E.g.
```
let v = vec![vec![1u8,2,3]];
let lba = LargeBinaryArray::from_slice(&v);
```
Now the API is gone, I was wondering if you could advise on alternatives. I can copy the old code back into my code or I can contribute to implement `From<Vec<Vec<u8>>>` to arrow-rs.
I wanted to check if you may have any insight on how other users adapted this change.

**Comment by alamb** [comment]
Hi @kazuyukitanimura 

How about using https://docs.rs/arrow/latest/arrow/array/struct.GenericByteArray.html#method.from_iter_values

This works for me:

```rust
    let v = vec![vec![1u8,2,3]];
    let lba = LargeBinaryArray::from_iter_values(v);
```

**Comment by kazuyukitanimura** [comment]
Thank you @alamb for the reply. I somehow remembered `from_iter_values` was slower, but now I tested it again. Both performs similarly. Not sure where I got the wrong impression. I will go with `from_iter_values`. Thanks again.

**Pull request merged**
