### PR TITLE
Minor: Improve documentation about optimizer

### PR DESCRIPTION
**Pull request by alamb**
## Which issue does this PR close?

Part of #7013 

## Rationale for this change

@comphead  suggested we have some better documentation of the Optimizer rules https://github.com/apache/arrow-datafusion/pull/9959#pullrequestreview-1983529791 and I agree!

## What changes are included in this PR?

Update the documentation of the Optimizer so we now have a summary of the available rules

Here is what the docs look like now:

Screenshot 2024-04-05 at 4 33 13 PM

## Are these changes tested?
CI doc tests

## Are there any user-facing changes?
No, just doc changes

### CODE REVIEW

**Review by Jefffrey — APPROVED** [review]

**Comment by alamb** [comment]
Thanks for the review @Jefffrey

**Comment by alamb** [comment]
One thing I found that was strange is that the `push_down_projection` module actually has no code (it is only tests for `optimize_projections`) It would be cool if we could consolidate the tests for `push_down_projection` into `optimize_projections`

**Comment by Jefffrey** [comment]
> One thing I found that was strange is that the `push_down_projection` module actually has no code (it is only tests for `optimize_projections`) It would be cool if we could consolidate the tests for `push_down_projection` into `optimize_projections`

Raised #9978

**Review by waynexia — APPROVED** [review]
👍 It looks better now

**Pull request merged**
